### ISSUE TITLE
Main Banner

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#1]
Tentative Schedule for rotation of Main banner. Management asked that the banner be rotated more frequently.  I want to make sure we are all moving in the right direction. Still looking for Ideas for the rest of the year.

~~Stratmap Contract - 02/22~~
~~GeoRodeo - 03/05 with Call for Papers and Registration TNRIS/tnris.org#1513~~
~~Forum - 03/15 TNRIS/tnris.org#1510~~ 
~~GeoRodeo - 04/02~~
~~GeoRodeo Wrap up - 05/07 (pictures and presentations)~~
~~RDC Pages - ??/??~~ ~~(depends on completion of TNRIS/tnris.org#1423)~~
~~Training Updates 05/14~~
~~Forum TNRIS/tnris.org#1510 06/11/2018~~
~~Forum Recap TNRIS/tnris.org#1669~~
~~GeoRodeo Call for Papers TNRIS/tnris.org#1687~~
~~Hydrography Page TNRIS/tnris.org#1568~~
~~Parcel Pages TNRIS/tnris.org#1613~~
~~Address Page Point TNRIS/tnris.org#1614~~
~~GIO page refresh TNRIS/tnris.org#1569~~
~~DataHub~~
~~GeoRodeo Wrap up~~
~~Forum~~
~~Forum Wrap up~~
StratMap Contracts Request For Offer

**Comment by adambreznicky** [comment]
banner schedule completed

**Comment by ghost** [comment]
@gmullins @christoball 

<img width="1338" alt="Screen Shot 2019-11-18 at 2 33 21 PM" src="https://user-images.githubusercontent.com/8459928/69091705-719b9e80-0a10-11ea-83d8-05a9d7f7348e.png">

**Comment by adambreznicky** [comment]
duplicate of issue 108?

**Comment by christoball** [comment]
@adambreznicky I talked to @mitchellryant and we'll close this one and make an issue for banner when new ones come up. We'll put our banner schedule in google docs or something instead of here.

**Comment by adambreznicky** [comment]
@christoball @mitchellryant 
right on, that sounds good to me! i was just trying to bring attention to the fact this issue only exists to say that we are working on another issue (of which actually has the details of the task) and that this year's schedule has come to an end. however y'all wanna manage it moving forward is cool with me. 

a google doc with the long term list sounds like a great idea to me. then issues can be opened for each change and closed when completed. sounds like a good way to keep issues from staying open for lengthy periods of time and getting lost in task management.
thanks fella!
