### ISSUE TITLE
Forum updated agenda 9.9.19

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#10]
[9.9.2019 Forum Agenda_Draft.xlsx](https://github.com/TNRIS/tnris.org/files/3591068/9.9.2019.Forum.Agenda_Draft.xlsx)
@christoball

**Comment by christoball** [comment]
combining #11 and #20 into this issue

**Comment by christoball** [comment]
@KCMack @gmullins agenda is updated with latest info, includes miguels bio from other issue and stratmap session descriptions: http://glidden.tnris.org/texas-gis-forum/2019/agenda/

**Comment by KCMack** [comment]
Adding to this issue. Please update the agenda with Ryan Fennell's bio.  The attached file has been updated.
[Copy of 9.9.2019 Forum Agenda_Draft_9.13.19.xlsx](https://github.com/TNRIS/tnris.org/files/3611809/Copy.of.9.9.2019.Forum.Agenda_Draft_9.13.19.xlsx)

**Comment by ghost** [comment]
@christoball Looks good to me!

**Comment by christoball** [comment]
@KCMack Latest version incorporating ryan fennel bio and carto presentation fix
http://glidden.tnris.org/texas-gis-forum/2019/agenda/

**Comment by KCMack** [comment]
Looks great!  Thank you.
