### ISSUE TITLE
Forum Photos Captions

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#101]
Wednesday
Photo 01 - Change Richard's Title to Deputy Executive Administrator
Photo 02 - Change Richard Title to Deputy Executive Administrator
Photo 03 - Add single quotes around Title of Show.
Photo 04 - Add single quotes around Title of Show.
Photo 07 - Change Peter's Title to Chairman of the Board
Photo 08 - Change Peter's Title to Chairman of the Board
Photo 19 - Change capitalization of AECOM

**Comment by christoball** [comment]
@mitchellryant preview of fixes ready here:
http://ellwood.tnris.org/news/2019-11-04/texas-gis-forum-2019-wrap-up-photo-recap/
