### ISSUE TITLE
Forum Day 2 keynote slide link

### ISSUE THREAD

**Issue by ilyannakadich** [TNRIS/tnris.org#104]
@christoball  Hey Chris, I wanted to send someone who was not at the Forum a link to the presentation by Leslie Sweet and notice the slides are from another presentation.  It's located on the network at M:\Forum_GeoRodeo\2019_Forum\Presentations\Hurricane Harvey - H-E-B's Response.pptx  Thanks! Ilyanna

**Comment by christoball** [comment]
@ilyannakadich its available, but I put the incorrect link. I'll fix that but you can directly point them to it here: https://speakerdeck.com/texasnaturalresourcesinformationsytem/hurricane-harvey-h-e-b-disaster-response

**Comment by ilyannakadich** [comment]
@christoball  Thank you!
