### ISSUE TITLE
Upload GIS Solution Group Mtg Notes - June

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1042]
[GIS SG Meeting Notes 2016-06-16.docx](https://github.com/TNRIS/tnris.org/files/376510/GIS.SG.Meeting.Notes.2016-06-16.docx)
@christoball 
Please upload to GIS SG Group page
Please change next meeting date to Aug 23, 1026, 2:30 p.m. - 4:00 p.m.

**Comment by christoball** [comment]
resolved in #1043
