### ISSUE TITLE
Address Point News Article

### ISSUE THREAD

**Issue by ilyannakadich** [TNRIS/tnris.org#107]
@christoball  Chris, Here is the news article for the new address points dataset.  Gayla reviewed - please let me know if you have any additional edit suggestions.  Thanks, ilyanna
[Texas Address Point News.docx](https://github.com/TNRIS/tnris.org/files/3859582/Texas.Address.Point.News.docx)

**Comment by christoball** [comment]
@ilyannakadich @gmullins 
For a news article, this needs a little more narrative, in particular why is it becoming a common schema news? Is this the first time this has happened? how will this make stakeholders' job easier? 

I think another paragraph following the intro addressing these questions would help. Also, including a quote from a stakeholder on why they're excited for this, etc...

**Comment by ilyannakadich** [comment]
@christoball  Thanks for the recommendations.  How's this version?
[Texas Address Point News.docx](https://github.com/TNRIS/tnris.org/files/3860643/Texas.Address.Point.News.docx)

**Comment by christoball** [comment]
@ilyannakadich love it, gives it a much more human element.

**Comment by christoball** [comment]
@ilyannakadich @gmullins preview ready:
http://washburn.tnris.org/news/2019-11-20/texas-address-points-datasets-transformed-into-common-schema/

**Comment by ilyannakadich** [comment]
@christoball  Looks great to me!  Thoughts @gmullins ?

**Comment by ghost** [comment]
@christoball @ilyannakadich Looks great to me. My only suggestion is to put Michelle's quote in italics or some other way to offset it within that paragraph.
