### ISSUE TITLE
Publish Ortho & Lidar StratMap Pages

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1070]

**Comment by gmullins** [comment]
How about:
Download the technical specification for Texas orthoimagery acquisition projects

Same for lidar.

**Comment by gmullins** [comment]
Ortho graphic

![aerotriangulation](https://cloud.githubusercontent.com/assets/4921113/17752301/c2aba9d8-6490-11e6-9ccf-0252c158942f.jpg)

**Comment by KCMack** [comment]
OOoh, how cool.  Will you tell me about it tomorrow?

kcm

**Comment by christoball** [comment]
@gmullins where is this graphic from?

**Comment by gmullins** [comment]
@christoball probably from here: https://iphonedroneimagery.com/tag/aerotriangulation/
AT is an essential step in orthoimagery production and is what makes the aerial image into a map.

**Comment by gmullins** [comment]
@christoball where are we on these pages? please publish. we really need specification doc's for lidar and orthoimagery online. thx!

**Comment by christoball** [comment]
@gmullins @ThorTheDestroyer can yall take a look?

While this may not have everything just yet (I know it's missing timeline imagery) if this is alright I'd like to push this so we can get the page out there, since I know y'all have been waiting on it.

We can keep fleshing it out as needed but at least this basic stuff can be out there.

### Lidar
https://deploy.tnris.org/api/v1/preview/31bdad5dbb6470ce4d45b07ba4f4809f533ec805/stratmap/elevation-lidar/

### Ortho
https://deploy.tnris.org/api/v1/preview/31bdad5dbb6470ce4d45b07ba4f4809f533ec805/stratmap/orthoimagery/

**Comment by gmullins** [comment]
@christoball @ThorTheDestroyer They look good to me for the push. Let's do it!
