### ISSUE TITLE
kim ludeke retirement article review

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1079]
@rwade2126 

Richard, please review article text for publication to "Around the State". All the responses are direct from Kim. Pictures will be uploaded and arranged by @christoball.

Kim also mentioned this:
_"One thing I don’t know if I mentioned but one of my early projects of which I am very proud is the work Richard Wade and I did in support of the Balcones Canyonlands Conservation Plan.  We did mapping and spatial analysis of the various preserve configurations."_

Maybe you can extrapolate on the above and add it into your intro or closing statement?

**Comment by geochik** [comment]
@christoball - pics for k ludeke article:
![dangermond_tgic](https://cloud.githubusercontent.com/assets/7750220/18067973/d047a24a-6e04-11e6-8bca-81b2f7249290.jpg)
![copy of kim ludeke 3](https://cloud.githubusercontent.com/assets/7750220/18067977/d4d6749e-6e04-11e6-968f-79aecb353e17.JPG)
![kimludeke_ludekeranch 2](https://cloud.githubusercontent.com/assets/7750220/18067978/d4dfc396-6e04-11e6-8b52-939d0fd530e6.JPG)
![imglab038](https://cloud.githubusercontent.com/assets/7750220/18067983/dcf041a0-6e04-11e6-8235-92a2e1fa71b9.jpg)
![imglab050](https://cloud.githubusercontent.com/assets/7750220/18067986/e28e88ba-6e04-11e6-9b58-6c15faadb8f9.jpg)
![imglab2073](https://cloud.githubusercontent.com/assets/7750220/18067987/e514be2e-6e04-11e6-8769-d354a725afe7.jpg)
![kimludeke_ludekeranch 2](https://cloud.githubusercontent.com/assets/7750220/18067989/e6f047b8-6e04-11e6-97bd-5e24bbd9363c.JPG)
![kimrichard](https://cloud.githubusercontent.com/assets/7750220/18067991/e8a2b424-6e04-11e6-90db-222ccac852e8.jpg)

**Comment by geochik** [comment]
@christoball Can we start with the 3 pictures that are captioned? I will get the others captioned by Kim himself. Thanks!

**Comment by geochik** [comment]
@christoball Sorry, that's actually 4 captioned pics.

**Comment by geochik** [comment]
@christoball Ready to go.

**Comment by christoball** [comment]
resolved in #1085
