### ISSUE TITLE
StratMap Contracts Request For Offer 

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#108]
Create banner for StratMap Contracts Request For Offer in December

**Comment by christoball** [comment]
@gmullins Please provide concepts and place information that would need to be on the banner here.

**Comment by ghost** [comment]
@christoball The intent of this banner message is to announce the opening of the StratMap/DIR Contracts - after 4 years of being closed to new contractors. The audience is the geospatial commercial vendor community (Surdex, Fugro, etc who have to reapply and new companies that have expressed interest such as Atlantic and KCI). 

I don't have any graphic related to this but can advise with you.

Here are some sound bites from an email I sent today to all interested parties: _Thank you for your interest in the StratMap/DIR Contracts, a contracting vehicle designed to improve access to geospatial data products, services and software in the state of Texas. After four years of success, the re-bid of these contracts is coming up this December 2019!

Currently, the solicitation release date has been moved to December 2019 (date TBD) with a pre-bid meeting also planned for December 2019 (date TBD). For official information, please visit the DIR Current Contracting Initiatives site where the Request for Offer will be posted. It will be listed as: 
Geographic Information Systems (GIS) Hardware, Software, and Services and Information Technology (IT) Based Land Surveying Hardware, Software and Related Services
DIR-CPO-TMP-444 Geographic Information Systems (GIS) Hardware, Software, and Services and Information Technology (IT) Based Land Surveying Hardware, Software and Related Services
 
All current contract holders are required to re-submit.
 
Thank you, and we look forward to working with you!_

Thanks!

**Comment by christoball** [comment]
@gmullins will there be an article/press release type thing to announce this as well? We should start prepping that and may want to run it upstairs since it involves contract stuff.

**Comment by ghost** [comment]
@christoball I spoke with Communications on this yesterday, and there will not be a press release, rather they will tweet it once the banner is up on our site. I'm open to writing a brief article to explain it once someone clicks on the banner. I'm wrapped up in a lidar evaluation today and tomorrow (Thu), but happy to chat with you of course. The RFO itself has not been released. Date still TBD.

**Comment by ghost** [comment]
@christoball Also, this doesn't have a whole lot to do with TWDB Contracts, although I welcome their review. This is coming out from DIR Contracting.

**Comment by christoball** [comment]
@gmullins Talked to @rwade2126 and we came up with this tag line for the contract banner

The StratMap Contract
Creating Texas Data

![stratmapcontract_banner_2020](https://user-images.githubusercontent.com/1877550/70728356-e340d280-1cc6-11ea-9d7e-3584e6f54e7b.jpg)

**Comment by christoball** [comment]
@gmullins need a quick line explaining what we're announcing for the other text.

**Comment by christoball** [comment]
New text from @gmullins

 Special Announcement across the top (to be removed after solicitation closes in early February).
Small change:
After four years of success, the re-bid of StratMap contracts is coming up this December 20, 2019!

Body change:
The Department of Information Resources (DIR) maintains multiple Cooperative Contracts which are designed to strengthen Texas’ capabilities to procure quality digital map data, services and software. The contracts are for use by customers that include Texas state, regional and local government offices, including river and water authorities, and public education entities. The process for procuring GIS products, custom geospatial data and services and software is administered by TNRIS and known as the Texas Strategic Mapping (StratMap) Contracts.

The StratMap/DIR Contracts are awarded to companies which are technically evaluated by a team of GIS professionals and determined to provide quality geographic data products, services, and GIS software. The availability of these contracts streamlines the procurement process for any acquisition of geographic data, services, and software and provides beneficial competition among some of the best companies in the industry.

Change:
Vendors heading to Vendors 2016 - 2020

Thanks!

**Comment by christoball** [comment]
@gmullins @ThorTheDestroyer Newest Banner draft

![stratmapcontract_banner_2020_2nd](https://user-images.githubusercontent.com/1877550/71038667-f51bde80-20e7-11ea-95e9-b33dd8ab6271.jpg)

**Comment by ghost** [comment]
@christoball @ThorTheDestroyer I love it! Only suggestion is to crop off the Dept. of Information Resources line from their logo.

**Comment by ghost** [comment]
@christoball The RFO from DIR has been posted so I'm ready to push the banner and website changes when you are.
 
On the page, the announcement should now read:
After four years of success, the re-bid of StratMap contracts is happening now! See the official [Request for Offer](http://www.txsmartbuy.com/sp/DIR-CPO-TMP-444) posting.

**Comment by christoball** [comment]
@gmullins front page preview here:
http://washburn.tnris.org/

I felt like the logos weren't necessary on the front page but I can still add them 

Contracts page preview here: 
http://washburn.tnris.org/stratmap/stratmap-contracts/
