### ISSUE TITLE
Add message to beta site

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/tnris.org#108]
Basic auth - nothing fancy. Just something to indicate to someone who might have stumbled onto it that they are looking behind the curtain.

**Comment by jseppi** [comment]
Maybe just a simple banner (activated via simple JS check of the hostname) that says something like

> This is the beta version of tnris.org
> For our official site, please visit tnris.org

**Comment by wilsaj** [comment]
:+1:  should also display for deploy previews
