### ISSUE TITLE
StratMap Contracts updates

### ISSUE THREAD

**Issue by gmullins** [TNRIS/tnris.org#1090]
@christoball 

- Remove Infogroup box completely. They will not have a contract.

- Turn on West
Vendor Contract Page in progress
DIR Vendor Contract page: http://dir.texas.gov/View-Search/Contracts-Detail.aspx?contractnumber=DIR-TSO-3468&keyword=West

Thx!!

**Comment by christoball** [comment]
@gmullins I've resolved this but we're having deployment issues on the website, so unfortunately I won't be able to push them at the moment.

**Comment by christoball** [comment]
@gmullins never mind, @mitchellryant got it working!
