### ISSUE TITLE
StratMap Contract update

### ISSUE THREAD

**Issue by gmullins** [TNRIS/tnris.org#1096]
@christoball

Turn on Hexagon Geospatial
Vendor Contract Page in progress
DIR Vendor Contract page: http://dir.texas.gov/View-Search/Contracts-Detail.aspx?contractnumber=DIR-TSO-3472&keyword=Intergraph

RazorTek
Vendor Contract Page: http://www.razor-tek.com/

Thx!!

**Comment by gmullins** [comment]
@christoball Can you please make these updates? Thx!

Turn on Hexagon Geospatial
Vendor Contract Page in progress
DIR Vendor Contract page: http://dir.texas.gov/View-Search/Contracts-Detail.aspx?contractnumber=DIR-TSO-3472&keyword=Intergraph

RazorTek
Vendor Contract Page: http://www.razor-tek.com/

West
Vendor Contract Page: https://www.west.com/safety-services/partners/texas-department-of-information-resources/

**Comment by christoball** [comment]
@gmullins yes ill do it right away. so razortek's contract page just goes to their home page?

This isn't the link?
http://www.razor-tek.com/tx_dir_information/tx_dir.htm

**Comment by gmullins** [comment]
@christoball yes, you're right. that is the correct link for razortek: http://www.razor-tek.com/tx_dir_information/tx_dir.htm

**Comment by gmullins** [comment]
@christoball Please update Hexagon's Vendor Contract page with this link: http://www.hexagongeospatial.com/legal/texas/texas-dir

Thx!

**Comment by christoball** [comment]
All updated: https://tnris.org/stratmap/stratmap-contracts/
