### ISSUE TITLE
new data: FEMA 2015-2016

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1099]
lidar
- [ ] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @mitchellryant
- [ ] Data Processing [renaming file, data organization, coverage map] @mitchellryant
- [ ] Quality Assurance @ThorTheDestroyer
- [ ] Move data to production shares @mitchellryant
- [ ] Data Publication [Update data catalog sheet, create data catalog images, supplemental reports staging] @ThorTheDestroyer
- [ ] Data Story @ThorTheDestroyer
- [ ] Final Publication @christoball @ThorTheDestroyer

**Comment by ThorTheDestroyer** [comment]
data delivered to TNRIS 09/19/2016

**Comment by mitchellryant** [comment]
@ThorTheDestroyer if you let me know the year and PPMS I will rename all the data files.

**Comment by mitchellryant** [comment]
Dewitt is 0.71 cm, 2 points per square meter, with 1m dems

**Comment by ThorTheDestroyer** [comment]
Clear Fork Brazos is 71cm, 2 points per square meter with 1m dems

**Comment by ThorTheDestroyer** [comment]
Rio Grande is 1m NPS with 1m dems

**Comment by mitchellryant** [comment]
Rio Grande has all been renamed.

Started working on Jack/Archer. Project report says the are 2259 tiles, that is the number of DEMs delivered, only 749 las tiles delivered to TNRIS.

**Comment by mitchellryant** [comment]
issue was split into 4 issues per area
https://github.com/TNRIS/tnris.org/issues/1164
https://github.com/TNRIS/tnris.org/issues/1165
https://github.com/TNRIS/tnris.org/issues/1166
https://github.com/TNRIS/tnris.org/issues/1167
