### ISSUE TITLE
Speaker Slides Forum 2018

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#111]
Form parameters
==================

Name: Yanli Zhang
Email: zhangy2@sfasu.edu
Phone: 936-468-2157
Address: 419 East College St, Nacogdoches, TX, 75962
Organization: SFASU
Industry: Education 
Question/Comment: 
`I was at the 2018 GIS Forum and when I submitted my presentation, I clearly label it as "NO" for putting it online later. However, I just found my entire file is online. Would you please remove it ASAP? Thanks`

**Is what he saying true?
Do we provide the option for not putting them online?
Why did it take this person a year to notice?**

**Comment by christoball** [comment]
@mitchellryant i've deleted them from speakerdeck and made a commit to remove the link on the 2018 agenda page.

**Comment by ghost** [comment]
@christoball @KCMack if the changes have been made and everything is in order, then create a PR to make the changes.

**Comment by christoball** [comment]
resolved in #110
