### ISSUE TITLE
Data Download Update Notes

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1117]
Adding some notes on the additions to the data download.

Suggestions:
- Change info icon from fontawesome to glyphicon '**glyphicon glyphicon-info-sign**'
  - Make 'more info' popup the same height as main part.
- Put expand arrow on right side of columns sorting. Put a light grey version on inactive columns that get darker on hover

**Comment by adambreznicky** [comment]
reference commit d19a351

changes implemented.
