### ISSUE TITLE
IE9: training page expand/collapse looks janky

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/tnris.org#113]
Gradient doesn't show up, so "Expand Policy" overlays the text:

![screen shot 2015-01-12 at 1 35 53 pm](https://cloud.githubusercontent.com/assets/303866/5709532/41f0b762-9a60-11e4-8dc2-bfc575a6a754.png)

**Comment by christoball** [comment]
Changed the look - added border and background to 'Expand Policy' clickable area.

Text won't bleed underneath on ie9 when gradient is gone.
