### ISSUE TITLE
run javascript through closure compiler on build

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/tnris.org#116]
to trim down script size

**Comment by jseppi** [comment]
Looks like the site.min.js is only ~1.1kb over the wire.

**Comment by wilsaj** [comment]
mostly to trim down vendor.js - we could only ship parts of vendored libs that are used

**Comment by jseppi** [comment]
Yeah I don't know how well ClosureCompiler will work on code that has not been written according to its conventions. I doubt much of its static analysis/dead code fanciness will work that well or at all :(

**Comment by wilsaj** [comment]
Even if it does work, it looks like it would be a lot of work to set up for only marginal benefit. Closing.
