### ISSUE TITLE
new data: fema 2014 rio grande

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1164]
- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @mitchellryant
- [x] Data Processing [renaming file, data organization, coverage map] @mitchellryant
- [x] Quality Assurance @ThorTheDestroyer
- [x] Creation of derviative products @ThorTheDestroyer
- [x] Data Publication [Update data catalog sheet, create data catalog images, supplemental reports staging] @ThorTheDestroyer
- [x] Data Story @ThorTheDestroyer
- [x] Final Publication @christoball @ThorTheDestroyer https://github.com/TNRIS/tnris.org/pull/1252
- [x] Move data to production shares @mitchellryant
- [x] Inform TNRIS staff of data availability @ThorTheDestroyer 
- [x] Add to Data Download https://github.com/TNRIS/data-download/issues/86 @mitchellryant

**Comment by mitchellryant** [comment]
Rio Grande TX - 2014, 1m NPS, and 1m dem

**Comment by ThorTheDestroyer** [comment]
@mitchellryant 2ft and 5ft shapefiles were created and are ready to be moved to production shares
R:\Contours\FEMA\2014\Rio\2ft\shapefiles
R:\Contours\FEMA\2014\Rio\5ft\shapefiles

**Comment by mitchellryant** [comment]
@ThorTheDestroyer need flight and qaqc vendors to update index.

**Comment by ThorTheDestroyer** [comment]
Acquisition- Photo Science, Inc. a Quantum Spatial Company
QAQC- Quantum Spatial
