### ISSUE TITLE
new data: fema 2016 dewitt

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1165]
- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @mitchellryant
- [x] Convert data from USNG to USGS (las and dem)
- [x] Data Processing [renaming file, data organization, coverage map] @mitchellryant
- [x] Creation of derviative products @ThorTheDestroyer
- [x] Quality Assurance @ThorTheDestroyer
- [x] Data Publication [Update data catalog sheet, create data catalog images, supplemental reports staging] @ThorTheDestroyer
- [x] Data Story @ThorTheDestroyer
- [x] Final Publication @christoball @ThorTheDestroyer https://github.com/TNRIS/tnris.org/pull/1252
- [x] Move data to production shares @mitchellryant
- [x] Inform TNRIS staff of data availability @ThorTheDestroyer 
- [x] Add to Data Download https://github.com/TNRIS/data-download/issues/86 @mitchellryant

**Comment by mitchellryant** [comment]
Dewitt - 2016, 71 cm or 2 ppsm, and 1m dems

**Comment by mitchellryant** [comment]
loading data into als tools to convert from las to laz, i get the following erro.

set_epsg_code: look-up for 2278 not implemented
set_ProjectedCSTypeGeoKey: look-up for 2278 not implemented

**Comment by mitchellryant** [comment]
dems need to be chopped to match USGS grid. las has been done.

**Comment by mitchellryant** [comment]
when converting las to las get the following error.

set_ProjectedCSTypeGeoKey: look-up for 2278 not implemented                                                                            
set_epsg_code: look-up for 2278 not implemented                                                                                        
set_ProjectedCSTypeGeoKey: look-up for 2278 not implemented                                                                            
laszip -lof file_list.txt -olaz                                                                                                        
laszip -lof file_list.txt -odir "r:\LiDAR\fema_del\DeWittCo_TX_LiDAR_Delivery_to_FEMA_RVI\las" -olaz                                   
ERROR: point type not supported                                                                                                        
ERROR: cannot open laswriterlas with file name 'r:\LiDAR\fema_del\DeWittCo_TX_LiDAR_Delivery_to_FEMA_RVI\las\fema15-70cm_2897032a2.laz'
ERROR: could not open laswriter                                                                                                        
usage:                                                                                                                                 
laszip *.las                                                                                                                           
laszip *.laz                                                                                                                           
laszip *.txt -iparse xyztiarn                                                                                                          
laszip lidar.las                                                                                                                       
laszip lidar.laz -v                                                                                                                    
laszip -i lidar.las -o lidar_zipped.laz                                                                                                
laszip -i lidar.laz -o lidar_unzipped.las                                                                                              
laszip -i lidar.las -stdout -olaz > lidar.laz                                                                                          
laszip -stdin -o lidar.laz < lidar.las                                                                                                 
laszip -h

**Comment by ThorTheDestroyer** [comment]
I wonder it it is because they are las version 1.4.  Is  the las tools on the machine you are using to convert them current?

**Comment by mitchellryant** [comment]
current the las tools site barely loads, nothing downloads.

copied project from github with binaries.  writes out but every file has the stnerr
WARNING: EVLRs not supported. header->start_of_first_extended_variable_length_record is 259915456. writing 0 instead.
WARNING: EVLRs not supported. header->number_of_extended_variable_length_records is 1. writing 0 instead.
WARNING: legacy number_of_point_records in header of LAS 1.4 file should be zero.
WARNING: legacy number_of_points_by_return[0] in header of LAS 1.4 file should be zero.
WARNING: legacy number_of_points_by_return[1] in header of LAS 1.4 file should be zero.
WARNING: legacy number_of_points_by_return[2] in header of LAS 1.4 file should be zero.
WARNING: legacy number_of_points_by_return[3] in header of LAS 1.4 file should be zero.

**Comment by mitchellryant** [comment]
@ThorTheDestroyer need flight and qaqc vendors to update index.

**Comment by mitchellryant** [comment]
@ThorTheDestroyer unable to locate the following files on project share. (las, laz, dem, hypso)
fema16-70cm_2897032a1
fema16-70cm_2897032a3
fema16-70cm_2897032c1
fema16-70cm_2897073a4
fema16-70cm_2897073b3
fema16-70cm_2997523b2
fema16-70cm_2997532d2
fema16-70cm_2997541c1
fema16-70cm_2997592c3
fema16-70cm_2997594a1
fema16-70cm_2997594a3
fema16-70cm_2997594c1
fema16-70cm_2997594c3
fema16-70cm_2997622c1
fema16-70cm_2997622c2

**Comment by ThorTheDestroyer** [comment]
Tiles along that western edge appear to not have data, see below. 

![image](https://cloud.githubusercontent.com/assets/8398036/25352527/f5ba9caa-28f1-11e7-8823-c26386988251.png)

not sure why, but the entire index(i am using) appears to have almost a ring of empty tiles. Around it. 

![image](https://cloud.githubusercontent.com/assets/8398036/25353558/52af9188-28f5-11e7-9fb8-2adde890b92a.png)


Are we working from the same index? 

The missing central tiles will be re-cut, compressed and placed on Projects in the current respective dewitt fema delivery directory  in a folder called missing.

**Comment by mitchellryant** [comment]
i generated an index in global mapper on the dem dir projects\lidar\fema\dem\2016\. loaded this geometry into a blank fc with matching schema to prod lidar index. my index is here projects\lidar\fema

center files (fema16-1m_2997622c1.dem and fema16-1m_2997622c2.dem) are in dem dir.

I had to run the cmd to get files sizes on the uncompressed las files from project\lidar\dem_del dir.

**Comment by ThorTheDestroyer** [comment]
Ah, okay now I understand.  Our usual methods don't work on these bizarre FEMA datasets.  The DEMs have overlap while the LAS do not.  The DEMs directory shows those tiles because the overlap just happens to grabs a sliver of data.  so while the DEM returns tiles from the re-tiling, the LAS will not(see below). 
![image](https://cloud.githubusercontent.com/assets/8398036/25354790/fb054644-28f9-11e7-8cd8-516c056f21ef.png)

**Comment by mitchellryant** [comment]
how do you want to proceed with the slivers and surrounding areas?
