### ISSUE TITLE
new data: fema jack and archer

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1167]
- [ ] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @mitchellryant
- [x] Data Processing [renaming file, data organization, coverage map] @mitchellryant
- [ ] Creation of derviative products @ThorTheDestroyer
- [ ] Quality Assurance @ThorTheDestroyer
- [ ] Data Publication [Update data catalog sheet, create data catalog images, supplemental reports staging] @ThorTheDestroyer
- [ ] Data Story @ThorTheDestroyer
- [ ] Final Publication @christoball @ThorTheDestroyer
- [ ] Move data to production shares @mitchellryant
- [ ] Add to Data Download @mitchellryant

**Comment by mitchellryant** [comment]
Jack\Archer - 2015, 70cm, and 1m dems

**Comment by mitchellryant** [comment]
@ThorTheDestroyer 

Started working on Jack/Archer. Project report says the are 2259 tiles, that is the number of DEMs delivered, only 749 las tiles delivered to TNRIS. 

need to contact fema about missing tiles.

**Comment by ThorTheDestroyer** [comment]
Process is being postponed until FEMA can find and send the remaining LAS Tiles
