### ISSUE TITLE
update bootstrap to v4

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/tnris.org#117]
this is a big task, but bootstrap should be updated to version 4.3.1 (latest). currently using version 3.4.1.

v4 is a major rewrite of the package so i expect this requires a slow, conscientious process of implementing minor alterations across dozens (if not hundreds) of .md & .njk files. the most obvious or significant change to make the update will be a combing of every markdown, template, & component (including js dynamically created ones) to update html tags and classes.

source distributed information about what needs to change can be found [here](https://getbootstrap.com/docs/4.0/migration/).

probably should start by making the package update, attempting to build the app, reading the errors and ironing them out (that is if any exist). after it builds, it'll probably not look as it should, so from there the classes/tags can be reviewed. of course, holler for help  if needed

**Comment by christoball** [comment]
Started a feature branch for this called:
feature/bootstrap-4

I'll be going through it as I can to bring it all into alignment.

**Comment by JasonKleinert** [comment]
Looks like Bootstrap v3 (our current version) has been moved to end of life on July 24 and will no longer receive critical security updates. [https://blog.getbootstrap.com/2019/07/24/lts-plan/](https://blog.getbootstrap.com/2019/07/24/lts-plan/)

Bootstrap has recently (June 2020) released v5-alpha, [https://blog.getbootstrap.com/2020/06/16/bootstrap-5-alpha/](https://blog.getbootstrap.com/2020/06/16/bootstrap-5-alpha/). Presumably v5 beta will be on the way soon. One major change, they are dropping their jQuery dependency. It will probably still be easiest for us to upgrade to v4 then move to v5 once it goes into a production release.

**Comment by adambreznicky** [comment]
resolved via commit 56f1b91558391399eab0de4b0ee025d825d2a19b
