### ISSUE TITLE
data catalog: remove some tpwd data

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1174]
Per request from TPWD the following datasets have been removed from the data catalog google sheet.

TPWD Texas Biotic Provinces Lines
TPWD Texas Biotic Provinces Polygons
TPWD Omernik Regions Level IV
TPWD Playas
TPWD Significant Streams Segments
TPWD Springs
TPWD Lakes & Bays
TPWD Basins

Information was copied to 3rd sheet.

**Comment by mitchellryant** [comment]
From: Marian OBrien
Date: Friday, December 16, 2016 at 10:49 AM
To: Ryan Mitchell 
Cc: "IT GIS Team (IT-GIST)"
Subject: TPWD public facing data
 
Hi Ryan,
 
Hope your holidays are off to a great start. I wanted to let you know that TPWD has a new public facing GIS web page. Check it out here: http://tpwd.texas.gov/gis/
 
We would like to take down our old data downloads page however, the TNRIS data catalog points to data on our old site and if we take it down it will break those links on the TNRIS page. The TPWD GIS community has concluded we should only host data created by the agency and just provide links to the original data sources for those data we previously provided as base layers.
 
My question for you is: who is the keeper of the data catalog https://tnris.org/data-catalog/? I will provide the TPWD data as zipped shapefiles with metadata and/or whatever else is needed to update the content on your site. If you are not the person who can make these changes, please let me know who to contact to replace the TPWD data currently available from TNRIS.
 
I really appreciate your help in cleaning this up so we can take down our old data downloads website.
 
Regards,
~Marian
 
 
Marian O’Brien
Texas Parks & Wildlife Department
IT-GIS Team Analyst

**Comment by mitchellryant** [comment]
From: Ryan Mitchell
Sent: Friday, December 16, 2016 1:38 PM
To: Marian OBrien
Cc: IT GIS Team (IT-GIST)
Subject: Re: TPWD public facing data

We do not house any of the data on our site, the links download directly from you site. I changed the links to be correct from your new page. The following datasets were in the data catalog, but no longer have links on your site or I did not see them.
 
What do you want to do with them?
 
 
TPWD Texas Biotic Provinces Lines
TPWD Texas Biotic Provinces Polygons
TPWD Omernik Regions Level IV
TPWD Playas
TPWD Significant Streams Segments
TPWD Springs
TPWD Lakes & Bays
TPWD Basins
TPWD Bailey's Ecoregions http://www.fs.fed.us/rm/ecoregions/downloads/ecoregions-united-states/data-sets/eco-us-shp.zip
 
 
Ryan

**Comment by mitchellryant** [comment]
Hi Ryan,
Thanks for your quick response! Will you take them off your site? We only want to share what we have up on our site right now. Going forward, as we add to our downloads I will notify you and send the links for you to point to. Does that work for you?
~Marian

**Comment by adambreznicky** [comment]
removing the datasets from the catalog and then copying the updated catalog down (as per the traditional method of updating the catalog) should not cause any real errors. But for cleanliness and consistency, those datasets' search criteria should be removed from the catalog search file located here:
../tnris.org/static/js/data-catalog/attributes.js
Please let me know if you have any questions or issues about this. I'll come right over.

**Comment by christoball** [comment]
Merged the updated CSV into the master.
