### ISSUE TITLE
Add 1st Quarter GIS Meeting Agenda

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1175]
Upload the agenda to the 
**static/documents/gio-meetings** 
folder.

Uncomment the button from the 
https://github.com/TNRIS/tnris.org/blob/master/templates/partials/gio-meeting.html
file, and update the link to the new agenda file

**Comment by geochik** [comment]
@adambreznicky 
Here is the PDF! Let me know what the URL will be. Thanks!!
[gio-meeting-agenda-20170110.pdf](https://github.com/TNRIS/tnris.org/files/669671/gio-meeting-agenda-20170110.pdf)

**Comment by geochik** [comment]
@adambreznicky 
Correction....just got an update so THIS is the correct PDF. Thanks!!
[gio-meeting-agenda-20170110.pdf](https://github.com/TNRIS/tnris.org/files/669697/gio-meeting-agenda-20170110.pdf)

**Comment by adambreznicky** [comment]
updated and deployed.
