### ISSUE TITLE
data download: adding lidar data

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1202]
- [x] create zip files for liar download (all data and files related to Quarter-Quad) @mitchellryant
- [x] load data to download s3 bucket @mitchellryant
- [x] modify all lidar entries of data catalog (adding info about compression, decompression, and tools) @mitchellryant
- [x] add field to data catalog for lidar breaklines and project metadata
- [x] zip and copy lidar breaklines and project metadata to s3 for download from data catalog (breaklines and project meta) @mitchellryant https://github.com/TNRIS/tnris.org/issues/1224
- [x] locate best download location for lastools, my need to host a version on aws.
- [x] add to data download @mitchellryant https://github.com/TNRIS/data-download/issues/84

**Comment by mitchellryant** [comment]
Sample text for lidar entries:

Lidar data for Texas is made available online through the use of  data compression using LASTools (https://rapidlasso.com/lastools/). LASTools is an open-source collection of tools for lidar data viewing and manipulation. TNRIS uses the LASzip portion of LASTools for compression\decompression.  LASTools provides a lossless compression of the data from las to laz formats. 

Software with native LAZ support
Fugroviewer (2.0 and up) by Fugro
QT Modeler (7.1.6 and up) by Applied Imagery
ERDAS IMAGINE (14.1 and up) by Hexagon Geospatial
Global Mapper (13.1 and up) by Blue Marble Geo
Trimble RealWorks (8.1 and up) by Trimble Navigation Limited
ENVI LiDAR (5.1 and up) by Exelis VIS
FME (2012 and up) by Safe Software
Pointools by Bentley Systems
Pix4uav by Pix4D
LAStools by rapidlasso - fast tools to catch reality
plas.io 3D Web Viewer by Hobu Inc.
Leica LIDAR Survey Studio LSS (2.2 and up) by Leica Geosystems AG
FUSION (3.40 and up) by Bob McGaughey of the USDA
Voyager (1.3 and up) by Voyager GIS
LIDAR Analyst (5.2 or 6.0 and up) by TEXTRON Systems
TerraScan, TerraMatch, TerraPhoto, and TerraSlave (015.xxx and up) by Terrasolid
Carlson (2016 and up) by Carlson Software
Point Cloud Technology by Point Cloud Technology, GmbH
GRASS GIS (7.0 and up) by Open Source Geospatial Foundation (OSGeo)
PointCloudViz by mirage
LidarViewer by route scene

**Comment by adambreznicky** [comment]
added the additional lidar description info to the catalog entries for all datasets within the data-catalog.csv which have a 'Lidar' value populated in the 'tile_index' column. you can QC/review the change here: https://deploy.tnris.org/api/v1/preview/f22df65ae947f3445ec4d48b09e9fb4b5791837f/

if it all looks good, just let me know and i'll deploy it.
