### ISSUE TITLE
Have fallback graphic/behavior for copy url when flash isn't available

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#122]
Currently just a blank space if there is no flash.

**Comment by christoball** [comment]
@jseppi @wilsaj can this just say 'Service URL' when there's no flash?

![serviceurl](https://cloud.githubusercontent.com/assets/1877550/5763428/f7cb5992-9caf-11e4-9784-af05f415d0e0.jpg)

**Comment by jseppi** [comment]
I just made the buttons properly hide when Flash is unavailable. I also made the inputs auto-highlight when focused for easier ctrl-c pushing.
