### ISSUE TITLE
new dataset: naip 2016

### ISSUE THREAD

**Issue by gmullins** [TNRIS/tnris.org#1222]
- [x] Add data to measures spreadsheet @gmullins
- [x] Route Data Shipment [copy data to TNRIS Projects share] @mitchellryant 
- [x] Data Processing [renaming file, data organization, coverage map] @mitchellryant
- [x] Generate compressed JPEG2000 DOQQs @mitchellryant 
- [x] Quality Assurance @gmullins
- [x] Inform TNRIS staff of internal data availability @gmullins
- [x] Download Prep [zip, copy to s3 bucket] @mitchellryant
- [x] Move data to production shares @mitchellryant
- [x] Data Publication Update data catalog sheet @gmullins
- [x] Data Publication Create data catalog images @gmullins
- [x] Data Publication Supplemental reports staging @gmullins
- [x] Data Publication Tile Index staging @mitchellryant 
- [x] Data Story @gmullins
- [x] Publish data catalog (need data catalog url to add data to download) @christoball https://github.com/TNRIS/tnris.org/pull/1256
- [x] Add to Data Download @mitchellryant https://github.com/TNRIS/data-download/issues/85
- [x] Final Publication @christoball @gmullins
- [x] Inform TNRIS staff of public data availability @gmullins

**Comment by gmullins** [comment]
@mitchellryant I'm done with the images and supp reports.

**Comment by christoball** [comment]
Add images to admin/website/updates/naip 2016... folder
