### ISSUE TITLE
data catalog: macro for breakline download

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1224]
lidar breaklines have been uploaded to s3. a macro will need to be created to add the download link to the data catalog, similar to ones fro supplement reports and tile index.

@adambreznicky will be handling the issue, please keep @T-fal and @DavidHickman in the loop.

s3 location 
/tnris-datadownload/datacatalog/lidar_breaklines

**Comment by mitchellryant** [comment]
https://s3.amazonaws.com/tnris-datadownload/datacatalog/lidar_breaklines/

s3://tnris-datadownload/datacatalog/lidar_breaklines

**Comment by adambreznicky** [comment]
issue resolved via commit 0b2cc4ae776cd5607a18aa72f8c65585a19af145
