### ISSUE TITLE
data catalog: update 02/27/17

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1226]
@christoball Could you please update the data catalog csv? Made a couple of spelling corrections and added a new field (lidar_breaklines). this field will be used by a macro to add the breaklines as a download to the catalog. The macro will work similar to the macros for supplemental reports and tile index. @adambreznicky will be creating the new macro.

**Comment by adambreznicky** [comment]
issue resolved via commit 0b2cc4ae776cd5607a18aa72f8c65585a19af145
