### ISSUE TITLE
About page quotation from Texas Water Code

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#123]
The quoted mission of TNRIS is not actually in the Texas Water Code as it is currently written: http://www.statutes.legis.state.tx.us/Docs/WA/htm/WA.16.htm

> The mission of TNRIS is to provide a "centralized information system incorporating all Texas natural resource data, socioeconomic data related to natural resources, and indexes related to that data that are collected by state agencies or other entities." (Texas Water Code, 16.021).

**Comment by jseppi** [comment]
cc @christoball

**Comment by wilsaj** [comment]
The commit that closed this issue didn't touch the about page...

**Comment by wilsaj** [comment]
Ok, I see it now. Was in a different commit.
