### ISSUE TITLE
new dataset: brazos 2017

### ISSUE THREAD

**Issue by gmullins** [TNRIS/tnris.org#1241]
- [x] Add data to measures spreadsheet @gmullins
- [x] Route Data Shipment [copy data to TNRIS Projects share] @mitchellryant 
- [x] Data Processing [renaming file, data organization, coverage map] @mitchellryant
- [x] Quality Assurance @gmullins
- [x] Download Prep [zip, copy to s3 bucket] @mitchellryant
- [x] Move data to production shares @mitchellryant
- [x] Data Publication Update data catalog sheet @gmullins
- [x] Data Publication Create data catalog images @gmullins
- [x] Data Publication Supplemental reports staging @gmullins
- [x] Data Publication Tile Index staging @mitchellryant 
- [x] Data Story @gmullins
- [x] Final Publication @christoball @gmullins https://github.com/TNRIS/tnris.org/pull/1296
- [x] Inform TNRIS staff of data availability @gmullins
- [x] Add to Data Download @mitchellryant

**Comment by gmullins** [comment]
@mitchellryant I'm done with organizing and checking over this dataset. They are ready for you.

**Comment by mitchellryant** [comment]
@gmullins
![frabz-my-job-here-is-done-ac06cc](https://cloud.githubusercontent.com/assets/8459928/24922939/950c2784-1eb5-11e7-8396-5ba680679332.jpg)
