### ISSUE TITLE
data catalog counter needs fix (off by 8)

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/tnris.org#1244]
the total number of datasets on the data catalog counter is always 8 less than the number of datasets shown. i would bet many dollars this is due to datasets being added/removed from the catalog. 
 
![selection_036](https://cloud.githubusercontent.com/assets/5650145/24216367/f1092a16-0f09-11e7-922b-95bd9db2a921.png)
example-- searching for 'plss' shows -6 on the counter. 
searching 'bexar' lists 9 cards but only has 1 on the counter. 

need to look up how the number is originally generated and fixed to be more dynamic so that if datasets do come & go the counter doesn't need to updated again.

**Comment by christoball** [comment]
resolved in #1271
