### ISSUE TITLE
data catalog: otls data description

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1248]
@christoball 
Per GLO's request, please change the description on the [OTLS data page](https://tnris.org/data-catalog/entry/original-texas-land-survey/) as follows:
Email correspondence - [RE_ Railroad Commission OTLS Data 03272017.pdf](https://github.com/TNRIS/tnris.org/files/873386/RE_.Railroad.Commission.OTLS.Data.03272017.pdf)

**Description**

An interpretation, by the Railroad Commission of Texas (RRC), of the Original Texas Land Surveys boundaries and bay tracts. The dataset was derived by the RRC, from General Land Office (GLO) Abstracts of Original Land Titles, maps of State-Owned Submerged Lands of the Texas coast (bay tracts), and county maps compiled and drawn by GLO draftsmen, showing the boundaries of the original Texas land grants.
 
This dataset is a digital interpretation by the RRC of the geographic placement of the original land grants and bay area tracts, and is not a legal survey product.

Thank you!!!!

**Comment by mitchellryant** [comment]
I changed this in the google sheet. only really affects eh short and long description fields

@geochik It may be important to note, that the original description was more than likely directly lifted from the TxRRC OTLS metadata.
