### ISSUE TITLE
Put preliminary GeoRodeo Program up

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1250]

**Comment by christoball** [comment]
Will also post registration link.

**Comment by adambreznicky** [comment]
it is time to post the registration and tweet that registration is now open. 
Our keynotes can be posted on the website with their headshots and bios. They will be Todd Mostak & Sara Safavi. We will not be posting their presentation abstracts/subject matter yet.

Headshots can be found on the M: drive here:
smb://twdb4aefssvr/vault/Forum_GeoRodeo/2017 GeoRodeo/Speakers/Pictures
Bios can be found on the shared google spreadsheet: GeoRodeo Topic Submissions
