### ISSUE TITLE
Update 2017 Qtr 2 GIS Community meeting location

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1258]
Please update the GIS Community meeting location to:
**Texas Parks and Wildlife Department - Headquarters
4200 Smith School Rd
Austin, TX 78744**
Path - tnris.org/templates/partials/gio-meeting.html

**Comment by adambreznicky** [comment]
address updated.
commit #1b0f709270d19bc5122e52aceeceb10936201c1e

LINK:
https://tnris.org/geographic-information-office/
