### ISSUE TITLE
GIS Community Mtg Agenda Upload

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1260]
Please upload and send link to me when ready. 
Thank you!
[gio-meeting-agenda-20170418.pdf](https://github.com/TNRIS/tnris.org/files/906250/gio-meeting-agenda-20170418.pdf)

**Comment by geochik** [comment]
Adam, a million apologies. I just got an update from one of the speakers. Here is an updated version of the agenda.
[gio-meeting-agenda-20170418.pdf](https://github.com/TNRIS/tnris.org/files/906313/gio-meeting-agenda-20170418.pdf)

**Comment by adambreznicky** [comment]
LINK:
https://tnris.org/static/documents/gio-meetings/gio-meeting-agenda-20170418.pdf

agenda uploaded and now available.
commit #1b0f709270d19bc5122e52aceeceb10936201c1e
