### ISSUE TITLE
Videos for land parcels and address points

### ISSUE THREAD

**Issue by ilyannakadich** [TNRIS/tnris.org#128]
@christoball  According to Matt's email, the videos now have closed captioning and are located here:  S:\Shared\90Temp\TNRIS\Video  What is the next step to get them on YouTube and the Land Parcel and/or Address Points pages?  Thank you! Ilyanna

**Comment by christoball** [comment]
@ilyannakadich Can you provide some titles and a very short description of each one that can be used for the youtube?

**Comment by christoball** [comment]
@ilyannakadich how is this for Michelle Culver?

Michelle Culver, a Natural Resources Specialist with the Texas General Land Office's Beach Access and Dune Protection Program, speaks about how her agency uses the Address Points and Land Parcel data to monitor and regulate construction on Texas's beaches.

**Comment by ilyannakadich** [comment]
@christoball Sounds great!

**Comment by christoball** [comment]
@ilyannakadich @gmullins 

Here's a look at the videos embedded into the tops of the pages:
http://washburn.tnris.org/stratmap/land-parcels/

http://washburn.tnris.org/stratmap/address-points/

What do yall think?

**Comment by ghost** [comment]
@christoball @ilyannakadich I think they look great! Is there a way to freeze frame the land parcels one not on John's face? I like how the address points one is freeze framed on the fire scene. 
Will be fun to put one on the lidar page too when that gets produced by TWDB Comm.
Thx!

**Comment by christoball** [comment]
@gmullins I don't think the screenshots of the billboards are as interesting as the fire ones and I like seeing the texas graphic to tie it to the other pages. Take a look now, I put a screenshot where you can see his label so it makes more sense why he's on there.

http://washburn.tnris.org/stratmap/land-parcels/

**Comment by ilyannakadich** [comment]
@ilyannakadich @gmullins How about these short descriptions for the other two videos?

Texas Department of Transportation Right of Way Highway Beautification Program utilizes the statewide land parcel dataset to save time and effort in the billboard permitting process to examine land use, determine access rights, and remove illegal signs.

Texas A&M Forest Service utilizes the statewide address point dataset to quickly locate homes, evaluate threats, and provide reporting data for FEMA grants.
