### ISSUE TITLE
Lidar Status Map on Website and Carto

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1285]
Please remove all Lidar Availability and status maps off of the TNRIS main Carto site to avoid confusion/conflict with availability maps on the TNRIS StratMap page which are current. 

Also, how can we update [this map](http://tnris.maps.arcgis.com/apps/Viewer/index.html?appid=3a5712b6cc36472f8036446e7b49c52d)? If it is unnecessary then let us remove it as it does not accurately show current status.

**Comment by mitchellryant** [comment]
I changed the pop_link and status_map_cartodb_id in the data catalog to tnris-sm status map. The data catalog will need to be updated for changes to go through.

the esri map is the data in the lidar\_status dir, based on a dissolve of the actual availability index it contains **Project Name, Source, Flight Year, Vendor Acquisition, Vendor QAQC, Project Status, Data Catalog, Available Data** fields. a shape file is also available for download in the lidar availability zip. this map is typically updated after a dataset is moved to prod.  the pending areas are not in the status fc.

for your status map can you look at making the field names as human readable as possible?

**Comment by mitchellryant** [comment]
changed the lidar status map link in lidar availability canned response.

**Comment by ThorTheDestroyer** [comment]
fields have been renamed.

**Comment by mitchellryant** [comment]
I can not change the data catalog coverage map to your viz. the data catalog only has the viz number and the site builds the url around it. the full url to your map has your login name. 

you could share your data set with the main tnris account, and i could add that to the tnris viz.

**Comment by ThorTheDestroyer** [comment]
The map has been shared with the head tnris account

**Comment by mitchellryant** [comment]
@christoball can you update the data catalog to incorporate the 2 change to the lidar availability entry.

**Comment by mitchellryant** [comment]
@christoball since the data change frequently could we remove the overview and detail images and just use the coverage map.
