### ISSUE TITLE
data catalog: new fema lidar does not sort

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1286]
New fema lidar dataset alway first. do not sort.

is this by design? 

also an error on this page 

https://tnris.org/data-catalog/entry/fema-2014-rio-grande/ looks like some thing is not closed.

**Comment by christoball** [comment]
@mitchellryant fixing this. I need to regenerate the search index. 

When adding a new entry, it's also necessary to add a date to the **'Date_added'** field. @ThorTheDestroyer @gmullins
