### ISSUE TITLE
gio: add associate gio picture

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1292]
Can you add felicia photo to the following page https://tnris.org/geographic-information-office/?

She might like you to change the background or something

![thumbnail_felicia retiz](https://cloud.githubusercontent.com/assets/8459928/25489906/e49e6d2a-2b30-11e7-9cf0-23ecd3681982.jpg)

**Comment by christoball** [comment]
@geochik was the background on this photo removed?

**Comment by christoball** [comment]
You can see what the white background looks like here: https://beta.tnris.org/geographic-information-office/ @mitchellryant @geochik

**Comment by christoball** [comment]
resolved in #1288
