### ISSUE TITLE
Add Christine Doig and Tim Renner to the GeoRodeo page

### ISSUE THREAD

**Issue by DavidHickman** [TNRIS/tnris.org#1294]
Hey @christoball , 

Can you add Christine Doig and Tim Renner to the GeoRodeo page, please? Their photos are in the vault and presentation information has been added to GeoRodeo Topic Submissions. Let me know if you have any questions.

Thanks!

**Comment by adambreznicky** [comment]
completed via commit 4209de7cd3fa3b8bec881244ece6f4f8e4b4eac3
