### ISSUE TITLE
georodeo: create schedule

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1295]
8:00-8:45 Breakfast Social
8:45-9:00 Opening Remarks - Richard Wade
**_09:00-10:00 Keynote Todd Mostak, MapD_**
10:00-10:15 Break
10:15-10:45 Diana Turner, Marni Wilhite, City of Austin
10:45-11:15 Katherine Smyth, ESRI
11:15-11:45 Glynnis Ritchie
11:45-1:15 Lunch
**_1:15-2:15 Keynote Sara Safavi, Boundless_**
2:15-2:45 Christine Doig, Continuum Analytics 
2:45-3:00 Break
3:00-3:30 Tim Renner, Homeaway
3:30-4:00 Jason Deckman, KTMPO 
4:00-4:30 Lightning Talks
4:30-4:45 Closing Remarks
saw and liked this schedule: http://www.devopsdaysaustin.com/#schedule

**Comment by adambreznicky** [comment]
added sidebar agenda via commit 24c50cf8204582cadbe3e890392ffe8911c35bbf

@christoball you probably want to make the schedule more primary and the main content, as opposed to a side note like i did. 
Also, the breakfast explicitly mentions that ESRI sponsored it. i know we had 3 top level sponsors. their names should be explicitly mentioned on the schedule also, i just didnt know where/how.

thanks
