### ISSUE TITLE
data download search match order

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/tnris.org#130]
Should prioritize quads that begin with the thing being searched, instead of alphabetical order for any match. For example, the current behavior is:

![screen shot 2015-01-16 at 9 49 04 am](https://cloud.githubusercontent.com/assets/303866/5779013/f0bca038-9d64-11e4-9bce-4ef947037b0a.png)

But there's a quad named Spring (and several that begin with spring), so those should be first.

**Comment by jseppi** [comment]
It would be better to have this done on the API side. That way results could be limited to a smaller number and still maintain priority sorting.
