### ISSUE TITLE
GeoRodeo Site Updates

### ISSUE THREAD

**Issue by DavidHickman** [TNRIS/tnris.org#1307]
- [ ] Add Todd's picture next to his name on the agenda

- [x] Update link for Tim in Agenda Overview so it links to his speaking time 
fixed in https://github.com/TNRIS/tnris.org/commit/b75f040435a522ca8782500376ce660c4f80f275

- [ ] Add a note that people will be able to register on-site

**Comment by adambreznicky** [comment]
- [ ] Also, Brian Smith is the new speaker for the ATX Floods presentation. his headshot is on the vault. Please replace Marni's mention with his name/picture 

![](smb://twdb4aefssvr/vault/Forum_GeoRodeo/2017%20GeoRodeo/Speakers/Pictures/BrianSmith.JPG)

**Comment by mitchellryant** [comment]
duplicate issues
https://github.com/TNRIS/tnris.org/issues/1308
https://github.com/TNRIS/tnris.org/issues/1309
