### ISSUE TITLE
Edit javascript for GIO agenda once API is ready

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#131]
An issue to remind us to edit the javascript once the API has been adapted for the GIO Community Meeting Agenda.

**Comment by jwhaney** [comment]
close via PR #133. the new code is sitting on the develop branch for now until i get the new api code approved, merged, and deployed. then i'll merge the tnris.org develop branch into master to go to production.

**Comment by jwhaney** [comment]
@christoball everything is up and running now. both the api and tnris.org have been deployed. new form input for community meeting agenda pdf urls is available in the api admin console now. i went ahead and put the hardcoded url in the appropriate gio calendar event record. everything seems to work well. let me know if you have any questions or concerns.

![Screenshot from 2019-12-17 09-25-57](https://user-images.githubusercontent.com/13525011/71009181-70ad6980-20af-11ea-93b7-c31ba2b62947.png)
