### ISSUE TITLE
tnris.org: add Location to 3rd Qtr Mtg

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1315]
@christoball  Please add location to GIS Community meeting box.
Robert E. Johnson Conference Center
Room: Central
1501 N. Congress Ave.
Austin, TX 78701
http://www.roomsched.tlc.texas.gov/REJ/Assets/Graphics/map.gif

**Comment by mitchellryant** [comment]
added with https://github.com/TNRIS/tnris.org/commit/76cf9e7b0751f7811ef2603e96a74163972c3e61
