### ISSUE TITLE
GeoRodeo Wrap-Up

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1325]
Updated the front page to remove the banner, but unfortunately, I couldn't figure out how to embed Sara's web page into the agenda as a presentation. I did embed Christine's speakerdeck.

If y'all can come up with some ideas how to share Sara's, or get the original file that can be turned into a speakerdeck, that could work. Or we can just link to it.

**Comment by mitchellryant** [comment]
Diana\Byran, Sara, Glynnis, Katherine, and Jason's presentation added.
