### ISSUE TITLE
file uploads

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/tnris.org#133]
Allow file uploads from order form so people can submit AOI files. A few other future use cases have been floated, too, so it should be pluggable.

**Comment by jseppi** [comment]
I think probably client-side uploads to an S3 bucket will be the best approach for this. Then the submitted form should contain the path returned from the uploaded file.
This will mean we will need a microapp to generate short-lived S3 policies.

**Comment by wilsaj** [comment]
Agreed about S3. We should also set a policy to expire / archive files: http://docs.aws.amazon.com/AmazonS3/latest/dev/intro-lifecycle-rules.html

**Comment by jseppi** [comment]
working on this one

**Comment by jseppi** [comment]
I set a 2-week delete policy on the bucket

**Comment by jseppi** [comment]
implemented as of c7f3b82c6fbbc07c41a4e066fb79e8069c0fe820

**Comment by jseppi** [comment]
@ThorTheDestroyer 
This should be working now. The upload portion of the form is shown when the user selects that they have a Site File (for a LiDAR data request). When the order form is submitted, the form values will include a link to the uploaded file.

The upload section will not show up if the browser doesn't support the way we're doing uploads (IE 9 and earlier).

**Comment by ThorTheDestroyer** [comment]
Thank you James! I’ll let the RDC staff know.

-Joey
