### ISSUE TITLE
new stratmap dataset not searchable

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/tnris.org#1335]
the new StratMap Brazos 2017 6in NC\CIR dataset is not searchable/sortable within the data catalog. this is because it is not present in the /static/js/data-catalog/attribute.js object. 
Please run the python script to update this object file. it will then include the current datasets present in the data-catalog.csv so that the search/sort functionality will recognize this new data.

please holler for me if ya need a hand. i'd be happy to help.

**Comment by christoball** [comment]
Resolved in recent pull requests.
