### ISSUE TITLE
StratMap Contracts page rewrite

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#134]
@christoball 
Special Announcement across the top (to be removed after solicitation closes in early February).
Small change:
After four years of success, the re-bid of StratMap contracts is coming up this December 20, 2019!

Body change:
The [Department of Information Resources (DIR)](https://dir.texas.gov/) maintains multiple [Cooperative Contracts](https://dir.texas.gov/View-About-DIR/Pages/Content.aspx?id=41) which are designed to strengthen Texas’ capabilities to procure quality digital map data, services and software. The contracts are for use by customers that include Texas state, regional and local government offices, including river and water authorities, and public education entities. The process for procuring GIS products, custom geospatial data and services and software is administered by TNRIS and known as the **Texas Strategic Mapping (StratMap) Contracts**. 

The StratMap/DIR Contracts are awarded to companies which are technically evaluated by a team of GIS professionals and determined to **provide quality geographic data products, services,** and **GIS software**. The availability of these contracts **streamlines the procurement process** for any acquisition of geographic data, services, and software and provides beneficial competition among some of the best companies in the industry.

Change:
Vendors heading to Vendors 2016 - 2020

Thanks!

**Comment by christoball** [comment]
@gmullins I'm going to combine this into #108
