### ISSUE TITLE
tnris.org: note about WMS services changing

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1361]
as part of the migration to AWS all the ArcGIS Server and WMS urls will be changing.  After Aug 31 any link to r.tnris.org will not work.

**Comment by christoball** [comment]
Have a top header warning and write an article.

**Comment by mitchellryant** [comment]
- migration of server\services to different cloud provider
- url for all services raster and vector will change
- all services will be on same server
- services will continue to be published as both ArcGIS and WMS services.
- reduction in number of services with focus on NAIP, TOP, and StratMap images
- increase in speed and quality
- increase in vector services published
- investigation of publishing services of elevation data






To access the services in ArcGIS:
1. In ArcMap, choose Add Data > GIS Servers > Add ArcGIS Server
2. Select Use GIS services
3. Insert the URL https://webservices.tnris.org:6443/arcgis/services and click Finish.
4. After completion you will be be able to see all ArcGIS services.

**Comment by christoball** [comment]
Changes to instruction button

**To access the services in ArcGIS Desktop:**
1. In ArcMap, choose Add Data > GIS Servers > Add ArcGIS Server
2. Select Use GIS services
3. Insert the URL https://webservices.tnris.org:6443/arcgis/services and click Finish.
4. After completion you will be be able to see all ArcGIS services.

**To access the services in ArcGIS Pro:**
1. On the Insert tab, in the Project group, click the Connections drop-down list and click New ArcGIS Server. The Add ArcGIS Server User Connection dialog box appears.
2. Type the URL of the ArcGIS Server site you want to connect to in the Server URL text box. The URL varies depending on the site configuration. https://webservices.tnris.org:6443/arcgis/services
3. Click OK.

**Comment by KCMack** [comment]
Effective August 31, all online map services will migrate to a different cloud provider.  
What this change means to you:
•	The URL for all raster and vector services will change.  
•	Web services URLs will be consolidated. 
•	Web services will continue to be hosted as both ArcGIS and WMS services.  
•	Fewer Orthoimagery web mapping services will be available, however they will continue to be available for download through the data catalog.
•	All NAIP, TOP, and StratMap image datasets will continue to be offered as web map services. 
The benefits to you: 
•	Increase in speed and image quality.
•	Increase in number of vector services published.
Also,  we’re investigating the potential to publish elevation data services.  Stay tuned for this update.

**Comment by KCMack** [comment]
Good to go.

**Comment by christoball** [comment]
Requesting @adambreznicky help dismissing the alert

**Comment by christoball** [comment]
I've incorporated the content and its now ready for review.

Front page with alert: https://preview.tnris.org/haish/2473b7bbf1c9f5be8cd3286963c366418e8f98ac/

Article: https://preview.tnris.org/haish/2473b7bbf1c9f5be8cd3286963c366418e8f98ac/news/2017-08-25/major-changes-improvements-online-map-services/

Online Map Services page:
https://preview.tnris.org/haish/2473b7bbf1c9f5be8cd3286963c366418e8f98ac/maps-and-data/online-mapping-services/

**Comment by KCMack** [comment]
Is it possible to Bold the letters on the front page banner for at least the first two weeks of September?

**Comment by christoball** [comment]
@KCMack i reformatted the alert to be more prominent.

https://preview.tnris.org/haish/d81faf5d05da7a09c304206cc7c88a2492619765/

**Comment by KCMack** [comment]
Much better - eye catching

**Comment by christoball** [comment]
@adambreznicky just a heads up, I rushed and merged this into master without the script to keep the alert dismissed.

**Comment by adambreznicky** [comment]
not a problem - i would have suggested you to do so.
i'm working on the dismissal functionality now and will close this issue when i push that into master.

**Comment by adambreznicky** [comment]
functionality enhanced so that when a user dismisses the banner it stays hidden within their browser despite which page they visit or exiting and returning to the page.
this change has already been deployed.
resolved via commit 3bef0a70c6c7626eb70b682dd135bd370b2df4e5
