### ISSUE TITLE
Upload-Parcel-Study

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1365]
@christoball 
Please upload and provide the links. Thank you!

[Texas_Statewide.Parcel.Data.Report_FINAL.pdf](https://github.com/TNRIS/tnris.org/files/1156139/Texas_Statewide.Parcel.Data.Report_FINAL.pdf)
[Texas_Statewide.Parcel.Data.Supplement_FINAL.pdf](https://github.com/TNRIS/tnris.org/files/1156138/Texas_Statewide.Parcel.Data.Supplement_FINAL.pdf)

**Comment by christoball** [comment]
@geochik Docs are available as links on GIO page 'Documents' section:
https://tnris.org/geographic-information-office/
