### ISSUE TITLE
test

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/tnris.org#1369]
New article added to Washburn Branch. 
https://preview.tnris.org/washburn/550763710475c29089419280de917361921cff0c/news/2017-06-29/lost-as-child-online-maps-pointed-hometown-forum-keynote-saroo-brierley/

**Comment by jseppi** [comment]
![image](https://user-images.githubusercontent.com/697848/28481180-820c0d7a-6e29-11e7-8493-7984d0241488.png)
