### ISSUE TITLE
SM Contracts text edit

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#137]
@christoball At the top of https://tnris.org/stratmap/stratmap-contracts/ , can you please change "For the solicitation release date and other....." to "For the solicitation **response due date** and other....."

thx!

**Comment by christoball** [comment]
@gmullins preview up here and going ahead and pushing to production.

http://washburn.tnris.org/stratmap/stratmap-contracts/

**Comment by ghost** [comment]
@christoball perfect
