### ISSUE TITLE
US Census Bureau 

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1373]
Please add to Around the State

US Census Bureau Update
The US Census Bureau recently announced important information for Texas about the 2020 Local Update of Census Addresses and new job openings for Geographic Specialists

Local Update of Census Addresses
On July 14, the US Census Bureau began to mail the Local Update of Census Addresses (LUCA) Invitation packets to all Highest Elected Officials (HEO).  They will continue to mail through the end of the month.  Many local GIS officials will receive a courtesy copy of the invitation.  Interested individuals should check with their HEO if they do not receive an invitation by August 1st.  More information can be found on the Census Bureau’s website https://www.census.gov/geo/partnerships/luca.html. Or call with questions 1-844-344-0169 or email at GEO.2020.LUCA@census.gov.

Open Positions
The Census Bureau has a few temporary Geographic Specialist positions opening in the Dallas-Fort Worth metro area. They will recruit from Denver but will open a geographic operation office in Irving, TX starting in April of 2018.  The position announcement and description can be found on the US Census Bureau website 
https://www.census.gov/about/census-careers/opportunities/positions/region-field/geo-spec/DENRO-GS-TX.html

**Comment by christoball** [comment]
@KCMack view preview here: https://deploy.tnris.org/api/v1/preview/8f8597f1382ead5cdc290aee64b9834282fb3a0f/around-the-state/2017-07-28/us-census-builds-towards-2020-regional-updates-jobs/
