### ISSUE TITLE
www.tnris.texas.gov Not working

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1383]
Not sure how long this has been issue because I don't check the url regularly - but the TWDB page  uses the **www.tnris.texas.gov** url on their link to our page and it is currently not working.

Did this change in the shift or have we not been maintaining that link?

**Comment by adambreznicky** [comment]
okay, i added www.tnris.texas.gov to the list of accepted domains for cloudfront so the link works now. but there is no ssl cert applied to www.tnris.texas.gov so it's popping an 'unsecure' warning. problem is that we do not own or maintain the texas.gov domain (obviously) so we cannot apply the ssl cert to that domain....

the owner of texas.gov will have to apply it. i wouldnt know where to begin to find out who manages that...

**Comment by adambreznicky** [comment]
Ryan spoke with Paul, the domain is going to be deprecated. i have removed this domain from cloudfront's CNAME list
