### ISSUE TITLE
new article review

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/tnris.org#1384]
i addded bladhlda
previeww.tnris.org

**Comment by adambreznicky** [comment]
fix the spelling

**Comment by adambreznicky** [comment]
https://juntoo.co/s/ee0da63
these are my changes

**Comment by KCMack** [comment]
Is this what you intended for me to review:

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
