### ISSUE TITLE
data catalog: GLO broken links

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1386]
We did this before, so maybe the data was reverted with the UI change.

GLO Colonial Waterbird Rookery Areas layer was supposed to be removed.

**TNRIS Data Catalog Broken Link**
GLO Beach Access Points | http://www.glo.texas.gov/land/land-management/gis/files/BeachBayAccess.zip

GLO Coastal Leases (Point Locations) | http://www.glo.texas.gov/land/land-management/gis/files/NonMineralPt.zip

GLO Coastal Leases (Polygon Locations) | http://www.glo.texas.gov/land/land-management/gis/files/NonMineralPoly.zip

GLO Environmental Sensitivity Index Shoreline | http://www.glo.texas.gov/land/land-management/gis/files/ESI.zip

GLO Priority Protection Habitat Areas | http://www.glo.texas.gov/land/land-management/gis/files/PPA.zip

GLO State Submerged Lands | http://www.glo.texas.gov/land/land-management/gis/files/StateSubmergedLands.zip

GLO Oil & Gas Leases | http://www.glo.texas.gov/land/land-management/gis/files/ActiveLeases.zip

GLO Oil & Gas Pooling Agreements/Units | http://www.glo.texas.gov/land/land-management/gis/files/ActiveUnits.zip

**Comment by adambreznicky** [comment]
you're correct, they were removed before. I think the markdown-entries branch had already been created when they were previously removed, so when we merged the markdown entry pages into production it brought them back.
conveniently, the using markdowns for the entries pages makes it easy to remove them. their markdown pages just need to be deleted.

**Comment by christoball** [comment]
Resolved in latest merge into master
