### ISSUE TITLE
Forum Social Page

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1387]
Preview first draft here:
https://beta.tnris.org/texas-gis-forum/2017/social/

@KCMack @rwade2126 @geochik

**Comment by christoball** [comment]
Please consider this:
30 years of the Texas GIS Forum will be celebrated with a spectacular social event at the Starlight Terrace at The Oasis on Lake Travis, the Sunset Capital of Texas. Thanks to our our Platinum Sponsors, let’s celebrate with amazing entertainment, scrumptious food and drinks, with a knock-your-socks out view.

3:00 PM – Shuttles begin leaving from the J.J. Pickle Center to the Oasis
4:30 PM – Keynote Speaker Saroo Brierley
5:30 PM – Kick off the social with music by Colton Turner and the Rockin’ Roses
6:45 PM – Sunset
7:00 PM – Shuttles begin leaving the Oasis back to the J.J Pickle Center

The social is included with your GIS Forum registration.
If you wish to drive instead of taking the shuttle, the Oasis Restaurant is located at:
6550 Comanche Trail,
Austin, Texas 78732
512.266.2442

Note: add the Platinum sponsors at the bottom of the page one time, either as part of the narrative, or with the rest of the sponsors, but not twice.

Thanks!

**Comment by christoball** [comment]
Updated version:
30 years of the Texas GIS Forum will be celebrated with a spectacular social event at the Oasis on Lake Travis, the Sunset Capital of Texas. Thanks to our Platinum Sponsors, we will celebrate this milestone occasion with an inspirational keynote speaker, amazing entertainment, scrumptious food and drink, and a knock-your-socks off view.

Also, the schedule can be emphasized by boxing it with color and white text - or outlined

**Comment by adambreznicky** [comment]
this looks great.
