### ISSUE TITLE
Thursday social page 

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1393]
Please consider this:
30 years of the Texas GIS Forum will be celebrated with a spectacular social event at the Starlight Terrace at The Oasis on Lake Travis, the Sunset Capital of Texas.  Thanks to our our Platinum Sponsors, let’s celebrate with amazing entertainment, scrumptious food and drinks, with a knock-your-socks out view.

3:00 PM – Shuttles begin leaving from the J.J. Pickle Center to the Oasis
4:30 PM – Keynote Speaker Saroo Brierley
5:30 PM – Kick off the social with music by Colton Turner and the Rockin’ Roses
6:45 PM – Sunset
7:00 PM – Shuttles begin leaving the Oasis back to the J.J Pickle Center

The social is included with your GIS Forum registration.
If you wish to drive instead of taking the shuttle, the Oasis Restaurant is located at:
6550 Comanche Trail,
Austin, Texas 78732
512.266.2442

Note: add the Platinum sponsors at the bottom of the page one time, either as part of the narrative, or with the rest of the sponsors, but not twice.

Thanks!

**Comment by christoball** [comment]
There's already an issue for this. Moving the content there.
https://github.com/TNRIS/tnris.org/issues/1387

**Comment by KCMack** [comment]
Updated version:
30 years of the Texas GIS Forum will be celebrated with a spectacular social event at the Oasis on Lake Travis, the Sunset Capital of Texas.  Thanks to our Platinum Sponsors, we will celebrate this milestone occasion with an inspirational keynote speaker, amazing entertainment, scrumptious food and drink, and a knock-your-socks off view.

Also, the schedule can be emphasized by boxing it with color and white text - or outlined

**Comment by KCMack** [comment]
Reopened to make edits to the text in beta.
Thanks
