### ISSUE TITLE
adding 3rd quarter 2017 gis community meeting notes

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1396]

**Comment by geochik** [comment]
@christoball 
The draft recap page is under review. Still pending are the following:

1. Adding logos to the tnris.org/static/images/gio-stories/logos/ folder (attached)
  -these logo file names have already been embedded into the web doc.
![txdmv_logo](https://user-images.githubusercontent.com/7750220/29574263-ae053ea4-8726-11e7-9a0e-af9b77b685bf.png)
![txgov_logo](https://user-images.githubusercontent.com/7750220/29574259-adeb8f68-8726-11e7-8b63-c3fe1aed6007.png)
![puc_logo](https://user-images.githubusercontent.com/7750220/29574260-adfc6b6c-8726-11e7-93e7-4296a53081e9.png)
![txcpa_logo](https://user-images.githubusercontent.com/7750220/29574261-adfd1ac6-8726-11e7-97ec-3c6135b4d2d4.jpg)
![floodviewer_logo](https://user-images.githubusercontent.com/7750220/29574262-adffcd16-8726-11e7-888d-5097a4bcabb5.png)
![census-logo](https://user-images.githubusercontent.com/7750220/29574264-ae0d350a-8726-11e7-8f86-5c74833b5eca.png)
![tda_logo](https://user-images.githubusercontent.com/7750220/29574265-ae0e9512-8726-11e7-84f8-23f6cf2b5946.jpg)

2. Adding slide decks to speaker deck and correcting the links on the web page. The slide decks are available here - M:\Admin\GIO\QtrlyCommunityMtgs\2017\Qtr3\Slides.

**Comment by geochik** [comment]
@christoball 
The first issue of uploading the image files is resolved.

**Comment by geochik** [comment]
https://preview.tnris.org/glidden/4831be24ead4ae9404da420293445edc0997da68/geographic-information-office/2017-07-18/gis-community-meeting-recap-3rd-quarter/

**Comment by geochik** [comment]
Review complete - FDR
@christoball  Ready for updates to slides and images

**Comment by christoball** [comment]
@geochik @KCMack Ready for final review:

https://preview.tnris.org/glidden/1e4f11c50e6ca9025a98c41b889fb2b6e1e0e8aa/geographic-information-office/2017-08-24/gis-community-meeting-recap-3rd-quarter/

**Comment by geochik** [comment]
My review is complete. Approved.

**Comment by KCMack** [comment]
The power point slide immediately following the GeoRodeo, StratMap Lidar needs fixing.  The words run over each other in the section listing StratMap Partners.

**Comment by christoball** [comment]
@KCMack its fixed now on the speakerdeck site. Is that the only fix?
