### ISSUE TITLE
forum sponsors: add razortek, hexagon

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1398]
add logos and links to forum sponsors section

**Comment by christoball** [comment]
Gold - Professional Plotter Technology Corporation
Silver - Sanborn

**Comment by christoball** [comment]
Ready for review by @KCMack 
https://beta.tnris.org/texas-gis-forum/2017/

**Comment by KCMack** [comment]
Pls make the following changes:
Sanborn,  please move from Gold to Silver
Professional Plotter, please move from Silver to Gold 
Razor-Tek, Exhibitor name - please update with hyphen and captial T

**Comment by christoball** [comment]
@KCMack I Fixed these issues, it's ready to go.

https://beta.tnris.org/texas-gis-forum/2017/

**Comment by KCMack** [comment]
Looks terrific!
