### ISSUE TITLE
Land Parcel website FAQ updates

### ISSUE THREAD

**Issue by ilyannakadich** [TNRIS/tnris.org#14]
@christoball  Please replace the existing FAQs with the attached.
[09102019 FAQs.docx](https://github.com/TNRIS/tnris.org/files/3596003/09102019.FAQs.docx)

**Comment by adambreznicky** [comment]
@ilyannakadich could you please export your document to a pdf and re-attach to this issue? .doc files are not web friendly or secure. pdf is the ideal format. thanks.

**Comment by ilyannakadich** [comment]
[09102019 FAQs.pdf](https://github.com/TNRIS/tnris.org-deux/files/3596572/09102019.FAQs.pdf)

**Comment by christoball** [comment]
@adambreznicky you're correct that PDFs are better for documents uploading, but she was providing content for the website, not a document upload.

@ilyannakadich Basically, if it's an actual document that will be downloadable on our site, like the land parcel study update doc for example, we prefer PDFs. 

When you're providing content that will go on the page, I'm fine with word docs or pasting directly into the comments here.

Sorry for the confusion, let me know if you need any clarification.

**Comment by adambreznicky** [comment]
gotcha! <thumbs up emoji>

**Comment by ilyannakadich** [comment]
@christoball  Thanks for the clarification!  On that note, can you please hyperlink the words "TNRIS land parcel schema" to the attached pdf document in 3rd and 4th FAQ?  

Also, add a link within the website intro sentence on left side "...GIS land parcel schema"

[TNRIS Land Parcel Schema.pdf](https://github.com/TNRIS/tnris.org-deux/files/3596816/TNRIS.Land.Parcel.Schema.pdf)

**Comment by christoball** [comment]
@ilyannakadich the FAQ is now updated:
http://washburn.tnris.org/stratmap/land-parcels/

**Comment by ilyannakadich** [comment]
@christoball I made edits throughout the FAQs and prefer a complete replace as to not miss anything. There are four FAQs missing and a few have not been updated.  Should be a total of 12.  Also, the last FAQ has a Contact Us issue - should be TCPA.

**Comment by christoball** [comment]
@ilyannakadich i did completely replace it there was minor html error that messed something up. 

Fixed it: http://washburn.tnris.org/stratmap/land-parcels/

**Comment by ilyannakadich** [comment]
@christoball  One small edit on the first FAQ:  What is a geographic parcel? should be 

What is a geographic land parcel?

The rest looks great!

**Comment by christoball** [comment]
@ilyannakadich got it. fixed and moving forward to production.

http://washburn.tnris.org/stratmap/land-parcels/
