### ISSUE TITLE
Forum: Add Agenda

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1400]
Add forum agenda to website

View first draft here:
https://preview.tnris.org/ellwood/97185067733750cc6db6a3366926ff800f1cdf65/texas-gis-forum/2017/agenda/

**Comment by KCMack** [comment]
Kyle Walker's head shot
[Uploading walker_photo.png...]

**Comment by KCMack** [comment]
Pls change Opening Remarks to Welcome & Introductions for all three mornings
Add Bern's Title - Chief Technology Advocate and Product Strategist at Esri
Wednesday 9:00 - 10:30 middle session Digging Deeper: Detailed GIS Data Management for NG 9-1-1 - David Peck, West  - update the speakers
Thursday afternoon session correct last name spelling -  Daniel Sheehan, CARTO
Friday session - Add Big Tex
Welcome & Introductions - add 8:15

Thank you.

**Comment by KCMack** [comment]
Correction to  my comments: The Thursday 9:00 - 10:30 session Digging Deeper speaker change.

**Comment by christoball** [comment]
Agenda with latest round of edits:
https://preview.tnris.org/ellwood/cb657719f6009195b69999c4c52a5e7b6832a65c/texas-gis-forum/2017/agenda/

**Comment by KCMack** [comment]
Additional updates to the agenda (post Forum conference call):
Thursday schedule:
3:00 Break - Board Buses for Oasis Keynote and Social Event
3:30 Buses Depart
4:15 Opening Remarks and Special Keynote Speaker
5:30 Social Event
6:45 Sunset
7:15 Board Buses for the Pickle Center Commons
7:30 Buses Depart

Thursday Program changes:
9:00 session - Geodetically Accurate GIS..... Remove Ashton Brinkley

Rename Tech Demos to Platinum Presentation on both Wednesday and Thursday

**Comment by KCMack** [comment]
Request review by geochik -

**Comment by geochik** [comment]
@christoball 
Please change Joanna Sanchez Edwards to:
Joanna Sanchez, Ph.D.
Picture attached.
![JoannaSanchez.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599c64cafada7e0606ba7cba/125516c66e82c728ace21e0d46c29b9b2d8c829a8ee7bc4ba147b2d86b56357c2301a03f32dfa17de615295459561af8430d0a43fcf98929afb3382388090cffcd7f1d2598694ef1e1c84afd13b0328d4b83b7b68b49c0eb3b22e68986463e18030ac4.jpg)

**Comment by geochik** [comment]
@christoball 

-Please omit the name Ashton Binkley, Binkley & Barfield, Inc. from Session A Thursday morning slot.

 -Please change the organization for Stephanie Long from TPWD to Austin Community College.

 -Please spell out the following names:
    -D. Haverlah to Daniel Haverlah (correct last name spelling)
    -J. Jordan to Jeffrey Jordan
    -J. Bixby to Jeremy Bixby
    -J. Branigan to John Branigan
    -D. Arctur to David Arctur
    -H. Evans to Harry Evans
    -B. Porter to Brent Porter
    -J. Trelogan to Jessica Trelogan

 -Please add Michael Ouimet, Texas Division of Emergency Management to the Developing Near-Real-Time Flood Impact Mapping in Texas

@KCMack

**Comment by geochik** [comment]
@christoball 

Found a couple more things.....
-Adjust the time format for the pre-conference workshops to match the rest of the agenda schedule. The inconsistency is also present in the Thursday session times.
 *Either use a.m./p.m. or AM/PM.

-Is it necessary to use the word "Conference" above each of the three conference days?

-Regarding the "Unstarred presentations will be greyed out." comment, does that mean they are all greyed out until they get starred? Or does it mean if they choose to "Show Only My Starred Presentations" the unstarred will be greyed out? If the latter, I suggest moving the "greyed out" statement  (in parenthesis) after the checkbox statement.

**Comment by geochik** [comment]
Review complete - FDR

**Comment by christoball** [comment]
agenda incorporating latest edits:
https://preview.tnris.org/ellwood/e95344b0be88023066382c88894aa8d4407fcf91/texas-gis-forum/2017/agenda/

**Comment by geochik** [comment]
Very nice! One issue remains unfixed:
-Please omit the name Ashton Binkley, Binkley & Barfield, Inc. from Session A Thursday morning slot.

Sean Wohltman headshot attached.
![SeanWohltman.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599c64cafada7e0606ba7cba/125516c66e82c728ace21e0d46db919b2db58ca183fdb242aa1fbcd6395428792c07b7692ac7b671e8102e57560b1aae140d5844fcf98b22a3b26f72df5b19f1c32f0e2a92624cf5f2d75dad0ba8238a4584b3bc894ac8e03b20e18f8e4d2c53.jpg)

**Comment by christoball** [comment]
made those edits, added sean photo. 

https://preview.tnris.org/ellwood/1384762efda64775b98143beb7f60280ea0e6e49/texas-gis-forum/2017/agenda/

Front page with featured speaker headshots
https://preview.tnris.org/ellwood/1384762efda64775b98143beb7f60280ea0e6e49/texas-gis-forum/2017/
