### ISSUE TITLE
Added NGA WMS Links

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/tnris.org#1403]
added 4 WMS links to the NGA dataset. 
wasn't sure the category of the links on the WMS Services page so I just added them to Texas Orthoimagery Program. let me know if you want me to change this.

https://preview.tnris.org/razor-wire/56d014b356847738a1ec0c6ba80a894bb381ad9f/

please review the data catalog entry page, and WMS services page to make sure everything looks right and the links seem valid

**Comment by KCMack** [comment]
Eliminate the extra : in To Access Services in ArcGIS Pro

**Comment by christoball** [comment]
@KCMack i fixed that extra colon:

https://preview.tnris.org/razor-wire/3704f0f5474f43c682022e3a8ed832349b98bdc6/maps-and-data/online-mapping-services/

**Comment by KCMack** [comment]
Great.  Thanks.

**Comment by christoball** [comment]
Does this need anything else or is it ready to merge?

**Comment by KCMack** [comment]
I think it's ready to go.  Let it rip!

**Comment by christoball** [comment]
resolved in bd85aa10f5bd4b55785a7dc0a7e8f3922b8616f6
