### ISSUE TITLE
Todd Mostak bio and session topic

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1407]
Session Topic: GPUs & Their Role in Geovisualization

Bio: As a research fellow at the Computer Science & Artificial Intelligence Lab at MIT, Todd recognized the possibilities behind the mechanics of Xbox and PlayStation to transform traditional data analytics platforms. Replacing his CPU for a GPU, Todd was one of the first innovators to discover the untapped potential of GPUs to analyze, visualize and explore data in ways never done before. Now? He is reducing query times from hours to milliseconds for companies like Verizon, Amazon, Simulmedia and npm, enabling them to spend significantly less time crunching data and more time analyzing it to make key business decisions.

**Comment by christoball** [comment]
@KCMack updated todd's info:
https://preview.tnris.org/ellwood/ddfa140693537e603d62db3d2e040e26812b739e/texas-gis-forum/2017/agenda/#todd-mostak

**Comment by KCMack** [comment]
Looks good.  Thanks very much.

**Comment by christoball** [comment]
resolved in f5dc3d8bae76a15befdb9254c3a2fafc5739f318
