### ISSUE TITLE
Joanna Sanchez bio

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1410]
Minor editorial changes:
Joanna was born and raised in the Texas Rio Grande Valley, and earned her undergraduate degree from Trinity University in Geosciences. Joanna’s work with her non-profit, Odisea, and the Gates Millennium Scholarship Association and Hispanic Scholarship Fund (she is a recipient of both), inspired her to go back to school. In 2017, she earned her Ph.D. in the Department of Educational Administration at UT-Austin where she conducted research projects that incorporated the use of GIS and spatial analysis to explore research and policy questions. Her policy experience includes work with Texas State Representative Mary González and as a policy fellow with the White House Initiative on Educational Excellence for Hispanics in Washington, D.C. She currently holds a postdoctoral research associate position in K-12 STEM Education at Howard University in Washington, D.C

**Comment by KCMack** [comment]
Please give one more review before it moves to "ready to go!"

**Comment by christoball** [comment]
incorporated these edits:
https://preview.tnris.org/ellwood/6773958a264936db775aeeb8f18ca3f0e677a120/texas-gis-forum/2017/agenda/#joanna-sanchez

**Comment by KCMack** [comment]
Consolidated the bio.

Joanna was born and raised in the Texas Rio Grande Valley, and earned her undergraduate degree in Geosciences from Trinity University. Joanna’s work with her non-profit, Odisea, and the Gates Millennium Scholarship Association and Hispanic Scholarship Fund (she is a recipient of both), inspired her to go back to school. In 2017, she earned her Ph.D. in the Department of Educational Administration at UT-Austin where she conducted research projects incorporating the use of GIS and spatial analysis to explore research and policy questions. She gained policy experiences with Texas State Representative Mary González and as a policy fellow with the White House Initiative on Educational Excellence for Hispanics. She is currently a postdoctoral research associate in K-12 STEM Education at Howard University.

**Comment by christoball** [comment]
resolved in da9e825dd38373d99be76452727885443a84af38
