### ISSUE TITLE
Make category pills on Data Catalog entries linkable

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1412]
Would like to see the category pills on data catalog entries go to a page of that category.

Could it link to the main data catalog page with the filter already set to that category? This could also lead towards creating urls with filters that could be shared.

![link](https://user-images.githubusercontent.com/1877550/29887548-678c830c-8d83-11e7-9cb7-83e7672a4c68.jpg)

**Comment by adambreznicky** [comment]
this *will* require creating URLs within the data catalog. which in turn requires creating a router for it... and it will then no longer be static and instead a separate app. I think this is a little out of scope for the current structure of the site and not really *worth* (for lack of a better word) embarking in.

i think it would be more wise to consider this type of thing and roll it into a larger, reconfiguration of the site as a whole -- bringing together data download, data catalog, historical aerials, and creating a map catalog.

**Comment by mitchellryant** [comment]
added to #1320
