### ISSUE TITLE
data catalog: Add WMS links for Brazos 2015

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1413]
multiple wms services with to one data catalog entry.

StratMap Brazos 2015 6in NC\CIR - https://webservices.tnris.org/arcgis/services/StratMap/StratMap15_NC_CIR_6in_Brazos/ImageServer/WMSServer

StratMap Palestine 2015 6in NC\CIR - https://webservices.tnris.org/arcgis/services/StratMap/StratMap15_NC_CIR_6in_Palestine/ImageServer/WMSServer

stratmap-brazos-and-palestine-2015-6in-nc-cir.md

**Comment by adambreznicky** [comment]
https://preview.tnris.org/razor-wire/b20c640e4914138ac82afceec35b7066ae4d5301/

please review the wms links page and the data catalog entry to make sure it all looks good. if so, it can be merged into master/prod. you can do it or i can, just lemme know

**Comment by mitchellryant** [comment]
everything looks good. @christoball please merge to master

**Comment by christoball** [comment]
resolved in b20c640e4914138ac82afceec35b7066ae4d5301

merging into master
