### ISSUE TITLE
Make Harris the same logo in both spots

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1415]

**Comment by christoball** [comment]
Richard requested both logos appear the same, wihtout the 'geospatial solutions'

**Comment by christoball** [comment]
made logos the same. @pwblanton @KCMack double check here:
https://preview.tnris.org/ellwood/a8fa3f7932357de9ca1be557c68f21d0f212ef34/texas-gis-forum/2017/

**Comment by pwblanton** [comment]
Thank you!!!
