### ISSUE TITLE
Head shots for Lacey Loftin

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1418]
Workshop Instructor Head shot

**Comment by KCMack** [comment]
![Loftin Biography Picture Map.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599df692453cba2d8789d6c6/125516c66e82c728ace21e0d46c49b9c378b8de9ade0b044b65ce09c3006177a2a10b63975c5ce29af0037431f1d11f6140b1b56f6eb8c22a1b4397683085fef84385874c63d13a5bd864cbd54bd32975dc7e7e2de139db17770a599855d3f160f198cff5932a99148c95af74fe35f18.png)

**Comment by christoball** [comment]
resolved in ad6a143b0a8d63dbceaa3d16b72ac0af98324d16
