### ISSUE TITLE
Add photos - J. Harrison, E. Pimpler, J. Castagneri, Katherine Symth

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1419]
Photo for Jennifer Harriso
![jenny](https://user-images.githubusercontent.com/4912083/30172013-275a9378-93b9-11e7-8e2c-262c524af158.jpg)
n

**Comment by KCMack** [comment]
Eric Pimpler
![img paper](https://user-images.githubusercontent.com/4912083/30175256-7eed1cfa-93c3-11e7-9255-8c8556e80503.jpg)

**Comment by KCMack** [comment]
James D. Castagneri
![james castagneri](https://user-images.githubusercontent.com/4912083/30183639-d07776ac-93e0-11e7-8a91-e37fbfaf30a1.jpg)

**Comment by KCMack** [comment]
![katherine_headshot](https://user-images.githubusercontent.com/4912083/30188993-3c063e6a-93f7-11e7-8778-a0f9892c37fb.jpg)

**Comment by mitchellryant** [comment]
Katherine Smyth name was misspelled twice for the GeoRodeo, so lets be careful out there.

**Comment by christoball** [comment]
resolved in 73712cf5fea298a4f525246b60f73c64fa8433d5
