### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by pwblanton** [TNRIS/tnris.org#1420]
Adam is teaching me Waffle!

https://tnris.org/texas-gis-forum/2017/agenda/#keynote-bern

**Comment by pwblanton** [comment]
I edited something; please review it. Thanks! Remember, this is just me learning the system!

**Comment by mitchellryant** [comment]
too many emails

**Comment by pwblanton** [comment]
Hah! Adam is now teaching me to use Scrible! Watch out!
http://scrible.com/s/69FSA

**Comment by pwblanton** [comment]
Remember, this is just a test! Please don't make any edits based on my comments!

**Comment by KCMack** [comment]
xyz

**Comment by christoball** [comment]
resolved
