### ISSUE TITLE
Texas imagery FAQ update

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1422]
Updating FAQ section to include pricing tiers and remove language referencing the pilot.

**Comment by geochik** [comment]
@christoball - the word file contains a table to be inserted into this page at line 50.
[Tiers_Graphic4website.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599c64cafada7e0606ba7cba/125516c66e82c728ace21e0d46dc9d9f3191bc8e9de8af4bad5ea4832c44347a3d01e1673295f127b54778154d555ca9485f5d41faf0dd7fa4e369778a5c0befd8685b27c46816bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8f4a3f180d1e80fd5833a48b06.docx)

@gmullins @KCMack - I made changes to a couple of questions regarding the cost. https://preview.tnris.org/glidden/f308ff1ab0143020902482c69658eab5c2e284e9/texas-imagery-service/#how-will-maintenance-and-imagery-update-costs-be-covered-in-the-future-
Specifically:
How much does the service cost for my agency?
Can I join at any time during the year?
The Texas Imagery Service now contains layers by year. What are these new layers? (updated the years)
I also removed references to the "updates" at the top of the page. I am working on a new update that will describe the end of the pilot phase and the full-on subscription model.

**Comment by mitchellryant** [comment]
@geochik just incase .
 https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables

**Comment by gmullins** [comment]
Finished my edits!

**Comment by geochik** [comment]
I'm good with Gayla's edits!

**Comment by KCMack** [comment]
My recommendation is to shorten the third line  to read: "Texas has collaborated with Google to provide a cost-efficient and widely accessible mapping tools........"

**Comment by gmullins** [comment]
@christoball can you also make KCMack's edit? That section is not in the markdown. We should be done after that and the table. Thx!

**Comment by christoball** [comment]
Table ready for review:
https://preview.tnris.org/glidden/5e244a19199fc2f0e9f13b7ce256c797c2d114ba/texas-imagery-service/#how-much-does-the-service-cost-for-my-agency-

@geochik @gmullins

**Comment by gmullins** [comment]
@christoball Nice table - just one tweak - could the High Moderate and Minimum for the State Agency match the colors for Regional and Local?..then make State Advanced a totally different color. Thx!

**Comment by christoball** [comment]
@gmullins changed the colors:
https://preview.tnris.org/glidden/9aef3eb90569715b3f3a9d72d0455077401b8796/texas-imagery-service/#how-much-does-the-service-cost-for-my-agency-

**Comment by gmullins** [comment]
Awesome! Looks like we're done :)

**Comment by christoball** [comment]
@geochik told me the dollar amounts need to change?

**Comment by gmullins** [comment]
@christoball Another Tier Level was added last week to the State Agency table. Let's call it Super at $375,000. It is now Tier 1, Advanced is Tier 2, and so on.

**Comment by christoball** [comment]
@gmullins @geochik added 'super' level. Does this finalize it?
https://preview.tnris.org/glidden/529e440f43fd82ba38e236f31ba119302a38b8c2/texas-imagery-service/#how-much-does-the-service-cost-for-my-agency-

**Comment by geochik** [comment]
@gmullins - what do you think of “Power” instead of “Super”?

**Comment by gmullins** [comment]
@geochik @christoball Yes! "Power" - no "Super"

**Comment by christoball** [comment]
@geochik @gmullins Changed it to 'power'. Is it ready to go now?
https://preview.tnris.org/glidden/4e14cca53b9ccd62f1c294e823f780d1a43596c4/texas-imagery-service/#how-much-does-the-service-cost-for-my-agency-

**Comment by geochik** [comment]
@christoball YES! Release the hounds!

**Comment by christoball** [comment]
resolved in 1db87f3f6a74d77e70f457b62d3001ad6da77159
