### ISSUE TITLE
rdc: create research and distribution page.

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1423]
Creation RDC page (Suggestions of the email on 02/07/2017)

- [ ] RDC Description @ThorTheDestroyer (50% complete need some images\graphics)
- [x] Historic Archive Information (Description of Agencies in the Archive, Breakdowns about the scale and altitude information and what that means for scanning.) @LaurenKirk (100% complete)
- [x] Photo Search Process @LaurenKirk @ThorTheDestroyer (100% complete)
- [ ] Simplified Pricing Sheet @LaurenKirk @ThorTheDestroyer (75% complete needs editing)
- [ ] Image Gallery @LaurenKirk @ThorTheDestroyer @christoball (0% complete)
- [x] Stock Photos @christoball

**Comment by mitchellryant** [comment]
#942

**Comment by christoball** [comment]
content taken from #942

template: page.html
title: Research & Distribution Services (RDC)
abstract: The RDC offers a variety of additional products, support and services from our in-house staff. We provide hands-on assistance and expertise.

### TNRIS Research and Distribution Center

  The Research and Distribution Center(RDC) was established to facilitate the public's need to access datasets not readily available through our website.  The RDC is the physical repository of historical imagery, maps, reports and publications.   Historical imgagery within the archive dates back to 1927 with historical topo and planning maps dating back to 1890. 
  
  The RDC consistantly answers over 750 online requests for data each year. In Fiscal year 2015 the RDC was responsible for reproducing 386,069 square miles of Lidar data, amounting to ~85 TeraBytes of data being distributed to public privite entities.  

##RDC services include: 
* Reproductions, digital conversion, and spatial referencing of historical maps and aerial imagery
* Custom mapping using TNRIS datasets
* Digital data reproduction and distribution of orthoimagery, Lidar, and other bulk datasets on thumb drives, external hard drives and via digital download
* Staff assistance in locating geospatial information and related data or information provided through other agencies
* Data support for TNRIS datasets
* Reproduction of Texas Water Development Board (TWDB) publications and maps

Please [contact us](contact) for more information about these services and
datasets.

**Comment by christoball** [comment]
*Joey's note from previous issue:*
Generated Dallas 1927 and current TOP 12 inch Downtown Dallas images to be used as comparison graphics(slider, fader, whateverer). Put them in your staff folder in new directory RDC_Page

**Comment by mitchellryant** [comment]
@ThorTheDestroyer could you please provide more details about what you are looking for. 

1. Archive inventory update and availability on website - are you looking for more columns and data in the RDC search than is in the existing data download search.  

2. Online Historical Imagery viewer.  Images or Footprints? special services or from AGS?

3. Add historical photo index mosaics to download. Location of images so  can determine how best to get the data into the download.

4. Create RDC page. we are using the base page created from #942 as a start. to you envision this page jumping off from the RDC services current location or being added to the Programs heading off the main heading bar. would this be a tabbed page like the existing StratMap pages.

**Comment by ThorTheDestroyer** [comment]
1. More columns and the ability to add columns in the future.  
     needed columns as of now: photo index location, line  and spatial index location, scan      status, georeference status, scanned image location,  Mosaic dataset location.

**Comment by mitchellryant** [comment]
Issue to create columns.
https://github.com/TNRIS/historical-aerials/issues/24

**Comment by ThorTheDestroyer** [comment]
2. This can be addressed in the future after the other issues are addressed, since it could will likely pull from or incorporate them depending on how we want the viewer to work.

3. Mosaics are currently being QC'd.  Are county datasets on the download page referenced by county name or fips code(full or partial)? Final locations will be created to align with conventions of current county dataset in download. 

4. I envision the RDC page will reside in the program heading and function with multiple pages in the same manner as the stratmap pages.  Appropriate sections of the pages can be determined based on input from tnris staff and will reflect the resources of the RDC.

**Comment by mitchellryant** [comment]
@christoball is working on a mock of that page(s). It is good to have an idea of where you wanted it to go. i will need to discuss the placement with @rwade2126 .

**Comment by mitchellryant** [comment]
issues has been divided into for separate issues. going forward this this issue will focus on the creation of the expanded RDC page.

**Comment by mitchellryant** [comment]
can we modify the location of this page https://tnris.org/maps-and-data/research-and-distribution/ from map and data to RDC?

**Comment by christoball** [comment]
@mitchellryant yes, in the draft I've started, the new url will be:
tnris.org/research-distribution-center

**Comment by mitchellryant** [comment]
RDC Pricing Sheet Table.
**Services and Products**| |**Pricing**
-----|-----|-----
**Historical Imagery Requests:**| | 
Historical search (1 image per decade):| |$40.00 per site
Single year search:| |$18.00 per site
Scanned historical frame:| |$10.00 per image
Scanning + Georeference of historical frame| |$20.00 per image
FTP delivery (0-10GB)| |$7.00 
 | | 
**Digital Data Request:**| | 
Data Copying to External Hard Drive| |staff time: $46.00 per TB
 | ||computer resources: $0.15 per GB
 | | 
Data Copy to FTP Site (0-10GB)| |$50.00 
TNRIS Flash Drive| |$40.00 
TNRIS 1TB Hard Drive| |$100.00 
TNRIS 2TB Hard Drive| |$125.00 
 | | 
**Custom Map Creation:**| | 
Custom Map Creation| |$37.50 per hour 
Plotting| | 
36” paper(heavy bond/photo)| |$0.10/0.25  
60” paper(heavy bond/photo)| |$0.30/0.75
 | | 
**Maps:**| | 
USGS National map| | 
with aerial background| |$10.00 per map
without aerial background| |$8.00 per map
 | | 
USGS topographic map| | 
24k (7.5 minute series)| |$8.00 per map
100k, 200k, 1 million| |$10.00 per map
 | | 
Historical topographic map| | 
Research Fee| |$18.00 
Reproduction| |$8.00 per print
 | | 
TWDB map reproduction| |$8.00-10.00 per map
 | | 
Miscellaneous Maps(FEMA,NWI, ect.)| |price varies
 | | 
**Shipping & Delivery:**| | 
USPS| |$5.00-$7.00
FedEx| |$10.00-$15.00
FTP (maximum of 10 GB)| |$7.00

**Comment by mitchellryant** [comment]
RDC Pricing Explanation. A markdown file will need to be created for this.

**TNRIS RDC Pricing Explanation**

Pricing for staff time and resources is derived from the [Texas Administrative Code Title 1, Part 3, Chapter 70,rule §70.10.](http://texreg.sos.state.tx.us/public/readtac$ext.TacPage?sl=R&app=9&p_dir=&p_rloc=&p_tloc=&p_ploc=&pg=1&p_tac=&ti=1&pt=3&ch=70&rl=10)

Historical imagery Request:
Full Historical Search: ~2.5 hours of Labor for locating, compiling, and reproducing at $15.00 an hour
Overhead charge at 20% of labor
Total: $40.00 per site

Single year Historical Search: ~1 hour of Labor for locating, compiling, and reproducing at $15.00 an hour
Overhead charge at 20% of labor
Total: $18.00 per site

Scanning of Historical Imagery: ~1/6 hour of labor for programming at $28.50 per hour
~1/6 hour of labor for locating, compiling, and reproducing at $15.00 an hour
Overhead charge at 20% of labor
~$1.00 per image Computer resource charge (PC, Scanner, Server for ~1/4 of an hour) 
Total: $10.00 per image

Digital Data Request and Delivery:
Hard drive Data Copies: ~1 hour of labor for Programming at $28.50 per hour per 1TB of data
~2/3 hour of labor for locating, compiling, and reproducing at $15.00 an hour per 1TB of data
Overhead charge at 20% of labor
$0.15 per GB for Computer Resource charge (calculated by average time to transfer and 
Convert to external drive from internal server via PC)               
Total: $46.00 per TB with $0.15 per GB 


FTP Delivery Charge: ~1/6 hour labor for programming at $28.50 per hour
Overhead charge at 20% of labor
~1.5 downloads from data transfer bucket on Amazon cloud at $0.09(10GB Limit)
Total: $7.00


Digital Data Download (up to 10 GB): ~1 hour of labor for Programming at $28.50 per hour 
~1/2 hour of labor for locating, compiling, and reproducing at $15.00 an hour     
Overhead charge at 20% of labor
Ftp Delivery at $7.00
Total: $50.00


Custom Data Creation or Custom Services:
Custom Map Creation: Per hour charge for Programming $28.50 
Overhead charge at 20% of labor
$3.40 per hour Computer resources charge (PC and Server)
Total Cost: $37.50

Custom Data Conversion: Per hour charge for Programming $28.50 
Overhead charge at 20% of labor
$3.40 per hour charge for Computer resources (PC and Server)
Total Cost: $37.50

**Comment by ThorTheDestroyer** [comment]
is this going to be posted to the website? If so we may need to pass it by legal for their blessing.

**Comment by mitchellryant** [comment]
@ThorTheDestroyer let me know how that turns out.

if we are going to build this page out we will need more content than existed in #942 or on https://tnris.org/maps-and-data/research-and-distribution/. I would like this page to be a reference that @LaurenKirk and TR and point people to to get information. The pricing sheet and explanation of pricing is a good reference. Also thinking about a page to explain what a historic search is.  Later a full search feature for the archive could be added.

**Comment by ThorTheDestroyer** [comment]
Same page, bruh.  What was previously written in that markdown was overview type language that functioned merely as a starting point/place holder and is mostly what exists now. When development with IS became very limited due to their workload, I put it on hold.  I want it to function in the same manner as you are indicating but will need IS to assist in developing the parts to make it function that way.   When we push it to the site it need to be as close to final as possible(main historical image viewer can wait).  Archive search feature does needs to be there.  I don't want to push a half job just to put more words up there. We could just shove those pricing pdfs in a bucket and link them on the current page.   When the RDC pages gets added i want people to see almost everything it can do, so they want to come back and use it again. If we add functionality to it later, they may never know it exists and won't click on it later cause they read it already and there is no point in going back.  Once some pieces get built and I can see how their real function matches theory,  I'll be able to lay it out in detail.

**Comment by mitchellryant** [comment]
The RDC page(s) will mostly be done by @christoball. The header bar for the site will be re-worked to accommodate the RDC. Possible name change too, since most to the data is online and you guys do not "distribute" that much any more.

**Comment by ThorTheDestroyer** [comment]
I've envisioned the RDC page to resemble how the StratMap pages are structured.  Below is a starting point on the main divisions and general ideas for the pages I feel would be representative and provide appropriate resources to address main functions of the RDC.

RDC Header
        |_ Historical Imagery-Archive Map, Archive search, Samples, etc
        |_Historical Maps-listing of resources, historical map gallery, etc.
        |_Data/Research Requests-pricing sheet, product information, order link,policies, etc.

**Comment by christoball** [comment]
View the draft RDC content here:
https://preview.tnris.org/razor-wire/be50803475dee2e9c4c9742e3504bb64acad10a1/research-distribution-center/

Prices page:
https://preview.tnris.org/razor-wire/be50803475dee2e9c4c9742e3504bb64acad10a1/research-distribution-center/prices/

**Comment by LaurenKirk** [comment]
@mitchellryant @ThorTheDestroyer @christoball I wrote some brief agency descriptions for the website and also pulled some copies of images for each agency that can be used as examples.  Feel free to edit the descriptions.  Both can be found at M:\IS\Projects\Website\RDC_Page

**Comment by mitchellryant** [comment]
@christoball can you add a "tab" to show the custom mapping page, as we discussed yesterday.

**Comment by christoball** [comment]
Latest version with Historical Imagery Archive and Custom maps moved:
https://preview.tnris.org/razor-wire/848ed57dbfc746727ba6ab561620de90daa7135a/research-distribution-center/

the formatting of the acquiring agencies can change, just a start.

**Comment by mitchellryant** [comment]
@ThorTheDestroyer first pass at updating the process page.

https://preview.tnris.org/razor-wire/023eda5fb2c1a4bf92c2cc7cecd7c660c4df9408/research-distribution-center/

**Comment by pwblanton** [comment]
I’ll review again tomorrow! Thanks for including me!

**Comment by mitchellryant** [comment]
This info is going to be great to have online.
 
Here are my suggestions. Mostly word changes:
 
Main
Title: Research & Distribution Center (RDC) Services
 
…with historic topographic and…
…TeraBytes of data distribution to….
 
Pricing
DIGITAL DATA REQUEST*
 
*May supply own external hard drive.
I don’t know if this is an option but it should probably be stated if it is.
 
Historical Imagery Archive
To submit an Historical Imagery request…. When you click on…
This just needs to be cleaned up.
Provide a link/button to the Data Search & Download main
 
The customer can decide to continue or cancel the research.
 
Custom Maps
From customized contour maps to historical imagery posters of your hometown, we can make the map you’re looking for.
 
Important Note: Coverage area on all maps must be within Texas and show data from the TNRIS archive.

from @gmullins

**Comment by christoball** [comment]
Most up to date version of RDC pages: https://preview.tnris.org/razor-wire/1aa7743ea4747dd56b2cfdca95f4d4b0983c445e/research-distribution-center/

**Comment by christoball** [comment]
The historical imagery archive page needs an intro paragraph.

The stratmap pages have good examples of good intro paragraphs.

https://www.tnris.org/stratmap/elevation-lidar/

**Comment by mitchellryant** [comment]
@christoball can we move all this work to its own feature branch. so I could get my branch back. Im not sure when or if it will ever get published.

also can we change out the county map on the custom map page. EOB has some better\newer county maps.
