### ISSUE TITLE
Wrong Kim Ludeke photo

### ISSUE THREAD

**Issue by gmullins** [TNRIS/tnris.org#1424]
Photo needs to change from Rob A. to Kim L. here: https://tnris.org/around-the-state/2017-07-28/us-census-builds-towards-2020-regional-updates-jobs/

**Comment by gmullins** [comment]
![rob_wrong.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b691ca086d420011f174f3/125516c66e82c728ace21e0d46fa9b981c9591a681eefd0fe64de29b234324676b5ee17e29d2b17de91b7f055d0a1bab41585f46f5fc8d78a4e33b62964e49bc8f3900299f7744eeaa880dbd01b0218e4f80b7b98d4ec5ea3e21e499c2.jpg)

**Comment by christoball** [comment]
Thanks for catching this.

resolved in 8449915f70c52b9fb24bf9fdbeaddfabbc01b7c6
