### ISSUE TITLE
fix Joanna and Kyle Affiliation

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1425]
Adding organization for two keynote speakers

**Comment by geochik** [comment]
@christoball 
Please add the organization name to the keynotes mentioned below:
Joanna Sanchez, Ph.D., Howard University - Department of Educational Leadership and Policy
Kyle Walker, Ph.D.,  Texas Christian University - Center for Urban Studies
This change applies to two occurrences:
https://tnris.org/texas-gis-forum/2017/agenda/
https://tnris.org/texas-gis-forum/2017/

**Comment by christoball** [comment]
@geochik the titles are meant to be quick snapshots. The description is where we get more detailed.

We would need to edit these down to something simpler for the snapshots on the front page in particular

I would propose 
**Joanna Sanchez, Ph.D., Howard University**

**Kyle Walker, Ph.D., Urban Studies Professor** or **Kyle Walker, Ph.D., Texas Christian University.**

See here for example with full title.
![sanchez.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599de1581827cf2b06d2e400/125516c66e82c728ace21e0d46fb9594208a86b3cda5fd53b652fa912a5265296b51fa7c22d0b571bb4629040a584eac415a5641f8aa8b7ea1a42062c80d55b98e30063e937f03a6aa8317b500bf208e4c87b1b48f49c2ee3a37aa.jpg)

**Comment by geochik** [comment]
@christoball  For consistency, let's go with organizations only and no titles for all.

Also, if it fits, can you please replace Department of Educational Administration to the Department of Educational Leadership and Policy in Joanna's bio?

**Comment by christoball** [comment]
Preview the changes to the speakers here:
https://preview.tnris.org/ellwood/bc6a89a28d37c568cb58bde6eda591fd5d1cb62d/texas-gis-forum/2017/

**Comment by christoball** [comment]
resolved in 35ee915b369984f33c35d8dfc4824ab17d4e893e
