### ISSUE TITLE
Remove Quantum from sponsors

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1427]
Please remove Quantum.

They requested a refund when told they didn't qualify for Exhibitor level

**Comment by christoball** [comment]
They were never added.

**Comment by KCMack** [comment]
Under Exhibitors Quantam Spatial is listed.  Please Remove it.  Confusion caused by misspelling.

Thanks!

**Comment by christoball** [comment]
Sorry, fixing this. Will be fixed with next commit.

**Comment by KCMack** [comment]
Thanks very much

**Comment by christoball** [comment]
resolved in 510d6edea5f1be18305b57cb823bed4c41f5a462
