### ISSUE TITLE
Forum workshops

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1428]
Please add lines between the individual workshop sessions to make them easier to read.

Thanks!

**Comment by christoball** [comment]
This work better?
https://preview.tnris.org/ellwood/7ba1da5d82af1dbf95ae0e161a43d65ec259bdc7/texas-gis-forum/2017/workshops/

**Comment by KCMack** [comment]
Perfect, thank you!

**Comment by christoball** [comment]
resolved in 510d6edea5f1be18305b57cb823bed4c41f5a462
