### ISSUE TITLE
Bio for Bern

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1429]
Bern has witnessed the development of GIS from the mid-80’s when he began his geospatial career with Esri as an applications specialist.  His abilities were quickly recognized providing him with opportunities to be involved in a broad spectrum of GIS implementation and software development projects.
Highlights of his career include authoring Esri’s first user call and bug tracking system, developing the first GUI for ARC/INFO (ArcTools), and teaching/promoting Avenue (scripting language for ArcView 2.0).  Bern has also served as the product manager for MapObjects, MapObjects IMS, ArcIMS, ArcGIS Explorer Desktop, and ArcGIS Online. In addition to ArcGIS Online, he’s recently been involved with product management for the Living Atlas and Story Maps.
The depth of Bern’s professional experience and knowledge keep him in high demand for worldwide workshops and keynote engagements.  As a product strategist and technical evangelist, he focuses on ways to broaden access to geographic information and GIS capabilities via the web.  Through it all, he remains humble and entirely fascinated by the ever-evolving state of GIS and its capabilities to make a difference.
He's been known to say that on a good day he's making a map, and on a great day, he's on one.

**Comment by pwblanton** [comment]
Just two edits: first line remove the comma in mid-80s, and in the second line add a comma after the word "recognized". Looks great!

**Comment by christoball** [comment]
Adding this to existing issue #1405
