### ISSUE TITLE
Harris Platinum Article Spotlight

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1436]
Create article for Harris's platinum sponsor promotion

**Comment by KCMack** [comment]
Today’s important decisions about city expansions, emergency preparedness, utilities and asset management, and other long-range planning activities often require a comprehensive look at not only the specific area of concern, but also adjacent areas to properly evaluate impacts. Light-detecting and ranging (LiDAR) elevation data has become an essential tool to helping us gain a general understanding of the physical landscape for planning and infrastructure development. But traditional LiDAR offers limited resolution, so important details are often lacking, and the cost to mobilize aircraft for wide-area collections can be cost prohibitive, particularly for smaller local governments.

To address this challenge, the Channel Islands Regional GIS Collaborative (CIRGIS) recently partnered with Harris for a project that is bringing next-generation geospatial data to its Southern California stakeholders. And the results bring significant long-term impacts.

**Comment by christoball** [comment]
@KCMack preview here: https://preview.tnris.org/ellwood/8e11fdcf548d6b3c78043b946afccbe2cf1fe967/news/2017-10-09/forum-platinum-sponsor-spotlight-harris-geospatial/

**Comment by KCMack** [comment]
Looks good.
