### ISSUE TITLE
TX Imagery Service Announcement Article

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1437]
An article to announce end of Imagery Service Pilot program ending and what that means for subscribers.

**Comment by gmullins** [comment]
Preview ready: https://preview.tnris.org/washburn/76c7e6c5bf46f9ce5abbdeab9c54c9d9a0dca20c/news/2017-10-02/texas-imagery-service-subscription/

@christoball Please use these images. I was thinking statewide as the thumbnail and the zoomed in on on the article page.
Also please include the Request a Link button but change to 'Request Trial Links Today'
![TIS_Statewide.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b691ca086d420011f174f3/125516c66e82c728ace21e0d46dcbda91cb197a89beca84aa058b2d86b56357c2301a03f32dfa17de615295459561af8430d0a43fcf98929afb3382388090cffcd7f1d2598694ef1e1c84afd13b032894f8fb7b98a4ac6ea3525e08c87473d0c48.jpg)
![TIS_example.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b691ca086d420011f174f3/125516c66e82c728ace21e0d46dcbda91c879ba882f9b346e611b2843b492d762a10e17132d0ba7fed172d580b0b4cf9145f5f44fcfb802ea2e53e258d4e17ff933c0120996048e6edc00db513bb27814e80b6ba8c4ec8e83424e68b885d73.jpg)

**Comment by KCMack** [comment]
Generally looks really good.  
A couple of questions:
1. Is the spacing  (or gap) intentionally large between the intro that ends in "Texas GIS Community by offering features such as:" and the dot points ?   Can there be less of a gap?
2. Dot point #3 -  how about modifying the language to read,  " updated imagery every three years, and possibly more frequently for many urban areas;

**Comment by gmullins** [comment]
I updated KCMack's 2. suggestion. On 1. @christoball can you lessen the space. I don't see how. https://preview.tnris.org/washburn/e1bd2b4fd03649e258324cc70e0ba14aa58bff82/news/2017-10-02/texas-imagery-service-subscription-available-now/
Also @christoball can you include the red Request a Link button but change to 'Request Trial Links Today' Same change for Texas Imagery Service page please.
![red button.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b691ca086d420011f174f3/125516c66e82c728ace21e0d46fa919e638096bd9be6b101e81fe086264c22703d46f96925dcb47aea1422050b5d1bf946585f44fef08c2ff5b46977984019af80330b2b9b645bf9fa9015ad00b22a8a4a85b1bc8f4ac2ed3b22e18f9d02.jpg)

**Comment by christoball** [comment]
@gmullins Made those edits. ready to go?
https://preview.tnris.org/washburn/b98068463a57d225211a1e2a2780b85f7cbc4b0f/news/2017-10-02/texas-imagery-service-subscription-available-now/

**Comment by gmullins** [comment]
@christoball Almost. 'Request Trial Links Today' 
And can you move it away from the italicized statement. It shouldn't look like it goes with that last line which acts as more of a disclaimer. Thx!

**Comment by christoball** [comment]
@gmullins does this look right? Can you move this to 'ready to go' if everything is correct?
https://preview.tnris.org/washburn/1e3858a5590d69a07f93724a648afbbdb13c2e98/news/2017-10-02/texas-imagery-service-subscription-available-now/

**Comment by gmullins** [comment]
Made geochik's change. Now ready.
https://preview.tnris.org/washburn/daffd52bab4e7c371d834aba816a63304d1be55d/news/2017-10-02/texas-imagery-service-subscription-available-now/

**Comment by christoball** [comment]
resolved in 90b8f095870e6f6c55436a108e0e2b3b21a3768a
