### ISSUE TITLE
Time change for HOLL

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1439]
Please change the time on Thursday
FROM: 9:00 - 5:00
TO: 9:00 - 3:00

Thank you.

kcm

**Comment by mitchellryant** [comment]
#1434 says this was resolved with https://github.com/TNRIS/tnris.org/commit/e24b325fa6384fae1d982d740fbf4d72a411c839
but time on site is still 5:00pm.

**Comment by christoball** [comment]
Sorry, I accidentally changed Wednesday. Now fixed: https://tnris.org/texas-gis-forum/2017/agenda/


resolved in 09bd9f5edfe4c5416ed25eb3e19971750e812595
