### ISSUE TITLE
push /maps page to prod

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/tnris.org#144]
the /maps page has been sitting idle, and complete, for several months now. it is overdue to be pushed to production. we have been waiting on management to reconcile this new page with TWDB IT upstairs. pushing to prod from our side is absolutely no issue and can be done in minutes but we need approval "from other DEAs as it provides their maps" and creates cause for the TWDB website maps page to 'go away' (although it technically doesn't _have to_).

**Comment by ghost** [comment]
@adambreznicky We have the green light from Richard to publicly launch the new Map Catalog. So anything that needs to be done to push it out there can go. Hurrah! He said the other DEAs (John and Jessica) approved with no issues.
 
This will run concurrently with the TWDB maps site for a month or two until they take theirs down and link to us.

**Comment by christoball** [comment]
@adambreznicky @gmullins @e00o 

Preview here of Maps link in header, footer
http://washburn.tnris.org/

And on the order map page:
http://washburn.tnris.org/order-map/

**Comment by adambreznicky** [comment]
looks good to me! both header & footer links, as well as the 2 links on the order-map page are all correct. i vote push it at will.
:)
