### ISSUE TITLE
agenda updates - sep 28

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1440]
From CMP:
- Stacey Lyle’s co-presenter Jerry Jaynes (no title/org yet but we should go ahead and list him.  I’ve been trying to get his info for a bit now)
- Daniel Haverhah > Coleen Gentiles, City of Austin, IT Geospatial Analyst
- David Arctur > in addition to the other gentlemen listed… please add
David Maidment, University of Texas at Austin
Professor of Civil Engineering

**Comment by christoball** [comment]
Made these changes. @KCMack can you double check them:
https://preview.tnris.org/ellwood/52313b62c46b2bdffcc023b0fef1c4a6ffc03ee5/texas-gis-forum/2017/agenda/

**Comment by KCMack** [comment]
Looks good, Chris.

**Comment by christoball** [comment]
resolved in 52313b62c46b2bdffcc023b0fef1c4a6ffc03ee5
