### ISSUE TITLE
Forum Platinum Sponsor Presentation Description

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1441]
Esri will make their presentation on Wednesday 1:15-2:15

Story Map Craft: Putting your best story forward

Story Maps are extremely popular, and one of the easiest and most visible ways to tell your story, or inform a public audience. Story Maps let you combine authoritative maps with narrative text, images, and multimedia content, making it easy to harness the power of maps and geography in easy-to-build apps (no programming required). While easy to author, the differences between a great, effective story map and a mediocre one are sometimes subtle. Creating a great story map takes some extra thought and tradecraft, and an awareness of certain techniques and best practices. This session will detail the process involved in creating truly awesome story maps, and go through techniques you can use to create your very best stories. Common pitfalls, and how to avoid them, will also be discussed.

**Comment by christoball** [comment]
@KCMack preview here:
https://preview.tnris.org/ellwood/73226009cbd70ebee195b20a595a11e255c9fe4c/news/2017-10-11/forum-platinum-sponsor-spotlight-esri/

**Comment by christoball** [comment]
@KCMack's comments

changes can be viewed at https://storymaps.arcgis.com/en/

Brief description: Engage and Inspire Your Audience
Esri Story Maps let you combine authoritative maps with narrative text, images, and multimedia content. They make it easy to harness the power of maps and geography to tell your story.
No Coding Required.Incredibly Powerful.Open Source.
Become a Story Map Author

Share a place you love. Make your case. Showcase your organization's plans and projects. Everyone has a story. What's yours?

**Comment by christoball** [comment]
One of the two options listed:
http://www.esri.com/esri-news/arcnews/fall13articles/implementing-web-gis

https://blogs.esri.com/esri/arcgis/2017/08/04/opsintellarcgis/

**Comment by pwblanton** [comment]
I like the Esri spotlight!

**Comment by christoball** [comment]
resolved in fd0664a0889f831b19f9591663617befe4df4bce
