### ISSUE TITLE
Update Forum workshops descriptions

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1442]
New content on the spreadsheet includes Zena's biography.

Also, attached is Zena's head shot.

Thanks
![zena pelletier](https://user-images.githubusercontent.com/4912083/31098881-c2d1bde8-a789-11e7-9347-cc5109135468.JPG)

**Comment by KCMack** [comment]
Chris, this one is for you to update.

**Comment by christoball** [comment]
resolved in 63b419ecd437b2683811f0c772a3d2489a0a9444
