### ISSUE TITLE
Instructor headshots

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1445]
Head shots for instructors Michael Beavers and Brig Bowles
![beavers_headshot](https://user-images.githubusercontent.com/4912083/31149508-c64df06e-a855-11e7-9806-a30fe7680110.jpg)
![brig bowles](https://user-images.githubusercontent.com/4912083/31149529-de253206-a855-11e7-932c-0a1cb66c21e1.jpg)

**Comment by christoball** [comment]
resolved in 63b419ecd437b2683811f0c772a3d2489a0a9444
