### ISSUE TITLE
Catalog Entry for East Texas Lidar

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1448]
The Texas Water Development Board(TWDB) and the Texas Commission on Environmental Quality(TCEQ) partnered to acquire High quality lidar data. The Statement of Work was issued by the Strategic Mapping Program (StratMap) of the Texas Natural Resources Information System (TNRIS), part of the Texas Water Development Board (TWDB).The project area is approximately 3,501 square miles in San Jacinto, Walker, Montgomery, Hunt, Rains, Hopkins,Wood, Delta, and Lamar County, Texas. The data was acquired by Fugro with third party QAQC from AECOM. The project specification for the lidar data acquisition was developed to support a point density of 4 points per square meter, The dates of acquisition are December 29, 2016-March 22, 2017. The purpose of this LiDAR data was to produce high accuracy 3D elevation products, including tiled LiDAR in LAS 1.4 format, 3D breaklines, and 1 meter cell size hydro flattened Digital Elevation Models (DEMs).

Lidar data for Texas is made available online through the use of data compression using LASTools. LASTools is an open-source collection of tools for lidar data viewing and manipulation. TNRIS uses the LASzip portion of LASTools for compression\decompression. LASTools provides a lossless compression of the data from las to laz formats.

Software with native LAZ support
ERDAS IMAGINE (14.1 and up) by Hexagon Geospatial
Global Mapper (13.1 and up) by Blue Marble Geo
ENVI LiDAR (5.1 and up) by Exelis VIS
FME (2012 and up) by Safe Software
LAStools by rapidlasso
plas.io 3D Web Viewer by Hobu Inc.
FUSION (3.40 and up) by Bob McGaughey of the USDA
Voyager (1.3 and up) by Voyager GIS
GRASS GIS (7.0 and up) by Open Source Geospatial Foundation (OSGeo)

**Comment by mitchellryant** [comment]
---
name: StratMap 2017 50cm East Texas Lidar
short_description: <p>Lidar data for Delta, Hopkins, Hunt, Rains, and San Jacinto Counties </p>
type: Raster
available_formats: LAS
source: Brazos County
coverage_extent: Delta, Hopkins, Hunt, Rains, and San Jacinto Counties
data_download_lvl:
statewide_coverage:
footprint: 1/64 USGS Quadrangle
download_size:
recommended_use: Basemap, Research, Analysis
date_created: 2015
tags: Delta County, Hopkins County, Hunt County, Rains County, San Jacinto County, Lidar, Point Cloud, LAS, Elevation, County, Historical
known_issues: None
alternative_data: 1M Hydro-Enforced DEM, 3D Breaklines
derivative_data: 2ft and 5ft Contours
spatial_reference: <p><a href='https&#58;//epsg.io/26914'>EPSG 26914</a></p>
relationship_tag:
category: Lidar
download: T
download_link:
order: T
wms_category:
wms_link:
pop_link:
status_map_cartodb_id: bbedf274-2141-4b1c-a443-8d339e7a9e7c
agency:
agency_web:
agency_gis_page:
date_added: 2017-10-06
license: CC0
tile_index: Lidar
supplemental_report: T
lidar_breaklines: T
urlized_name: stratmap-2017-50cm-east-texas
filename: data-catalog/entry/stratmap-2017-50cm-east-texas.md
template: data-catalog-entry.html
title: StratMap 2017 50cm East Texas
urlized_category: lidar
detail_image_url: images/data-catalog/entry/
overview_image_url: images/data-catalog/entry/
thumb_url: images/data-catalog/entry/
supplemental_report_url: https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/stratmap_2017_50cm_east_texas_supplementalreports.zip
tile_index_url: https://tnris-datadownload.s3.amazonaws.com/d/tnris-lidar/state/tx/tnris-lidar_tx.zip
license_text: Public Domain (Creative Commons CC0)
license_url: https://creativecommons.org/publicdomain/zero/1.0/
---

The Texas Water Development Board(TWDB) and the Texas Commission on Environmental Quality (TCEQ) partnered to acquire High quality lidar data. The Statement of Work was issued by the Strategic Mapping Program (StratMap) of the Texas Natural Resources Information System (TNRIS), part of the Texas Water Development Board (TWDB).The project area is approximately 3,501 square miles in San Jacinto, Walker, Montgomery, Hunt, Rains, Hopkins,Wood, Delta, and Lamar County, Texas. The data was acquired by Fugro with third party QAQC from AECOM. The project specification for the lidar data acquisition was developed to support a point density of 4 points per square meter, The dates of acquisition are December 29, 2016-March 22, 2017. The purpose of this LiDAR data was to produce high accuracy 3D elevation products, including tiled LiDAR in LAS 1.4 format, 3D breaklines, and 1 meter cell size hydro flattened Digital Elevation Models (DEMs).                      

Lidar data for Texas is made available online through the use of data compression using [LASTools](https://rapidlasso.com/lastools/). LASTools is an open-source collection of tools for lidar data viewing and manipulation. TNRIS uses the LASzip portion of LASTools for compression\decompression. LASTools provides a lossless compression of the data from las to laz formats.

- Software with native LAZ support
- ERDAS IMAGINE (14.1 and up) by Hexagon Geospatial
- Global Mapper (13.1 and up) by Blue Marble Geo
- ENVI LiDAR (5.1 and up) by Exelis VIS
- FME (2012 and up) by Safe Software
- LAStools by rapidlasso
- plas.io 3D Web Viewer by Hobu Inc.
- FUSION (3.40 and up) by Bob McGaughey of the USDA
- Voyager (1.3 and up) by Voyager GIS
- GRASS GIS (7.0 and up) by Open Source Geospatial Foundation (OSGeo)

**Comment by mitchellryant** [comment]
@ThorTheDestroyer have the images, supplemental reports, and breaklines been place on teh vault?

**Comment by ThorTheDestroyer** [comment]
Supplemental reports and breaklines have been placed in the vault.  Currently waiting on data to load to produce image.  Images should be completed by Monday morning.

**Comment by mitchellryant** [comment]
Supplemental Reports and Breaklines have been uploaded to s3 bucket. be sure to test links on preview build.

**Comment by ThorTheDestroyer** [comment]
2D image had been placed in datacatalog image repository. software throwing errors when trying to view 3D, will investigate and create image when possible.

**Comment by ThorTheDestroyer** [comment]
3D image has been placed in image repository on the vault

**Comment by mitchellryant** [comment]
@ThorTheDestroyer does this image (stratmap_2017_50cm_east-texas_mapview.jpg) need to rotated 90^?  if not it will not fit properly display area.

**Comment by ThorTheDestroyer** [comment]
I mean, it can be rotated, or it can be cropped. Since its a graphic, does it need to be spatially accurate? I think we may have rotated graphics in the past, if it needs to be redone, I can get to it early next week.

**Comment by mitchellryant** [comment]
the preference is that images in the data catalog fit the display window, so no white space is showing. this does not alway happen. spatial accuracy is not an issue.  it is more about look, feel, and consistency. the .mxd it setup to export the image to a set dpi and size.

**Comment by christoball** [comment]
@mitchellryant @ThorTheDestroyer ready to preview here:
https://preview.tnris.org/haish/0c2edbdba24f590286ea239d431c608c53e590c9/data-catalog/entry/stratMap-2017-50cm-east-texas-lidar/

**Comment by mitchellryant** [comment]
please add EPSG 26915 (https://epsg.io/26915) to the special reference. Data is in 2 zones.

**Comment by christoball** [comment]
resolved in 0c2edbdba24f590286ea239d431c608c53e590c9
