### ISSUE TITLE
East Texas Lidar data release

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1451]
https://github.com/TNRIS/tnris.org/blob/haish/content/markdown/news/2017-10-06-lidar-data-release-east-texas-project.md

**Comment by mitchellryant** [comment]
@christoball added front matter and fixed some formatting. (still need some tweaks)
all images need to be replaced with East Texas Images. 
data catalog entry will also need to be added #1448

https://preview.tnris.org/haish/64c4852b78facda86513f56e58478b98b34a6fa0/news/2017-10-06/lidar-data-release-east-texas-project/

**Comment by christoball** [comment]
Ready to preview here:
https://preview.tnris.org/haish/0c2edbdba24f590286ea239d431c608c53e590c9/news/2017-11-13/lidar-data-release-east-texas-project/

**Comment by christoball** [comment]
@mitchellryant @ThorTheDestroyer the map seems to be a little off center, with the coverage area showing up towards the top of the embedded map.
![lidarmap2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599de1581827cf2b06d2e400/125516c66e82c728ace21e0d46e49d9e22908ea89fbbfd0fe64de29b234324676b5ee17e29d2b17de91b7f055d0a1bab41585f46f5fc8d78a4e33b62964e49bc8f3900299f7744eeaa880dbe06b0218e4e85b0bd894bc5e83927e299c2.jpg)
![lidarmap1.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599de1581827cf2b06d2e400/125516c66e82c728ace21e0d46e49d9e22908ea89fb8fd0fe64de29b234324676b5ee17e29d2b17de91b7f055d0a1bab41585f46f5fc8d78a4e33b62964e49bc8f3900299f7744eeaa880dbd00b0218e4e85b0bd894bc5e83927e699c2.jpg)

**Comment by mitchellryant** [comment]
changed the starting zoom level from 8 to 9.

**Comment by christoball** [comment]
@KCMack can you give this a final look before we push it out?
https://preview.tnris.org/haish/0c2edbdba24f590286ea239d431c608c53e590c9/news/2017-11-13/lidar-data-release-east-texas-project/

**Comment by KCMack** [comment]
Add space before (DIR) in the last sentence of the first paragraph.
Add space before (TCEQ) in the second sentence of second paragraph.
Spell out RDC - Research and Distribution Center in the Data Access section near the bottom of the pate.

**Comment by christoball** [comment]
resolved in 0c2edbdba24f590286ea239d431c608c53e590c9
