### ISSUE TITLE
A la cart lunch sponsorship

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1458]
Looks like Merrick is sponsoring both Wed and Thurs lunch according to the agenda. If this is the case, the sponsorship page should be updated to strike the Thursday lunch option as "already taken".
https://tnris.org/texas-gis-forum/2017/sponsors-and-exhibitors/

**Comment by christoball** [comment]
resolved in b0616b87bd6a074f353e796433c9946b1a46489c
