### ISSUE TITLE
Workshop Head shots

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1460]
Jeff Ferzoco, CARTO
![ferzoco jeff](https://user-images.githubusercontent.com/4912083/31411022-f78a133a-add5-11e7-95ba-9fecbdd8cef6.jpg)

Brian King, - GISP Session - Monday @ 8:00 am
![brian_king](https://user-images.githubusercontent.com/4912083/31410995-e1a67586-add5-11e7-9e46-eb628291a79f.jpg)

Mike Slovacek - Field Data Collection with TerraGoEdge Software session
![slovacek mike](https://user-images.githubusercontent.com/4912083/31411017-f271080e-add5-11e7-88c9-5bd6a4297707.jpeg)

Rich Grady,  AppGeo session - Tuesday, 8:00 am
![grady rich](https://user-images.githubusercontent.com/4912083/31411035-01f75cec-add6-11e7-9d30-52e95b7f82a4.jpg)

**Comment by KCMack** [comment]
![michael terner headshot - copy](https://user-images.githubusercontent.com/4912083/31461354-e80b8862-ae8e-11e7-8cf6-90a92762a4aa.jpg)

**Comment by christoball** [comment]
who is the last one?

**Comment by KCMack** [comment]
It's Mike Terner, AppGeo

**Comment by christoball** [comment]
resolved
