### ISSUE TITLE
AppGeo Workshop Instructors - change

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1464]
Please add:
Kate Hickey
Caitlin Schneider
Ross Topol 

Please remove:
Rich Grady

**Comment by christoball** [comment]
resolved in 42cc361d50cde61787e4306590e49ab2bcaef399

**Comment by KCMack** [comment]
Please remove the bio and photo for Rich Grady and add photos for Kate, Caitlin, Ross and Mike

**Comment by christoball** [comment]
i don't have headshots for kate, caitlin, or ross

**Comment by KCMack** [comment]
Bios for the 4  new instructors:
Caitlin Schneider is a GIS Analyst with AppGeo, in the Austin office.  She has experience in detailed spatial data collection and processing methods, spatial and non-spatial data integration, quality control and data documentation.

Ross Topol is a Full Stack Engineer with AppGeo, in the Austin office.  He currently works on designing, building and maintaining custom web applications for a variety of AppGeo clients ranging from local municipalities to federal agencies.  Ross is also an active member of the javascript community as a mentor to aspiring developers and as an advocate for open source technologies.

Kate Hickey is a Vice President with AppGeo.  She has been studying the business requirements of government, developing geospatial IT strategies, and planning GIS systems for federal, state, and local governments for over 15 years.

**Comment by KCMack** [comment]
Please add Caitlin's last name to the list of App Geo instructors.  The spreadsheet has been updated.

**Comment by KCMack** [comment]
Update the workshop more information page with the instructor change  - delete Rich Grady and add Caitlin Schneider, Ross Topol and Kate Hickey's  - names, bios and head shots.

**Comment by christoball** [comment]
resolved in 9efa0feda823a0f5f43661f2ccbdeecb23c9aa0d
