### ISSUE TITLE
Lidar DEM documentation Issue

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1472]
All mentions of Hydro-enforced dems needs to be changed to Hydro-flattened.  This has caused the USGS to remove our data as being QL2 in agency databases and needs to be corrected.

**Comment by mitchellryant** [comment]
@ThorTheDestroyer is this for all Lidar datasets of just StratMap, USGS, and FEMA?

**Comment by ThorTheDestroyer** [comment]
Looks like it is for everything.

**Comment by mitchellryant** [comment]
https://github.com/TNRIS/tnris.org/commit/74cdf9302041e1d272b8cb8647f8ea7241403ae5
