### ISSUE TITLE
Forum Wrap-Up Article & Photos

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1473]
Create forum thanks and photo recap

**Comment by KCMack** [comment]
2017 Texas GIS Forum Wrap-up

Thank you to the many people who helped make the 30th Year Celebration a success!  

Each year we attempt to develop an interesting and informative program.  We search the landscape to identify impressive keynote speakers who inspire us to be our bests selves and challenge us to focus on new, emerging technologies.  We hope the Forum speakers motivate you to utilize your data and applications for better visualization and decision-making.

We want to recognize and thank our sponsors, speakers, workshop instructors, moderators, and all of you who participated in this year’s Texas GIS Forum.

Many images were captured from the week of learning and information sharing.  We hope you enjoy them.

Thank you again!

TNRIS Team

**Comment by KCMack** [comment]
Additions to the article listed below
2017 Texas GIS Forum Wrap-up

Thank you to the many people who helped make the 30th Year Celebration a success!

Each year we attempt to develop an interesting and informative program. We search the landscape to identify impressive keynote speakers who inspire us to be our bests selves and challenge us to focus on new, emerging technologies. We hope the Forum speakers motivate you to utilize your data and applications for better visualization and decision-making.

We want to recognize and thank our sponsors, speakers, workshop instructors, moderators, and all of you who participated in this year’s Texas GIS Forum.

Many images were captured from the week of learning and information sharing. We hope you enjoy them.

We are diligently working to post the speakers' presentation slides.  Links coming soon! 

Finally, mark in your calendars for the 2018 Texas GIS Forum on October 22-26.

Thank you again!

TNRIS Team

**Comment by pwblanton** [comment]
QUESTION: Should we specifically acknowledge all of the work CMP does??? I think so!

 Anyway, here's my suggested edits.

Thank you to the many people who helped make the 30th year celebration a success!

Each year we attempt to develop an interesting and informative program. We search the landscape to identify impressive keynote speakers who inspire us to be our best selves and challenge us to focus on new, emerging technologies. We hope the Forum speakers motivated you to utilize your data and applications for better visualization and decision-making.

A huge shout-out to all of our sponsors, speakers, workshop instructors, moderators, and all the attendees at this year’s Forum.

Many images were captured from the week of learning and information sharing. We hope you enjoy them.

We are diligently working to post the speakers' presentation slides. Links coming soon!

Finally, mark in your calendars for the 2018 31st Texas GIS Forum on October 22-26, 2018!.

Thank you again!

TNRIS Team

**Comment by KCMack** [comment]
Additions to the article listed below
2017 Texas GIS Forum Wrap-up

Thank you to the many people who helped make the 30th Year Celebration a success!

Each year we attempt to develop an interesting and informative program. We search the landscape to identify impressive keynote speakers who inspire us to be our bests selves and challenge us to focus on new, emerging technologies. We hope the Forum speakers motivate you to utilize your data and applications for better visualization and decision-making.

We want to recognize and thank our sponsors, speakers, workshop instructors, moderators, and all of you who attended this year’s Texas GIS Forum.

Many images were captured from the week of learning and information sharing. We hope you enjoy them.

We are diligently working to post the speakers' presentation slides and videos. Links coming soon!

Finally, mark in your calendars for the 2018 Texas GIS Forum on October 22-26.

Thank you again!

TNRIS Team

**Comment by christoball** [comment]
@KCMack Ready for review:
https://preview.tnris.org/razor-wire/892c13a742118d52f9af040c89fbf99b4a1acdf6/news/2017-11-02/texas-gis-forum-2017-photos-thanks/

**Comment by KCMack** [comment]
One change, please eliminate the extra S in the following sentence:
"... our bests selves and challenge us..."  Should be our best selves

Thanks!

**Comment by christoball** [comment]
resolved in 3a6d31d00c9ae912c6369e3939d8ad23abe0c57f
