### ISSUE TITLE
Texas Mentorship Program page

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1474]
Develop dedicated page for Tx Mentorship Program under Education and Training
Sign up URL - http://bit.ly/TxGISMentor

**Comment by mitchellryant** [comment]
@christoball @adambreznicky 

we should look into moving the sheet into a main account. also maybe adjusting the form to populate different sheets. more custom interface

**Comment by christoball** [comment]
@KCMack mentorship page ready for review. Felicia looked at it with me and gave the thumbs up so if looks good to go we'll push it out.

https://preview.tnris.org/ellwood/d46084d24eb02b5c8df200da3e91790532018770/education/gis-mentorship/

**Comment by KCMack** [comment]
Look good!

**Comment by christoball** [comment]
resolved in d2692b3381217a14dbe1424e3dabe461b840decc
