### ISSUE TITLE
Change GIS Community meeting date and location

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1480]
Change meeting date and location to the following:

1st Quarter 2018
Tuesday, January 16, 2018
2:00 p.m. - 4:00 p.m.
Robert E. Johnson Conference Center, Central Room
1501 North Congress Ave.
Austin, TX 78701

**Comment by christoball** [comment]
resolved in 46be7e53d7e660d2f909043db6a2d38466e42972
