### ISSUE TITLE
GeoRodeo 2018 Page

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/tnris.org#1482]
Please create the 2018 GeoRodeo Page. When completed I can set up the /georodeo redirect (just let me know).

It can stand simply as a save-the-date for now... until we elaborate with the call for papers and such. No new wrangler images need to be present yet.

I'll also put together a surveymonkey about last years' event and add it to the page when complete.

Urgent?

Thanks

**Comment by christoball** [comment]
@adambreznicky @DavidHickman @JasonKleinert @mitchellryant are we going to have the call for presentations right now? Is this just a pure 'save the date'?

**Comment by adambreznicky** [comment]
i vote we just put it up now as a pure save the date.. just to get something out there. adding the call for presentations requires updating the form and google sheet. i can do that later this week.

**Comment by christoball** [comment]
@adambreznicky sounds good

**Comment by christoball** [comment]
Know it's not much but here's a preview of the the save the date page:
https://preview.tnris.org/ellwood/0db69d2da7e10947cc2f42822e7ebbe6520563e3/georodeo/2018

**Comment by KCMack** [comment]
The Save the Date graphic looks good.  No need to add the other narrative information.  But, it should clearly state "Save the Date"

**Comment by christoball** [comment]
@KCMack does this work?
https://preview.tnris.org/ellwood/2f4f0b77e5e560b5af37da16a66439d103a3ea03/georodeo/2018/

**Comment by KCMack** [comment]
The graphic is terrific with the Save the Date included.  In my opinion, no other information is needed.

**Comment by christoball** [comment]
Great, im going to push it out. 

resolved in 4c3566e96407e0a54160723bbaf8f778b9df4605
