### ISSUE TITLE
TNRIS iweb content

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1483]
content for the TNRIS's section on iweb

**Comment by christoball** [comment]
Need a short paragraph about TNRIS for the preview on the divisions page of iweb
![preview1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599de1581827cf2b06d2e400/125516c66e82c728ace21e0d46f8869f358b86bedeabf301b44fff9e2c4533317346f67227d7b67ee6467f530a0a49ac41585d4df9fdda29f3b12e6c981e5ab38532022d8c6853beb2901eb80bbb258a4e8db6bd884dc1e1352cf5c6.png)

**Comment by christoball** [comment]
**Just taking a quick stab at it to get ideas going**

As a division of the TWDB, our mission is to provide high quality historic and current geospatial data products and education and training for the general public and other state agencies, including our own. We have over 1,000,000 frames of Aerial Photography and over 200 unique datasets.

We support the TWDB with custom mapping, mapping application development, and more. We are also home to the Geographic Information Office, which seeks to advance the GIS community through collaboration, expertise, cost-sharing initiatives and exceptional customer service.

**Comment by KCMack** [comment]
Let's replicate this: https://tnris.org/about/
And add a section about the GIO like this https://tnris.org/geographic-information-office/

**Comment by KCMack** [comment]
Try this:
Texas Natural Resources Information System (TNRIS) was established by the Legislature in 1968 as the Texas Water-Oriented Data Bank. In 1972, after four years of growth and diversification, it was renamed the Texas Natural Resources Information System.

TNRIS provides high quality historic and current geospatial data products, education and training, while advancing the Texas GIS Community through collaboration, expertise, cost-sharing initiatives and exceptional customer service.

TNRIS provides the TWDB with maps: custom, standard agency requests, fulfilling legislative and board  requests, and custom graphics used for documents and presentations.  Additionally TNRIS staff are responsible for developing and maintaining two critical applications: the flood application and  the interactive State Water Plan.

TNRIS is home to the Texas Geographic Information Office, The Geographic Information Officer works in collaboration with state agencies to draft public policy recommendations and funding requirements related to the acquisition, distribution, and sharing of geospatial information.

**Comment by mitchellryant** [comment]
i would like to use this opportunity to answer the long serving TWDB questions. Who are you guys? and What do you do down there.

I was thinking about creating an "org style chart" using names/photos of staff. (FR will just have to get over the photos.) The chart could show the TNRIS teams members with skills and responsibilities.

I have discussed this suggestion with some staff members  and they agree it is a good avenue to explore.

**Comment by mitchellryant** [comment]
the iweb cms will be Cascade CMS, https://www.hannonhill.com/products/cascade-cms/index.html
