### ISSUE TITLE
Add Bern Keynote Update

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1486]
brief update with bern keynote video

preview: https://preview.tnris.org/ellwood/0806a5fc54cd53417fc22ad5f3f92135b7154124/news/2017-12-18/video-bern-szukalski-2017-texas-gis-forum-keynote/

**Comment by christoball** [comment]
@KCMack do you have a short paragraph about Craig?

**Comment by KCMack** [comment]
The preview looks terrific!

**Comment by geochik** [comment]
@christoball Blurb for Craig Pedersen

Craig Pedersen has thirty-five years of experience in organizational management and leadership in the areas of state and local governance, finance, and water policy.Mr. Pedersen’s 1981¬–2002 career in the Texas state government included both administrative and policy positions, and culminated in eleven years as the Executive Administrator of the Texas Water Development Board, where he was recognized for organizational innovation in both leadership and policy.

**Comment by christoball** [comment]
@KCMack @geochik 2nd draft:
https://preview.tnris.org/ellwood/daa1ea525f1873023727d90565b228f1d96c33bc/news/2017-12-18/forum-video-bern-szukalski-craig-pedersen/

**Comment by geochik** [comment]
@christoball  I'm good with it but there is an extra little hyphen between 1981 and 2002 on Craig's bio.
