### ISSUE TITLE
Add GIS Community Agenda

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1487]
Need to upload GIS Community agenda and hotlink on GIO page.
Agenda located here: M:\\Admin\GIO\QtrlyCommunityMtgs\2018\1stQtr\GISComm_Agenda_20180116.pdf

**Comment by geochik** [comment]
Agenda has been uploaded and changes made to add agenda to GIO page on Glidden. Please merge with Master upon review.

**Comment by DavidHickman** [comment]
fixed in 970500c037d4608bd4c4e4ee2767605b858b3974
