### ISSUE TITLE
Forum Poster Contest Winners

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1488]
Please add the contest winners to the 2017 Forum website

Details can be found:M:\Forum_GeoRodeo\2017 Forum\Poster Contest\Winners

**Comment by christoball** [comment]
Preview of article available here:
https://preview.tnris.org/ellwood/6d124b0a3b6e83d0318a62c0ec55f451e562a608/news/2018-01-10/poster-gallery-winners-207-texas-gis-forum/

**Comment by KCMack** [comment]
I  think it looks fabulous!!

**Comment by christoball** [comment]
resolved in 50afe0d66cf8b331a705bfe756a1cd25cc29cfdc
