### ISSUE TITLE
Add GIS SG Meeting Notes

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1489]
Meeting note updates for 6 months worth of GIS Solutions Group meeting notes.
Page listing updated on Glidden. Notes need formatting and posting.
Notes available here - M:\Admin\DCS_GIS Solutions Governance Council\Meeting Notes_Agenda\Updates

**Comment by christoball** [comment]
All the notes have been added, preview here, using the meeting notes list on the side:
https://preview.tnris.org/ellwood/2eb82e24e9f3d0af318c8712d2a0aff35a82fdb6/geographic-information-office/gis-solutions-group/

**Comment by geochik** [comment]
Please update meeting date for next GIS SG meeting to January 18, 2018. Same time.

**Comment by geochik** [comment]
One more set of notes to upload:
[GIS SG Meeting Notes 2017-03-07 Final.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599c64cafada7e0606ba7cba/125516c66e82c728ace21e0d46cfbda963b1a4e9a2ecba57ad53f7d4074933763a44f17b21d2ae78ec0f2b564f2917f210044d58eeb9cb74fce36f34985619e8d86a5d71c03445f8bad74ab801ba20894680b2ef8819c7fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ae44951a2163167ee77346e0a.docx)

Also, please add the following months as "No meeting held":
April 2017
August 2017
October 2017

Thank you!

**Comment by geochik** [comment]
Nov 2017 - remove extra bullet under "Local Partners"
July 2017 - Add a little more space between "Owner/Description" columns at the bottom of the page
June 2017 - remove extra dash on 3rd bullet under "Collaboration and Input Discussion"
May 2017 - remove last section title on the page - "Collaboration and Input Discussion"

**Comment by christoball** [comment]
@geochik made those edits, preview here:
https://preview.tnris.org/ellwood/9c758409499d04098134d93d72e8a18656f72280/geographic-information-office/gis-solutions-group/

**Comment by geochik** [comment]
@christoball  Looks great! Love the format of the columns at the bottom of June notes. 

Will you still remove the notes beyond one year from the list?

Thanks so much!

**Comment by christoball** [comment]
made it 12.

resolved in 50afe0d66cf8b331a705bfe756a1cd25cc29cfdc
