### ISSUE TITLE
2018 Training Program Schedule

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1490]
Please add the schedule.  The spreadsheet has been updated

**Comment by christoball** [comment]
Preview schedule here:
https://preview.tnris.org/razor-wire/798a12970eaf70b8e7c2e16186cc57c9d1672cf1/training/

preview front page here:
https://preview.tnris.org/razor-wire/798a12970eaf70b8e7c2e16186cc57c9d1672cf1/

**Comment by KCMack** [comment]
Thanks, Chris.

As soon as the link is sent to me, I’ll be sure to pass it along.

Both the schedule and front page look good.

Many thanks,

KCM

**Comment by KCMack** [comment]
Please update the training schedule on preview.  Spreadsheet has been revised with dates and class fees.

**Comment by christoball** [comment]
latest preview:
https://preview.tnris.org/razor-wire/c0c539f6161c8f9c7fd4a6768967fa2a5f2b9c85/education/

**Comment by KCMack** [comment]
Once more refresh from the spreadsheet.  Patricia found several items that required correction.  
After the refresh, please publish the schedule.

Thank you.

**Comment by christoball** [comment]
resolved in 50afe0d66cf8b331a705bfe756a1cd25cc29cfdc
