### ISSUE TITLE
Remove "Updates" from Texas Google Imagery Page

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1491]
Request to remove update section from Google page.

**Comment by geochik** [comment]
Chris, this project is moving along on its own. Gayla emails all updates to participants via email. Please remove "Latest Updates" section from Texas Google Imagery page - https://tnris.org/texas-imagery-service/

**Comment by christoball** [comment]
removed it

 resolved in 387ec7cf49520f99d18ed98a937987da3ee364a3
