### ISSUE TITLE
Main banner idea, StratMap Contracts

### ISSUE THREAD

**Issue by gmullins** [TNRIS/tnris.org#1492]
Feb or Mar may be a good time to show off this since that will begin the two-year mark of the contracts.

Something like: 

First two years of StratMap/DIR Contracts are a huge success! 

Over 90 geospatial services and products purchased
Over 400 geospatial software purchases
All from over 270 Texas government agencies

This contract vehicle provides savings in ease of use and deep discounts to state, regional and local Texas government agencies.

If you’re not one of the 270 agencies already using these contracts, check them out here. 

Some word cloud graphics are here if helpful at all: M:\SM\SM Contract\Word Cloud

**Comment by gmullins** [comment]
![Cloud 1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b691ca086d420011f174f3/125516c66e82c728ace21e0d46cb98953686c3f8cda5fd53b652fa912a5265296b51fa7c22d0b571bb4629040a584eac415a5641f8aa8b7ea1a42062c80d55b98e30063e937f03a6aa8317b500bf218e4a84b1bc8b4ac2ed3b37aa.png)
![Cloud 1 (2).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b691ca086d420011f174f3/125516c66e82c728ace21e0d46cb98953686c3f8cfa1ed0ae611b2843b492d762a10e17132d0ba7fed172d580b0b4cf9145f5f44fcfb802ea2e53e258d4e17ff933c0120996048e6edc00db513bb28814e80b7b98f4dc7e83923e48b885d73.png)

**Comment by gmullins** [comment]
Here are the thoughts in paragraph form:

The first two years of the StratMap/DIR Contracts have been a huge success! Since early 2016, over 270 government agencies across Texas have used the contracts to purchase over 90 geospatial services or data products and over 400 geospatial software licenses. The StratMap/DIR Contracts provide savings in ease of use and deep discounts to state, regional and local Texas government agencies. Geospatial services, products and software are provided by 17 pre-qualified vendors, each with a Department of Information Resources (DIR) itemized pricing index and associated % discounts.

Services and products range from public safety GIS data analysis and management systems training to road centerline updates/development and new orthoimagery/lidar/ground control services, to name a few. Software licensing and maintenance are also available for purchase using these existing state contracts with leading GIS companies.

If you are not one of the over 270 agencies already taking advantage of these contracts, check them out here.

**Comment by mitchellryant** [comment]
@christoball we are going with the StartMap Contracts as the March banner. Can you work on a graphic and get the data content above on a page.

**Comment by christoball** [comment]
@gmullins Graphic Draft
![stratcontracts.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599de1581827cf2b06d2e400/125516c66e82c728ace21e0d46fb8088229680a681fdad42a749e3d665043761260ea62864c7b96aea1b2c535a5947f8155a0a11fbf9892ba4bf3974d95e5eeac3714d36976345f3e5db55ea43a82a994e8cbcbd8f4dc9e93921e482864c39161755.png)

**Comment by christoball** [comment]
1st draft of article:
https://beta.tnris.org/news/2018-02-26/two-years-stratmap-contracts/

**Comment by KCMack** [comment]
The article looks good.  The language is tight and points are made in succession.  I like the left side box highlighting the statistics.  

I recommend it's a go.

**Comment by gmullins** [comment]
Hurrah! I'm good to go too.

**Comment by christoball** [comment]
resolved in 84995e39cc66efd2f88ee3d3d182178227967572
