### ISSUE TITLE
Automate GIS Solutions Group notes list

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#150]
Make the list of Solutions Group Notes automatically populate on this page:
https://tnris.org/geographic-information-office/gis-solutions-group/

- Requires front-end javascript, 'For loop'
- Shows last 12
- API would need checkbox or dropdown to select a document type, i.e. "Solutions Group Notes"

Some of the older Notes were published as markdown pages. I'm fine with not referencing these at this point, instead just using the document upload and urls.

**Comment by jwhaney** [comment]
backend api issue created here - https://github.com/TNRIS/api.tnris.org/issues/62
