### ISSUE TITLE
East Texas Local News Update

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1501]
Update about east texas news piece.

Video embed needs debugging assistance.

Working on ellwood branch

**Comment by adambreznicky** [comment]
adjusted the embed in commit edf28ad483ac2ad95e8d435b81052e723dbf618a

ready for your final tweaks (if any) merger into master

**Comment by christoball** [comment]
Added article text. @geochik  and @KCMack can yall look over?

https://preview.tnris.org/ellwood/32440c4ef158953d5b2d403652e6abb289633d0c/geographic-information-office/2018-02-07/east-texas-gis-community-tnris-featured-local-news/

**Comment by geochik** [comment]
@christoball  - I'm good with the write-up but 2 things:
1. Can we list someone else as the "author" of the page? Having my name as the author of the article feels like boasting. Does that make sense?
2. Before production, I would like to change the date on the next GIS Community meeting. Separate ticket to follow.

**Comment by christoball** [comment]
1. yes. how about just 'Geographic Information Office'
2. will do.

What was the day of this East Texas meeting and are there more details about it somewhere?

**Comment by geochik** [comment]
1. Perfect!
2. Thank you!
The only link to the meeting comes from the LinkedIn group administered by the organizer Justin Cure - https://www.linkedin.com/groups/1953489. The meeting was held at SFASU on Friday, February 2.

**Comment by christoball** [comment]
Made those edits and changed the GIO meeting:
https://preview.tnris.org/ellwood/d8f09f5efd0ffc363aa4461a49bf0207741bbe7d/geographic-information-office/2018-02-07/east-texas-gis-community-tnris-featured-local-news/

**Comment by christoball** [comment]
resolved in 1ab8370ae28dfdbf1353561f0c9150bc09668ba9
