### ISSUE TITLE
Central Texas Lidar public release

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1504]
- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer
- [x] Data Processing [renaming file, data organization, coverage map] @ThorTheDestroyer @mitchellryant
- [x] Creation of derviative products @ThorTheDestroyer
- [x] Quality Assurance @ThorTheDestroyer
- [ ] Data Publication [Update data catalog sheet, create data catalog images, supplemental reports staging] @ThorTheDestroyer
- [ ] Data Story @ThorTheDestroyer @christoball 
- [ ] Final Publication @christoball @ThorTheDestroyer 
- [x] Move data to production shares @ThorTheDestroyer
- [ ] Inform TNRIS staff of data availability @ThorTheDestroyer 
- [x] Add to Data Download  @mitchellryant https://github.com/TNRIS/data-download/issues/89

**Comment by ThorTheDestroyer** [comment]
LAZ are currently being compressed. Data is being copied to  the Lidar drive under 
stratmap-2017-50cm-central-texas

**Comment by ThorTheDestroyer** [comment]
LAZ created and moved to lidar share, DEMs moved to lidar share.  

5ft contours currently being generated. Process was initiated 02/13/17 and based on current progress should complete in four days(~95 hours of  processing time remaining).

**Comment by ThorTheDestroyer** [comment]
Data story has been created. 

https://github.com/TNRIS/tnris.org/blob/haish/content/markdown/news/2018-03-09_2017-centraltexas-lidar

**Comment by ThorTheDestroyer** [comment]
2ft contours are currently being created

**Comment by ThorTheDestroyer** [comment]
All data has been moved to lidar directory. Coverage map under main carto account ready for creation to complete data processing

**Comment by mitchellryant** [comment]
@ThorTheDestroyer here is the id for the coverage map

3a604ee9-301b-4bf2-82a5-095072ef6076

**Comment by ThorTheDestroyer** [comment]
Images have for article and release story have been placed in their respective locations.

**Comment by mitchellryant** [comment]
@gmullins preview with KM edit
news article - https://preview.tnris.org/haish/6f5865c24a3f87706bc36e22a71d23f712d32636/news/2018-03-19/lidar-release-central-texas/
data catalog - https://preview.tnris.org/haish/6f5865c24a3f87706bc36e22a71d23f712d32636/data-catalog/entry/stratmap-2017-50cm-central-texas-lidar/

**Comment by christoball** [comment]
Added images to article and to data catalog entry

What text do you want on the image slider for each side?

article:
https://preview.tnris.org/haish/969fe4f65874715217b8eb11c405a3006c7ad4c7/news/2018-03-19/lidar-release-central-texas/

data catalog entry:
https://preview.tnris.org/haish/969fe4f65874715217b8eb11c405a3006c7ad4c7/data-catalog/entry/stratmap-2017-50cm-central-texas-lidar/

**Comment by ThorTheDestroyer** [comment]
for new: StratMap 2017, for Old: CAPCOG 2012

**Comment by gmullins** [comment]
Looking good! Made my edits in github. 
@ThorTheDestroyer Wondering if more zoomed in slider images would show the old/new data difference better.

**Comment by christoball** [comment]
Updated slider text and cropped in closer for more detail:
https://preview.tnris.org/haish/568e435d0511fd7008856e4cbe0806117e9eaeee/news/2018-03-19/lidar-release-central-texas/

**Comment by KCMack** [comment]
Under product specification, the spacing between the  second and third dot point is different.  Please make the spacing consistent between dot points: "Average first return....." and "Point data...."

**Comment by gmullins** [comment]
@christoball crop looks good! Please use StratMap over Stratmap (slider label).

**Comment by adambreznicky** [comment]
added to data download app via data-download commit 1948252508c3aa158172385488fd26952d7d63b6

**Comment by christoball** [comment]
resolved in bcdd407d062e96d1e823acedaddc5ee28af7c22a
