### ISSUE TITLE
iweb: Update Staff Section

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1505]
Can we add short description of responsibilities to staff page? i would like this page to be able to direct people to right person to ask a question.

This is my first pass, needs formatting. 

Richard Wade - Deputy Executive Administrator
Patricia Blanton - Executive Assistant
Felicia Retiz - Associate GIO 
Kathleen Mack - Business Manager\Training Program
Miguel Pavon - Special Projects (VR Sandbox)

Information  Services
Ryan Mitchell - Team Lead (TNRIS Data and Data Services)
Chris Ledesma - Web Site and Graphics
Adam Breznicky - Application Development
Jason Kleinert - Application Development

Strategic  Mapping (StratMap)
Gayla Mullins - Manager (Remote Sensing and Imagery)
Erik O'Brian - Cartography and Plotting
Joey Thomas - Research  & Distribution Team Lead, StratMap Lidar\Elevation
Lauren Kirk - RDC Analyst
Walter Couser - Intern
Chelsea Sidenblad - Intern

**Comment by christoball** [comment]
Made these edits in cascade.
