### ISSUE TITLE
iWeb: StratMap

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1506]
The black box on the TNRIS iWeb page looks out of place. Please make it a simple paragraph that follows the GIO description paragrah with the following text:

TNRIS is also home the the <link to SM page>Texas Strategic Mapping Program (StratMap). StratMap was originally established in 1997 by Senate Bill 1 to develop consistent statewide digital data layers. Since then, its primary goal has been to acquire and improve digital geographic data for statewide mapping applications. StratMap also maintains comprehensive data standard specifications to ensure consistent, high quality data products across the State. StratMap personnel at TNRIS work with multiple agencies on cost-share initiatives to provide the State of Texas with best value data products.

This message is approved by @gmullins

**Comment by christoball** [comment]
This has been resolved, thanks for the suggestion:
https://iweb.twdb.texas.gov/offices-divisions/tnris/index.html
