### ISSUE TITLE
TNRIS Training - course closed

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1508]
Please change the status from OPEN to CLOSED for ArcGIS Pro Quick-Start dates: February 22-23

The spreadsheet has been updated

**Comment by christoball** [comment]
@KCMack Updated this on preview. Let me know if it looks good to go. The front page preview of upcoming courses was also changed.

https://preview.tnris.org/ellwood/cacf2bb4bee405b8275e8094f53949d0b98e51d5/education/

**Comment by christoball** [comment]
resolved in 40eb4e3961d6a33db07bbba25882bc2e7c561b24

**Comment by KCMack** [comment]
Chris, please reverse the new date action taken.  Last night 3 additional people registered for the class so we will host it on March 1-2 as originally planned.  I'll update the spreadsheet.
