### ISSUE TITLE
Save the Date - 2018 Texas GIS Forum

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1509]
Please create a graphic as a place holder to announce the dates of the Texas GIS Forum - October 22-26, 2018

**Comment by christoball** [comment]
@mitchellryant can you redirect tnris.org/texas-gis-forum to the 2018 page at texas-gis-forum/2018/index once this goes live? We expect to have it up by friday or next monday.

**Comment by mitchellryant** [comment]
Let @adambreznicky or @JasonKleinert know when you are ready, and they will make the change of the redirect.

**Comment by adambreznicky** [comment]
redirects deployed via deployment repo commit 6a0354e50bf7656e90c72eb306914e2115fba407
