### ISSUE TITLE
Texas Imagery Service under Programs

### ISSUE THREAD

**Issue by gmullins** [TNRIS/tnris.org#1511]
Please move https://tnris.org/texas-imagery-service/ as new Program in listing as Texas Imagery Service.

**Comment by gmullins** [comment]
Texas Imagery Service should be same heading level as StratMap and Education & Training.
![TIS_list.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b691ca086d420011f174f3/125516c66e82c728ace21e0d46dcbda91c8e8aba9babf301b44fff9e2c4533317346f67227d7b67ee6467f530a0a49ac41585d4df9fdda29f3b12e6c981e5ab38532022d8c6853beb2901eb80bbb258a4686b7b5834ec1ed3422f5c6.jpg)

**Comment by gmullins** [comment]
Please also keep on GIO page for now.

**Comment by christoball** [comment]
Preview and double check the new navigation here:
https://preview.tnris.org/ellwood/edf6340367932edd58682d00e881fe17a2ef5df2/

**Comment by gmullins** [comment]
Looks good!

**Comment by gmullins** [comment]
Adding @geochik to review.

**Comment by geochik** [comment]
That was easy! Looks perfect!!

**Comment by christoball** [comment]
resolved in edf6340367932edd58682d00e881fe17a2ef5df2
