### ISSUE TITLE
TRAINING Course Date Changed

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1512]
The date for Intermediate Programming in ArcGIS with Python  has been moved to March 14-15.  
The current session status changed to CLOSED
The spreadsheet has been updated

**Comment by christoball** [comment]
Preview changes here: 
https://preview.tnris.org/ellwood/55e39f1c807b00838677630c913520494cd8e538/education/

**Comment by christoball** [comment]
resolved in 152f0ac719d61b5e6057fa8f11b715deab518f24
