### ISSUE TITLE
GeoRodeo Updates

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/tnris.org#1513]
The timing surrounding the GeoRodeo for this year is shrinking and we need speaker submissions! Deadline for call for presentations is just a couple weeks away

* Update the mini-banner GeoRodeo graphic on the front page of the site. Should announce the open call for presentations rather than save the date.
* Update all graphics on the GeoRodeo page and site in general with this years' space graphics
* Tweet about the call for presentations
* (Side Note) Tweet about the current open dev position

**Comment by christoball** [comment]
@adambreznicky i heard you working on a registration form. Can you add that as a page in the 2018 GeoRodeo and to the nav.html?

**Comment by adambreznicky** [comment]
will do! i plan to have the form completed by EOB friday

Side note: we will be ordering stickers next week also. we plan to order 3" by 3" die-cut stickers. we'd like to use the awesome, new code wrangler in a space car image you made for this year. we'd like to keep it more generic (no date or georodeo text), just have "tnris.org" on there. could we get this graphic also?
https://www.stickermule.com/products/die-cut-stickers

**Comment by christoball** [comment]
Preview new graphic page here: https://preview.tnris.org/ellwood/8bc235d4a8938a20e150c310e6406a47f89d746d/georodeo/2018/

**Comment by adambreznicky** [comment]
georodeo page looks good.

front page issues:
* georodeo banner links to stratmap contracts page still
* 'small' banner image is still the stratmap contracts image. (if you shrink the page width or look at it on mobile, the banner image is the stratmap banner)

**Comment by adambreznicky** [comment]
also, i dont know if you intended to change the active color on the call for presentations & register buttons in the nav bar but when active, they are still the original salmon color

![Screenshot from 2018-03-06 08-24-03.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5972568472d14a001f805e0f/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f3783dd5b568ef1a36535b424eaf53444d04bea6d37ef5f22e7a985902ead368597d926913f9ed851fbf01b8298e4bd6b4e98d5edcfa7f74b9dfd0126754505a9bf54f34a8934acd5af648e54b57a215316bef647b.png)

**Comment by christoball** [comment]
those things should be fixed now. if it looks good ill post asap.

https://preview.tnris.org/ellwood/563d616f675ec1a0c9a9dfe0931d1fc77e8c8fe2/

**Comment by adambreznicky** [comment]
looks good to me! let's go to prod!

only thing we need yet is the sticker image so we can order them up this week. thanks
