### ISSUE TITLE
TNRIS Training - new Purchasing section

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1515]
Narrative attached describing information purchasing agents need to know, along with a W-9 PDF

**Comment by KCMack** [comment]
[CMP W-9_3.1.18.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599df692453cba2d8789d6c6/125516c66e82c728ace21e0d46cbb9aa63b5cef0b0baf112ea0ca8d665043761260ea62864c7b96aea1b2c535a5947f8155a0a11fbf9892ba4bf3974d95e5eeac3714d36976345f3e5db55ea43a82a994d86bcbd8f4dc9e13921e68f86473e1b1755.pdf)
[For Purchasing Agents_3.1.18.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599df692453cba2d8789d6c6/125516c66e82c728ace21e0d46ce9b8863b296bb8ce1be50ad53f7d40841227d3d179c783ed4ad79e70037431f1d11f6140b1b56f6eb8c22a1b4397683085fef84385874c63d13a5bd864cbd54bd32975dc7e7e2de139db17770a599855d3f170f198cfe543ca49d4acf5ef14be35f18.docx)

**Comment by christoball** [comment]
Preview the Purchaser Resources page here:
https://preview.tnris.org/ellwood/379d7aad9f7a5670b04702f371429dfb115eddf2/education/purchasers/

**Comment by christoball** [comment]
Resolved
