### ISSUE TITLE
1st Qtr GIS Community Notes

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1516]
Notes from the 1st qtr meeting are available for review and correction on Glidden.
Known issues:
Need a logo for UT-CSR (Roll Call)
The meeting slides include the feature presentation and require upload to Speaker Deck - M:\Admin\GIO\QtrlyCommunityMtgs\2018\1stQtr\GIS_QtrlyMtg1_2018_v2.pptx

**Comment by christoball** [comment]
The UT CSR doesn't have a viable logo to use.

**Comment by geochik** [comment]
@christoball  I sent a request to CSR for a logo. Is there a specific format you want? What was the issue with the logo?

**Comment by geochik** [comment]
![CSR.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599c64cafada7e0606ba7cba/125516c66e82c728ace21e0d46cba7a861cec1b99de6b546a749b2ce6b137e247b51f5727481b12dba152b515f5d47a9450b5d11fbeb9539e4e76224d50152a7842f4d7ed43c16a6b9871dbf09b22082488db0b48a5e8d.png)

@christoball  Please let me know if there is a different format you need.

**Comment by christoball** [comment]
@geochik this one works. There was no logo on their site and different versions when I searched, so I didn't know what was actually official.

**Comment by christoball** [comment]
resolved in 1ce8127562e67bbb1276212a1a20351cbcce9153
