### ISSUE TITLE
Add Upload AOI to Historic Order form

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1521]
Add Upload AOI to Historic Order form, this will allow user of the to upload an AOI when requesting Historic data. You can already do this when requesting lidar data.

**Comment by adambreznicky** [comment]
was previously set up to allow this functionality, only it required the Historical order to be digital. i updated the form to allow an AOI upload for both paper and digital historical orders.
changed via commit fec41781417203d2c5e58710e2315f3c99964996
deployed to production.
