### ISSUE TITLE
Texas Emergency GIS Response Team Training

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1522]
Texas Emergency GIS Response Team (EGRT) Training

Training for GIS Responders
Training is critical to perform as a GIS responder.  This one-day, free training event uses the EGRT Response Guide to define the role and response protocols including checklists for emergency scenarios.  Students will receive the ERGT Response Guide.

Requirements to become a Texas ERGT volunteer: participate in a one-day ERGT training class, review the ERGT Standard Operational Guidelines, and complete three required FEMA training courses

Instructor: David Allen

Registration: Texas Emergency GIS Response Team website

Location: Stephen F. Austin Building, 1700 North Congress Avenue, Room 172, Austin, Texas 78701

Date/Time: March 26, 2018 at 8:30 – 4:30

**Comment by adambreznicky** [comment]
added to front page via commit 11410f26a86464e756a3264317ba0a35f41b5ddc

**Comment by KCMack** [comment]
https://guestli.st/501663  Link to the Registration Website
Thanks

**Comment by adambreznicky** [comment]
link added via commit 20db360c457a7f1b8b87b5711bea7dee03a54647

**Comment by christoball** [comment]
resolved in 5a043366f64536e3225a78840f90c4daa19b6de3
