### ISSUE TITLE
TNRIS Training - close sessions

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1525]
Please change status from OPEN to CLOSED on:
April 2-3 Learning ArcGIS Pro1: Fundamentals
Mapy 10 Learning ArcGIS Pro 2: Analysis, Automation, and Sharing
The spreadsheet has been updated.

**Comment by KCMack** [comment]
Yes, please.

**Comment by christoball** [comment]
resolved in ce4b971046c34dd4b9ff25b1fb7127c901d83350
