### ISSUE TITLE
Texas Imagery Service Updates

### ISSUE THREAD

**Issue by gmullins** [TNRIS/tnris.org#1526]
Map of Latest Updated Imagery for near top of here: https://www.tnris.org/texas-imagery-service/

**Comment by gmullins** [comment]
Map is: https://tnris-twdb.carto.com/u/tnris-sm/builder/e573eae2-a7f2-4b23-8a26-92696d8d5947/embed

**Comment by gmullins** [comment]
Add link to FAQ topic - How much does the service cost for my agency?

**Comment by mitchellryant** [comment]
is there a way to make the FAQ collapsable or more reader friendly?

**Comment by christoball** [comment]
I've made some edits. Needs some fine tuning, but check out how we could maybe rearrange the faq.

https://preview.tnris.org/washburn/cb4c161e96c7dff31d3982929fab559ff83d73a9/texas-imagery-service/

**Comment by gmullins** [comment]
I like it! Here are a few suggested adjustments:

- Add title for map above map: 'Latest Updated Imagery'. 
- Take off top 'Learn more in the Project FAQ'?
- Take off 'Project FAQ' text
- Linked FAQs in blue text

Thx!

**Comment by christoball** [comment]
These are good suggestions, but my issue with the blue text is it isn't very readable. It's meant for when links are shorter and inline with other text. 

I'm going to try some  other ways to indicate they are links.

**Comment by christoball** [comment]
Before we publish, can the text with underscores in the map be edited to look natural?

**Comment by gmullins** [comment]
I think the current plan is to leave them as is until the next map update which should happen within the month of April. They should be resolved then.

**Comment by christoball** [comment]
I pushed some of my edits but the sticky FAQ list doesnt seem to be working.

https://preview.tnris.org/washburn/cd70ee16b75cbffd3d7ce5c68c4d80a7d1c84948/texas-imagery-service/
