### ISSUE TITLE
StratMap 2017 Coastal Lidar Public Release

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1534]
- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer
- [x] Data Processing [renaming file, data organization, coverage map] @ThorTheDestroyer @mitchellryant
- [x] Creation of derviative products @ThorTheDestroyer
- [x] Quality Assurance @ThorTheDestroyer
- [x] Data Publication [Update data catalog sheet, create data catalog images, supplemental reports staging] @ThorTheDestroyer
- [x] Data Story @ThorTheDestroyer @christoball 
- [x] Final Publication @christoball @ThorTheDestroyer 
- [x] Move data to production shares @ThorTheDestroyer
- [ ] Inform TNRIS staff of data availability @ThorTheDestroyer 
- [ ] Add to Data Download  @mitchellryant https://github.com/TNRIS/data-download/issues/90

**Comment by ThorTheDestroyer** [comment]
- [] Add data to measures spreadsheet @ThorTheDestroyer
- [] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer
- [] Data Processing [renaming file, data organization, coverage map] @ThorTheDestroyer @mitchellryant
- [] Creation of derviative products @ThorTheDestroyer
- [] Quality Assurance @ThorTheDestroyer
- [ ] Data Publication [Update data catalog sheet, create data catalog images, supplemental reports staging] @ThorTheDestroyer
- [ ] Data Story @ThorTheDestroyer @christoball 
- [ ] Final Publication @christoball @ThorTheDestroyer 
- [] Move data to production shares @ThorTheDestroyer
- [ ] Inform TNRIS staff of data availability @ThorTheDestroyer 
- [] Add to Data Download  @mitchellryant https://github.com/TNRIS/data-download/issues/89

**Comment by ThorTheDestroyer** [comment]
Data copy to projects complete

**Comment by ThorTheDestroyer** [comment]
LAZ compression underway

**Comment by ThorTheDestroyer** [comment]
dem catalog created, 2ft and 5ft contours currently being generated.

**Comment by mitchellryant** [comment]
I think going forward this should be rename to StratMap 2017 Jefferson\Liberty Lidar. This will keep with the convention we have of naming the projects for Download and Data Catalog with their regional areas. 

It will also prevent confusion, for the customers, when the 2018 StratMap and FEMA coastal areas are released.

![download](https://user-images.githubusercontent.com/8459928/38992005-086057c2-43a5-11e8-8efd-47697a2dfb4d.jpg)

**Comment by mitchellryant** [comment]
@ThorTheDestroyer here is the carto id for the data catalog.

1906a6bb-ceba-4eb8-8ff7-022f01e7a641

**Comment by ThorTheDestroyer** [comment]
Sounds good to me, I'll rename them in the articles and catalog

**Comment by ThorTheDestroyer** [comment]
Coastal article and catalog images created and saved to website directory.

**Comment by ThorTheDestroyer** [comment]
article and catalog renamed.  Directory will be renamed after data copies complete.

**Comment by christoball** [comment]
Photos added to article and data catalog entry:
https://preview.tnris.org/haish/f5f384c24b2efe389cbfb22c53779d7f9609555b/news/2018-04-13/lidar-release-jeffersonliberty/

**Comment by mitchellryant** [comment]
StratMap 2017 Liberty 35cm & Jefferson 50cm Lidar

**Comment by christoball** [comment]
Latest version with adjusted names: 
https://preview.tnris.org/haish/88b5fdff12a8c7e4b23a03f895f01934c7f52901/news/2018-04-24/lidar-release-jefferson-liberty-counties/

**Comment by ThorTheDestroyer** [comment]
Data catalog Entry Title change to StratMap 2017 Jefferson 50cm & Liberty/Chambers 35cm Lidar

**Comment by gmullins** [comment]
Article looks great! A reminder to insert the XX cm for the accuracy statements.

**Comment by mitchellryant** [comment]
@christoball  please rename the data catalog md from stratmap-2017-50cm-jeffersonliberty-lidar to stratmap-2017-50cm-jefferson-35cm-chambers-liberty-lidar

**Comment by christoball** [comment]
Now updated with new name. Going to go ahead and push.
https://preview.tnris.org/haish/b8e7bff7a05fa49f70bb7912f1ac67a010b27e2b/news/2018-04-30/lidar-release-jefferson-liberty-counties/

**Comment by christoball** [comment]
Resolved, article published.
