### ISSUE TITLE
Lou article

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1536]

**Comment by KCMack** [comment]
Lou Falconieri, the "face of TNRIS" to many of its users in the early years, has passed away. Lou headed up the TNRIS User Services desk from the 1970s until his retirement in 199?. The ultimate "people person," he provided a wonderfully high level of personalized customer service. Lou's specialty was helping people locate aerial photography, satellite imagery, and maps. He had the uncanny ability to go to the exact canister of NASA film or the file drawer containing the needed imagery, whether recent or covering decades of history. He will be remembered by hundreds of TNRIS users for his generosity and professionalism. He will also be fondly remembered by the scores of student interns whom he mentored and befriended. They are all over the country now, many them in geography-related government or teaching positions - Including Richard Wade, the current TNRIS Division Chief - and they all feel a debt of gratitude to Lou for his encouragement and support. Prior to his TNRIS career, Lou served in the US Air Force from 1954 to 1977, retiring as Lieutenant Colonel.

**Comment by christoball** [comment]
Updated text with Lou's employment dates.

**Comment by christoball** [comment]
Preview front page here:
https://preview.tnris.org/ellwood/0e40eab83d7641cdd3e77f33cddfcaa5480382da/

And article here:
https://preview.tnris.org/ellwood/0e40eab83d7641cdd3e77f33cddfcaa5480382da/around-the-state/2018-04-12/in-memory-of-lou-falconieri-early-face-tnris/

**Comment by christoball** [comment]
added and Changed photos around
https://preview.tnris.org/ellwood/cef4674f684d1397f8ed6e9129fdf4324df05fa4/around-the-state/2018-04-12/in-memory-of-lou-falconieri-early-face-tnris/

**Comment by christoball** [comment]
resolved in edf37b9e767af281c7d48bd048e95222177772ea
