### ISSUE TITLE
Create Rodeo Walk-in Sign-in Sheet

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1537]
Please modify the training sign-in sheet with the GeoRodeo logo.  This will enable walk in participants to let us know they're part of the group for reporting purposes.

**Comment by KCMack** [comment]
[Sign-in Template_2018.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599df692453cba2d8789d6c6/125516c66e82c728ace21e0d46db9d9d2dcf8aa7cfddba4eb451f1802c797523785ce1673295f127b54778154d555ca9485f5d41faf0dd7fa4e369778a5c0befd8685b27c46816bea4905dee5fee7fd616cfe3fe9846d2e9352fe68e8d4c3716051b88fe5f34a08b06.xlsx)

**Comment by christoball** [comment]
Resolved
