### ISSUE TITLE
Add Parking Pass to GeoRodeo page

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1538]

**Comment by KCMack** [comment]
[GeoRodeo_Parking Pass 2018.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599df692453cba2d8789d6c6/125516c66e82c728ace21e0d46cf9195118d87ac80d68f42b656f99a2e0617723a17e37920d4bb6af3006b1300051bff054a5556f9f08e29a3b03524de5e5eb8d66d5f74c43414a8eb804ab813a632c91edbe2e3d7158abd7f37ed998e47341f001a8af65536a59842c95cf059ac.pdf)

**Comment by christoball** [comment]
resolved in a6bbb2dfa121a9f50b736cfd04e97326bbdf218b
