### ISSUE TITLE
New address point page on StratMap

### ISSUE THREAD

**Issue by ilyannakadich** [TNRIS/tnris.org#1542]
New pages added to StratMap Program Area. Pages for Parcels and Address Points initiatives. Pages will need t be added to main nav bar and to nav bar on StratMap Pages.

**Address Points**
- [ ] Embedded map @ilyannakadich @gmullins
- [ ] Status of Address points for Texas and creation of missing counties.
- [ ] Creation of building footprints.

**Comment by adambreznicky** [comment]
merged with issue #1543
