### ISSUE TITLE
Add Parcel/Address Points Pages on StratMap

### ISSUE THREAD

**Issue by ilyannakadich** [TNRIS/tnris.org#1543]
New pages added to StratMap Program Area. Pages for Parcels and Address Points initiatives. Pages will need t be added to main nav bar and to nav bar on StratMap Pages.

IDEAS!!

**Parcels**
- [ ] Embedded map @ilyannakadich @gmullins 
- [ ] Parcel Project research summary currently on GIO Page
- [ ] Hopes\Goals\Dreams
- [ ] OTLS v CAD Parcels

**Address Points**
- [ ] Embedded map @ilyannakadich @gmullins
- [ ] Status of Address points for Texas and creation of missing counties.
- [ ] Creation of building footprints.

**Comment by adambreznicky** [comment]
Please add a new tab on the StratMap page https://tnris.org/stratmap/ for Address Points Initiative

**Comment by adambreznicky** [comment]
i will create a new preview branch for @ilyannakadich and do this preliminary setup for her environment. ideas for content?

**Comment by adambreznicky** [comment]
@ilyannakadich 's new preview branch has been created, the preview page has been updated, and the CI has been configured. it is named:
# FRYE

**Comment by adambreznicky** [comment]
initial stratmap program pages and navigation for Parcels and Address Points. this should establish the shell/framework for future content and project status updates
commit 012cc46cbfbe56bba91314bd0783bad8ba5233f2

view here:
https://preview.tnris.org/frye/012cc46cbfbe56bba91314bd0783bad8ba5233f2/

**Comment by christoball** [comment]
Closing this issue. Please do not merge the two pages we've created for Address Points and Parcel Data.
