### ISSUE TITLE
Create sponsor graphics

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1546]
The GeoRodeo now has 3 sponsors:
The Texas GIS Forum
Esri
Here  (graphic to follow)

 Text - Thank you to our sponsors who make it possible to host the Texas GeoRodeo

**Comment by KCMack** [comment]
![HERE_Logo_2016_POS_sRGB (002).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599df692453cba2d8789d6c6/125516c66e82c728ace21e0d46c0b1a806bdafa688e68011f40ca6ab1969144c3a36840930cdb378ed0b394d4d1f0cf31b0d0c00eef39b2eafb13e758c555fb9d3380a73c63d11aeb1871bec03ef27995397f4edd4189fb5646fb2c99d452c1f0d1288fa5f31a69f42c85df749e64a47e9.png)
![HERE_Logo_2016_NEG_sRGB (002).PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599df692453cba2d8789d6c6/125516c66e82c728ace21e0d46c0b1a806bdafa688e68011f40ca6ab0763004c3a36840930cdb378ed0b394d4d1f0cf31b0d0c00eef39b2eafb13e758c555fb9d3380a73c63d11aeb1871bec03ef27995397f4edd4189fb5646fb2c99d452c1f0d1288fa5f31a69f42c85df24de24c47e9.PNG)

**Comment by mitchellryant** [comment]
merged #1549
