### ISSUE TITLE
Flood App ATS

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1551]
around the state on the flood app.
repackaged TWDB news release, announcing the Flood App v3.
Flood App v3 released 05-21-2018. release to follow about 1 week later.

**Comment by mitchellryant** [comment]
Updates to the Texas Water Development Board Flood Viewer Now Live
 
AUSTIN – (June 19, 2018) – The Texas Water Development Board (TWDB) recently released updates to the TWDB Flood Viewer. The latest features provide an intuitive way for users to visualize areas in the way of a potential flooding and remain informed via text messaging.
 
The Flood Viewer now supports forecasting elements that are collected from the National Weather Service gages. These gages have the capability to measure the flow of water and forecast flood stages. In addition, anyone who subscribes to those gages through the Flood Viewer can now receive notifications via text when a gage predicts a flood scenario. These updates will give users a quick understanding of what is to be expected in the coming hours or days based on the gage data.
 
The updated Flood Viewer also incorporates a “Latest Gage Activity” section that displays the latest Twitter feeds for all gages reporting flooding activity in chronological order. When you click on a tweet, a zoomed-in view of that gage will open in a new map.
 
For more information on what to do before, during, and after a flood, please visit TexasFlood.org.
 
The TWDB is the state agency charged with collecting and disseminating water-related data, assisting with regional planning, and preparing the state water plan for the development of the state’s water resources. The TWDB administers cost-effective financial assistance programs for the construction of water supply, wastewater treatment, flood control, and agricultural water conservation projects.

**Comment by mitchellryant** [comment]
FYI,
 
Here is the link from the TWDB press release about the flood viewer.  Please create the “around the state” article  with links to this article.  The article is different than my wording which is in the email below.  Feel free to use whichever article works for you or pick and choose from each article as needed.  I have also added a screen shot that illustrates the new feature of the viewer.
 
http://www.twdb.texas.gov/newsmedia/press_releases/2018/06/flood_viewer.asp
 
Thanks,
 
Richard

**Comment by mitchellryant** [comment]
#1577

**Comment by KCMack** [comment]
Try this addition referencing the TNRIS Development Team's work in the 3rd paragraph

Updates to the Texas Water Development Board Flood Viewer Now Live

AUSTIN – (June 19, 2018) – The Texas Water Development Board (TWDB) recently released updates to the TWDB Flood Viewer. The latest features provide an intuitive way for users to visualize areas in the way of a potential flooding and remain informed via text messaging.

The Flood Viewer now supports forecasting elements that are collected from the National Weather Service gages. These gages have the capability to measure the flow of water and forecast flood stages. In addition, anyone who subscribes to those gages through the Flood Viewer can now receive notifications via text when a gage predicts a flood scenario. These updates will give users a quick understanding of what is to be expected in the coming hours or days based on the gage data.

The TNRIS Development Team was tasked with examining the NWS stream gage data and writing new code to identify the gages with predictive ability.  Also, they wrote code to identify and show  the gages actively forecasting flood stages.  

The updated Flood Viewer also incorporates a “Latest Gage Activity” section that displays the latest Twitter feeds for all gages reporting flooding activity in chronological order. When you click on a tweet, a zoomed-in view of that gage will open in a new map.

For more information on what to do before, during, and after a flood, please visit TexasFlood.org.

The TWDB is the state agency charged with collecting and disseminating water-related data, assisting with regional planning, and preparing the state water plan for the development of the state’s water resources. The TWDB administers cost-effective financial assistance programs for the construction of water supply, wastewater treatment, flood control, and agricultural water conservation projects.

**Comment by christoball** [comment]
Previews

Front page:
https://preview.tnris.org/ellwood/d36a3ddc578754bb73a167ad73f44cd8936309c2/

Article:
https://preview.tnris.org/ellwood/d36a3ddc578754bb73a167ad73f44cd8936309c2/around-the-state/2018-06-27/updates-texas-water-development-board-flood-viewer-now-live/

**Comment by KCMack** [comment]
I like it.

Let it rip!

Kathleen

**Comment by christoball** [comment]
resolved in d36a3ddc578754bb73a167ad73f44cd8936309c2
