### ISSUE TITLE
Refresh StratMap Page

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1554]
- Update Numbers
~~- Update latest data releases~~
~~- Update latest initiatives~~

**Comment by gmullins** [comment]
Bullet 2 - Latest data releases should be:
https://www.tnris.org/news/2018-04-30/lidar-release-jefferson-liberty-counties/
https://www.tnris.org/news/2018-04-02/lidar-release-central-texas/
https://www.tnris.org/news/2017-11-13/lidar-data-release-east-texas-project/

**Comment by christoball** [comment]
data releases now updated in abee352192a31268c3283041a898d23c199105f2

**Comment by mitchellryant** [comment]
![images](https://user-images.githubusercontent.com/8459928/40683750-0cd99cbc-6355-11e8-88ff-e1c2fbad3069.jpg)

**Comment by ThorTheDestroyer** [comment]
Looks right to me based on the spreadsheet.

**Comment by gmullins** [comment]
Great. @christoball This is a go!

**Comment by christoball** [comment]
Closing this issue! Updated the numbers and think its all good.

resolved in 3f7f650847aee119eeb42cd286a92fa129e3f854
