### ISSUE TITLE
Training - Change Course Status

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1555]
Change the status of the following courses from OPEN to CLOSED
Editing with ArcGIS 10 - May 11
R For Data Science: Programming and Efficient Data Management - May 21
The spreadsheet has been updated to reflect these changes

**Comment by KCMack** [comment]
Please change the status from CLOSED to OPEN for the course R for Data Science.
A purchasing agent contacted me with 9 students to register.  We can hold the class.

The spreadsheet has been updated.

**Comment by christoball** [comment]
resolved in 6d631cd3480492a744699136ef7ff73d0d066c60

**Comment by KCMack** [comment]
Please CLOSE Advanced  Cartography on June 4th.
