### ISSUE TITLE
GeoRodeo Wrap-up

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1556]
Publish a wrap up and photo recap of the 2018 GeoRodeo

See the forum wrap up for an idea of format:
https://www.tnris.org/news/2017-11-06/texas-gis-forum-2017-photos-thanks/

Need an intro paragraph

**Comment by adambreznicky** [comment]
Wrap up text:

"""
Another Texas spring, another successful GeoRodeo!!!
The TNRIS Developer team would like to express our sincerest gratitude to all of this years' speakers and attendees. We strive each year to ensure this event is comfortable, joyous, and educational for everyone and we hope each participant felt the benefits of these efforts. Whether it was the detailed raster tiling processes demonstrated by Mark, the open data narrative told by Andrew, the comical serverless database education by Chris, or the inspirational tale of Cristy... we at TNRIS enjoyed all of our presenters and would like to say 'Thank You' again.
The TNRIS Developer team is working to acquire the presenter's slides and will post them to the GeoRodeo webpage as they arrive.
We are considering several changes to the event for the future in hopes of shakin' it up and providing a fresh, fun conference next year. Look out for information and updates and we hope to see you all again next spring!
Thanks again,
The TNRIS Developer Team
"""

Please feel free to edit as you feel necessary.
Thanks, Adam

**Comment by adambreznicky** [comment]
does anyone have a decent video of the GISCAT? should it go on the site alongside the recap photos?
it doesn't have to... just an idea. i'm personally indifferent.

**Comment by christoball** [comment]
@adambreznicky i tried downloading it out of google drive and had some troubles. ill try again.

**Comment by adambreznicky** [comment]
Cristy Burch's presentation  slides link:
https://drive.google.com/file/d/1jtt46tuHmdR1N2eyCZwpphJx1mGr92vz/view?usp=sharing

**Comment by christoball** [comment]
Preview of post:
https://preview.tnris.org/ellwood/9ed6ca7f4a5be189680fef76892f686dfcb163d3/news/2018-05-14/georodeo-2018-wrapup-and-photos/

**Comment by christoball** [comment]
resolved in 5f64dec12d46f522dae67d243775a491cd66d69a
