### ISSUE TITLE
Update DCS GIS SG Meeting Notes for Feb, March, May 2018

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1559]
GIS SG notes ready for review and posting.

**Comment by christoball** [comment]
Where are these located in the branch? I can't find them.

**Comment by geochik** [comment]
I'm going to need help with this. I have them on Sublime. I thought I committed the notes but I can't find them either.

**Comment by geochik** [comment]
@christoball - The address below is the commit. It contains 3 changed files.

https://github.com/TNRIS/tnris.org/commit/b5c790c2ef50a494bf623ea1fedd32e0151709ac

**Comment by geochik** [comment]
@christoball When can the notes be pushed to the site?
