### ISSUE TITLE
Census News Article

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#156]
The attached article is ready for publishing to the News section of TNRIS.ORG. Please feel free to make design changes. Please also include Dr. Lila Valencia, Texas Demographer's Office as Editor (Edited by...) if possible.
[Census_Article_Final.docx](https://github.com/TNRIS/tnris.org/files/4154714/Census_Article_Final.docx)
Census _web page badges_ can be found at the following links:
https://2020census.gov/content/dam/2020census/materials/partners/2019-03/Census%20Partnership%20Web%20Badges_1A_v1.8_12.10.2018.jpg
https://2020census.gov/content/dam/2020census/materials/partners/2019-03/Census%20Partnership%20Web%20Badges_2A_v1.8_12.10.2018.jpg
https://2020census.gov/content/dam/2020census/materials/partners/2019-03/Census%20Partnership%20Web%20Badges_3A_v1.8_12.10.2018.jpg
https://2020census.gov/content/dam/2020census/materials/partners/2019-03/Census%20Partnership%20Web%20Badges_4A_v1.8_12.10.2018.jpg 

Thank you!

**Comment by christoball** [comment]
@geochik I have some questions about the article and some suggestions/edits. Can we go over when you're back in the office?

**Comment by geochik** [comment]
@christoball  Yes, but feel free to edit the document and send to me for review in advance if you like.

**Comment by christoball** [comment]
@geochik that makes sense, You can see what I did in the link below.

The main major change I suggest is some reordering. With news articles, the start should generally deal with the most recent issues. I moved the paragraph about TNRIS's history supporting the census further in, and start off with the main point of the article, which is supporting this year's efforts

http://glidden.tnris.org/news/2020-02-06/tnris-supports-efforts-make-texas-count/

**Comment by geochik** [comment]
[Census Article w:Edits.docx](https://github.com/TNRIS/tnris.org/files/4181468/Census.Article.w.Edits.docx)
@christoball changes have been made. All grammatical with a couple of new words, all the way to the end. Thanks!

**Comment by christoball** [comment]
@geochik I've finalized the text with latest edits. It's ready to go when you give the green light.

http://glidden.tnris.org/news/2020-02-06/tnris-supports-efforts-make-texas-count/

**Comment by geochik** [comment]
@christoball Okay! This version has now been officially vetted by TWDB communications.  Please replace the current article with this text. Once complete, I'll review one last time!
[Census.Article.w.TWDBEdits.docx](https://github.com/TNRIS/tnris.org/files/4195516/Census.Article.w.TWDBEdits.docx)

**Comment by geochik** [comment]
@christoball  We are good to launch!
