### ISSUE TITLE
new dataset: USGS 2016 Neches Basin

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1567]
**Data**
- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer
- [x] Data Processing [renaming file, data organization] @ThorTheDestroyer
- [x] Creation of derivative products @ThorTheDestroyer
- [x] Quality Assurance @ThorTheDestroyer

**Publication**
- [x] Move to Content Creation @ThorTheDestroyer 
- [x] Coverage Map @mitchellryant
- [x] Data Publication [data catalog text\images, breakline\reports staging] @ThorTheDestroyer
- [x] Data Story @ThorTheDestroyer @christoball 
- [x] Final Publication @christoball @ThorTheDestroyer 
- [x] Move data to production shares @mitchellryant
- [ ] Inform TNRIS staff of data availability @ThorTheDestroyer 

**Download**
- [ ] Add to Data Download  @mitchellryant https://github.com/TNRIS/data-download/issues/91

**Comment by mitchellryant** [comment]
@ThorTheDestroyer what is the resolution?

**Comment by ThorTheDestroyer** [comment]
70 cm

**Comment by ThorTheDestroyer** [comment]
it should be, but i'll try to find something that confirms it.

**Comment by ThorTheDestroyer** [comment]
some of the dems are busted, I'll try re downloading to double check them.

**Comment by ThorTheDestroyer** [comment]
Thanks!

**Comment by mitchellryant** [comment]
dem for B2 an B4 finished downloading overnight.

**Comment by mitchellryant** [comment]
based on past experience, we should check to make sure data lines up with existing US National Grid index.

**Comment by mitchellryant** [comment]
based on past experience, we should check to make sure data lines up with existing US National Grid index.

**Comment by ThorTheDestroyer** [comment]
dem catalog completed, currently 107 missing or corrupted dem tiles.

**Comment by ThorTheDestroyer** [comment]
DEM download request for validation: 15RUQ3904275  its in sector B2

**Comment by ThorTheDestroyer** [comment]
here is the list. 
[missing-dems-by-sector.txt](https://github.com/TNRIS/tnris.org/files/2059191/missing-dems-by-sector.txt)

**Comment by mitchellryant** [comment]
LiDAR\USGS_LPC_TX_Neches_B1-B5_2016_IMG_2018

**Comment by mitchellryant** [comment]
carto id - 6f19d035-4c89-4f86-b758-ab25745081eb

**Comment by ThorTheDestroyer** [comment]
Data is ready to be copied to active lidar share. 

R:\LiDAR\USGS_LPC_TX_Neches_B5_2016_LAS_2018\laz
R:\LiDAR\USGS_LPC_TX_Neches_B5_2016_LAS_2018\dem
R:\LiDAR\USGS_LPC_TX_Neches_B4_2016_LAS_2018\dem
R:\LiDAR\USGS_LPC_TX_Neches_B4_2016_LAS_2018\laz
R:\LiDAR\USGS_LPC_TX_Neches_B3_2016_LAS_2018\laz
R:\LiDAR\USGS_LPC_TX_Neches_B3_2016_LAS_2018\dem
R:\LiDAR\USGS_LPC_TX_Neches_B2_2016_LAS_2018\dem
R:\LiDAR\USGS_LPC_TX_Neches_B2_2016_LAS_2018\laz
R:\LiDAR\USGS_LPC_TX_Neches_B1_2016_LAS_2018\dem
R:\LiDAR\USGS_LPC_TX_Neches_B1_2016_LAS_2018\laz
R:\LiDAR\Neches_staging\Contours\2ft\shp
R:\LiDAR\Neches_staging\Contours\5ft\shp

Copy this directory last to overwrite invalid dems from main directories. 
R:\LiDAR\USGS_LPC_TX_Neches_B1-B5_2016_IMG_2018\dem

**Comment by mitchellryant** [comment]
Neches Basin File Count @ThorTheDestroyer 
las - 12,163
laz - 16,796
dem - 16,817
2ft - 16,736
5ft - 16736

**Comment by ThorTheDestroyer** [comment]
LAS extent file in delivery confirms laz total of 16,796
other datasets need further investigation

**Comment by ThorTheDestroyer** [comment]
contours appear to cover entire project boundary.
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b69ffa9b23ef00118092ef/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51fa7c22d0b571bb4629040a584eac415a5641f8aa8b7ea1a42062c80d55b98e30063e937f03a6aa8318b500bf23884e87b1b98b4fc8e03c37aa.PNG)

**Comment by ThorTheDestroyer** [comment]
DEM total now at 16796

**Comment by mitchellryant** [comment]
https://tnris-twdb.carto.com/u/tnris/builder/6f19d035-4c89-4f86-b758-ab25745081eb/embed

**Comment by LaurenKirk** [comment]
@ThorTheDestroyer @mitchellryant @christoball 

Had a customer notify me this morning that the Supplemental Report and Lidar Breaklines links for the Neches River Basin lidar project are broken (see below):

![neches_lidar_error](https://user-images.githubusercontent.com/31768897/44797636-4875c080-ab75-11e8-9efa-e7e971f902f0.PNG)

**Comment by mitchellryant** [comment]
Data Publication [data catalog text\images, breakline\reports staging].
zip files are to be named correctly (same as .md).
copied to file server.
then file are sync to the water vapor in the sky for user to download.
if these do not happen, users can not get data.

all has been corrected. 

~sometimes i feel like janitor.
