### ISSUE TITLE
StratMap Hydro Page

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1568]
- Create StratMap Hydro Page (pick a branch) (Please add additional ideas )
- Workshop
- images
- will add to main stratmap nav bar.
- [ ] create  banner @christoball

**Comment by mitchellryant** [comment]
![login-468](https://user-images.githubusercontent.com/8459928/40683690-d9ed8ae8-6354-11e8-84d7-a2c7a224c759.png)

**Comment by ThorTheDestroyer** [comment]
I have not gotten a lot of info on this other than being asked at the end of a meeting about if i could do it.  I'm happy to put something together, but the purpose for this page's creation and what it should include has not been communicated to me by those deciding to have this page created.  If they below questions can be answered, I can have enough to start. 

 what is the purpose of this page? @geochik @gmullins 

Should we call ourselves the NHD State Steward even though that system is apparently going away? @gmullins  @geochik 

What other datasets are envisioned being highlighted by the page(all water related data)? @gmullins  @geochik

**Comment by geochik** [comment]
@ThorTheDestroyer The purpose of the NHD Steward page is to bring awareness to the data and for posting announcements such as the new Markup app and updates to the data itself. For Texas. If you have information about the "system" going away, this is something we will need to discuss. Your name is listed on the stewardship page for Texas, several times, and with that comes much responsibility. We can get together with Gayla to discuss page content or whether you would prefer a different way to communicate NHD upgrades and updates.
The concern that updates were not being distributed were brought forth by the USGS. The signed stewardship remains in effect until one or both parties agree to terminate.

![TXNHD.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599c64cafada7e0606ba7cba/125516c66e82c728ace21e0d46dcacb40ba6c1e5cdf9ad4cae58f3806b1c65267053f17e26dce72ced477e565f5f4eae485d5b17feac8e39baa47e21d40854b088270a36d43703adbf881eba03bd268e4c87b3bc8d45c6fa70.jpg)

**Comment by mitchellryant** [comment]
[30 of 90 complete.](https://youtu.be/8xSFi-Tn2_g)

**Comment by mitchellryant** [comment]
@ThorTheDestroyer @gmullins @geochik issue has been moved to backlog due to lack of everything.

**Comment by ThorTheDestroyer** [comment]
I'll post what I've created into github this week sometime.  Haven't had a chance to write it into a markdown due to a plethora of everything.

**Comment by ThorTheDestroyer** [comment]
here is the write up.

[NHDpage.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b69ffa9b23ef00118092ef/125516c66e82c728ace21e0d46c6bcbe338384accda5fd53b652fa912a5265296b51fa7c22d0b571bb4629040a584eac415a5641f8aa8b7ea1a42062c80d55b98e30063e937f03a6aa8318b500bf238c478cb1ba8849c2ef3f37aa.txt)

**Comment by mitchellryant** [comment]
## National Hydrography Dataset(NHD) and Watershed Boundary Dataset(WBD)
The [National Hydrography Dataset (NHD)]( https://www.usgs.gov/core-science-systems/ngp/national-hydrography) and [Watershed Boundary Dataset (WBD)]( https://www.usgs.gov/core-science-systems/ngp/national-hydrography/watershed-boundary-dataset?qt-science_support_page_related_con=4#qt-science_support_page_related_con) are digital geospatial datasets that map the surface water of the United States. The NHD represents the national drainage networks and related surface water features including rivers, streams, canals, lakes, ponds, glaciers, coastlines, dams, and stream gauges. The NHD has attributed these features and includes classification and other characteristics, delineation, geographic name, position and related measures, a "reach code" through which other information can be related to the NHD including the direction of water flow. This network of reach codes allows analysis to trace movement in upstream and downstream directions. The NHD can support many applications, such as making maps, geocoding observations, flow modeling, data maintenance, and stewardship.
The WBD represents drainage areas of the country in eight nested levels called hydrologic unit codes(HUCs).
Texas stretches across three HUC-2 regions encompassing the Arkansas-White-Red Region, Texas-Gulf Region and Rio Grande Region; furthermore, Texas contains over 6,450 HUC-12 Subwatershed. The NHD for Texas contains over 1.5 Million features. 

## Updates
[NHD Plus HR Beta]( https://www.usgs.gov/core-science-systems/ngp/national-hydrography/nhdplus-high-resolution) is the newest iteration of the NHD product being currently produced. NHDPlus HR is comprised of a nationally seamless network of stream reaches, elevation-based catchment areas, flow surfaces, and value-added attributes that enhance stream network navigation, analysis, and data display. 
 In Texas NHD Plus HR is currently available for all regions of Texas and beta QC is either in progress or completed. 
The NHDPlus HR is built using:

- The National Hydrography Dataset High Resolution data at 1:24,000 scale or better
- The 1/3 arc-second (10 meter ground spacing) 3D Elevation Program data
- The nationally complete Watershed Boundary Dataset
NHDPlus HR consists of vector and raster data layers. It includes a snapshot of the NHD and WBD at the time the NHDPlus HR was built, as well as the following components:
- A set of value added attributes, in addition to the standard NHD attributes, that enhance stream network navigation, analysis and display
- An elevation-based catchment area for each flowline in the stream network
- Catchment characteristics, including mean annual precipitation, mean annual temperature, and mean annual runoff, and mean latitude
- Cumulative drainage area characteristics
- Mean annual flow (1971-2000) and velocity estimates for each flowline in the stream network
- Flow direction, flow accumulation, elevation, and hydro-enforced elevation rasters
- Headwater node areas
- Flowline min/max elevations and slopes

## New USGS Markup Application for NHD public updates and edits.

The [Markup Application]( https://edits.nationalmap.gov/markup-app) is a web-based mapping tool allowing public users to submit edits, or markups, to the NHD, WBD, and NHDPlus HR. Users can log in with any gmail account to suggest corrections and improvements to the data using local knowledge. For more information and details on how to use the tool see the USGS new [Markup App Video]( https://www.youtube.com/watch?v=4hnvgPZxY5Q) for help using the tool.

**Comment by christoball** [comment]
I've put this content into a draft page. 

My main thought is the text doesn't clarify how the NHD is tied to TNRIS or StratMap

https://preview.tnris.org/haish/8a260dc9c5d693d9a6c5a20cb4a19d8984f8a188/stratmap/hydrography/

**Comment by ThorTheDestroyer** [comment]
Good point,  I'll add some additional information at the top citing role as the state steward and push it on Haish. I also am working on an additional graphic for the main banner image on that page.  I'll pass it along once it finishes up.

**Comment by christoball** [comment]
@thorthedestroyer how did you conceive of the updates section working? Will it be regulary updated?

**Comment by ThorTheDestroyer** [comment]
The USGS has established partnerships across the nation for maintaining and editing the datasets. The USGS believes that this is best accomplished by individuals or organizations with local knowledge of the hydrography and are motivated to ensure the accuracy of the data. TNRIS fulfills the role of principal steward of the NHD and WBD in addition to being the NHD technical point of contact for Texas.  For further information or questions regarding details about the NHD or WBD in Texas, please [Contact TNRIS]( https://tnris.org/contact/).

**Comment by ThorTheDestroyer** [comment]
Add the above section before the updates sections

**Comment by ThorTheDestroyer** [comment]
If regions get refreshed, new tools get developed, or more functionality/features are added, I would post them there.  We can rename it "Recent Developments" or "Ongoing Efforts"  or something else if that conveys a better message.

**Comment by ThorTheDestroyer** [comment]
![NHD_Main_Banner.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b69ffa9b23ef00118092ef/125516c66e82c728ace21e0d46c6bcbe1caf82a081d69d42aa53f5866b0a65633b0ba92e7391a172fd1722565d5a48a5150c5d11a9fe892ba6b435758e0f09b8d67f4366846c4ff8e7df46f554f832815d84b1b68b49c3e13c24e08e864c3b1d040ac4.jpg)

here is the main banner image.

**Comment by christoball** [comment]
Hydro page with banner image:
https://preview.tnris.org/haish/a066cfa264952d834e5b0833ae739deda76f35d7/stratmap/hydrography/

**Comment by mitchellryant** [comment]
@KCMack @pwblanton please review!

**Comment by ThorTheDestroyer** [comment]
I'm thinking it could use another in the body of the page. Thought?

**Comment by christoball** [comment]
was planning to add this under some of the other section:
![nhd_stuff.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599de1581827cf2b06d2e400/125516c66e82c728ace21e0d46e69c9e1c9197bc89effd0fe64de29b234324676b5ee17e29d2b17de91b7f055d0a1bab41585f46f5fc8d78a4e33b62964e49bc8f3900299f7744eeaa880dbe06b0218e4b86bfba8e4fc3e03c24ee99c2.jpg)

**Comment by pwblanton** [comment]
I reviewed the page(s) and gave my hand-written edits to Kathleen Mack for her review.

**Comment by ThorTheDestroyer** [comment]
After going back and looking at everything I think it looks good. I think that adding in the Region map above will work great, too. In case you want to add a slider and or a different banner, here are some more options. If you still don't like it, send me a pallet and I'll use that.

**Comment by ThorTheDestroyer** [comment]
![nhd_slider_1.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b69ffa9b23ef00118092ef/125516c66e82c728ace21e0d46e69c9e1c918fa08becad7cf51fbcd6395428792c07b7692ac7b671e8102e57560b1aae140d5844fcf98b22a3b26f72df5b19f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3b88d4dc5ef3427e58f89482c53.jpg)

**Comment by ThorTheDestroyer** [comment]
![nhd_slider_2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b69ffa9b23ef00118092ef/125516c66e82c728ace21e0d46e69c9e1c918fa08becad7cf61fbcd6395428792c07b7692ac7b671e8102e57560b1aae140d5844fcf98b22a3b26f72df5b19f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3b88d4dc5ef3426e58a8f4d2c53.jpg)

**Comment by ThorTheDestroyer** [comment]
![NHD_alternate_Banner.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b69ffa9b23ef00118092ef/125516c66e82c728ace21e0d46c6bcbe1c838fbd8afbb142b058cfb6284829763b46ef696097ec22ba416f43554d4ba5465a5a42f5addd29f3e33b708a5c09e4d4690c76933a03b0aac04ee155e57dd205d0f4ae805ec1ef3724e28f884e3b16051b8df85b36b2d4.jpg)

**Comment by christoball** [comment]
Made some additions/changes:
https://preview.tnris.org/haish/6554f1713d139efb8e7256b620fa1d59ca72e30a/stratmap/hydrography/

**Comment by mitchellryant** [comment]
@christoball @ThorTheDestroyer @gmullins 

Are we on check to publish by 01/31, as stated in the Jan 10 email.?
If not what is holding us back?

**Comment by gmullins** [comment]
I reviewed the page.
@christoball  Change analysis to analysts in "This network of reach codes allows analysis to trace movement in upstream and downstream directions."

Move NHDPlus graphic map to just under NHD text. Then WBD text, then WBD graphic map.

Use @ThorTheDestroyer 's NHD Markup tool image from above issue.

Take off gov shutdown Notice.

Change this "NHD Plus HR Beta is the newest iteration of the NHD product being currently produced." 
to this "NHD Plus HR Beta is the most recent iteration of the NHD product."

Change this "The nationally complete Watershed Boundary Dataset NHDPlus HR consists of vector and raster data layers."
to this "The complete nationwide Watershed Boundary Dataset NHDPlus HR consists of vector and raster data layers."

Thanks!

**Comment by gmullins** [comment]
@ThorTheDestroyer Sound good. So like this? Trying to avoid "being produced"
"NHD Plus HR Beta is the newest iteration of the NHD product currently in production for Texas."

**Comment by ThorTheDestroyer** [comment]
@gmullins 

how about 

@ThorTheDestroyer Sound good. So like this? Trying to avoid "being produced"
"NHD Plus HR Beta is the newest iteration of the NHD product currently available for Texas."

**Comment by gmullins** [comment]
@ThorTheDestroyer Sounds good!

**Comment by ThorTheDestroyer** [comment]
![NHD_example-2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b69ffa9b23ef00118092ef/125516c66e82c728ace21e0d46c6bcbe1c879ba882f9b346e90fb2d86b56357c2301a03f32dfa17de615295459561af8430d0a43fcf98929afb3382388090cffcd7f1d2598694ef1e1c84afd13b0328a468fb7b98e45c3e93b24e1838f4f3f0c48.jpg)

**Comment by ThorTheDestroyer** [comment]
![NHD2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b69ffa9b23ef00118092ef/125516c66e82c728ace21e0d46c6bcbe71c0cfeb9ffbb049a15ee4d67304722a7e56f67d2981e77aba472c515f5f4ca5445c0c46a9fe9b37b4f46d2ede0356b49b381d66cc2f10a5b2831abb08b9218d4983b1b98c4fd2a5.jpg)

**Comment by christoball** [comment]
@ThorTheDestroyer final draft here. If it looks good I'll go ahead and push:
https://preview.tnris.org/haish/4eb19448645c0ac5a4f3bbd2cde011b76a52a727/

**Comment by gmullins** [comment]
Looks good to me! @christoball Please arrange the StratMap tabs in this order: 
Main  StratMap Contracts  Orthoimagery  Elevation-Lidar  Hydrography  Land Parcels  Address Points

**Comment by christoball** [comment]
@gmullins I got the current order of tabs from @geochik 

Just want to make sure there is consensus on that.

**Comment by gmullins** [comment]
@christoball 
@geochik and I have consensus :) We'd like this order: Main StratMap Contracts Orthoimagery Elevation-Lidar Hydrography Land Parcels Address Points

Thx!

**Comment by christoball** [comment]
page pushed to production

 resolved in 3dd3121504e536bdd38ecbb203a0b34d49275260
