### ISSUE TITLE
Texas Imagery Service pricing update

### ISSUE THREAD

**Issue by gmullins** [TNRIS/tnris.org#1570]

**Comment by gmullins** [comment]
Please change pricing table to 
Regional Agency flat fee $15,000**
Local Agency flat fee $6,000**

The Data usage statements only apply to State Agency table.

**Comment by gmullins** [comment]
Change 
"Cost for the service is distributed across state, regional, and local government based on the amount of data usage. There are "tiers" within each level of government:"
to
"Cost for the service is distributed across state, regional, and local government. State agency cost is based on the amount of data usage in 'tiers'. Regional and local agencies have a flat rate."

**Comment by gmullins** [comment]
Possibly update Tx Imagery Service graphic on home page to announce new pricing structure.

**Comment by christoball** [comment]
resolved in 5673ce1d1e2a9a2ddf040f1d5cd8ff7800cb8e2e
