### ISSUE TITLE
June Training Courses Status Change and Date Change

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1571]
Change status from OPEN to CLOSED for the following:
6/4 Advanced Cartography
6/5 Telling Your Story with Story Maps
6/13 Data QC and CleanUp
6/14 Python Primer
6/15 Collector and Survey
6/20 Editing in ArcGIS Pro
8/15 Getting Started with ArcGIS Arcade
8/16 Web AppBuilder
Reschedule 6/1-2 Using Spatial Analyst in ArcGIS to 8/15-16
The spreadsheet has been updated

**Comment by christoball** [comment]
resolved in 7fa636ef9b49e5bc62abba840b3a32b26e8facfb
