### ISSUE TITLE
new dataset: CRWR Address Points

### ISSUE THREAD

**Issue by gmullins** [TNRIS/tnris.org#1572]
A new data card needs to be created for the CRWR Address Points. This is a soft release, so no Latest News article necessary.

**Comment by ilyannakadich** [comment]
State.  I’ll create a few different products and use naming recommendations below.

~ Ilyanna

**Comment by mitchellryant** [comment]
Questions?:

1. is this dataset being actively maintained (stratmap\crwr) or is a more of a one off?
2. is it only existing address points or does it also contain generated points for the counties without addressing?
3. is there metadata?
4. who is handling support of dataset? (stratmap\crwr)
5. did you envision in the data download\catalog or as some sort of one off download on the stratmap address page? 

i might have more questions!

**Comment by gmullins** [comment]
Rather than create data card now, the plan is to link the .shp off of new Address Points page when page goes live.

**Comment by ilyannakadich** [comment]
@mitchellryant , there is a newer version of the data here, so please replace including the xml metadata file.  R:\address\CWE_addpts_2017
