### ISSUE TITLE
Texas Flood application - Around the State Article

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1577]
First draft.
TWDB has released the third version of the Texas Flood Application, www.map-.texasflood.org which was developed by the TNRIS Development Team.  The new features provide an intuitive way for users to stay informed and visualize potential flooding events.

The new release benefits from the National Weather Service (NWS) gages that have future predictive abilities related to flood stage and water flow.  This enables subscribers to receive text or email updates when a gage is predicted to enter a flood scenario “action”.  Visual indicators, or halos, highlight those gages predicted to flood.  The gage halo color intensity will indicate the maximum stage/flow predicted by the NWS.  These predictive and visual abilities will provide a quick understanding about water flow expected during the coming hours or days for that specific gage.

Additionally, the “Latest Gage Activity” will display the latest twitter feeds for all gages reporting flooding activity.  Clicking on a tweet will feature a new map zoomed into that gage for inspection.  

We anticipate that this new version of the Texas Flood Application will be used to prepare for flooding events.

**Comment by mitchellryant** [comment]
#1551

**Comment by KCMack** [comment]
Cancel this item.  See #1551 amended

**Comment by christoball** [comment]
resolved in d36a3ddc578754bb73a167ad73f44cd8936309c2
