### ISSUE TITLE
Add Bill Johnson Keynote

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1579]
Add Bill Johnson to website, forum page

**Comment by KCMack** [comment]
[Bio for William F Johnson.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599df692453cba2d8789d6c6/125516c66e82c728ace21e0d46ca9d9563848cbbcfdeb64fa854f19969606759260cad387f8ba164fd52690e050a1de853524d41f5fe8b2ea0bf682488095eead16d5f76cf3815ffbad718ad1da862da11d1e9e1d30695aa2f2ff58a88453f1b06188bfe5835a49143c15fe406.docx)
[Carpe Geo and Parvus Momentum.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599df692453cba2d8789d6c6/125516c66e82c728ace21e0d46cb95883387c38e8ae6ff42aa59b0a4285431663a448e247d80ed3caa4f394d4d1f0cf31b0d0c00eef39b2eafb13e758c555fb9d3380a73c63d11aeb1871bec03ef27995397f4edd4189fb5646fb2c99d452c1f0d1288fa5e35a2984ec85efe4ee34947e9.docx)
![WFJ head shot 4-18.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599df692453cba2d8789d6c6/125516c66e82c728ace21e0d46dfb2b0638a86a88ba9ac4bab49b0c064177f316546b3397f8fe62bab0021435a5649ae445e5610a8fbdc7ea1b63c7088550ee9826f0a73d42103eee9dc4be05ce36ade0d97bcae8b44cae93826e7898e4a3f1e041b8cfc4f78.jpg)

**Comment by christoball** [comment]
preview article here: https://preview.tnris.org/ellwood/0ae6def5cc0ea409bcd7668018720fad0678cfa8/news/2018-07-25/forum-keynote-bill-johnson-carpe-geo-appgeo/

**Comment by KCMack** [comment]
All looks good, but I suggest that you capitalize Carpe Geo Evangelist in Bill's official title with Applied Geographics as his bio states.

After that minor change, please release it.

Thanks!
KCM

**Comment by christoball** [comment]
resolved in bbc7f4b3ef190f8da381e6a1a30dbb4334263a19
