### ISSUE TITLE
2020 Quarter 2 GIS Community Meeting Notes

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#158]
Finally received guest presentation slides today. Community notes are now ready for web publishing. Presentation slides are located here - https://twdb-my.sharepoint.com/:f:/g/personal/felicia_retiz_twdb_texas_gov/EnnhH0Xb14lLpV1dGdVp7zsBYx9OaSLjH4eHzjOnVkq94w?e=FAZ4jm
Notes:
[20200114_Quarter1_GISCommunityMtg_Notes.docx](https://github.com/TNRIS/tnris.org/files/4160759/20200114_Quarter1_GISCommunityMtg_Notes.docx)

**Comment by christoball** [comment]
@geochik be sure to tag me @christoball in the comment when you make the issue to make sure I see it.

**Comment by geochik** [comment]
Oh yes!! Will do. Thanks!

**Comment by christoball** [comment]
@geochik draft here, ready to go live when you say so:
http://ellwood.tnris.org/geographic_information_office_news/2020-02-12/gis-community-meeting-notes-slides-2020-1st-quarter/
