### ISSUE TITLE
Forum Call For Papers Page

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1582]
Add CFP page and paper submission form

**Comment by KCMack** [comment]
[Call for Presentations is Open 2018.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599df692453cba2d8789d6c6/125516c66e82c728ace21e0d46cb95962fc285a69da98f51a14ef59a3d47337a260ab06b7996a307af4775415d5f4fa453444d04bea6d37ef5f22e7a985902ead368597d926913f9ed851fbf01b8298e4bd6b4e98d5edcfa7f74b9dfd0126754505a9bf54f34a7934acd5bf74fe24e51a31b3365e7647b.docx)

**Comment by christoball** [comment]
Grow Seedling graphic.

**Comment by christoball** [comment]
Preview page:
https://preview.tnris.org/ellwood/c2fc76a842157ddcf155f8f249e7af42e355d658/texas-gis-forum/2018/call-for-papers/

**Comment by KCMack** [comment]
Pls change the banner date to reflect the 2018 Texas GIS Forum

**Comment by KCMack** [comment]
https://app.smartsheet.com/b/form/fa33c6c62c994cbbbde19fd1269a14dc 
Call for Papers link

**Comment by christoball** [comment]
resolved in 74061cd5632ed881838b05917245bcaaef26b3e1
