### ISSUE TITLE
Qtrly Meeting Location Update

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1583]
Please update the meeting location for the 3rd Quarter GIS Community Meeting on the GIO page.
Add the following address
Texas Parks and Wildlife Department Headquarters
4200 Smith School Rd
Austin, TX 78744

**Comment by geochik** [comment]
@christoball  Will you have time to work on this today?

**Comment by christoball** [comment]
resolved in f554306f6784e18b9cc39e2799ec0c0bd9a17c4a
