### ISSUE TITLE
Event Calendar

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1584]
I am looking for ideas for embedding an event calendar widget on the GIO Page. I see that Google Calendar can be customized to show just the events in a list. Are there other customizable calendars that can be easily managed and manipulated?

**Comment by mitchellryant** [comment]
https://www.eui.eu/ServicesAndAdmin/ComputingService/EMail/GuideCalendarInternetPublish

**Comment by christoball** [comment]
I'd suggest creating a GIO gmail and we embed a google calendar.

**Comment by mitchellryant** [comment]
i looked at adding publishing the existing office 365 calendar for the GIO, but is did not work. looks like google calendar is the best method.  

major concern is the events will be added to wrong google calendar, if you are not paying attention.

**Comment by mitchellryant** [comment]
that would have been the kind of helpful thing to know when the ticket was opened. or any details. why did we open a second issue for something for the GIO Page Refresh #1569
