### ISSUE TITLE
HGAC 2008 lidar catalog products corrections

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1585]
1m DEMs changed to 5ft DEMS(actual)

**Comment by mitchellryant** [comment]
@ThorTheDestroyer using github desktop update haish to be current with master.
make the change to the markdown file.
push back to github. if it builds properly.
add content creation tag to issues.
@christoball will merge into master.

**Comment by ThorTheDestroyer** [comment]
I did all that except content creation tag. Somehow it keeps reverting changes in Haish that I am removing manually. I push the deletion, and they keep coming back.  Any ideas? 

-Joey

**Comment by ThorTheDestroyer** [comment]
ahh so technically it is the same, all the updates that were there before were removed, but it still says that the branch is 7 edits ahead. 

![image](https://user-images.githubusercontent.com/8398036/42385803-70247348-8103-11e8-960a-e91f28d1c57b.png)

**Comment by ThorTheDestroyer** [comment]
Build successful
![Build.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b69ffa9b23ef00118092ef/125516c66e82c728ace21e0d46ca81932f86c1e5cdf9ad4cae58f3806b1c65267053f17e26dce72ced477e565f5f4eae485d5b17feac8e39baa47e21d40854b088270a36d43703adb0881eba02ba28834683b0b88d4cc7fa70.PNG)

**Comment by christoball** [comment]
pushed. resolved in 07632de965933b492f3526e3ce1a6b82e989f374
