### ISSUE TITLE
FORUM Sponsorship

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1587]
Description of sponsor levels and benefits

**Comment by KCMack** [comment]
[Sponsor Description_ 2018.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599df692453cba2d8789d6c6/125516c66e82c728ace21e0d46db84952d918cbbcfcdba50a74ff9843d4f287d1644f17b21dda164fd52690e050a1de853524d41f5fe8b2ea0bf682488095eead16d5f76cf3815ffbad718ad1da862da11d1e9e1d30695aa2f2ff58a88453f1b06198dfc5e36a39a42c151e406.docx)

**Comment by KCMack** [comment]
Reopen - didn't mean to close.

**Comment by KCMack** [comment]
Please add the sponsor page to the website:

[Sponsor Draft 2018.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599df692453cba2d8789d6c6/125516c66e82c728ace21e0d46db84952d918cbbcfcdad42a249b0c679177f316546b3397f8fe62bab0021435a5649ae445e5610a8fbdc7ea1b63c7088550ee9826f0a73d42103eee9dc4be05ce36ade0d97bcae8b4bcae93826e6838a463a16021f89fc4f78.docx)

**Comment by christoball** [comment]
Preview Page:
https://preview.tnris.org/ellwood/c2fc76a842157ddcf155f8f249e7af42e355d658/texas-gis-forum/2018/sponsors-and-exhibitors/

**Comment by KCMack** [comment]
Please change the banner to reflect 2018 Texas GIS Forum

**Comment by christoball** [comment]
Added the sponsor registration link: https://tnris.org/texas-gis-forum/2018/sponsors-and-exhibitors/

**Comment by KCMack** [comment]
Please replace the Rules with this version.

[Rules and Regulations 2018_7.24.18.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599df692453cba2d8789d6c6/125516c66e82c728ace21e0d46da81962691c3a881edff71a15ae59828522e7c2717e37920d4bb17e80c2955415e46be5d4a1f06a3a3dc78e2a436628f550cefd46b5620923f44f9bf821fbf03b3258f1c87e3bb9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecb5af24ce34a56a016366af43b.pdf)

**Comment by KCMack** [comment]
Note: replace the Rules and Regulations in both locations on sponsorship page.

**Comment by christoball** [comment]
resolved in bbc7f4b3ef190f8da381e6a1a30dbb4334263a19
