### ISSUE TITLE
GIS Qtrly Mtg - Slide

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1589]
1. Need new intro slide with updated meeting date: July 24, 2018

2. Change text to 3rd Quarter

**Comment by geochik** [comment]
![2018_gio_intro_slide.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599c64cafada7e0606ba7cba/125516c66e82c728ace21e0d46bac4cb7bbd84a080d6b64db04fffab3a4a2e772c46ef696097ec22ba416f43554d4ba5465a5a42f5addd29f3e33b708a5c09e4d4690c76933a03b0aac04ee155e57dd205d0f4ae805ec1e03724e2888e483817001e8ff7593db2d4.jpg)

**Comment by christoball** [comment]
emailing it to you now.
