### ISSUE TITLE
Forum Page Corrections

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1592]
Please correct the following:
1. Switch order of keynote speakers on front Forum Page. Brian Unger should be left, Bill Johnson right.

2. All registration links need to be changed to open in a new tab when clicked.

3. Sponsorship page - very last sentence needs a space between "the" and the sponsor rules link:
https://tnris.org/texas-gis-forum/2018/sponsors-and-exhibitors/ 
"After viewing theSponsor Rules and Regulations. visit the link to register as a sponsor."

**Comment by adambreznicky** [comment]
resolved via commit 6cea0721352e2eb039f945712c034a8a9edd609e
