### ISSUE TITLE
New photo of Brian Unger

### ISSUE THREAD

**Issue by rwade2126** [TNRIS/tnris.org#1593]
Chris, I have made a change to the Brian Unger photo that we are using on the website.  The original photo looked distorted.  Please swap out the photo with the photo located in: M:\Forum_GeoRodeo\2018 Forum\Keynotes\Brian Unger\Unger-Brian 2

**Comment by christoball** [comment]
resolved in 33dd5398761599548cd56cea617325d271e724d9
