### ISSUE TITLE
GIS Solutions Group - Meeting Notes

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1596]
Meeting notes for June and July GIS Solutions Group meetings. Please make update to GIS Solutions Group page located on GIO page.

Also, please update "Next Meeting" to August 14, 2:30 - 4:00 p.m.

**Comment by christoball** [comment]
Where are the notes?

**Comment by geochik** [comment]
Oh man! This happened last time. They are on Glidden. I guess I didn't push or something. I'll work on it after the staff meeting.

**Comment by geochik** [comment]
Glidden commit: 3cc7400a4cc3c384e7d26b9b111a04b874360661

**Comment by christoball** [comment]
resolved in d1cc090bf73c3b67d8de2546c0512b0038e72713
