### ISSUE TITLE
Forum Social Sponsorship

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1597]
- [x] Create Graphic for forum social sponsorhip
- [x] update platinum sponsor wording
- [x] Update site to show one tech demo has been taken

**Comment by christoball** [comment]
@KCMack @rwade2126 @geochik 
see a preview of the social sponsor promo here:
https://preview.tnris.org/ellwood/7fa45e8946c1b23260c2ecdcd23b4bd55ee39c2e/texas-gis-forum/2018/sponsors-and-exhibitors/

**Comment by geochik** [comment]
LOVE!!!

**Comment by KCMack** [comment]
Thought you might like it.

Want it to be a tad smaller relative to the other sponsor mentions?

kcm

**Comment by geochik** [comment]
Yes, good eye. At least the text.

**Comment by KCMack** [comment]
Richard likes it, too.

We’ll add it as a banner or at least separate a` la carte item.  Thinking about valuing it at $1,000.  Thoughts about cost?

Happy grandmother?  Getting any sleep at all?

kcm

**Comment by christoball** [comment]
Added the forum social to a la carte, preview here:

https://preview.tnris.org/ellwood/b768d1b842bc26ac7c0fb1783f55465f3c667f4f/texas-gis-forum/2018/sponsors-and-exhibitors/#co-sponsor-the-forum-social-1000

**Comment by KCMack** [comment]
IT looks terrific, Chris!

Kathleen

**Comment by christoball** [comment]
resolved in b768d1b842bc26ac7c0fb1783f55465f3c667f4f
