### ISSUE TITLE
Bell burnet lidar project supplemental report link

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1598]

**Comment by ThorTheDestroyer** [comment]
link is bad because file is missing.

**Comment by mitchellryant** [comment]
fixed

**Comment by ThorTheDestroyer** [comment]
dug through the HPIDs hole and found what i needed.  QAQC report on active drive looks to not be the final one also.   new supp report has been placed in the supplemental report directory.

**Comment by ThorTheDestroyer** [comment]
@mitchellryant  I just replaced the one you just put there with the one i made which includes some additional documentation on the project.

**Comment by ThorTheDestroyer** [comment]
will you also replace the qaqc report on the active lidar directory with these?
[usgs_TX_Bell-Burnet-McLennan_2011_QA_REPORT_FINAL.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b69ffa9b23ef00118092ef/125516c66e82c728ace21e0d46fd879d30bdb791b0cbba4fa810d2813b4822676429a007758bed29b17d29515e5e21cd30373d319c86eb4fc9c0450efb2019f1c32d1d2b9c6842e8aa880dba08bd228e498ce2e8881995ef3d25e789864a3a4d074d8eed4127e2c8159c07ab12ab1817b6192462e17c377944971b732a6b6121a9f4de44ca.pdf)
[stratmap11-50cm_bbm_qaqc-report.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b69ffa9b23ef00118092ef/125516c66e82c728ace21e0d46fb808822968ea89fb8ee0ef10df3991644257e1615a23a73c8f12daf4d69154d435cec03070511afbd9b21b4b3357788590de485395d21933a11acb88016ba05e922de4897aaaec81d9ebc6278bec1da0d2c14171980f55c30a39a4ece5ef64de64f52a2017b.pdf)
