### ISSUE TITLE
Forum sponsors missing

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#16]
@christoball Just noticed the lowest level of listed sponsors are missing here: https://tnris.org/texas-gis-forum/2019/
and
here: https://tnris.org/texas-gis-forum/2019/sponsors-and-exhibitors/

**Comment by christoball** [comment]
@gmullins thanks for catching this, I've fixed it and will go ahead and move it forward to prod.
http://frye.tnris.org/texas-gis-forum/2019/
