### ISSUE TITLE
StratMap Orthoimagery Flyer

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1602]
Create a informational piece for StratMap Orthoimagery.

**Comment by gmullins** [comment]
Content: [Uploading TNRIS StratMap Orthoimagery Flyer content.docx...]

**Comment by gmullins** [comment]
Will drag graphics here ASAP.

**Comment by gmullins** [comment]
![Building_Updates.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b691ca086d420011f174f3/125516c66e82c728ace21e0d46ca81932f868aa788d68a53a05ce4913a046b313916ac217586f76ae5002e58585d4baa480c0b46a9ac8e2ba6b63e798f5858ef846a4d68d47f40f2ecdd42e64bef62994597b7b4804dc5eb3e22e38288483e1d07119bb2.jpg)

**Comment by gmullins** [comment]
![crop_noseamline_TOP.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b691ca086d420011f174f3/125516c66e82c728ace21e0d46eb869533bd8da69cecbe4ea854fe91167208436b48e13b628ae92dbc56395b4d5a47ab435d594da8ad8b7ef3b13c708a5e02e8d53e5d21c12f0dbefad341eb5ee779c11ac7a4b6984dc8e23c20e488884b3716041088fc5927ed.jpg)
![crop_seamline_TXImageryService.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b691ca086d420011f174f3/125516c66e82c728ace21e0d46eb869533bd90ac8ee4b34aaa58cfa0116f2a722e01b1324380f13eb6417e43434d0eee1e020a17b8eb8339a3bf3b728f5a02b9856f0a21c13d11acba8b1abb52b8758c5d99a4fedb1294b7607caddecd5d340c071883fe5836a39e4fc150f743e04e5db65e.jpg)
![cropcircles_cir.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b691ca086d420011f174f3/125516c66e82c728ace21e0d46eb869533818abb8ce5ba509b5ef9866b0a65633b0ba92e7391a172fd1722565d5a48a5150c5d11a9fe892ba6b435758e0f09b8d67f4366846c4ff8e7df46f554f832815d84b1b68b49c3eb3a21ee838e473f1d060ac4.jpg)
![cropcircles_nc.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b691ca086d420011f174f3/125516c66e82c728ace21e0d46eb869533818abb8ce5ba509b53f3d665043761260ea62864c7b96aea1b2c535a5947f8155a0a11fbf9892ba4bf3974d95e5eeac3714d36976345f3e5db55ea43a82a994e82bcbd8f4fc3ef392cef8a874e3d1b1755.jpg)
![Drought_Change_Buchanan_1m_NAIP_2010May02_zoom.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b691ca086d420011f174f3/125516c66e82c728ace21e0d46cc869536858bbdb0cab742aa5af5ab0b53247b280aa2254fd4ee1791635231305d4ead41250e0dfcfbe661f9e96162964e4baf8e370a27822f1bbebd8b18bd04bc29df1b87e3e98d4cc0e83f2ce28fdc4d6b1917049bbd0c6bf4c6169112a309f34747a51b3c62e375357b439d1674246a6324b9b1.jpg)
![Drought_Change_Buchanan_1m_NAIP_2014Jul08_EDITED.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b691ca086d420011f174f3/125516c66e82c728ace21e0d46cc869536858bbdb0cab742aa5af5ab0b53247b280aa2254fd4ee1791635231305d4ead45221a18fcf1e65ed2cf5805fe4e17ff912f002e936e55beb2901ab606b8258d46d1e2bedf19c7e83d25e5828a4b6d1c501f9be34f77f1c71f9705af01b40f47ae01376bec77337f44931a7c246a6f27acffcd1b.jpg)
![leafoff_2010Feb16.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b691ca086d420011f174f3/125516c66e82c728ace21e0d46e4919b258d85afb0bbef12f47bf5967810653f6b14b1247a80e03cfd18395456584ca947510b10feacdc2ca6b63c7283590fbed3385866da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3e26e08f86473f16071980ed10.jpg)
![leafon_2011Nov09.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b691ca086d420011f174f3/125516c66e82c728ace21e0d46e4919b258d8d96ddb9ee128a52e6c470046b313916ac217586f76ae5002e58585d4baa480c0b46a9ac8e2ba6b63e798f5858ef846a4d68d47f40f2ecdd42e64bef62994597b7bb804dc5eb3e22e382874e361f0d1f9bb2.jpg)
![River_Channel_Update.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b691ca086d420011f174f3/125516c66e82c728ace21e0d46da9d8c2690bc8a87e8b14da151cfa1394226672c46ef696097ec22ba416f43554d4ba5465a5a42f5addd29f3e33b708a5c09e4d4690c76933a03b0aac04ee155e57dd205d0f4ae805ec1e03724e2888c483a170d1981fd5e35b2d4.jpg)
![TOP_Statewide.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b691ca086d420011f174f3/125516c66e82c728ace21e0d46dcbbaa1cb197a89beca84aa058b2d86b56357c2301a03f32dfa17de615295459561af8430d0a43fcf98929afb3382388090cffcd7f1d2598694ef1e1c84afd13b0328a478fb7b9894fc7ec342de6838e473e0c48.jpg)

**Comment by gmullins** [comment]
Other drought image.
![Drought_Change_Buch_1m_NAIP_2014Jul08.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b691ca086d420011f174f3/125516c66e82c728ace21e0d46cc869536858bbdb0cab742aa5af5ab0b53247b1655ae145ea4ca1880102b505b250bf041504d58eeb9cb74fce36f34985619e8d86a5d71c03445f8bad74ab801ba20894680b2ef8819c7fa2137a5dad11b61435c52dcbd4f3fb29842c259f348e24a50a4103267ee71376e0a.jpg)

**Comment by gmullins** [comment]
All are available here too plus a gallery of nice orthoimagery for general purpose in the Gallery folder: M:\SM\Imagery\Uses\Graphics_for_flyer

**Comment by gmullins** [comment]
Also, I'm going to keep searching for maybe a better seam vs no seam pair. Thx!

**Comment by christoball** [comment]
@gmullins how big is the drought_change_buch... file?

**Comment by gmullins** [comment]
I bet that's it. It's 8,882 KB. It is here: M:\SM\Imagery\Uses\Graphics_for_flyer

**Comment by christoball** [comment]
@gmullins 
- [ ] get 2016 lake buchanan
- [ ] supply quotes
- [ ] New Seam example
- [ ] Check Airport location

**Comment by gmullins** [comment]
Quote about other imagery options:
 "I appreciate the outreach and unfortunately Hemphill County UWCD cannot pay this high cost of aerial imagery."  - Hemphill County Underground Water Conservation District

**Comment by gmullins** [comment]
2016 Lake Buchanan out of drought. Image date August 3, 2016. Big glare on water. Not sure if worth messing with. What do you think?
![Drought_Change_Buch_1m_NAIP_2016Aug03.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b691ca086d420011f174f3/125516c66e82c728ace21e0d46cc869536858bbdb0cab742aa5af5ab0b53247b1655ae145ea4ca1880102b50592e0bfb415b4d58eeb9cb74fce36f34985619e8d86a5d71c03445f8bad74ab801ba20894680b2ef8819c7fa2137a5dad11b61435c52dcbd4f3fb29b48c259f348e24455ad113463e4743e6e0a.jpg)

**Comment by gmullins** [comment]
The other quote: 
"This imagery has been very helpful to us. We are currently using the 2015 orthoimagery provided by the Texas Orthoimagery Program to map the extent and distribution of aquatic habitats in Texas bays. The diversity of aquatic habitats (salt marsh, mangrove, intertidal oyster reef, seagrasses) found in Texas estuaries necessitates the use of 4-band imagery (R, G, B, and IR) for this mapping. This information is and will continue to be foundational for fisheries and landscape management of the Texas coast." - Zach Olsen, Texas Parks & Wildlife Department

I know, pretty long, we have his permission to cut if necessary.

**Comment by gmullins** [comment]
Better seam comparison graphics.
![TXGoogleImagery_WhartonGalv_11242014west_01232017east.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b691ca086d420011f174f3/125516c66e82c728ace21e0d46dcacbd2c8d84a58ac0b242a358e28d16712f723b10ac255784ef3e80132a535b5d4ead451f0a07b896892aa4b53e708b5b5ebc92294d68d47d53f3e2d74cfb13b0328e4682b4b98c4594bc3f70b28c8f4f3e1c0c1d8dac5f60a78b57da1aa715b51208fd596321f47c247d409e1f702f6f662faafddf578e8369b6f7.jpg)
Other Imagery Option

![TOP_WhartonGalv_02182015.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b691ca086d420011f174f3/125516c66e82c728ace21e0d46dcbbaa1cb58ba89dfdb04d835cfc82161675227156f37a25c7af6aaf50740b0a0c0abe4b4a5a4dfbfb8c2dafe26872df090cedd16d5d7dc33942aeed850da313f871d51bdaebe5c01982fa3737e68c854e3b1d011980fe5c36a39b4cc94abb.jpg)
StratMap Orthoimagery

**Comment by gmullins** [comment]
@christoball Checked off my items. Let me know when you want to touch base on this again. Thx!

**Comment by christoball** [comment]
@gmullins I'm free this afternoon to show where it's at and finalize.

**Comment by christoball** [comment]
Hey, I'm sorry, but I think a handful of these images need to be resampled in order for them to be good enough quality for printing.

Images that need to exported at 300 DPI
- [ ] The composite image of TX
- [ ] Palo Duro Canyon Image
- [ ] Coastal Image - For this can you let me know when you do it so i can take a look and see about maybe changing how much dark water vs. land is showing?
- [ ] Building Footprints Image
- [ ] Red River Image
- [ ] The Lake Buchanan series of images

**Comment by christoball** [comment]
Closing issue!
