### ISSUE TITLE
Infinite redirect loop possible with the /georodeo/ yearly redirect

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#1604]
If you visit the `/georodeo/XXXX` URL for a non-existent year, you'll get stuck in an infinite rewrite/redirect loop.

Demo: Visit `https://tnris.org/georodeo/2014/` -> your browser location bar will keep expanding with the pattern `http://tnris.org/georodeo/2018/2018/2018/2018/2018/ ... /2018/2018/2018/2018/2014`.

**Comment by adambreznicky** [comment]
@jseppi 
interesting. 
why are you trying to find georodeo pages for years when the event didn't exist?
we will eagerly await your pull request with the fix.

**Comment by adambreznicky** [comment]
@jseppi 
i find it quite telling that you only ever come to us with issues and never solutions. what kind of relationship are you fostering here buddy?
haha

**Comment by jseppi** [comment]
Haha 😆

It did exist that year (I believe 2013 was the first one)! I think that is when tnris.org was still on Drupal, hence no pages for those years in this repo.

I can't PR because the NGINX config is not in a public repo :(

GeoJohnson, who is in the 2015 promo video but was first mentioned in 2014, came up in the Mapbox Slack so I was doing some quick historical referencing, which led me to the redirect bug.

**Comment by adambreznicky** [comment]
what you thought was 'quick' at least.
joke is on you
