### ISSUE TITLE
Forum Pre-Conference Training and Registration

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1605]
Please update the website with the current 2018 training schedule and details.
Note: additional information will be added  as provided by the instructors.
Once training is on the website, please open the link to Registration

**Comment by christoball** [comment]
Workshop Main Page preview:
https://preview.tnris.org/ellwood/eb80bc99c99d1b0e9ce00ac18cc88b2643845733/texas-gis-forum/2018/workshops/

Main Forum Page preview now with registration:
https://preview.tnris.org/ellwood/eb80bc99c99d1b0e9ce00ac18cc88b2643845733/texas-gis-forum/2018/

**Comment by KCMack** [comment]
Both look great!  Let 'em rip!!

**Comment by christoball** [comment]
resolved in 58e1e01b938a7e2c4bc8ae74d8dfc2a38950c685
