### ISSUE TITLE
Change dates on Call for Papers page

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1606]
Please change the dates on the following:
Submission
The deadline for abstracts is August 6, 2018.
Should read: The new deadline for Abstracts is August 15, 2018

Acceptance
Applicants will be notified of abstract acceptance and will receive additional instructions by email no later than August 15, 2018.
Should read:
...by email no later than August 24, 2018

**Comment by KCMack** [comment]
And one more thing at the bottom of this page, please make this address a hyperlink;
For inquiries, please email kmcthompson@cmpmanagement.com or call

**Comment by christoball** [comment]
resolved in 58e1e01b938a7e2c4bc8ae74d8dfc2a38950c685
