### ISSUE TITLE
Prepare the Poster Contest Page

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1607]
Please replicate the 2017 page with date changes (made below):
Forum Poster Gallery & Contest
The purpose of the poster gallery is to promote and recognize the advances of map design, cartography, and GIS. The map gallery is open to all attendees and vendors. Attendees will have the opportunity to vote on each poster based on the following criteria:
Map design
Use of space
Subject matter
Communication
Creativity
Originality
Winners
The top 3 vote earners will be highlighted on the TNRIS website under the 'Latest News' section following the forum.

The top vote earner will also receive a small gift.

Physical Guidelines for Poster
Maximum size limit: 36” X 36”
Medium: Bond or Photo Paper
Submission Deadline: Friday, October 12, 2018
Posters may be picked up after 2:00pm on Thursday, October 25, 2018.

Posters will be displayed in the atrium of the J.J. Pickle Research Center.

Info and Mailing Address
Send us your basic information in the form on this page and mail your poster in order to arrive no later than the Oct. 12 deadline, to the following address:

Texas Natural Resources Information System
Attn: Erik O'Brian
1700 N. Congress, B-40
Austin, Texas, 78701

**Comment by christoball** [comment]
Preview poster page here:
https://preview.tnris.org/ellwood/1c5642af09648ba0baaa12068d1f9dbadcfb2439/texas-gis-forum/2018/poster-gallery/

**Comment by KCMack** [comment]
Looks great, Chris.  Let it rip!!

**Comment by christoball** [comment]
resolved in ae9b2689a1d42f55da65d512f76627b7ccf60848
