### ISSUE TITLE
Changes to the Forum Workshops

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1608]
1) The spreadsheet has been updated to include a description of R for Data Science

2) Teresa Howard's session has been cut.

**Comment by KCMack** [comment]
The course is actually Monday morning, R for Data Visualization.  The description has been added to the spreadsheet.

**Comment by christoball** [comment]
resolved in 75662aa623e5ba74799d81e08434f3ac7a5dc073

**Comment by KCMack** [comment]
Please update again.  Sara Safavi submitted a course description which has been added to the spreadsheet.
