### ISSUE TITLE
lidar status map embed link error

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1610]
lidar status map on stratmap elevation page is not returning the carto map.
For some reason there are two forward slashes instead of one before embed map. the link should read
 "https://tnris-twdb.carto.com/u/tnris-sm/builder/a5dfc759-9a90-4acd-a8d1-57d521c7e1fe/embed_map"

**Comment by christoball** [comment]
resolved in 6faee43f8010eb56672b9c91d3ab87115302142f
