### ISSUE TITLE
Crockett County Lidar release

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1611]
image and data story in work document can be found in Website\Updates\Crockett Lidar data release

**Comment by KCMack** [comment]
The project Area of Interest covers areas where previous Lidar acquisition did not meet the USGS Quality level 2 data specifications.
In the sentence above, capitalize the L in Lidar and add THE USGS Quality..."

**Comment by gmullins** [comment]
My suggestions:

New sentence: Data acquisition and processing were performed by The Sanborn Map Company https://www.sanborn.com/ 

The project area of interest covers a gap in Texas where no lidar data previously existed.

**Comment by christoball** [comment]
Article preview ready here: 
https://preview.tnris.org/haish/0273191bb658f3a04e98a4354f3c35208b380783/news/2018-08-24/2018-lidar-release-crockett-county/

**Comment by gmullins** [comment]
Found an "a" that needs to go away: 
....lidar data for a portions of Crockett ...

And the Lidar Status Map link points incorrectly to the Crockett dataset instead of statewide.

**Comment by KCMack** [comment]
Question for Gayla and Joey - is Lidar always capitalized?  It seems that we have been inconsistent.  Please advise.

**Comment by mitchellryant** [comment]
fixed lidar status map. wrong map id.

new preview:
https://preview.tnris.org/haish/72a7f24e63c3679740704152c626a1380449041e/news/2018-08-24/2018-lidar-release-crockett-county/

**Comment by mitchellryant** [comment]
If #1601 has 2 items about the data release {Data Story & Final Publication} is a separate issue needed or could we just use new dataset issue?

**Comment by christoball** [comment]
resolved in eb7a905809ecb6e1b4c3bc2d2b620a180a876988
