### ISSUE TITLE
Parcel Data page

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1613]
**Parcels**
- [ ] Content @ilyannakadich @gmullins
- [ ] Images @ilyannakadich @gmullins
- [ ] Embedded map @ilyannakadich @gmullins
- [ ] Parcel Project research summary currently on GIO Page
- [x] Contact button @jwhaney 
- [ ] Content Review @KCMack @pwblanton
~~- [ ] Contact Form~~
~~- [ ] Hopes\Goals\Dreams~~
~~- [ ] OTLS v CAD Parcels~~

**Comment by christoball** [comment]
@gmullins @ilyannakadich preview of placeholder page here:
https://preview.tnris.org/frye/9282a605c44d958fe1ccecbdb62c7c9eea999a12/stratmap/land-parcels/

**Comment by ilyannakadich** [comment]
![BeeParcels.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ad8b51668e3f40011a1dbde/125516c66e82c728ace21e0d46ca919f138391aa8ae5ac01e81fe086264c22703d46f96925dcb47aea1422050b5d1bf946585f44fef08c2ff5b46977984019af80330b2b9b645bf9fa9015ad03bb2a8a4a86b3b98f4cc3e03d26e18f9d02.PNG)

**Comment by ilyannakadich** [comment]
@christoball - how about this image for the land parcels page top image?  It is a variety of parcel sizes and land uses.

**Comment by gmullins** [comment]
@ilyannakadich I suggest making the lines yellow, orange or maybe white. Those usually pop better on top of imagery. Yes, nice variety!

**Comment by ilyannakadich** [comment]
![BeeParcels2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ad8b51668e3f40011a1dbde/125516c66e82c728ace21e0d46ca919f138391aa8ae5ac11e611b2843b492d762a10e17132d0ba7fed172d580b0b4cf9145f5f44fcfb802ea2e53e258d4e17ff933c0120996048e6edc00db513bb27814e80b5b98f49c1e8342dee888d5d73.PNG)

**Comment by gmullins** [comment]
@ilyannakadich Pretty!

**Comment by christoball** [comment]
This is cool!

Can you bring the area of the city over more towards the center?

@ilyannakadich and can you export it at a higher resolution, At 300dpi? That way I'll be able to use it any future print stuff as well.

**Comment by ilyannakadich** [comment]
I figured it out in Pro!

**Comment by ilyannakadich** [comment]
M:\Website\SM\Map

**Comment by christoball** [comment]
cool, check it out on the page here:
https://preview.tnris.org/frye/1030a34a36dba98eb02e840b1aa7cd1f52fcc0d5/stratmap/land-parcels/

Looks like maybe the line width could be backed down just a tad, otherwise its good.

**Comment by ilyannakadich** [comment]
Done.  You can try the Map2 version and let me know.

**Comment by christoball** [comment]
looks good:
https://preview.tnris.org/frye/88a1a2049bdb2c763abf3c7d97fab4015a1b0a2a/stratmap/land-parcels/

**Comment by gmullins** [comment]
@christoball  This page needs basic text information for now about the initiative. Let's leave off stats and maps for now. More information is coming as we work with a committee, etc.  Plus a contact form that goes direct to Ilyanna. 
@ilyannakadich Can you provide some basic wording?
And something like "Statewide parcel data is currently not available from TNRIS. We are in the early stages of planning this new monumental dataset. A general timeline of activities is......"
Thx!!

**Comment by ilyannakadich** [comment]
Basic wording below:

State agencies currently spend duplicative efforts to assemble, aggregate, and share geographic land parcel data.  TNRIS is the state clearinghouse for geographic data per section 16.021 of the Texas Water Code.  As such, TNRIS will coordinate the acquisition, aggregation, and sharing of geographic land parcels.  This initiative will save the state time and effort by providing one centralized source of annually updated geographic land parcel data.
Statewide geospatial land parcels are a vital reference tool for local, state, and federal agencies such as:
o	General Land Office (GLO) – Management of state lands; coastal land permitting; community development/revitalization; Veteran’s benefits issue management. 
o	Texas Division of Emergency Management (TDEM) - Mitigate emergency situations by accurately modeling and mapping areas to predict flooding along high-risk areas; planning and early evacuation procedure. 
o	Texas Department of Transportation (TXDOT) – Right of Way management for private or state-owned lands; transportation planning. 
o	Health and Human Services Commission (HHSC) – Determine structures in the path or vicinity of disease outbreak; analyze economic conditions for services. 
o	Texas Water Development Board (TWDB) – Determine if structures will be affected by flood conditions for early evacuation; determine properties that will be affected with the build of a new dam. 
o	Texas Animal Health Commission (TAHC) – Locate farms, ranches, feedlots, etc in the event of animal disease outbreak. 
o	Texas Commission on Environmental Quality (TCEQ) – Air permitting and air quality monitoring/analysis; determining water rights for landowners; water quality planning based on growth. 
o	Texas Parks and Wildlife Department (TPWD) – Land ownership notification; property transactions, planning, and management; emergency management and response. 
o	Commission on State Emergency Communications (CSEC) – Statewide emergency communications. 
o	Department of Public Safety (DPS) – Emergency management and response.
Year 1 goals (April 2018-2019)of this initiative include:
o	Evaluate cost/resources
o	GLO coastal county parcel refresh
o	Stakeholder meetings across the state
o	Project plan creation
o	Establish project committee
o	Marketing and communications plan
o	Project updates available online here
Please direct any project-specific questions in the form below:
<insert form that feeds into ticket system>

**Comment by christoball** [comment]
This content has been added, the contact form needs assistance from the developers to work properly.

https://preview.tnris.org/frye/bdb6fbab6bc11a38274640d5ca6cf7db80a80a3c/stratmap/land-parcels/

**Comment by mitchellryant** [comment]
why does this page need it own contact form?

**Comment by gmullins** [comment]
for people to get more info/ask questions about parcels. Tickets would go to ilyanna.

**Comment by mitchellryant** [comment]
i understand the purpose, but why do these 2 pages need contact form when the other 3 do not have have contact forms. how many different places on the site do contact forms need to be? We have a lot of trouble getting to correctly use the main contact form.

**Comment by gmullins** [comment]
bc these are two brand new datasets for us and therefore treated a little differently here in the beginning. I remember a contact form on the 2015 ortho project. i can see directly them to the main contact form "Please direct any project-specific questions here: https://www.tnris.org/contact/"

**Comment by mitchellryant** [comment]
for #1613 and #1614 it has been decided to add a  contact button that takes the user to the contact form.

**Comment by pwblanton** [comment]
Please replace the entire section with this.

General Land Office (GLO) – Management of state lands; coastal land permitting; community development/revitalization; veterans' benefits issue management.
Texas Division of Emergency Management (TDEM) - Mitigate emergency situations by accurately modeling and mapping areas to predict flooding along high-risk areas; planning and early evacuation procedure.
Texas Department of Transportation (TxDOT) – Right-of-way management for private or state-owned lands; transportation planning.
Health and Human Services Commission (HHSC) – Determine structures in the path or vicinity of disease outbreak; analyze economic conditions for services.
Texas Water Development Board (TWDB) – Determine if structures will be affected by flood conditions for early evacuation; determine properties that will be affected with the build of a new dam.
Texas Animal Health Commission (TAHC) – Locate farms, ranches, feedlots, etc. in the event of animal disease outbreak.
Texas Commission on Environmental Quality (TCEQ) – Air permitting and air quality monitoring/analysis; determining water rights for landowners; water quality planning based on growth.
Texas Parks and Wildlife Department (TPWD) – Land ownership notification; property transactions, planning, and management; emergency management and response.
Commission on State Emergency Communications (CSEC) – Statewide emergency communications.
Department of Public Safety (DPS) – Emergency management and response.
Year 1 goals (April 2018-2019) of this initiative include:

Evaluate cost/resources
GLO coastal county parcel refresh
Stakeholder meetings across the state
Project plan creation
Establish project committee
Marketing and communications plan
Project updates available online here

**Comment by mitchellryant** [comment]
waiting on @geochik and @KCMack edits. pages will not be published to site till @rwade2126 approves of content.

**Comment by geochik** [comment]
The page content document is now on version 5. It has been through enough reviews that it is now ready for a mockup. 
Chris, I know you will take the liberty to place the graphics as you see fit on the page. The agency logos and their needs are placeholders. 
Thank you all for your input!!
[Parcel Web Notes 2018_v5.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599c64cafada7e0606ba7cba/125516c66e82c728ace21e0d46d8958820878fe9b8ecbd038a52e4913a067523785c9c3d25c7af6aaf50740b0a0c0abe4b4a5a4dfbfb8c2dafe26872df090cedd16d5d7dc33942aeed850da313f871d51bdaebe5c01982fa3737e682854e3b1d0c1b81ff5836a69a43cb4abb.docx)

**Comment by christoball** [comment]
Parcel page now published!
https://tnris.org/stratmap/land-parcels/

resolved in 2f08d18b1734f738b8a5b81fb1ddbc1c2389b9f0
