### ISSUE TITLE
Stratmap Address Points Page

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1614]
**Address Points**
- [ ] Content @ilyannakadich @gmullins
- [ ] Images @ilyannakadich @gmullins
- [ ] Embedded map @ilyannakadich @gmullins
- [ ] Status of Address points for Texas and creation of missing counties.
- [x] Contact button @jwhaney 
- [ ] Content Review @KCMack @pwblanton 
~~- [ ] Contact Form~~
~~- [ ] Creation of building footprints.~~

**Comment by christoball** [comment]
@gmullins @ilyannakadich preview of address points placeholder page here: https://preview.tnris.org/frye/9282a605c44d958fe1ccecbdb62c7c9eea999a12/stratmap/address-points/

**Comment by gmullins** [comment]
@christoball  This page needs basic text information for now about the initiative. Let's leave off stats and maps for now. More information is coming as we work with a committee, etc. Plus a contact form that goes direct to Ilyanna.
@ilyannakadich Can you provide some basic wording?
And something like "Statewide address data is currently not available from TNRIS. We are in the early stages of planning this new monumental dataset. A general timeline of activities is......" And whatever else you want to say, of course.
Thx!!

**Comment by ilyannakadich** [comment]
@christoball there are a few image examples of address points at M:\Website\SM\addresspoints.docx

**Comment by ilyannakadich** [comment]
@christoball Basic wording below:

Geographic address points are a vital tool to conduct state business, such as emergency management, flood planning, permitting, and development.   A single source of statewide address point data currently does not exist.  The statewide address point aggregation initiative will save time for state agencies that currently acquire and aggregate this data to conduct state business.  Relationships throughout the state with local creators of address point data will allow TNRIS to aggregate and share this dataset publicly.  TNRIS is a reliable and unique state resource that provides high quality historic and current geospatial data products, education and training, which advances the GIS community through collaboration, expertise, cost-sharing initiatives and exceptional customer service.  

Year 1 goals (April 2018-2019)of this initiative include:
o	Evaluate cost/resources
o	Stakeholder meetings across the state
o	Project plan creation
o	Establish project committee
o	Marketing and communications plan
o	Project updates available online here
Please direct any project-specific questions in the form below:
<insert form that feeds into ticket system>

**Comment by christoball** [comment]
This content has been added. The contact form needs assistance from the developers to work properly.

https://preview.tnris.org/frye/bdb6fbab6bc11a38274640d5ca6cf7db80a80a3c/stratmap/address-points/

**Comment by mitchellryant** [comment]
why does this page need it own contact form?

**Comment by gmullins** [comment]
for people to get more info/ask questions about address points. Tickets would go to ilyanna.

**Comment by mitchellryant** [comment]
for #1613 and #1614 it has been decided to add a  contact button that takes the user to the contact form.

**Comment by pwblanton** [comment]
Geographic address points are a vital tool to conduct state business, such as emergency management, flood planning, permitting, and development. A single source of statewide address point data currently does not exist. The statewide address point aggregation initiative will save time for state agencies that currently acquire and aggregate this data to conduct business. Relationships throughout the state with local creators of address point data will allow TNRIS to aggregate and share this dataset publicly. TNRIS is a reliable and unique state resource that provides high quality historic and current geospatial data products, and education and training, which advances the GIS community through collaboration, expertise, cost-sharing initiatives, and exceptional customer service.

**Comment by pwblanton** [comment]
Ryan-- Oops... forgot to say replace the section with the above. Patricia

**Comment by mitchellryant** [comment]
waiting on @geochik and @KCMack edits. pages will not be published to site till @rwade2126 approves of content.

**Comment by gmullins** [comment]
@christoball Can you repost the preview link for our review? It seems to be broken.

**Comment by KCMack** [comment]
Please update the preview link

**Comment by christoball** [comment]
@ilyannakadich @KCMack @gmullins preview link available here: 
https://preview.tnris.org/frye/7c85b97dd95ce8347ca360e38158d7e61b8677d3/stratmap/address-points/

**Comment by christoball** [comment]
@gmullins for the link on the page to the address points download, can you provide a couple lines of info. Like 'This is a dataset of address points...etc.."

**Comment by gmullins** [comment]
How about: This address points dataset is the most recent *statewide* aggregation available to date. These data were compiled in 2017 by The University of Texas Center for Water and the Environment to assist the Texas Division of Emergency Management with flooding events. See full description of this dataset: https://ut-austin.maps.arcgis.com/apps/MapSeries/index.html?appid=557660a6c1ae40be8a2a084b0ad51a79

**Comment by christoball** [comment]
Added the download link to the preview:
https://preview.tnris.org/frye/a77ed637fe23da5646d01dc9025ba5efd6d1cbe1/stratmap/address-points/

**Comment by gmullins** [comment]
@christoball This page needs to be built out similarly to the Land Parcels page. @ilyannakadich can you provide current activity content and agency uses? They do not need to be as extensive as the parcels, if not available.

**Comment by gmullins** [comment]
@christoball We need to get back to this page. Please generate another preview.

**Comment by christoball** [comment]
@gmullins @ilyannakadich latest preview here: https://preview.tnris.org/frye/3608d429837c3995062a598064a98c330c92c23d/stratmap/address-points/

**Comment by ilyannakadich** [comment]
@christoball can you please make these updates?

Geographic address points are a vital tool to conduct state business, such as emergency management, flood planning, permitting, and development. A single source of statewide address point data currently does not exist. The statewide address point aggregation initiative will save time for state agencies that currently acquire this data to conduct business. Relationships throughout the state with local creators of address point data will allow TNRIS to collect and share this dataset publicly.

Download Dataset

This first statewide address point dataset was compiled in 2017 by The University of Texas Center for Water and the Environment to assist the Texas Division of Emergency Management with flooding events.  See full description of this project here: https://ut-austin.maps.arcgis.com/apps/MapSeries/index.html?appid=557660a6c1ae40be8a2a084b0ad51a79

Make the hyperlink to the word here above

Download Address Points (button)

Remove the Year 1 goals on right hand side and replace with same Goals and Objectives banner from Land Parcels site.  Replace “2017 Digital Parcel Data in Texas study” with “stakeholder meetings”

Add the same Agency Parcel uses graphics as Land Parcel site and replace “Land Parcel” with “Address Point”

**Comment by ilyannakadich** [comment]
@christoball Please find the FAQs here 
M:\Website\SM\Address Point Frequent Asked Questions.docx

**Comment by christoball** [comment]
@gmullins @ilyannakadich I'm incorporating all the edits and FAQ but this page is still lacking the Agency Uses. Need this asap if they're going to be ready by the Feb. 6 deadline.

**Comment by ilyannakadich** [comment]
@christoball Please use the same uses as parcels.  thanks

**Comment by christoball** [comment]
@gmullins @ilyannakadich Final draft of address points ready for review and push if looks good

https://preview.tnris.org/frye/ead5bd02866a75c0a7bc4f240d1f92b951847fb2/stratmap/address-points/

**Comment by ilyannakadich** [comment]
@christoball  Looks great!  Can you please remove this sentence in the intro since we have a link to the CWE data now.  " A single source of statewide address point data currently does not exist."

**Comment by christoball** [comment]
Page is pushed!

resolved in a54535fb3c0d86ad989f3ea50d0e6e8cde1e8e6a
