### ISSUE TITLE
GIS Forum Sponsors

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1615]
Current sponsors:
Platinum: Applied Geographics, Inc. and Surdex

Silver: South Central ArcUser Group  and Fugro

Exhibitor:  Tessellations, Inc.

A la carte: Wednesday Lunch  BIS Consulting, Inc

Updated logos have been requested.

**Comment by christoball** [comment]
resolved in e89c146ddb629095f39d66b801b0fe6bcea4248a

**Comment by mitchellryant** [comment]
reopened per @KCMack
