### ISSUE TITLE
old question on tx imagery service faq

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1619]
Just looking at some stuff on tx imagery service page and it seems like this item is outdated or not as relevant now. Or needs to be reworded

- How will maintenance and imagery update costs be covered in the future?
During the pilot year, which extends through March 2016, the GIS Solutions Group will review options for a fair and reasonable cost-recovery model using usage metrics and other factors. The more that play the less we all pay.

UPDATE - The Texas Imagery Service will be available without a fee through August 21, 2017.

-

**Comment by christoball** [comment]
link directly to question on faq: https://tnris.org/texas-imagery-service/#how-will-maintenance-and-imagery-update-costs-be-covered-in-the-future-

**Comment by gmullins** [comment]
I think we cover this in the How much does the service cost for my agency? question.
So let's delete the one you found altogether.

**Comment by christoball** [comment]
resolved in ca9a79bd52a7cf6e8bd5a0bd3a12a932b2a25443
