### ISSUE TITLE
Change workshop instructor photo

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1625]
Remove Mike Beaver's photo from the Monday Fundamentals of Census Geography and replace it with James Castaagneri

**Comment by KCMack** [comment]
![James Castagneri.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599df692453cba2d8789d6c6/125516c66e82c728ace21e0d46c295972691c38a8efaab42a353f58620046b313916ac217586f76ae5002e58585d4baa480c0b46a9ac8e2ba6b63e798f5858ef846a4d68d47f40f2ecdd42e64bef62994597b7bb804dc5eb3823e38f884d3e1b0c189bb2.jpg)

**Comment by christoball** [comment]
Where is the bio for Castagneri?

**Comment by christoball** [comment]
resolved in 13dabc8efdebf728c837fe7d8abddb7b76d1b4b9
