### ISSUE TITLE
Workshop updates - bio, photo, name

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1628]
Please update the workshop page:
Lidar workshop co-instructor Julie Parker has provided her bio and photo.

Chris LeSueur's name has been added to the Field Operations workshop
The spreadsheet has been updated

**Comment by KCMack** [comment]
![Julie Parker.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599df692453cba2d8789d6c6/125516c66e82c728ace21e0d46c281962a87c3998efbb446b61fbcd6395428792c07b7692ac7b671e8102e57560b1aae140d5844fcf98b22a3b26f72df5b19f1c32f0e2a92624cf5f2d75dad0ba821834584b3bf8f4bc2e13525e08f89492c53.jpg)

**Comment by christoball** [comment]
resolved in 4a47171c8be757ce253d863ad1ef9bde418c64df
