### ISSUE TITLE
third Platinum Sponsor

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1629]
Esri has registered for the 3rd and final Platinum Sponsor.  Please add their logo and update the description of options.
Also,  Surdex has agreed to be the Featured sponsor for the Social  Please indicate that option has been taken.

**Comment by christoball** [comment]
resolved in 34ab5dab4d76a04ada0cea2365fc6f3fd4b3d90c

**Comment by KCMack** [comment]
Please update the Platinum sponsor options.  Esri has taken the 2nd uncontested speaking slot.

**Comment by christoball** [comment]
speaking slot marked as claimed, resolved in e5a14a9e170525ee795f96d07b5e6dc6c0db588c
