### ISSUE TITLE
Surdex Color Logo

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1634]

**Comment by KCMack** [comment]
![Surdex Color Logo 300dpi 600dpi.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599df692453cba2d8789d6c6/125516c66e82c728ace21e0d46db818827879be9ace6b34cb61ddc9b2e4967207954a73b79c5b578ef466b084d435cec03070511afbd9b21b4b3357788590de485395d21933a11acb88016ba05e922de4897aaaec81d9ebc6278bec1da0d2c1417198ef55c30a39f4dc85cff4ae34a55a5017b.jpg)

**Comment by christoball** [comment]
resolved
