### ISSUE TITLE
Add Speaker to Forum Agenda

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1640]
1. Please add new speaker to the Wed., 10/24, 4-4:30 pm timeslot in Session B:
Jordan. (Word Doc uploaded)

2. Please apply new session name (same session listed above) to "DIY Projects"

**Comment by geochik** [comment]
[Texas GIS Forum_Carmona Abstract.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599c64cafada7e0606ba7cba/125516c66e82c728ace21e0d46dc91822291c38ea6daff65ab4fe59916652661240bad2a30a4e13bab507a021b4d52be011a001ea9aacd39aca439798d5e0eebd8390b76936816acb8821db604be73891a82a4a0980e91b6697abad2c51a7c0c0f0a88f75734a59a4dc05ff04ee94f56a116242e.docx)

**Comment by christoball** [comment]
resolved in e636244fc6d397bd2544e5d79aad7f6e117e9fde
