### ISSUE TITLE
hook up stratmap contact form

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1642]
We are adding a contact form to the new stratmap address points and land parcel pages.

It needs to be hooked up to the ticketing system, etc...

Latest preview here
https://preview.tnris.org/frye/bdb6fbab6bc11a38274640d5ca6cf7db80a80a3c/stratmap/land-parcels/

**Comment by mitchellryant** [comment]
for #1613 and #1614 it has been decided to add a  contact button that takes the user to the contact form.
