### ISSUE TITLE
reCAPTCHA error on Texas Imagery Service

### ISSUE THREAD

**Issue by gmullins** [TNRIS/tnris.org#1644]

**Comment by gmullins** [comment]
Error on form submission. Thx!!
![error.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b691ca086d420011f174f3/125516c66e82c728ace21e0d46ed86882c90c1e5cdf9ad4cae58f3806b1c65267053f17e26dce72ced477e565f5f4eae485d5b17feac8e39baa47e21d40854b088270a36d43703adb0881eba02bd228c4687b0bb8d48c9fa70.png)

**Comment by mitchellryant** [comment]
it happens on occasion, extremely hard to troubleshoot since the devs can not recreate the error. I will have someone look into it.

I work around is to have the user clear cache and local storage or submit the form in a private (incognito) tab.

**Comment by mitchellryant** [comment]
can we give this a once through (again)? maybe look at the parameters being loaded through angular.

**Comment by adambreznicky** [comment]
@gmullins what domain are you using?... specifically:
"tnris.org" or "www.tnris.org"?

**Comment by gmullins** [comment]
this one - 
https://www.tnris.org/google-request/
Also throwing same error to City of San Antonio guy.

**Comment by adambreznicky** [comment]
updated contact app to accept the www. subdomain. re-tested successfully.
