### ISSUE TITLE
Update Unger's photo and bio

### ISSUE THREAD

**Issue by pwblanton** [TNRIS/tnris.org#1649]
![unger-brian](https://user-images.githubusercontent.com/28151412/46476072-df551e80-c7ac-11e8-8939-0a57ba1cd76d.png)
[Unger-Brian.docx](https://github.com/TNRIS/tnris.org/files/2446415/Unger-Brian.docx)

**Comment by christoball** [comment]
resolved in 85ae66f6d05e26177458aa4d5186805b3bc68b0e
