### ISSUE TITLE
SCAUG Ad Graphic

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#165]
1st Draft by Monday

Ad for SCAUG Booklet

**Comment by christoball** [comment]
Here's what I'm thinking for this:
![datahub-savethedate-scaugpreview](https://user-images.githubusercontent.com/1877550/74884590-2491d600-5339-11ea-855c-ffb66d97bf3d.jpg)

**Comment by christoball** [comment]
@ilyannakadich @geochik Here's what I'm thinking for this:
![datahub-savethedate-scaugpreview](https://user-images.githubusercontent.com/1877550/74884629-3d01f080-5339-11ea-83d9-01ee79e91400.jpg)

**Comment by ilyannakadich** [comment]
@christoball  Looks great!

**Comment by geochik** [comment]
@christoball Graphics are great! I think it's a little overcrowded with text in the top right corner. Can we omit the word "Data" and move the TNRIS logo to the left? See image...
![image](https://user-images.githubusercontent.com/7750220/74944127-23a18880-53bb-11ea-91e5-b60f9e800838.png)

**Comment by christoball** [comment]
@geochik hows this look?
![datahub-savethedate-scaugh2020-2](https://user-images.githubusercontent.com/1877550/74975502-c0c8e500-53ec-11ea-9b60-6333a72e85c2.jpg)

**Comment by christoball** [comment]
Graphic finalized and sent to print
