### ISSUE TITLE
Updated abstract and Title

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1650]
Wednesday 2:30 session, Jack Daly.

New Title and Abstract

Title: Solar Suitability Study Leads to Virtual Power Plant Testing

Abstract: In 2016, the City of Georgetown undertook an effort to study the solar suitability of every rooftop within the City’s electric service territory. Using 2015 LiDAR data, the area, shading, aspect, and slope of each rooftop was assessed in ArcGIS Pro, allowing the City to provide the average solar potential to electric customers in an ArcGIS Online application. Uncovering this data enabled the electric department to apply for an innovation grant from Bloomberg Philanthropies to test a new concept – the virtual power plant. Georgetown is already using 100% renewable energy via wind and solar power contracts.  However, by 2021 the peak electric demand will outpace supply.  Current contracts have fixed prices for the next 20-25 years, but there are cost and reliability concerns due to long-distance transmission.  The virtual power plant involves installing batteries and solar panels on homes within the city.  Power would be produced locally on residential rooftops.  Ultimately, the vision is an electric grid that improves service, reduces the impact of outages, provides protection against emergency weather and national security events, and keeps costs steady.

**Comment by christoball** [comment]
resolved in 85ae66f6d05e26177458aa4d5186805b3bc68b0e
