### ISSUE TITLE
Bio for Wednesday session at 2:30

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1654]
Jack Daly began his career with the City of Georgetown in 2013 as an executive assistant to the assistant city manager.  In 2015, he was promoted to assistant to the city manager. His responsibilities include overseeing the city’s communication department, managing city council and citizen correspondence, special projects related to city council goals, managing internal citywide communication, and a wealth of “other duties as assigned”.  Jack was recognized as employee of the year for the City of Georgetown in 2015.

Jack is a graduate of the University of Texas and hold as master’s degree in public administration from the University of North Texas.  He is active with the Texas City Management Association and Urban Management Assistants of Central Texas.

Christopher Foster, MPA, CGFO
Having served as the Manager of Resource Planning and Integration for the City of Georgetown, a position he has held since 2008.  His primary role is to manage the City’s Municipally Owned Utility power supply.  Previous work includes managing payroll for the Health and Human Services Commission, repairing computer equipment for both CVS and Walgreens organizations, and running his own tech repair company.  
Chris is a graduate of Georgetown High School, holding a Bachelor’s degree in Economics/Finance from the University of Mary-Hardin Baylor, and a Master’s in Public Administration from Texas State.  Chris is also a Certified Government Finance Officer through the Government Finance Officer's Association.  Chris is best known for the successful transition project of Georgetown’s power supply from a single provider that was over 90% fossil fuel based, to being 100% wind and solar powered completed in 2017.  Outside of energy Chris acts as the City’s economist and lead contract negotiator including water rights, garbage contracts, technological systems, development agreements, and more.  
Chris is married with three kids.  His dissertation, “Does Proximity Matter?  Measuring the Effect Green Space Has On Residential Water Consumption”, can be found in the Texas State MPA ARP archives.

**Comment by jwhaney** [comment]
resolved via commit 7d91c1ff8a76d085ac435c333336864b9dcd91e1
