### ISSUE TITLE
Update bio -  Christopher Foster - Wednesday 2:30

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1655]
Christopher Foster, MPA, CGFO, City of Georgetown
Christopher Foster has served as the Manager of Resource Planning and Integration for the City of Georgetown since 2008. His primary role is to manage the City’s Municipally Owned Utility power supply. Previous work includes managing payroll for the Health and Human Services Commission and other jobs repairing computer equipment. Chris is a graduate of Georgetown High School, has earned a Bachelor’s degree in Economics/Finance from the University of Mary-Hardin Baylor, and a Master’s in Public Administration from Texas State. Chris is also a Certified Government Finance Officer through the Government Finance Officer's Association. Chris is best known for the successful transition project of Georgetown’s power supply from a single provider that was over 90% fossil fuel based, to being 100% wind and solar powered completed in 2017. Chris also serves as the City’s economist and lead contract negotiator for issues including water rights, garbage contracts, technological systems, development agreements, and more.

**Comment by jwhaney** [comment]
resolved via commit d5ef5455f994451dbed52c82ec17d6f9140f056b
