### ISSUE TITLE
Online Registration Ends Friday, October 12, 2018

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1656]
Please add to the front page and any place the Register Today button appears

**Comment by christoball** [comment]
resolved. online registration is off of the page.

**Comment by KCMack** [comment]
Please reattach the links.  Kirby sent an email to our contacts that she has extended the registration by one day.  This was news to us.  Sorry

**Comment by christoball** [comment]
resolved in bd2c890c6f9d6678eca54ca2615f517f6a11eba6
