### ISSUE TITLE
New TNRIS Promo card

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#166]
Rework TNRIS card handout 

DataHub
Forum Save the Date
Training

**Comment by christoball** [comment]
@gmullins @ilyannakadich @geochik Preview of both sides of card
![datahub-side-newcard-web-preview](https://user-images.githubusercontent.com/1877550/76018044-3d77bb00-5ee5-11ea-89a4-aaf9cfc78c0b.jpg)

*****

![split-side-newcard-web-preview](https://user-images.githubusercontent.com/1877550/76018048-3e105180-5ee5-11ea-984a-3ee7f5f4816c.jpg)

**Comment by ilyannakadich** [comment]
@christoball @gmullins @geochik Looks great!  Can we possibly remove the commas in Browse, Download, Order and remove the www?  Also, please send a layout on 11x17 with four front and back.  Thanks, Chris!

**Comment by christoball** [comment]
resolved
