### ISSUE TITLE
Add presenter Wednesday 4:40 - 5:00

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1660]
Co Author and Presenter 
Dr. Carlos Portillo-Quintero
Presentation Title: Assessing the extent and landscape structure of Sand Shinnery Oak Prairie in the Southern High Plains using GIS and remote sensing: challenges and future directions.
Purpose: Presenting the work on ecosystem mapping using GIS technologies carried out by the Department of Natural Resources Management at Texas Tech University. 

Session Abstract: 
We investigated historical trends of the extent and geographical distribution of sand shinnery oak prairies (SSOP) on the Southern High Plains in New Mexico and Texas by investigating historical geospatial datasets and semi-automated image classification of post-1975 Landsat imagery. Our objective was to create a baseline dataset on land cover change in the historical distribution of SSOP that facilitates future investigations into how vegetation heterogeneity could have shaped lesser prairie-chicken (Tympanuchus pallidicinctus) habitat and population demography in the SSOP. We analyzed historical maps and documentation prior to the 1930s and remotely sensed data (aerial photography and satellite imagery) collected from 1930 to 2015. Land cover and land use maps from 19th and 20th centuries were digitized into a Geographic Information System. The presence of sand shinnery oak (Quercus harvardii), sand sagebrush (Artemisia filifolia) and grasses was identified through photo interpretation of canopy shape and texture information in 120 aerial photomosaics from 1930-1970 that were acquired for 22 sites within the study region. Distribution of the SSOP was analyzed using satellite imagery (Landsat time series) from 1975 to 2015. For New Mexico, results show that sand shinnery oak, sand sagebrush and grass associations have been reduced from an approximate potential extent of ~1,800,000 ha by the late19th century (mostly Lea, Eddy, Chaves and Roosevelt counties) to ~900,000 ha in 1977 and then to ~600,000 by 2015, with decreasing dominance of sand shinnery oak in the last 40 years. In Texas, sand shinnery oak prairies have been reduced to less than 25% of its historical potential extent (from 2,000,000 ha to 430,000 ha). We discuss methodological challenges in the mapping process and propose GIS-based methodologies to detect emerging trends in ecosystem loss based on time series of Landsat imagery.

Presenter Biography: Biologist specialized in the application of GIS and remote sensing technologies for biodiversity conservation. Dr. Portillo earned his PhD in Earth & Atmospheric Sciences from the University of Alberta in Canada and postdoctoral work in environmental monitoring in the same institution. Currently, he is an Assistant Professor in the Department of Natural Resources Management at Texas Tech University. He is a member of the Global Land cover Program and the Commission for Ecosystem Management of the International Union for the Conservation of Nature (IUCN).

**Comment by christoball** [comment]
resolved in 0839102bebe033dfa69ee0629b1562c073948829
