### ISSUE TITLE
Add final speaker for the Wednesday session

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1661]
5:00 - 5:30
Presentation Title: 9-1-1 and GIS in the 21st Century – What You Should Know Now.
Purpose: Provide an overview on how GIS data and processes will be the core of US public safety functionality going forward.
Session Abstract: With the advent of NG9-1-1 call routing and location technologies being dependent on local GIS data provisioning, responsibility for timely and accurate spatial data will fall upon local governments. This session will look at how GIS data is typically being developed today vs. the QA / QC processes and local accountability that will be required of it in the future. State and Federal work in this area will be touched on as well as national data requirements. No extensive knowledge of Public Safety or GIS is required for this session.
Presenter Biography: Mr. Kelly has 20 years of public and private sector GIS experience ranging from Appraisal District and Council of Governments to acting as a Senior GIS Solutions Engineer for PlantCML/Cassidian Communications. He now serves as Vice President of Geospatial Solutions with 911 Datamaster and is involved with both NENA and APCO standards work groups as well as serves as NENA’s liaison to NSGIC.

**Comment by christoball** [comment]
@KCMack  There's no speaker name or organization on here

**Comment by KCMack** [comment]
Oops!  Richard Kelly, Vice President of Geospatial Solutions with 9-1-1 Datamaster.

**Comment by christoball** [comment]
resolved in 0839102bebe033dfa69ee0629b1562c073948829
