### ISSUE TITLE
Description of the Esri tech talk

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1665]
Title: Data Collection in the Field – Past, Present, and Future
Description: For centuries cartographers have been putting outdoor observations onto paper, and with GIS we moved to represent the real world as digital data objects. The real world is where the data resides, and at some point, we as humans need to interact with this real world to bring it into our GIS.  From paper and clipboards to GPS, smartphones, wireless internet; we will discuss how field data collection has changed, where we are now, and what’s coming next.
Presenter - Chris LeSueur
Chris LeSueur is a Product Manager with the Apps Team in Redlands, California. He is responsible for managing Esri's mobile software products for smartphones, tablets, and rugged field devices. Chris has been with Esri for 18yrs working in various positions in Technical Marketing and Product Management.  Before starting his career at Esri, Chris graduated from Brigham Young University with a degree in Geographic Information Systems.

**Comment by christoball** [comment]
resolved in  bd2c890c6f9d6678eca54ca2615f517f6a11eba6
