### ISSUE TITLE
Parcel Page edits

### ISSUE THREAD

**Issue by gmullins** [TNRIS/tnris.org#1668]
- [x] Insert data distribution map @ilyannakadich
- [x] Please remove 'Year One (FY2019) - '. Should just be Goals and Objectives @christoball 
- [x] Also, per FR please bullet the agency uses instead of ;'s. @christoball

**Comment by gmullins** [comment]
@christoball Please remove 'Year One (FY2019) - '. Should just be Goals and Objectives

Also, per FR please bullet the agency uses instead of ;'s.

**Comment by gmullins** [comment]
[ ] Insert timeline of progress @ilyannakadich 
[ ] Insert map @ilyannakadich

**Comment by mitchellryant** [comment]
@gmullins do you have a target completion date in mind?

**Comment by gmullins** [comment]
I put 2 weeks for the checkbox items. The others seem like 'quick' fixes. Thx!

**Comment by christoball** [comment]
I've removed the 'year one' and turned the agency uses into bulleted lists.

**Comment by ilyannakadich** [comment]
@christoball  can we add a hyperlink to the parcel study report in this existing paragraph?

https://tnris.org/static/documents/gio/texas-statewide-parcel-data-report.pdf

In 2017, a statewide study was conducted to identify the availability of land parcel boundaries in a geographic information system (GIS) or other digital format. The study revealed, of the 253 county appraisal districts in Texas, a total of 212 counties reported the existence of digital parcel boundaries in their programs. Additionally, the report discovered there is no requirement for land parcel boundary development and maintenance in a GIS or other digital format.

**Comment by mitchellryant** [comment]
here is the map

<iframe width="100%" height="520" frameborder="0" src="https://tnris-twdb.carto.com/u/tnris/builder/ba0229b0-b91c-4775-98ae-93844e146496/embed" allowfullscreen webkitallowfullscreen mozallowfullscreen oallowfullscreen msallowfullscreen></iframe>

**Comment by gmullins** [comment]
Looks good! What happened to the legend?

**Comment by gmullins** [comment]
Looks ready to add to Parcels page. @ilyannakadich Do you agree?

**Comment by ilyannakadich** [comment]
YES!

**Comment by ilyannakadich** [comment]
I would like the map below the Goals and Objectives section. @christoball

**Comment by mitchellryant** [comment]
@christoball can al the edits be made, Reviewed, and published by 02/06?

**Comment by christoball** [comment]
@mitchellryant yes, that works great.

**Comment by christoball** [comment]
@mitchellryant can you make the default zoom view of the map 2 levels out?

**Comment by christoball** [comment]
Status map added here:
https://preview.tnris.org/frye/63ccfb311e218711c51984d8721f2da77efdfb6a/stratmap/land-parcels/

**Comment by mitchellryant** [comment]
zoom level of map set to 5

**Comment by christoball** [comment]
Is there a setting to turn off the title bar on the map embed?
[Uploading parcelmap.jpg...]

**Comment by mitchellryant** [comment]
no.

**Comment by christoball** [comment]
- [ ] Insert timeline of progress @ilyannakadich 
- [ ] Insert status map @ilyannakadich
Thanks!

**Comment by mitchellryant** [comment]
@gmullins moved the 2 additional items because she and @ilyannakadich still needed to work on them and we wanted the download map to be published. if all the work can be added and still meet the 02/06 publication date, then great.

also the map added is the download map. @gmullins and @ilyannakadich want to add a second map that shows levels of progress for the 253 CAD of Texas. I voiced my concerns that 2 maps would be confusing to the users, but that is what they want.

**Comment by ilyannakadich** [comment]
@christoball Please remove the percentage at 94 and remove the s on districts in "of the 253 appraisal districts datasets are available for download."  Also can you change the color of the bar to match the orange in the map?

We are working on finalizing the FAQs that will be added to the page before publishing.

**Comment by ilyannakadich** [comment]
@christoball Please find the FAQs here
M:\Website\SM\Parcel Frequently Asked Questions.docx

**Comment by christoball** [comment]
@gmullins are these FAQs supposed to be displayed on the page or as a file?

**Comment by christoball** [comment]
@gmullins @ilyannakadich I've gone ahead and mocked it up to the FAQs into the page alongside the Agency uses. I think this makes both more visually interesting and digestible

https://preview.tnris.org/frye/8e18b126c4b0ae2f18bfb8a2dd1bb2b0ad18c79d/stratmap/land-parcels/

**Comment by ilyannakadich** [comment]
@christoball  Placement is great!  Can you  please confirm that my hyperlinks work within the FAQs?  Thanks.

**Comment by gmullins** [comment]
@christoball These are the address point FAQs. Needs to be the parcel FAQs. Thx!

**Comment by christoball** [comment]
@gmullins  @ilyannakadich Final draft of Parcel Page edits. If it looks good, then we can push.

https://preview.tnris.org/frye/ead5bd02866a75c0a7bc4f240d1f92b951847fb2/stratmap/land-parcels/

**Comment by ilyannakadich** [comment]
@christoball  Looks great!
