### ISSUE TITLE
2018 forum recap

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1669]
Please review the preview of the forum recap.
https://preview.tnris.org/ellwood/18d6b1fb0f29c6722d935bb91699f8e0f9ae1827/news/2018-10-30/texas-gis-forum-2018-photo-recap/

I haven't changed the main image yet and I'm still working on the captions, but wanted to give y'all a chance to start looking at the text:

This was another great year. We enjoyed the poignant yet hilarious insights of Brian Unger, were inspired by the 'Carpe Geo' philosophy of Bill Johnson, ate amazing food at the Forum Social, and heard from other awesome people in our community doing the GIS work that keeps our state going strong.

We hope you enjoyed it as much as we did! We are sharing our photos from the conference, and will also be sharing the available slideshows from this year's presenters soon on the agenda page.

Don't forget to check out the 2018 Poster Contest Winners as well. Their maps illustrate serious (and not so serious) GIS analysis with innovative and engaging cartographic work.

Please save the date for October 21-25, 2019, when we'll return to the Commons Center for the 32nd Annual Texas GIS Forum. In the meantime, please send us any comments or ideas for what you would like to see at next year's event. We are always looking for ways to improve and make sure that, first and foremost, the Forum serves you, our Texas GIS community.

**Comment by KCMack** [comment]
Try this version:

This was another great year. We enjoyed the poignant yet hilarious insights of Brian Unger, were inspired by the 'Carpe Geo' philosophy of Bill Johnson, ate amazing food at the Forum Social, and heard from other GIS professionals in our community about their projects that have made a positive difference in the lives of Texans.

We hope you enjoyed it as much as we did! We are sharing our photos from the conference, and will also be sharing the available slideshows from this year's presenters soon on the agenda page.

Don't forget to check out the 2018 Poster Contest Winners as well. Their maps illustrate serious (and not so serious) GIS analysis with innovative and engaging cartographic work.

BOLD this first sentence:  **Save the date for October 21-25, 2019**, when we'll return to the Commons Center for the 32nd Annual Texas GIS Forum. In the meantime, please send us any comments or ideas that will make next year's event even better. We are always looking for ways to improve and ensure that the Forum serves you, theTexas GIS community.

Eliminate: Texas Team

Photos:
Check on the captions for the photos.
Eliminate Felicia at the Social
Second photo of Bill John is a tad over exposed, can it be fixed?
The last photo  - can you color correct?
Under heading of Day Three - Felicia's photo in yellow dress is from Day Two
For all days, please add good photos so the grid is complete to eliminate gaps

**Comment by KCMack** [comment]
Also, is it possible to make the social photos lighter?  Many of them are very dark making it impossible to see the people in action.

**Comment by christoball** [comment]
Final Draft:
https://preview.tnris.org/ellwood/31711dda3570df4f81e67bd81572f5bf9dd7836b/news/2018-11-09/texas-gis-forum-2018-photo-recap/

**Comment by KCMack** [comment]
Once you fixed the word spacing... you, the Texas GIS Community.  It's good to go

**Comment by christoball** [comment]
resolved in 6d3caa4857af7d54e6d1c659c22fd96242b76310
