### ISSUE TITLE
Updated RDC Pricing and Turn Around Time (March 2)

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/tnris.org#167]
@christoball @mitchellryant  @csidenblad 

Hey Chris, effective March 2nd the public pricing listed in the "Historic Imagery Pricing" section on TNRIS.org will update.  Can you please add the following updates?  Format can look exactly the same as it is currently.

Research:
$60/ Full Historical Search (multiple years or sites)
$30/Single Year Search (one site and one year)
$15/Frame Search (customer must be able to identify specific frames needed)

Imagery:
$10/frame
$20/georeferenced frame (all frames will be georeferenced to WGS 1984)

Delivery Options:
$7 digital download delivery (0-10gb)

Bulk Collection Delivery Option

Customers have the option of ordering any collection that has already **been scanned in full** for the data size price (see Data Reproduction Costs), rather than paying by frame. 

Delivery Policy:

TNRIS requests 3-10 business days for data requests and product turn around.  We do not accommodate any expedited orders.

**Comment by csidenblad** [comment]
@christoball @LaurenKirk @adambreznicky There were some questions regarding the formatting so lauren and I have provided a screenshot of the formatting we would like. Please let me know if you have any questions. 

![image](https://user-images.githubusercontent.com/23489372/75783926-fb087f80-5d26-11ea-9308-162a614d7c8b.png)

**Comment by christoball** [comment]
@LaurenKirk @csidenblad Ok, i think i matched this and I also rearranged some stuff to improve the layout:
http://washburn.tnris.org/research-distribution-center/historical-imagery-archive/

**Comment by christoball** [comment]
@LaurenKirk @csidenblad latest version with requested edits. Ready to push when you say so:
http://washburn.tnris.org/research-distribution-center/historical-imagery-archive/

**Comment by LaurenKirk** [comment]
@christoball @csidenblad 

Chris, looks great!  Please proceed.  Thank you!!
