### ISSUE TITLE
Publish the 2019 Training Schedule

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1674]
The Google Sheet has been updated.

Kirby has prepared the registration system but the link has not yet been activated.

Let me know if you have questions.

**Comment by christoball** [comment]
@KCMack Preview available here:
https://preview.tnris.org/ellwood/2d03610064740c0d4f999844c12282fc59d5d836/education/

**Comment by KCMack** [comment]
Look great!  Please publish.

**Comment by christoball** [comment]
resolved in aa94654364b09c932d9c42e5d6fe5bdd384cbbdf
