### ISSUE TITLE
GIS Community Meeting Update

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1679]
Please add location to the GIO page meeting announcement box:
Texas Commission on Environmental Quality
12100 Park 35 Circle (map)
Building A, Room 202
Austin, TX 78753
Tuesday, January 15, 2019
2:00 p.m. - 4:00 p.m.

**Comment by christoball** [comment]
resolved in 1b1f93f20847b8cd267f0b213fec43a285fc1b94
