### ISSUE TITLE
StratMap 2018 Upper Coast

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1682]
**Data**
- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer
- [x] Data Processing [renaming file, data organization]  @ThorTheDestroyer
- [x] Creation of derivative products @ThorTheDestroyer
- [x] Quality Assurance @ThorTheDestroyer

**Publication**
- [x] Move to Content Creation @ThorTheDestroyer
- [ ] Data Story @ThorTheDestroyer @christoball 
- [ ] Final Publication @christoball @ThorTheDestroyer 
- [ ] Inform TNRIS staff of data availability @ThorTheDestroyer 

**data.tnris.org**
~~- [ ] create collection @mitchellryant~~
~~- [ ] complete console collection form including metadata and description @ThorTheDestroyer~~
~~- [x] upload photos @ThorTheDestroyer~~
~~- [ ] upload supplemental info (breaklines, reports, index) @ThorTheDestroyer~~

**Download\Prod**
~~- [ ] Move data to production shares @mitchellryant~~
~~- [ ] Add to Data Download  @mitchellryant~~

**Comment by ThorTheDestroyer** [comment]
when is that going to occur?

**Comment by adambreznicky** [comment]
it is currently planned to occur in February

**Comment by ThorTheDestroyer** [comment]
In anyone opposed to doing a old style release(data catalog entry and article) without loading it to our download? 
cons: influx of orders in the RDC and calls  asking if it is available online.
pros: dataset it greatly needed due to it representing the impact of areas hard hit by Harvey, and the sooner it gets released the sooner work can be done on a lot of  public projects before potential heavy rains in the spring. 

I must not have been paying attention or something, so sorry I missed the notification about no data being released this month.  Otherwise i would have told everyone to expect the data at a later date.

**Comment by mitchellryant** [comment]
pro: people buying the data from you. you guys are always complaining about the slump in RDC sales.

you still have to write an article, i guess if you want to do everything twice. you can make a the markdown for the entry.

**Comment by ThorTheDestroyer** [comment]
But if I... and then they....but how can...
![tenor.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b69ffa9b23ef00118092ef/125516c66e82c728ace21e0d46fc91942c90c1e5cdf9ad4cae58f3806b1c65267053f17e26dce72ced477e565f5f4eae485d5b17feac8e39baa47e21d40854b088270a36d43703adb1881eba05bd208d4985b6ba8345c5fa70.gif)

sigh

**Comment by ThorTheDestroyer** [comment]
Data Release Story

---
title: 2018 Lidar Data Release for the H-GAC Operating Area & Coastal Region
author: Joey Thomas, StratMap
template: news.html
mainimage: static/images/data-catalog/entry/stratmap_2018_50cm_crockett_lidar_overview.jpg
thumbnail: static/images/data-catalog/entry/stratmap_2018_50cm_crockett_lidar_th.jpg
thumbalt: A thumbnail for H-GAC Operating Area & Coastal Region
abstract: A collaborative initiative to capture high-quality Lidar data for portions of Crockett County.
---

The Texas Natural Resources Information System (TNRIS) is pleased to announce the release of approximately 9167 square miles of newly acquired high resolution lidar data for portions of the Texas coastal region. This project was managed by the Texas Strategic Mapping ([StratMap](https://tnris.org/stratmap/)) Program and utilized the [StratMap Contracts](https://tnris.org/stratmap/stratmap-contracts/) held by the Department of Information Resources (DIR). Collection took place during the leaf-off season in Texas.

The StratMap contributing partner for this project was the Texas Water Development Board(TWDB), the Houston-Galveston Area Council of Governments(H-GAC), and the United States Geological Survey(USGS) 3-D Elevation Program. Lidar acquired from this project will be used for floodplain management and planning, feature extraction, water quality modeling, stream restoration potential analysis, change detection, 9-1-1, wildfire mitigation, habitat identification/modeling for endangered species, and hurricane recovery projects. Data acquisition and processing was performed by the [Fugro](https://www.fugro.com/) with third-party QA/QC being performed by [AECOM](https://www.aecom.com/). The project area of interest covers areas where previous lidar data was acquired a decade ago. 

Further details regarding this acquisition can be found by downloading the Project Report(s) found in the link below. 

([StratMap 2018 H-GAC & Coastal Region Project Reports](https://INSERT-LINK))



## Data Access

Due to website development, this dataset cannot be currently added to the Data Search & Download section of our site.  To directly download the data, please use the below link to download an index shapefile containing direct links to the lidar products.

<div class="media">
  <div class="media-left">
    {% include "./partials/data-download-button.html" %}
  </div>
  <div class="media-body">
    <p>Use our online Data Search & Download to locate Crockett County and download the available Lidar for this dataset</p>
  </div>
</div>

<div class="media">
  <div class="media-left">
    {% include "./partials/order-button.html" %}
  </div>
  <div class="media-body">
    <p>Lidar data and the associated geospatial products for this project are available for the cost of reproduction through the <a href="{{m.link('order-data')}}">TNRIS Research and Distribution Center (RDC)</a>.</p>
  </div>
</div>



## Coverage Area

View coverage areas in the interactive map below:

<iframe width="100%" height="520" frameborder="0" src="https://tnris-twdb.carto.com/u/tnris/builder/1be7ada8-df6b-4df6-a7f4-42ed8901c704/embed" allowfullscreen webkitallowfullscreen mozallowfullscreen oallowfullscreen msallowfullscreen></iframe>

Please see our [Lidar status map](https://tnris-twdb.carto.com/u/tnris-sm/builder/a5dfc759-9a90-4acd-a8d1-57d521c7e1fe/public_map) for statewide lidar coverage.


## PRODUCTS
- Classified all-return lidar in DO4Q tiles (1/64th of USGS Quad)  LAS 1.4 format
- Bare-earth digital elevation model (DEM) in .img format (1-meter)
- Lidar intensity images in GeoTIFF format (1-meter)
- Hydro-flattening breaklines in SHP or Geodatabase
- File-level FGDC metadata in XML


<img class="img-responsive" src="{{m.link('static/images/data-catalog/entry/stratmap_2018_50cm_crockett_lidar_detail.jpg')}}" alt="detail image of the Crockett County Lidar">

## PRODUCT SPECIFICATION
- Vertical NVA RMSEz tested 4.910 cm. The tested accuracy in all areas meets the project specification for an NVA RMSEz of 10 cm.
- Average first-return point density is 4.37 points per square meter (ppsm) meeting the 4 ppsm project specification.
- Point data is classified according to the following American Society for Photogrammetry and Remote Sensing (ASPRS) class schema:
  * Class 1:  Unclassified
  * Class 2:  Ground
  * Class 3:  Low vegetation
  * Class 4:  Medium vegetation
  * Class 5:  Tall vegetation
  * Class 6:  Buildings
  * Class 7:  Low Point (noise)
  * Class 9:  Water
  * Class 10: Ignored Ground
  * Class 14: Culverts
  * Class 17: Bridges

- **Projection Specifications**
  + Horizontal projection is UTM NAD83 (2011) Zone 14 & Zone 15
  + Vertical projection is NAVD88 Geoid 12B
  + Units are in meters denoting orthometric heights

**Comment by ThorTheDestroyer** [comment]
![coastal-lidar-release-banner.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b69ffa9b23ef00118092ef/125516c66e82c728ace21e0d46eb9b9b309682a5c2e5b647a54fbd862c4a22723a01ee29718bed2dad0037431f1d11f6140b1b56f6eb8c22a1b4397683085fef84385874c63d13a5bd864cbd54bd32975dc7e7e2de139db17770a599855d3f160f198cfb5534a89042ce51ff4fe25f18.jpg)

**Comment by ThorTheDestroyer** [comment]
if we don't explain that the data isn't being added to the regular download, then how will people know that they can't download it the normal way?

**Comment by mitchellryant** [comment]
because you are replace the coverage map with a one off download map, with title and description.

**Comment by ThorTheDestroyer** [comment]
ahh okay, now i understand what you are saying. 

Everything that has crockett remaining looks to be related to an image or a data catalog entry, so i left those since they are populated by your group. I wasn't sure if we were going to delete the catalog entry portion or not.

**Comment by mitchellryant** [comment]
here is the download map.

https://tnris-twdb.carto.com/u/tnris/builder/f4af476f-dae0-49a4-b3e9-a12399020c77/embed

**Comment by mitchellryant** [comment]
@christoball Discussed with @rwade2126, @gmullins, @ThorTheDestroyer would like this published by 2/06!

**Comment by mitchellryant** [comment]
@christoball @ThorTheDestroyer @gmullins 

1. Please change name of Article to 2018 Lidar Data Release for the Upper Texas Coast.
2. Change "StratMap 2018 H-GAC & Coastal Region Project Reports" to StratMap 2018 Upper Texas Coast Project Reports". Link is broken. 
3. Under Data Access Comment out Data Search and Download Button and text. Change Crockett to Upper Coast 
4. Comment out Coverage Area View coverage areas in the interactive map below: 

@mitchellryant 
Data needs to be re-synced to the bucket.

**Comment by gmullins** [comment]
@ThorTheDestroyer @christoball Looks good! Here are my edits.
1. Change "The StratMap contributing partner for this project was the Texas Water Development Board(TWDB), the Houston-Galveston Area Council of Governments(H-GAC), and the United States Geological Survey(USGS) 3-D Elevation Program." to
"The StratMap contributing partners for this project were the Texas Water Development Board(TWDB), the Houston-Galveston Area Council of Governments(H-GAC), and the United States Geological Survey(USGS) 3-D Elevation Program."
2. Use Fugro USA Land with this hyperlink: https://www.fugro.com/our-services/asset-integrity/mapping-and-surveying
3. Change "...previous lidar data was acquired..." to "previous lidar data were acquired..."
4. Change "Further details regarding this acquisition can be found by downloading the Project Report(s) found in the link below.
StratMap 2018 H-GAC & Coastal Region Project Reports" to 
"Further details regarding this acquisition can be found by downloading the StratMap 2018 H-GAC & Coastal Region Project Reports." (hyperlinked)
5. Change "To directly download the data, please use the below map to download lidar products." to
"To download the lidar data products, use the map below."
6. Take off the Crockett stuff.

**Comment by ThorTheDestroyer** [comment]
Looks great, along with the above edits, the link for the project reports is still invalid.  @mitchellryant did that location hyperlink get created?

**Comment by mitchellryant** [comment]
@christoball here is the link https://s3.amazonaws.com/tnris-datadownload/datacatalog/supplemental_reports/stratmap_2018_50cm_upper_coast_supplementalreports.zip

**Comment by christoball** [comment]
pushed to production with final edits

resolved in 1a6fefe3a2cff8d3c64b32d4a16a4cdb58523023
