### ISSUE TITLE
Course Cancellation

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#169]
![cancelled](https://user-images.githubusercontent.com/7750220/75258344-f0406e80-57ab-11ea-9c5d-62e60a9f6c73.PNG)
@KCMack  Are these courses closed or cancelled? If cancelled, please change the status to cancelled. Thank you!

**Comment by ghost** [comment]
@geochik @KCMack the status field is a true\false selection, (either open or closed). there is not  domain table with with other choices. 

if the class is cancelled, I would recommend adding the word "cancelled" to the title of the class

**Comment by KCMack** [comment]
The courses were both closed until we had a chance to reschedule.  They  have both been rescheduled.

**Comment by KCMack** [comment]
Issue needs to be closed

**Comment by christoball** [comment]
Resolved, spoke to @KCMack about notes we can make in descriptions to be clearer about what's going on.
