### ISSUE TITLE
Update GIS Community Meeting Location

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1692]
Please update the GIS Community Meeting location to:
Department of State Health Services
1100 West 49th Street
Bernstein Building, K100 Auditorium
Austin, Texas

**Comment by geochik** [comment]
Campus map may be uploaded for convenience.
[HHSC_campus.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599c64cafada7e0606ba7cba/125516c66e82c728ace21e0d46c0bca900bd80a882f9aa50e611b2843b492d762a10e17132d0ba7fed172d580b0b4cf9145f5f44fcfb802ea2e53e258d4e17ff933c0120996048e6edc00db513bb27814e80b3bc8a4cc9e93426e48c885d73.pdf)

**Comment by christoball** [comment]
resolved in c1b7cb6cdc0b6c106c65446f470205fa2addbbea
