### ISSUE TITLE
Remove Calendar Event on GIO Page

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1693]
Remove 2/19 Event. Add the following:
Texas Public Safety Conference
March 31 - April 3, 2019
Galveston, TX
Event Link: https://www.texaspublicsafetyconference.com/

**Comment by christoball** [comment]
@geochik When we remove something we need another event to replace it. There always needs to be four events up there.

**Comment by christoball** [comment]
@geochik sorry, i misinterpreted this, i thought the event you were saying to add was what needed to be removed.

**Comment by christoball** [comment]
resolved in 2c41d901b21d29eec24fd703cbc3e96b87285af0
