### ISSUE TITLE
URISA Video Article Review  (#1694)

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1695]
My window of opportunity to review the language was missed. Please consider replacing the intro text with the following:

"Deputy Geographic Information Officer, Felicia Retiz, Geographic Data Coordinator Ilyanna Kadich, and Strategic Mapping Program (StratMap) Manager Gayla Mullins participated in the URISA Texas February Online Speaker Series. The presentation included national initiatives, updates on current StratMap data projects, and information on upcoming events. If you missed it, don’t fret - we have it here for you to view."

**Comment by christoball** [comment]
@geochik I've made these changes.

resolved in d32653b90f3bd1567af005663c3f676414bd8a92
