### ISSUE TITLE
Close Training Sessions

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1696]
Please close both Mastering Web Maps  and Fundamentals of ArcGIS

**Comment by KCMack** [comment]
Please change the status of the two courses from Open to Close.

Please do this as soon as possible .  We're not accepting any more students.

**Comment by christoball** [comment]
Spreadsheet is updated and website updated. 

Resolved in 7b0c69ed8ecb2cc6e5b53538c47b2e7546b3b658
