### ISSUE TITLE
TX Imagery Service change

### ISSUE THREAD

**Issue by gmullins** [TNRIS/tnris.org#1697]
@christoball This is the only thing I see that should be changed in the short term bc their link goes to Google Cloud now:
 Remove Google Imagery Fact Sheet completely

**Comment by gmullins** [comment]
We're still working out our communication plan to the current subscribers and what we're doing moving forward, our message, before any more changes should be made to the page.

**Comment by christoball** [comment]
@gmullins so to be clear the stuff in the first comment should be changed though?

**Comment by gmullins** [comment]
@christoball Yes, please change. Apologies for the confusion. The news from Google has really rocked my world.

**Comment by christoball** [comment]
@gmullins also there's a promotional image of the Texas Imagery Service on the front page. Should that come down?

**Comment by christoball** [comment]
updated front page, took out link

resolved in 8b52b207752328f7635a8e55c2eb06c8cf3bd971
