### ISSUE TITLE
Enhancements to address and parcel pages

### ISSUE THREAD

**Issue by ilyannakadich** [TNRIS/tnris.org#1698]
Add graphic and timelines to both pages.

**Comment by ilyannakadich** [comment]
[Status and timelines.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ad8b51668e3f40011a1dbde/125516c66e82c728ace21e0d46db809b379790e98ee7bb03b054fd91254f29763a46ef696097ec22ba416f43554d4ba5465a5a42f5addd29f3e33b708a5c09e4d4690c76933a03b0aac04ee155e57dd205d0f4ae805ec1ef3724e28e8e46361e061b88f75433b2d4.docx)

**Comment by ilyannakadich** [comment]
@christoball The circular diagram is intended for both pages.  Verbiage for circular diagram caption:
Program Flow - This iterative program flow will occur throughout the year.  At no one time will there be a completed or final version of data as each data source has varying update schedules.  Please check each county for the most recent version of data.

Verbiage for both  timeline captions:  Program Timeline - This timeline documents past events and estimates future milestones.  As milestones are met, this timeline will be updated.  Please check each county for the most recent version of data.

**Comment by christoball** [comment]
@ilyannakadich @gmullins preview additions to land parcels page here:
https://preview.tnris.org/ellwood/eb86b25a166161095a510a5e03e1813468e90174/stratmap/land-parcels/#stratmap-by-the-numbers

**Comment by christoball** [comment]
@ilyannakadich I will add the verbiage in next iteration

**Comment by christoball** [comment]
@gmullins @ilyannakadich Latest versions with timelines and graphic added to both. Removed goals...

Land Parcels:
https://preview.tnris.org/ellwood/bfc5b37420027d8b8ddd2703e84fd3cc61e709b8/stratmap/land-parcels/

Address Points:
https://preview.tnris.org/ellwood/bfc5b37420027d8b8ddd2703e84fd3cc61e709b8/stratmap/address-points/

**Comment by gmullins** [comment]
@christoball I prefer the previous timeline colors. For some reason, my eye goes to the green items. The user will likely be searching for the yellow (and blue) future items. Could those be emphasized?

**Comment by christoball** [comment]
@gmullins what do you think of these colors?
https://preview.tnris.org/ellwood/4a173a83a7a467ac16de6816b786fcabf0894216/stratmap/land-parcels/

**Comment by gmullins** [comment]
@christoball My only comment on these is the colors are dull/dark compared to the brightness of the rest of the page, the circle flow graphic.

**Comment by christoball** [comment]
@gmullins i felt the bright colors were making the white text a little harder to read. I can try something in between.

**Comment by christoball** [comment]
@gmullins how is this:
https://preview.tnris.org/ellwood/916bfb42d1feaa516ffcc388a6f752217360cdc6/stratmap/land-parcels/

**Comment by gmullins** [comment]
Yes! @ilyannakadich will like the burnt orange as a UT grad. Thx.

**Comment by christoball** [comment]
@gmullins @ilyannakadich K, if this looks alright I'd like to go ahead and push.

**Comment by gmullins** [comment]
Do it :)

**Comment by christoball** [comment]
pushed

resolved in 916bfb42d1feaa516ffcc388a6f752217360cdc6
