### ISSUE TITLE
Forum Save the Date Website

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1699]
Publish 'coming soon' theater graphic to promote forum save the date to tnris.org

**Comment by christoball** [comment]
@KCMack preview forum save the date front page here:
https://preview.tnris.org/haish/c95c96dbe3a2778c761ae6e059c4239bd9dd5372/

and the initial forum page here:
https://preview.tnris.org/haish/c95c96dbe3a2778c761ae6e059c4239bd9dd5372/texas-gis-forum/2019/

**Comment by KCMack** [comment]
Looks great!  ,,,,,and make new connections.

**Comment by christoball** [comment]
resolved in 0fde923787fd39f79797f9fef7128c717b62cab5
