### ISSUE TITLE
Add class to training page

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1701]
Please add another session of Fundamentals of ArcGIS.  It will take place on April 25-26, 2019.

The spreadsheet has been updated.
Thanks very much.

The course is being added due to public demand.  We have a short amount of time before the session, so I've requested this to be added to the website ASAP

**Comment by christoball** [comment]
Class is added

resolved in c9266e33d582813c61c0ac58c7edebc2220545e7

**Comment by KCMack** [comment]
Thanks very much, Chris!

KCM
