### ISSUE TITLE
Story\Banner about new site

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1703]
Will need to create a news items and banner to announce the "soft" launch of data.tnris.org. 

**Primary News Item:**
The new application replaces the TNRIS data catalog, data download, order data, and online mapping services sections of our website. The url to the new app is below. It is based on the Python Django framework with a Postgres RDS instance sitting in AWS. The front end is a React.js app embedded within the project. There is also an API which is pretty cool and allows us to do all the work for the front end. The big thing with all this is that now our internal content creators (those responsible for getting new datasets ready for the public and maintaining existing ones) can more easily publish data to the website using the Content Management System that Django provides. It's pretty powerful stuff and beats the way we used to do things by a lot.

**Comment by KCMack** [comment]
Announcing new TNRIS Data Catalog, Data Download, Order Data, and Online Mapping Sections. 

The big thing is that you will now have access to updates quicker and can find the information you need more easily.  Why? Take a look  url..............

Have an interest in the background?  The new application is based on the Python Django framework with a Postgres RDS instance sitting in AWS.  The front end is React.js app embedded within the project.  The API is cool and allows us to perform the work for the front end.  With this new Data Catalog, it’s easier for the TNRIS content creators to quickly update the website.  When it's easier to publish data to the website using the powerful Django provided Content Management System, you have access to the data quickly.

It’s a win-win!

**Comment by mitchellryant** [comment]
Since we are going with a soft launch lets push the publication of the of the banner and news article till mid week. It will give me some time to develop the news article a bit more @KCMack @christoball 

Sorry for the late notice, wanted to discuss this you earliier.

**Comment by christoball** [comment]
[some ideas for fleshing this out more]

Announcing the TNRIS DataHub. This brand new DataHub will replace our Data Catalog, Data Search & Download, Data Ordering, and Online Mapping Services.  We are excited to bring you this streamlined approach to acquiring your data in one easy-to-use intuitive online application.

The big thing is that you will now have access to updates quicker and can find the information you need more easily. It will all be available at http://data.tnris.org

But we know this is a big step, so we're leaving our current data access pages up until June 1 of this year. At that point, the DataHub will be become the sole online access point for our data.

So what are the ways we've made it easier than ever to search, download, and order our data?

[I'm just putting possible headers here]
## View everything, including Historical Aerial Imagery, as a dataset
[Trying to say something how much is available now]
- 2030 Datasets found

## Download 
[some way to explain how the download will give you a map, with easy to click polygons based on what you're looking at]

## Powerful Filtering Sidebar
The search bar is a direct way to find what you need, and makes accurate suggestions by your search term. But our filter sidebar is another way to hone in on the data you need.

It includes basic sorting by newest (most recently added), oldest, alphabetical, and categories. You can search if a dataset is available online, through ordering, or by an external link to partner agencies.

But there are new powerful tools what you need. We now also have a filter 'By Geography'. This will open an online map to allow you specify an extent you want find data within.
[Screenshot]

And there is a timeline filtering that allows you to set a date range for data as well
[Screenshot]


## Dataset Citation

We know that many Academics, students, and other use our data for their research needs. Now, there's an a quick way to copy a formatted citation!
[Screenshot]

## Have an interest in the development? 

The new application is based on the Python Django framework with a Postgres RDS instance sitting in AWS. The front end is React.js app embedded within the project. The API is cool and allows us to perform the work for the front end. With this new DataHub, it’s easier for the TNRIS content creators to quickly update the website. When it's easier to publish data to the website using the powerful Django provided Content Management System, you have access to the data quickly.

It’s a win-win!

**Comment by KCMack** [comment]
My initial thoughts and suggestions in red.

Thanks,
kcm

**Comment by mitchellryant** [comment]
Pushed short article, will publish complete article when site goes full..
