### ISSUE TITLE
Modify TWDB and TNRIS graphics on sign-in sheet

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1706]

**Comment by KCMack** [comment]
[Course Sign-in Learning ArcGIS Pro 1 _ Maps and Projects.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599df692453cba2d8789d6c6/125516c66e82c728ace21e0d46cb9b8f319186e9bce0b84de954fed405432661270dad2c30a4f12b986b48413f1d11bc4048305481a8c968b6e762249a3c49b28b380c30852f0dbef8c040e554e964994597b3b58d4ec5ee3471b389da1a391e05188bf65831f39b1ecf4aea59a31c0bf04c6b3aac23746e4d861f72266a6223a9f5db51818060a0bf123d1b.xlsx)

**Comment by christoball** [comment]
Created and sent to @KCMack
