### ISSUE TITLE
StratMap Initiatives banner

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1707]
First take on the StratMap Banner:
https://preview.tnris.org/haish/14575b570f11dadf30d3136ae98fbd043df52c58/

**Comment by ilyannakadich** [comment]
@christoball  I like it!  Can we keep the verbiage consistent and use "Land Parcels" in lieu of "Land Parcel Data"?   Thanks!

**Comment by gmullins** [comment]
@christoball I agree with @ilyannakadich . Looks good! Looping in joey for his awareness.
The banner should go live after the new timelines are published for both the land parcels and address points pages. Thx!

**Comment by christoball** [comment]
Updated with edits:
https://preview.tnris.org/haish/80509b65da31d869ab4309f69875ef84a524e047/

**Comment by gmullins** [comment]
Great!

**Comment by christoball** [comment]
Banner updated on production

Resolved in 916bfb42d1feaa516ffcc388a6f752217360cdc6
