### ISSUE TITLE
Add agenda to GIS Community calendar event

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1708]
Please advise on how I should submit the document file.

**Comment by geochik** [comment]
[GISComm_Agenda_20190416.pdf](https://github.com/TNRIS/tnris.org/files/3010155/GISComm_Agenda_20190416.pdf)

**Comment by geochik** [comment]
Also need the map uploaded......
[DSHS_campus.pdf](https://github.com/TNRIS/tnris.org/files/3010192/DSHS_campus.pdf)

**Comment by christoball** [comment]
added

resolved in 2a0674b2072e94304a0c698ce12c2b681a9e6da9
