### ISSUE TITLE
Update GIO Page Calendar

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1711]
Please replace March 28 event, Houston Regional GIS Expo, with the following:

East Texas GIS & GPS User Group Meeting
April 11, 2019
3:30 - 5:00 p.m.
101 W Tyler St
Longview, TX 75601

**Comment by geochik** [comment]
Event URL - https://guestlist.co/events/603885?utm=4szz19i7x8jy9g2x

**Comment by christoball** [comment]
calendar is updated 

resolved in 6e7c75516f3b370c448120168aab6013c26c709a
