### ISSUE TITLE
new dataset: USGS 2018 Lavaca Wharton 

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1712]
Please reassign issues when your work is complete.

**Data**
- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer
- [x] Data Processing [renaming file, data organization]  @ThorTheDestroyer
- [x] Creation of derivative products @ThorTheDestroyer
- [x] Quality Assurance @ThorTheDestroyer

**DataHub**
- [x] Create collection @mitchellryant
- [x] Complete console collection form including metadata and description @ThorTheDestroyer 
- [x] Upload photos @ThorTheDestroyer 
- [x] Upload supplemental info (breaklines, reports, index) @ThorTheDestroyer 
- [x] Add resources  @mitchellryant 

**Download\Prod**
- [x] Move data to production shares @mitchellryant 
- [x] Make collection public  @mitchellryant 

**Publication**
- [x] Move to Content Creation @ThorTheDestroyer
- [x] Data Story @ThorTheDestroyer @christoball 
- [x] Final Publication @christoball @ThorTheDestroyer 
- [x] Inform TNRIS staff of data availability @ThorTheDestroyer

**Comment by ThorTheDestroyer** [comment]
![usgs-2017-70cm_lavaca-wharton_2D](https://user-images.githubusercontent.com/8398036/55895130-2586a280-5b81-11e9-87be-67c0266c6ed2.jpg)

**Comment by ThorTheDestroyer** [comment]
![usgs-2017-70cm_lavaca-wharton_3D_classification](https://user-images.githubusercontent.com/8398036/55895274-726a7900-5b81-11e9-935e-777d5ddf8ae0.jpg)

**Comment by mitchellryant** [comment]
data is labeled 2017 metadata says 2018 @ThorTheDestroyer 

<img width="708" alt="Screen Shot 2019-05-23 at 8 02 37 AM" src="https://user-images.githubusercontent.com/8459928/58254815-30605580-7d31-11e9-9f59-4d50963858f1.png">

**Comment by ThorTheDestroyer** [comment]
![image](https://user-images.githubusercontent.com/8398036/59385054-28407800-8d29-11e9-8f6a-dfba2332ce25.png)

My mistake, I just checked it and looks like everything including the datacard have the right date.  If there is a remaining issue please let me know, and I'll take care of it.
