### ISSUE TITLE
new dataset: USGS 2017 Red River

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1713]
Please reassign issues when your work is complete.

**Data**
- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @LaurenKirk 
- [x] Data Processing [renaming file, data organization]  @LaurenKirk
- [x] Creation of derivative products @LaurenKirk
- [x] Quality Assurance @ThorTheDestroyer

**DataHub**
- [x] Create collection @mitchellryant
- [x] Complete console collection form including metadata and description @LaurenKirk
- [x] Upload photos @LaurenKirk
- [x] Upload supplemental info (breaklines, reports, index) @LaurenKirk
- [x] Add resources @mitchellryant 

**Download\Prod**
- [x] Move data to production shares @mitchellryant 
- [x] Make collection public @mitchellryant 

**Publication**
- [x] Move to Content Creation @ThorTheDestroyer
- [x] Data Story @ThorTheDestroyer @christoball 
- [x] Final Publication @christoball @ThorTheDestroyer 
- [x] Inform TNRIS staff of data availability @ThorTheDestroyer

**Comment by LaurenKirk** [comment]
@ThorTheDestroyer Red River Lidar is now complete.

**Comment by LaurenKirk** [comment]
@christoball Hey Chris, I put an image for the new USGS Red River project here: M:\Website\datacatalog\images\usgs_2017_red-river 

Can you please resize it for the datahub?  Thanks so much!
@mitchellryant

**Comment by LaurenKirk** [comment]
oops, didn't mean to close

**Comment by mitchellryant** [comment]
@LaurenKirk no images loaded, so i can not make it public.

**Comment by christoball** [comment]
I've Added the optimized images under the same folder with _web added to filename.
