### ISSUE TITLE
new dataset: USGS 2016 Brazos River Basin

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1714]
Please reassign issues when your work is complete.

**Data**
- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @csidenblad 
- [x] Data Processing [renaming file, data organization]  @ThorTheDestroyer
- [x] Creation of derivative products @ThorTheDestroyer
- [x] Quality Assurance @ThorTheDestroyer

**DataHub**
- [x] Create collection @mitchellryant
- [x] Complete console collection form including metadata and description @ThorTheDestroyer 
- [x] Upload photos @ThorTheDestroyer 
- [x] Upload supplemental info (breaklines, reports, index) @ThorTheDestroyer 
- [x] Add resources  @mitchellryant 

**Download\Prod**
- [x] Move data to production shares @mitchellryant 
- [x] Make collection public  @mitchellryant 

**Publication**
- [x] Move to Content Creation @ThorTheDestroyer
- [x] Data Story @ThorTheDestroyer @christoball 
- [x] Final Publication @christoball @ThorTheDestroyer 
- [x] Inform TNRIS staff of data availability @ThorTheDestroyer

**Comment by ThorTheDestroyer** [comment]
@mitchellryant In I: will you please change the 3 files named Bridge_Saddles to usgs-2016-70cm_Bridge-Saddles-blk4?

Contours and contour metadata have been completed and are ready to move to production.

**Comment by mitchellryant** [comment]
@ThorTheDestroyer @christoball images are not the proper dimensions. please adjust and reload images.

https://data.tnris.org/collection/d55b62b3-fd81-4e15-a034-6fda56cde7de

**Comment by mitchellryant** [comment]
there is black space around both images. there is not supposed to be.

**Comment by ThorTheDestroyer** [comment]
Corrected, my math was off a bit.  Loaded new images with captions.
