### ISSUE TITLE
new dataset: USGS 2018 South Central Texas

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1715]
Please reassign issues when your work is complete.

**Data**
- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer
- [x] Data Processing [renaming file, data organization]  @csidenblad 
- [x] Creation of derivative products @csidenblad
- [x] Quality Assurance @ThorTheDestroyer

**DataHub**
- [x] create collection @mitchellryant
- [x] complete console collection form including metadata and description @csidenblad
- [x] upload photos @csidenblad
- [x] upload supplemental info (breaklines, reports, index) @csidenblad
- [x] Add resources  @mitchellryant 

**Download\Prod**
- [x] Move data to production shares @mitchellryant 
- [x] Make collection public  @mitchellryant 

**Publication**
- [x] Move to Content Creation @ThorTheDestroyer
- [x] Data Story @ThorTheDestroyer @christoball 
- [x] Final Publication @christoball @ThorTheDestroyer 
- [x] Inform TNRIS staff of data availability @ThorTheDestroyer

**Comment by csidenblad** [comment]
@ThorTheDestroyer I've finished creating derivative products, compressing, and renaming. Please check to be sure everything is in the correct place and it looks good. When I get the ok from you i'll update the DataHub entry and upload associated photos/files.

**Comment by csidenblad** [comment]
@christoball I have uploaded the images for the South Central collection to M:\Website\datacatalog\images, will you please resize to fit on the website? Please and thank you. 
@mitchellryant I believe all task expected of me are complete. Thank you again for helping to re-rename.

**Comment by csidenblad** [comment]
@christoball I uploaded a new point cloud image to replace the one that was too small. Let me know when you have finished resizing and I will add them to the data entry. Thanks again

**Comment by christoball** [comment]
@csidenblad I've added cropped and web-optimized versions to the same folder under M:\Website\datacatalog\images. 

I added _web to the file names to distinguish that.

**Comment by mitchellryant** [comment]
@csidenblad no images loaded so ic not make public
