### ISSUE TITLE
new dataset: USGS 2017 Brazos, Freestone, Robertson

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1716]
Please reassign issues when your work is complete.

**Data**
- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer 
- [x] Data Processing [renaming file, data organization]  @ThorTheDestroyer
- [x] Creation of derivative products @ThorTheDestroyer
- [x] Quality Assurance @ThorTheDestroyer

**DataHub**
- [x] Create collection @mitchellryant
- [x] Complete console collection form including metadata and description @ThorTheDestroyer 
- [x] Upload photos @ThorTheDestroyer 
- [x] Upload supplemental info (break lines, reports, index) @ThorTheDestroyer 
- [x] Add resources mitchellryant 

**Download\Prod**
- [x] Move data to production shares @mitchellryant 
- [x] Make collection public  @mitchellryant 

**Publication**
- [x] Move to Content Creation @ThorTheDestroyer
- [x] Data Story @ThorTheDestroyer @christoball 
- [x] Final Publication @christoball @ThorTheDestroyer 
- [x] Inform TNRIS staff of data availability @ThorTheDestroyer

**Comment by ThorTheDestroyer** [comment]
This dataset is currently only partially delivered.  We are currently awaiting delivery of the remainder of the products from NRCS Texas as soon as they can copy it over and send it our way.

**Comment by mitchellryant** [comment]
data labeled as 16 report list 17 @ThorTheDestroyer 

<img width="708" alt="Screen Shot 2019-05-23 at 10 45 38 AM" src="https://user-images.githubusercontent.com/8459928/58266762-f3ec2400-7d47-11e9-9520-5da1e3e79789.png">
