### ISSUE TITLE
Address point site content update

### ISSUE THREAD

**Issue by ilyannakadich** [TNRIS/tnris.org#1717]
Please update the FAQ "What is the Texas 9-1-1 Alliance?" with this content:

The Texas 9-1-1 Alliance is an interlocal cooperation entity composed of 27 Texas emergency communication districts with E9-1-1 service and related public safety responsibility for more than approximately 70% of the population of Texas. These emergency communication districts were created pursuant to Texas Health and Safety Code Chapter 772 and are defined under Texas Health and Safety Code Section 771.001(3)(B).

**Comment by christoball** [comment]
updated and resolved in e62e140288980120e3e41dc0bc16928c1dbdfe0a
