### ISSUE TITLE
Free ArcGIS Hands-on Workshop - Configuring & Deploying Mobile Apps

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1719]
TNRIS and TCEQ are coordinating with Esri to  host Free ArcGis Hands-on Workshops - Configuring & Deploying ArcGIS Mobile Apps on April 17 at 1:00 - 4:00 and April 18 at 8:30 - 12:00.
The half-day workshops will present how to configure and deploy ArcGIS field apps that support your field data collection workflows.  Attendees will become familiar with their ArcGIS Online organization.  Hands-on exercises will demonstrate how to setup and configure the apps for the field.  Additionally, you will learn how to analyze your field data and create powerful real-time dashboards to monitor field activities.
Bring your own device session:
ArcGIS Online Organizational Account with Publisher rights
iOS or Android Mobile Device (phone and/or tablet)
Laptop capable of signing into ArcGIS Online (optional)
Familiarity with ArcGIS Online is desired to complete the exercises.

Location: TCEQ 12100 Park 35 Circle, Building 'A', Austin, Texas 78753

RSVP: To attend, please RSVP Jon Doherty - jpdoherty@esri.com no later than April 10, 2019

**Comment by christoball** [comment]
article added to site

resolved in d68b33f2ba823818642460be2aa05671355c9ac9
