### ISSUE TITLE
Quick article on dataHub

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1720]
I've drafted a short article for the DataHub so we can have something on the front page until the full launch.

Preview here: https://preview.tnris.org/ellwood/f285857d1cdc3120b2e7a5d6fe4cdaf7bb4e1333/news/2019-04-09/datahub-an-early-look-at-future-tnris-data/

**Comment by KCMack** [comment]
Chris,  Try this version on for size:

Start trying it out today at data.tnris.org.

The new DataHub combines all of TNRIS's Data Catalog, Data Download, Data Ordering, and Online Mapping Services into one easy to use online application. It provides information and access to all of our available data.
This is a big change.  And, we suspect that our dedicated users may want to take it for a spin before we completely transition from the data sites you are familiar with. Between now and June 1, test drive the new DataHub and still have access all existing data pages.  After that date your key to the data will be through the new DataHub.

**Comment by christoball** [comment]
Incorporated edits and ready to publish.

https://preview.tnris.org/ellwood/97aa847997aea6dd48465f21f35fb6d3bb456667/news/2019-04-09/datahub-an-early-look-at-future-tnris-data/

**Comment by christoball** [comment]
article added

resolved in d68b33f2ba823818642460be2aa05671355c9ac9
