### ISSUE TITLE
Land parcel website update

### ISSUE THREAD

**Issue by ilyannakadich** [TNRIS/tnris.org#1721]
Chris, please update the parcel count and status bar to 129.  I updated the map, just waiting for it to synch with Carto.

**Comment by christoball** [comment]
Updated the parcel count.

Resolved in e8eca8ef9e44df39d57bdbeb84416d102a9d5fdd

**Comment by christoball** [comment]
@ilyannakadich please don't reopen closed issues unless the original task was unresolved. 

For new tasks, create a new issue i.e. 'Update Parcel count to 129'

Thank you!

**Comment by gmullins** [comment]
My bad! I showed @ilyannakadich how to reopen an issue but thought it was an accidentally closed one.
