### ISSUE TITLE
Updates to TNRIS Training page and front page

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1723]

**Comment by KCMack** [comment]
Please change status from: OPEN to CLOSED on the following courses:
Learning ArcGIS Pro 2
Learning ArcGIS Pro 3
Learning ArcGIS Pro 4

Switch out courses offered on front page to:
April 25-26
Fundamentals of ArcGIS
May 13-15
Intermediate GIS Concepts

**Comment by christoball** [comment]
updated workshops and front page

resolved in d68b33f2ba823818642460be2aa05671355c9ac9
