### ISSUE TITLE
DataHub Button

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1724]
Can you add the DataHub Button on the Parcel Page to the following pages?

[Address Points](https://tnris.org/stratmap/address-points/)

[Historical Imagery Archive](https://tnris.org/research-distribution-center/historical-imagery-archive/)

Also change the txt to:
Customers can preform a cursory search of the the TNRIS Historic photo archive by using the DataHub web application.

[Upper Coast Lidar News Article](https://tnris.org/news/2019-02-06/2018-lidar-release-hgac-operating-area-coastal-region/) Just add the button where the href is.

**Comment by christoball** [comment]
@mitchellryant Are we removing the 'order button' from the Upper Coast Lidar as well?

**Comment by christoball** [comment]
I've updated the pages, pushed to prod. If no further action is needed we can close this issue.

**Comment by christoball** [comment]
Closing issue, will follow up on any other changes we should make when @mitchellryant is back.

resolved in 0d826ebde7023ac86459a9d1b7996f4b65797e97
