### ISSUE TITLE
Update community meeting map link for tomorrow

### ISSUE THREAD

**Issue by gmullins** [TNRIS/tnris.org#1725]
@christoball Please update the map link to:
https://www.google.com/maps/place/Texas+Department+of+State+Health+Services/@30.319571,-97.7379335,16.5z/data=!4m5!3m4!1s0x8644ca66dad96815:0x87cec936c8f49f40!8m2!3d30.319167!4d-97.7353329?hl=en

on this: https://tnris.org/static/documents/gio-meetings/GISComm_Agenda_20190416.pdf

**Comment by christoball** [comment]
Fixed the pdf, shows the correct location now.

resolved in b22bf4bebbdf3f5aef863897d9a59b48d25adac9
