### ISSUE TITLE
Call for papers mention and link

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1728]
https://app.smartsheet.com/b/form/9c4e7c5b55104f0abfbac49ba4984888.  

Please add Call for Presentations to the Forum website.  We can use the same language as 2018.

**Comment by KCMack** [comment]
Abstract due date: June14
Notify abstracts accepted: July 1

**Comment by christoball** [comment]
Call for Papers added to forum page

resolved in 86da11968f124e04015f450705308e1609f55eee
