### ISSUE TITLE
Update TNRIS Course Cancellation Policy

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#173]
## TNRIS Training Program Cancellation Policy

Course cancellations are often unavoidable. Whether the class cancellation is initiated by the student or the Training Program, every effort to send an immediate notification must be exercised.

### Withdrawal/Cancellation

All course cancellations require written notice no later than 14 business days prior to the first day of the scheduled course. Email is an acceptable form of written communication- please email tnris@cmpmanagement.com. 

### Refund

All withdrawals made more than fourteen (14) business days prior to course start date will receive a full refund (minus $65 processing fee).

The full course refund is forfeited if a cancellation is made within fourteen (14) business days of a course start date or if a student is a no show.

Option: Registration and payment may be applied to a future course of equal value within the same fiscal year (09/01 - 08/31).

### Substitution

Student substitutions are allowed at no charge with 3-days written notice prior to the start of the course. Substitutions are not allowed within 3-days of a course start date.

### Course Cancellation

All courses must meet a minimum number of enrolled students. Occasionally a course must be cancelled due to low enrollment. 

Registered students will be notified no less than 1 week before the start date of the course. Notification via email and phone call will be made using the information provided in the registration.

When courses are cancelled, several options are available:

1. A full refund processed in the same manner paid.  
2. Apply the registration fee to a course of equal value held during the same fiscal year (9/01 – 8/31). 
3. Apply the registration fee to a course of equal value to a colleague from the same organization within the same fiscal year (9/01 – 8/31).

For all change and cancellation requests, please contact:   tnris@cmpmanagement.com.

**Comment by KCMack** [comment]
Thank you Chris.  Looks good.

**Comment by christoball** [comment]
@KCMack this is ready to preview:
http://glidden.tnris.org/education/
