### ISSUE TITLE
Update Program Timeline for Land Parcel website for Summer 2019

### ISSUE THREAD

**Issue by ilyannakadich** [TNRIS/tnris.org#1730]
@christoball Please update the Project Timeline box for Summer 2019 and turn it GREEN since our count is above 150 now.  Thanks!

**Comment by christoball** [comment]
@ilyannakadich what do you think about tweeting about this too? 

"Our initiative to create a comprehensive land parcel dataset is always moving forward. We just reached another milestone - over 150 appraisal district datasets are now available for download!

Our Land Parcels page always shows the latest status: https://tnris.org/stratmap/land-parcels/"

![image](https://user-images.githubusercontent.com/1877550/57026537-b4766000-6bff-11e9-859b-81f3c7947871.png)

**Comment by ilyannakadich** [comment]
YES!!

Best,
Ilyanna

**Comment by christoball** [comment]
Updated and pushed

resolved in 86da11968f124e04015f450705308e1609f55eee
