### ISSUE TITLE
Signs for the GeoRodeo

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1731]
2 signs announcing the GeoRodeo for the sandwich board to be place outside of the entrance to the Events Center -- 24X36 -- not on foam core.  Do we have something less thick?  

2  8 1/2X11 signs to be placed in the garage on the elevator doors.  1 Use This Elevator for the GeoRodeo.  1 Use the Other Elevator for the GeoRodeo for Cesar Chavez Street

1 sign announcing the financial supporters saying..... Thank you to our supporters Esri, GeoSpatial Training Services, and the Texas GIS Forum.  This one will go on an easel near the food tables.

1 table top sign - Pick up GeoRodeo Registration Name Tag Here

Let me know if you have questions.

**Comment by KCMack** [comment]
Make this 2 signs

1 sign announcing the financial supporters saying..... Thank you to our supporters Esri, GeoSpatial Training Services, and the Texas GIS Forum. This one will go on an easel near the food tables.

**Comment by christoball** [comment]
Printed and ready to go
