### ISSUE TITLE
GeoRodeo Registration Closes this week on May 9

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1732]
Please change this statement near the Registration link:
NOTICE: Registration will close in 2 weeks on May 9th. Be sure to register before then if you would like lunch and to attend the social at google

To read:
NOTICE: Registration will close on Thursday, May 9th.  Be sure to register before then if you would like to attend, have lunch and attend the social at Google after the GeoRodeo.

**Comment by christoball** [comment]
closing, there is already an issue for this #1727

**Comment by christoball** [comment]
Misunderstood this issue. I've updated the language as requested.

resolved in fd63fd1e1ef097383a7b673342ac680a7de45b72
