### ISSUE TITLE
TNRIS Training updates

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1733]
Please change status from OPEN to CLOSED
5/13/19  Intermediate GIS Concepts

On the front page switch the courses listed to:
Remove Intermediate GIS Concepts
Add - after Collector and Survey, 5/20-21/19 Introduction to Programming ArcGIS Pro with Python

**Comment by christoball** [comment]
training updated and front highlight changed

resolved in e28205e842f5b151b37eb9c5b28d8852bb32c51e
