### ISSUE TITLE
Update GIO Page Events Calendar

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1736]
Please omit past events and update with the following events on the GIO page:

NCTCOG Regional GIS Meeting
5/28/2019
Register to Attend! (https://www.nctcog.org/regional-data/geographic-information-systems-gis/meetings-classes/regional-gis-meeetings-and-classes/regional-gis-meeting
)

Texas Demographic Conference 2019
6/5 - 6/6
1617 North Interstate 35, Austin, TX 78702
Event Link (https://demographics.texas.gov/AnnualConference/Current)

Esri User Conference
7/8-7/12
San Diego Convention Center
San Diego, CA
Event Link (https://www.esri.com/en-us/about/events/uc/overview)

**Comment by christoball** [comment]
@geochik  When is the next GIO meeting?

**Comment by geochik** [comment]
July 23, 2-4 p.m.
Location pending

**Comment by christoball** [comment]
calendar is updated

resolved in c94ad501ea0604782e4897213a32a91e2948c207
