### ISSUE TITLE
reCAPTCHA language on google form

### ISSUE THREAD

**Issue by gmullins** [TNRIS/tnris.org#1739]
Ryan spoke with me about the reCAPTCHA. Can you please add this language to the bottom of https://tnris.org/google-request/

If you receive a reCAPTCHA error while submitting, please clear your cache (hold CNTRL + press F5) to make the reCAPTHCA "I'm not a robot" verification appear.

**Comment by mitchellryant** [comment]
I have discussed this with the team, we can not update the recaptha package. The plan is to disable it.

**Comment by gmullins** [comment]
Ok.
