### ISSUE TITLE
GeoRodeo Recap

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1740]
I imagine some nice words will need to be written thanking speakers and attendees.

- [x] Gathering missing presentations, please place them on the m:\ drive @JasonKleinert @adambreznicky @jwhaney 
- [x] Publish presentations @christoball 
- [x] Publish any photos @christoball

**Comment by adambreznicky** [comment]
M Drive: /vault/Forum_GeoRodeo/2019 GeoRodeo/Presentations/
presentation gathering:
- [ ] richard wade
- [ ] Patrick McGranaghan
- [ ] Andrew Chapkowski
- [ ] Michael Shensky
- [ ] Daniel K. Pearson
- [ ] Laura Bell Sepulveda
- [ ] Jordan Carmona
- [ ] Daniel J. Dufour
- [ ] Aubrey Drescher
- [ ] Thomas Montgomery
- [ ] Kevin Booth

**Comment by adambreznicky** [comment]
Jordan's presentation is not in the drive, but is here:
https://github.com/FeralCatColonist/GeoRodeo2019

**Comment by adambreznicky** [comment]
Kevin's presentation is not in the drive, but is here:
http://kb.gg/georodeo

**Comment by jwhaney** [comment]
Tom Montgomery's online version: https://docs.google.com/presentation/d/1lh1B56gQ195YMc-0RqzVvKpuggQnJQAaVpBHHTIIc3I/edit?usp=sharing

**Comment by christoball** [comment]
Preview of draft up:
https://preview.tnris.org/ellwood/048cceef2743c9a30cc93f06529b42605edee331/news/2019-05-21/2019-georodeo-wrap-up-photos-slides/

**Comment by adambreznicky** [comment]
update: michael shensky emailed his slides last night. i put the pdf in the drive.

preview looks great! i approve!

**Comment by mitchellryant** [comment]
@christoball thumbs up!!

**Comment by christoball** [comment]
Article is published - gonna close this issue - if there are more presentations we'll add them as they come in.

resolved in bd0a7f02d1acb610240380a94e0f9907613f2171

**Comment by mitchellryant** [comment]
Daniel K Pearson presentation link https://www.slideshare.net/slideshow/embed_code/key/nSe08kDDJyumHp

**Comment by christoball** [comment]
added pearson's slides

resolved in ac8fe09240fb933356a94b82fd729fb82b92345c
