### ISSUE TITLE
new dataset: NLCD 2016

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1742]
Please reassign issues when your work is complete.

**Data**
- [x] Add data to measures spreadsheet @gmullins 
- [x] Route Data Shipment [copy data to TNRIS Projects share] @gmullins 
- [x] Data Processing [renaming file, data organization]  @LaurenKirk @csidenblad 
- [x] Creation of derivative products @LaurenKirk @csidenblad
- [x] Quality Assurance @LaurenKirk @csidenblad @gmullins 

**DataHub**
- [x] Create collection @mitchellryant
- [x] Complete console collection form including metadata and description @LaurenKirk @csidenblad 
- [x] Upload photos @LaurenKirk @csidenblad
- [x] Add resources mitchellryant 

**Download\Prod**
- [x] Move data to production shares @mitchellryant 
- [x] Make collection public  @mitchellryant

**Comment by gmullins** [comment]
Thanks everyone!

**Comment by csidenblad** [comment]
@mitchellryant it doesn't look like you made this one public
