### ISSUE TITLE
Land Parcel website Program Timeline updates

### ISSUE THREAD

**Issue by ilyannakadich** [TNRIS/tnris.org#1744]
@christoball please update the Land Parcels website Program Timeline.  The box for Fall 2019 should now be green since we are over 200 counties of parcels.  Also, please update the verbiage in the Winter 2019 box to read "Winter 2019 +200 expected counties of parcel data posted in a standardized schema" Thanks!

**Comment by christoball** [comment]
resolved in 134f9eb3e6bdf1b9cbb1f2233f560b9482780c58
