### ISSUE TITLE
Land Parcel website Program Timeline updates 2

### ISSUE THREAD

**Issue by ilyannakadich** [TNRIS/tnris.org#1745]
@christoball Gayla and I reviewed the most recent updates together and have the following request.  Please update the Land Parcel website Program Timeline as below:

Spring 2019 150 counties of parcel data posted (remove Summer and replace with Spring)
Summer 2019 over 200 counties of parcel data posted (remove Fall and replace with Summer)
Fall 2019 over 200 counties of parcel data posted in a standardized schema (remove Winter and replace with Fall)

**Comment by christoball** [comment]
resolved in 134f9eb3e6bdf1b9cbb1f2233f560b9482780c58
