### ISSUE TITLE
Update GIS Community Meeting PPTs

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1746]
@christoball 
The "taglines" for each of the last three meetings are below. PPTs are uploaded except for Q2 2019. Too big to load. Will try to reduce and submit via network.

2018 Q3 - The 3rd Quarter GIS Community Meeting was held on July 24, 2018 at Texas Parks and Wildlife Department headquarters in Austin, TX. Roll Call notes are listed in Slide 13. Attendees were invited to give lightning talks. Notes on the talks can be found on Slide 14.

2019 Q1 - The 1st Quarter GIS Community Meeting was held on January 15, 2019 at the Texas Commission on Environmental Quality in Austin, TX. Guest presenters were Traci Tracey of Esri - San Antonio and Ed Kelly of the Department of Information Resources. Slides are included where permission granted. Roll call notes are located on Slide 28.

2019 Q2 - The 2nd Quarter GIS Community Meeting was held on April 16, 2019 at the State Health and Human Services Headquarters in Austin, TX. Dr. Stacey Lyle, Assistant Professor of Practice at Texas A&M was presented on his current efforts to help create the new State Plane Coordinate System of 2022 (SPCS2022). Roll call notes can be found on Slide 77.
[GIS_QtrlyMtg3_2018_FINAL.pptx](https://github.com/TNRIS/tnris.org/files/3213829/GIS_QtrlyMtg3_2018_FINAL.pptx)
[GIS_QtrlyMtg1_2019_FINAL.pptx](https://github.com/TNRIS/tnris.org/files/3213831/GIS_QtrlyMtg1_2019_FINAL.pptx)

**Comment by geochik** [comment]
@christoball 
The Q2 2019 PPTX is greater than 80MB. I can separate into two presentations or try PDF. The full PPTX can be found here - \\twdb4afssvr2\vault\Admin\GIO\QtrlyCommunityMtgs\2019\2ndQtr
File name: GIS_QtrlyMtg2_2019_FINAL.pptx

**Comment by christoball** [comment]
uploaded and added

resolved in 1bf02746b7f9f7d1de5fcbd8c8577eb463ef8027
