### ISSUE TITLE
New Custom Mapping Pricing

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/tnris.org#1748]
We'd like to add this to the custom map order form on tnris.org.  No rush.  Thanks duuudes!!

**Custom Map Pricing:**
Staff Fee: $100.00
Custom Map Fee: $75.00 ($37.50/hour for a 2 hour minimum)
Additional Time: $37.50/hour

**Printing Costs**:

Laser Prints:
8.5 x 11 --> $10.00
11 x 17 -->$12.00

Plotter Prints:
24 x 24-->$20.00
24 x 28-->$20.00
30 x 30-->$30.00
36 x 36-->$30.00
60 x 60 or larger-->starting at $50.00 contact RDC for more details 
   (maximum width is 60 inches)

Vector maps will be printed on bond paper.  Raster maps will be printed on satin.

**Shipping Costs:**
FedEx Standard Overnight
24 x 28 or smaller -->$10.00
30 x 30 or larger -->$15.00

USPS Standard Shipping
All map sizes $5.00

**Comment by christoball** [comment]
@LaurenKirk went ahead and rushed it 

https://tnris.org/research-distribution-center/custom-maps/

**Comment by LaurenKirk** [comment]
@christoball Thank you so much!!

**Comment by christoball** [comment]
resolved in cf041ce2aa37ecd2b6ee13a57d1dd2a10ef7555e
