### ISSUE TITLE
Historical Filter Button on RDC Main Page

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/tnris.org#1749]
Hey y'all,

We'd like to add a datahub button that will take the user to filter set of historic imagery.  Much like the one on the Ortho and Lidar pages.

Also, no rush.

**Comment by mitchellryant** [comment]
https://data.tnris.org/catalog/%7B%22filters%22%3A%7B%22category%22%3A[%22Historic_Imagery%22]%7D%7D

**Comment by christoball** [comment]
resolved in c6245ac82ce1802244a7fdb7e704aa90e7d14359
