### ISSUE TITLE
Leon Logothetis article

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1752]
Please add the following about our Keynote:
Leon Logothetis is a global adventurer, motivational speaker & philanthropist. It wasn’t always that way. He used to be a broker in the city of London where he felt uninspired and chronically depressed. He gave it all up for a life on the road. This radical life change was inspired by the inspirational movie The Motorcycle Diaries.

The days of living and working behind his ‘slab of wood’ (or desk to the layman) are well and truly over. His new passion: Finding ways for your inner rebel (that voice that tells you, you are worth so much more than you think) to come out and play.

The inner rebel tells you that your life is yours.  And anything you dream of is possible. Anything. And that the fuel for all this delicious potential is simple: Kindness and harnessing the power of human connection. And. Doing it all with a smile on your face and a spring in your step!

As host of the Netflix series, The Kindness Diaries, Leon circumnavigated the globe on his vintage yellow motorbike ‘Kindness One’, giving life-changing gifts along the way to unsuspecting good Samaritans. All of this whilst relying on the kindness of strangers. He recently returned from filming the second season of The Kindness Diaries in which he traveled from Alaska to Argentina in his vintage yellow VW Beetle Kindness Two, changing lives one mile at a time.

Leon is no stranger to adventure. He teamed up with First Book® & drove a car from London to Mongolia raising money to buy 10,000 books for underprivileged children in America. He also drove a vintage London taxi across America, giving free cab rides to the needy and working with Classwish to bring hope back to the schools of America.
Leon has documented his travels for numerous media outlets including:
•	Good Morning America, 
•	Los Angeles Times, 
•	San Francisco Chronicle, 
•	Outside, 
•	Good, 
•	Psychology Today, and 
•	The New York Times

His show The Kindness Diaries is streaming on Netflix! His books, Amazing Adventures of a Nobody, The Kindness Diaries and Live, Love, Explore: Discover the Way of the Traveler a Roadmap to the Life You Were Meant to Live, published by Readers Digest, are in stores now.

**Comment by christoball** [comment]
Promo materials link
https://drive.google.com/drive/folders/1-B2-bdeYYDoRZapLhYtVlwTKCuptprv8

**Comment by christoball** [comment]
@KCMack Draft article here: https://preview.tnris.org/ellwood/2dbec36b776f7438282758c63ddcc8df4140c000/news/2019-06-11/forum-keynote-leon-logothetis-host-kindness-diaries/

**Comment by KCMack** [comment]
Looks great!

**Comment by christoball** [comment]
resolved in a0381b2c61a3c2097cc678478dd4b1f529745beb
