### ISSUE TITLE
Training Pages Update

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1754]
Please update the training schedule page
New date - August 9, 2019  for Collector and Survey 123 for ArcGIS - Field Data Collection

Change status for Introduction to Programming  ArcGIS Pro with Python from OPEN to CLOSED

The spreadsheet has been updated.

Thank you.

**Comment by christoball** [comment]
training and front page has been updated

resolved in 2775e79655b757ede0c2e1ff77552a4d9a4a4054
