### ISSUE TITLE
Update the website front page and more

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1755]
Update with the following courses:
June 11-12 Introduction to R for Data Visualization
July 22-23  ArcGIS Pro Quick-Start for the GIS Professional

Please remove the June 13-14 ArcGIS Pro Quick-Start for the GIS Professional.  It has been crossed out of the spreadsheet.

**Comment by christoball** [comment]
Preview of updated front page here: https://preview.tnris.org/ellwood/974d5397531e032532807ef7142f49c27a54e4c6/

**Comment by christoball** [comment]
resolved in a7312a1c934c8185305e79d626438b427985492f
