### ISSUE TITLE
Forum Call for Papers

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1757]
Please add Call for Papers to the website front page .  Here's what we have sent to everybody.
[Texas GIS Forum 2019 - Call for Presentations Now Open!.pdf](https://github.com/TNRIS/tnris.org/files/3266452/Texas.GIS.Forum.2019.-.Call.for.Presentations.Now.Open.pdf)

**Comment by christoball** [comment]
resolved in a7312a1c934c8185305e79d626438b427985492f
