### ISSUE TITLE
Update GIO Calendar of Events

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1758]
Please remove past events, add the following:

June 18, 2019
North Texas Career Mixer
5:00PM
Green Gator, Las Colinas, TX
Event Link: https://urisatexas.org/event-3394080

June 20, 2019
North Texas SCAUG/ETUG User Group Joint Meeting
9:00AM-1:00PM
City of Paris Council Chambers
Event Link: https://scaug.org/event-3411148

Also, please update the GIS Community Meeting location to:
Texas Health and Human Services Commission
Brown-Heatly Building Rm 1420
4900 N. Lamar Blvd.
Austin, TX 78751
[campus.pdf](https://github.com/TNRIS/tnris.org/files/3266779/campus.pdf)

**Comment by christoball** [comment]
updated and resolved in 17b08e6fe28a9d02411860edbd77b17bc449c72f
