### ISSUE TITLE
No Refunds on RDC Pricing Page

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/tnris.org#1759]
Hey @christoball, can we add a short disclaimer on the RDC pricing page stating that we do not allow refunds.

Technically, because all of our data is free, customers are paying for the service of bulk data processing, printing, customizing, etc...

Thank you!

**Comment by christoball** [comment]
@LaurenKirk can you draft an idea of how you think it should be phrased?

**Comment by LaurenKirk** [comment]
@christoball see below (also, please format as you see fit):

Please note: TNRIS does not offer refunds for services rendered.  All data is available through the Public Domain at no cost.  All applicable fees are associated with the cost of data reproduction.

Let me know if you need anything else, thank you!!

**Comment by christoball** [comment]
added the language to the site

resolved in c6245ac82ce1802244a7fdb7e704aa90e7d14359
