### ISSUE TITLE
Notice about suspended courses and available online training

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#176]
[Notice from TNRIS Training.docx](https://github.com/TNRIS/tnris.org/files/4344422/Notice.from.TNRIS.Training.docx)

Please post

**Comment by christoball** [comment]
Hey, so I'm seeing that the courses in May are still available? Should  this be more specific to say that courses are suspended for the time being?

**Comment by KCMack** [comment]
Yes, that will work.  My rationale for keeping them open is that if people want to register, I’d want them to with the thought that we’ll be able to be at work by May and subsequent months.

Sorry for the late response – was working on my spreadsheet.

Thanks for making this happen and for asking great questions.

Stay healthy,
Kathleen

Kathleen C. Mack
Operations Manager
Texas Natural Resources Information System
A division of the Texas Water Development Board
Phone 512.463.4536


[cid:image002.png@01D5FD18.9F3BB370]

**Comment by christoball** [comment]
@KCMack see article preview here:
http://razor-wire.tnris.org/news/2020-03-17/tnris-training-suspended-providers-still-hold-online-courses/

See education page preview here:
http://razor-wire.tnris.org/education/

**Comment by KCMack** [comment]
Looks really, really good Chris.
