### ISSUE TITLE
2016 lidar acquisition project

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1760]
does this page still serve a purpose? https://tnris.org/2016-lidar-acquisition-project/
or this https://tnris.org/2017-lidar-acquisition-project/

It has information about projects that have been delivered.
should it be removed or updated with current ongoing projects?

i found it [here](https://www.google.com/search?q=tnris+lidar+projects&oq=tnris+lidar+projects&aqs=chrome..69i57.5175j0j7&sourceid=chrome&ie=UTF-8).

**Comment by christoball** [comment]
deleted these pages for now
resolved in fdc4ad573b440581ad845bae1bcda82665a93f24
