### ISSUE TITLE
data release:  2016-2018 USGS Lidar Data

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1761]
News article for 5 new USGS lidar collections.
#1712 
#1713
#1714
#1715
#1716

**Comment by ThorTheDestroyer** [comment]
---
title: 2016-2018 USGS Lidar Data Release 
author: Joey Thomas, StratMap
template: news.html
mainimage: static/images/updates/2019/2018_coastal_lidar_release_banner.jpg
thumbnail: static/images/updates/2019/2018_coastal_lidar_release_th.jpg
thumbalt: A thumbnail for 2016-2018 USGS Lidar Data Release 
abstract: A collaborative initiative by federal agencies to capture high-quality lidar data for several regions of Texas.
---

The Texas Natural Resources Information System (TNRIS) is pleased to announce the release of ~35,000 square miles of recently acquired high resolution lidar data for five federal agency collections from 2016-2018. Aerial collection took place during the leaf-off season in Texas.

The primary purpose of these projects was to develop consistent and accurate USGS Quality Level 2 (QL2) elevation datasets from high-accuracy lidar.

Details regarding these acquisitions can be found by downloading the supplemental reports found in the datahub entries listed below. 





## Data Access





<div class="media">
  <div class="media-left">
    <a class="btn btn-lg btn-tnris" href="https://data.tnris.org/collection/b5bd2b96-8ba5-4dc6-ba88-d88133eb6643"><img style="width: 20px; margin-bottom: 0 !important;" src="{{m.link('static/images/icons/baseline_view_comfy_white_36dp.png')}}"> Launch DataHub</a>
  </div>
  <div class="media-body">
    <p>To download the Upper Coast lidar data products, please use the [DataHub](https://data.tnris.org/collection/b5bd2b96-8ba5-4dc6-ba88-d88133eb6643).</p>
  </div>
</div>

<div class="media">
  <div class="media-left">
    {% include "./partials/order-button.html" %}
  </div>
  <div class="media-body">
    <p>Lidar data and the associated geospatial products for this project are available for the cost of reproduction through the TNRIS Research and Distribution Center (RDC) and the <a href="https://data.tnris.org">Data Download</a></p>
  </div>
</div>



## Coverage Area

View coverage areas in the interactive map below:

<iframe width="100%" height="520" frameborder="0" src="https://tnris-twdb.carto.com/u/tnris/builder/f4af476f-dae0-49a4-b3e9-a12399020c77/embed" allowfullscreen webkitallowfullscreen mozallowfullscreen oallowfullscreen msallowfullscreen></iframe>

Please see our [Lidar status map](https://tnris-twdb.carto.com/u/tnris-sm/builder/a5dfc759-9a90-4acd-a8d1-57d521c7e1fe/public_map) for statewide lidar coverage.


## PRODUCTS
- Classified all-return lidar  in LAS 1.4 format
- Bare-earth digital elevation model (DEM) in .img format (1-meter)
- Lidar intensity images in GeoTIFF format (1-meter)
- Hydro-flattening breaklines in SHP or Geodatabase
- Project-level FGDC metadata in XML

## PRODUCT SPECIFICATION
These lidar collections were all collected at the [USGS Lidar specification Version 1.2](https://pubs.usgs.gov/tm/11b4/Version1.2/tm11-B4.pdf).

- **Projection Specifications**
  + Horizontal projections are in UTM NAD83 (2011) Zone 14 & Zone 15
  + Vertical projection is NAVD88 Geoid 12B
  + Units are in meters denoting orthometric heights

**Comment by ThorTheDestroyer** [comment]
Here are some graphics for the banner. 
![Website_Banner_graphic](https://user-images.githubusercontent.com/8398036/59447779-74db9000-8dc9-11e9-85f3-8841c60139ff.jpg)

**Comment by christoball** [comment]
@ThorTheDestroyer can each collection be a different color on this map?

**Comment by ThorTheDestroyer** [comment]
![Datarelease_graphic_colored](https://user-images.githubusercontent.com/8398036/59620155-c3529c80-90f1-11e9-81e5-928e41455bb6.jpg)

**Comment by ThorTheDestroyer** [comment]
![Datarelease_graphic_colored-counties](https://user-images.githubusercontent.com/8398036/59620204-e7ae7900-90f1-11e9-8007-67dc23e4fee6.jpg)
@christoball  here are colored versions

**Comment by ThorTheDestroyer** [comment]
![Pointcloud_USGS_release3d](https://user-images.githubusercontent.com/8398036/59620265-09a7fb80-90f2-11e9-8925-ef2d0664c81a.jpg)
And here is the other one i forgot to include the other day.

**Comment by mitchellryant** [comment]
@christoball @ThorTheDestroyer does it make sense to hold off on the news article till #1766 is completed?

**Comment by christoball** [comment]
@ThorTheDestroyer @mitchellryant preview of article so far. I plan to add each dataset listed in some way.

https://preview.tnris.org/haish/515eab10b7e765b268dc42329f4acd7597a1e759/news/2019-06-12/2016-2018-usgs-lidar-releases/

**Comment by mitchellryant** [comment]
increasing spacing between DataHub button and sentence.
collection dates on graphic are incorrect.

**Comment by christoball** [comment]
@mitchellryant is this correct?

![usgs_2016_2018_collections](https://user-images.githubusercontent.com/1877550/59695288-9c5aa000-91af-11e9-8fd6-53460473efc2.jpg)

**Comment by mitchellryant** [comment]
yes. that is correct

**Comment by ThorTheDestroyer** [comment]
Looks good,  on the datahub link, do we just want to do something like this instead of listing them all separately? 

https://data.tnris.org/catalog/%7B%22filters%22%3A%7B%22category%22%3A[%22Lidar%22]%7D%2C%22search%22%3A%22USGS%20FEMA%22%2C%22sort%22%3A%22AZ%22%7D

I know the Neches pops up in there as well, but its close enough.

**Comment by christoball** [comment]
@ThorTheDestroyer if this works for you I think its a good approach

**Comment by ThorTheDestroyer** [comment]
Works for me.

**Comment by christoball** [comment]
article finalized and pushed to production

resolved in 259cc30cee7b9fa226b5b2619fe5648b35d7068d
