### ISSUE TITLE
2019 Forum Sponsorships

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1763]
Please update the Forum website with Sponsorship pages.  All sponsor content from 2018 is the same for 2019 except:
Exhibitor Only $1,750 - limit 10

Includes: 10X10 exhibit space (with electricity), draped table, 2 chairs, trash receptacle, and wireelss internet access.

The last sentence under this category should read:
Exhibitor Only option is reserved for government agencies, educational institutions, or small businesses, start-up companies with less than 25 employees, $2 million in annual revenue, or have been in existence for less than two years

A`La Carte Options
Co-sponsor the Forum Social - $1,000
We don't have the social venue set yet.

Name Tag Lanyards: $500
Or provide your own lanyards with your company logo

let me know if you have questions

**Comment by christoball** [comment]
@KCMack do you have the registration link?

**Comment by christoball** [comment]
Preview of sponsors page. Just needs to 2019 sponsor registration link after any other edits to go live:
https://preview.tnris.org/ellwood/a31a435e25ab376d2993e5d31cde3ccadc168810/texas-gis-forum/2019/sponsors-and-exhibitors/

**Comment by christoball** [comment]
@KCMack We also need updated sponsor rules and regulations

**Comment by christoball** [comment]
Resolved in c52def1b87e1da5e835eecc1ef5cc89d960bf59c
