### ISSUE TITLE
Sponsor/Exhibitor Rules and Regulations

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1769]
Please add this PDF 
[Rules and Regulations 2019 FINAL.pdf](https://github.com/TNRIS/tnris.org/files/3308052/Rules.and.Regulations.2019.FINAL.pdf)
to the sponsor page

**Comment by christoball** [comment]
resolved in c52def1b87e1da5e835eecc1ef5cc89d960bf59c
