### ISSUE TITLE
2019 Forum Workshops page

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1770]
Create page for 2019 forum training

**Comment by christoball** [comment]
Preview page here: https://preview.tnris.org/ellwood/ac9a60881e882a3e14302590a178613f7bb68653/texas-gis-forum/2019/workshops/

**Comment by christoball** [comment]
Comment on other issue
"Please refresh the page. Changes were made to the spreadsheet."
- @KCMack

**Comment by KCMack** [comment]
![Teresa Howard](https://user-images.githubusercontent.com/4912083/59937369-e04fde00-9417-11e9-98a7-c857568021d2.jpg)
Teresa Howard Monday @ 8:00 and Tuesday @ 8:00 

![2014-11-01_Sean_Moran_Head_Shot](https://user-images.githubusercontent.com/4912083/59951313-26b83380-943e-11e9-991b-c0296de59bba.jpg)
Sean Moran  Tuesday afternoon 1:00 - 5:00 pm

The spreadsheet has again been updated, please refresh the preview.

**Comment by christoball** [comment]
Latest preview:
https://preview.tnris.org/ellwood/67d8e1125df128b112001fa2dd613efe25981679/texas-gis-forum/2019/workshops/

**Comment by christoball** [comment]
Another preview with more instructor photos added:
https://preview.tnris.org/ellwood/87d1a0a1520c8fd9d14145ae2d99b7ecca2dfe1c/texas-gis-forum/2019/workshops/

**Comment by KCMack** [comment]
Looks great!  Please publish this page on Thursday, June 27

**Comment by KCMack** [comment]
Forum Registration link
events.eply.com/2019GISForumRegistration

**Comment by KCMack** [comment]
Forum Registration Rates:

 

  | Before Sept. 20 | Sept. 23 - Oct. 11 | Onsite | One Day
-- | -- | -- | -- | --
Government | $295 | $325 | $375 | $200
Industry | $345 | $375 | $425 | $250
Student | $50 | $50 | $50 | $25

**Comment by christoball** [comment]
resolved
