### ISSUE TITLE
Close Call for Presentations on June 21 

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1772]
At the end of your work day tomorrow, please Close the Call for Papers:

Under Submission - 

Replace   Deadline for presentation submission has been extended! 
With  Presentation Abstract Submission is CLOSED
And,
Remove the link to submit a presentation proposal

**Comment by KCMack** [comment]
It is probably safe to close the submission link.

**Comment by christoball** [comment]
closed it 

resolved in faf84b69e0749e7944634dab7409897b534a7bab
