### ISSUE TITLE
Photos for Workshop Instructors

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1773]
![ClaireDeVaughan](https://user-images.githubusercontent.com/4912083/59887398-cdda9380-9388-11e9-8bb1-4e8db17b41cb.JPG)   Monday at 1:00 The National MAp

![ep](https://user-images.githubusercontent.com/4912083/59887417-e3e85400-9388-11e9-8ea9-5ed88d4fb79e.png)  Eric Pimpler Monday at 1:00  USing R to Visualize US Census Data

![Brian_King cmyk (002)](https://user-images.githubusercontent.com/4912083/59887452-febac880-9388-11e9-9f2d-7dd6f035df55.jpg)  Brian King  Tuesday at 8:00 GISP Update

**Comment by christoball** [comment]
see #1770
