### ISSUE TITLE
Preview Pre-conference workshops

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1774]
Please refresh the page.  Changes were made to the spreadsheet.

**Comment by christoball** [comment]
Please keep any comments on the current issue for this: #1170

**Comment by KCMack** [comment]
Please refresh the training page.  New content has been added.

Kathleen Clancy's head shot if presented.  

At this point, we have all but a better resolution head shot for Bill Hodge and and content from CARTO (which is a long shot).
![Kathleen Clancy](https://user-images.githubusercontent.com/4912083/60034133-877a8280-966f-11e9-945b-20af6c104279.jpg)

**Comment by KCMack** [comment]
Up
![BH photo jpg](https://user-images.githubusercontent.com/4912083/60037032-33bf6780-9676-11e9-9170-3706546edee0.png)
dated head shot Bill Hodge

**Comment by KCMack** [comment]
![Zena Pelletier](https://user-images.githubusercontent.com/4912083/60051963-cde4d700-9699-11e9-86d4-ff5bfff17309.JPG)
Zena  Pelletier   Tuesday @ 1:00 PM

![ClaireDeVaughan](https://user-images.githubusercontent.com/4912083/60052006-e8b74b80-9699-11e9-9f2e-fa4d6b0036d4.JPG)
Claire DeVaughan  Monday @ 1:00 PM

**Comment by christoball** [comment]
@KCMack this issue is closed please use issue #1770
