### ISSUE TITLE
Create 'Events' Page

### ISSUE THREAD

**Issue by gmullins** [TNRIS/tnris.org#1775]
I just noticed there is no Forum link at the top of our site. Is that by design? Seems like it could go under Programs or under a new one called Events. Same with GeoRodeo.

**Comment by christoball** [comment]
@gmullins thanks, these are good points. 'Programs' is getting kind of full, but we have been thinking about adding an 'Events' tab to the top nav to showcase this since they are prominent parts.

This is something that I plan to make happen soon

**Comment by christoball** [comment]
Turning this issue into the issue for the events page that will show all the Texas GIS Forum and the GeoRodeo pages. Will add 'Events' to top nav.

**Comment by gmullins** [comment]
:)

**Comment by christoball** [comment]
Been working on this recently and have it at a place to check out.

@KCMack @geochik @gmullins 
https://preview.tnris.org/glidden/1525d9ba44ed4de09d355c3bd9bed19870635851/events/

**Comment by geochik** [comment]
Excellent start! Having access to past events from one location is not only great for the community, but also for us. I think it's also a great selling point as we continue to promote our events.
Thanks so much for working on this!

**Comment by KCMack** [comment]
I like it a lot.  Good snapshot of programs.

KCM

Kathleen C. Mack, PMP
TNRIS Operations Manager
1700 N. Congress Avenue
Austin, Texas  78701
Kathleen.Mack@twdb.texas.gov
512 463-4536

**Comment by gmullins** [comment]
I love it too! Excited about this page.
A highlight or breakout section for Upcoming events?
Adding in GIS Community Meetings?

**Comment by christoball** [comment]
Latest version: https://preview.tnris.org/glidden/3dcd57d1061d1510ff8b10b0f4ecbe1978a8f2fd/events/

@gmullins to answer your questions
1. This page is meant for TNRIS hosted/produced events only. We may have enough events for a full calendar but I wouldn't want to include this at this point.

2. I've added the next upcoming GIS Community Meetings but don't think it needs a whole section like the others. The community meetings would not work the same way as the others with their own unique graphics etc, and we don't ahve pages for every past Community meeting.
-

**Comment by KCMack** [comment]
Looks good

**Comment by gmullins** [comment]
Agreed!

**Comment by christoball** [comment]
Resolved with recent update to API
