### ISSUE TITLE
update: lidar status map link 

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1777]
please update the lidar status map with the link below. 

https://tnris-twdb.carto.com/u/tnris/builder/03970fcc-1040-4819-a08b-30c139add308/embed

for the StratMap elevation page. 

https://github.com/TNRIS/tnris.org/blob/master/content/markdown/stratmap/elevation-lidar.md

**Comment by christoball** [comment]
updated link included in this commit, resolved in 2b68d5f3e7f3bf2a3127117bd8ad1e4d225fdceb

**Comment by ThorTheDestroyer** [comment]
Looks like we forgot the link in the paragraph next to the status map.  

Will you please update the link in the paragraph shown below as well? 

_Lidar coverage varies across the state. Lidar coverage and project details (date, nominal point spacing, vendor, etc.) can be found on the Lidar Status Map. All details about each dataset in our collection can be found in the supplemental reports for each project._

**Comment by christoball** [comment]
@ThorTheDestroyer Fixed it, working in this preview:
https://preview.tnris.org/ellwood/4d6b557ab29aaa49a30d912fe596e24cd2cb884e/stratmap/elevation-lidar/

**Comment by christoball** [comment]
@ThorTheDestroyer does it look good to go?

**Comment by ThorTheDestroyer** [comment]
Looks great. Thank you
