### ISSUE TITLE
Update Address Point website timeline

### ISSUE THREAD

**Issue by ilyannakadich** [TNRIS/tnris.org#1778]
@christoball Please update the address point website timeline as below:

April 2019
Over 4 million updated address points received

Fall 2019
Over 6 million updated address points received

Winter 2019
Over 9 million updated address points received and posted on DataHub

**Comment by christoball** [comment]
@ilyannakadich Does this look right?
https://tnris.org/stratmap/address-points/

**Comment by ilyannakadich** [comment]
@christoball Looks great!

**Comment by christoball** [comment]
@ilyannakadich thanks

resolved in 378fd332a0de84c290291779aba61ec5baf2ddbb
