### ISSUE TITLE
Update to GIO Events Page

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1780]
Hello Chris,

Please remove the expired events and replace with the following:

2019 ESRI UC SCAUG User Social
July 9, 2019
5:30 - 7:00 p.m.
San Diego Convention Center, Room 28C & Plaza Terrace (Upper Level) 
111 W Harbor Dr
San Diego, CA 92101
Event Site - https://scaug.org/event-3388449

NORTH TEXAS User Group Meeting
August 21, 2019
City of McKinney - City Hall, Council Chambers
222 N. Tennessee St. 
McKinney, Texas 75069
Event Site - https://www.nctcog.org/regional-data/geographic-information-systems-gis/meetings-classes _(not actually listed just yet)_

**Comment by christoball** [comment]
updated events, resolved in e954e9812f110a0303e0c7278327bd3080948c34
