### ISSUE TITLE
2019 Forum Registration Rates

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1782]
Please update the registration rates as follows:
         Before September 20 | September 23 -   October 11 | Onsite | One-Day
Government | $325 | $375 | $425 | $275

Industry | $425 | $475 | $525 | $325

Student | $50 | $50 | $50 | $25

**Comment by christoball** [comment]
Is there another registration link? The current one still says test mode.

**Comment by christoball** [comment]
updated and live

resolved in e1bc95558c3ce45d134d67f3826afab182b35f12
