### ISSUE TITLE
2019 Poster Gallery & Contest

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1783]
The purpose of the poster gallery is to promote and recognize the advances of map design, cartography, and GIS. The map gallery is open to all attendees and vendors. Attendees will have the opportunity to vote on each poster based on the following criteria:

Map design
Use of space
Subject matter
Communication
Creativity
Originality

Winners
The top 3 vote earners will be highlighted on the TNRIS website under the 'Latest News' section following the forum.

The top vote earner will also receive a small gift.

Physical Guidelines for Poster
Maximum size limit: 36” X 36”
Medium: Bond or Photo Paper
Submission Deadline: Friday, October 11th, 2019
Posters may be picked up after 2:00 pm on Thursday, October 24, 2019.

Posters will be displayed in the atrium of the J.J. Pickle Research Center.

Info and Mailing Address
Send us your basic information in the form on this page and mail your poster in order to arrive no later than the Oct. 11 deadline, to the following address:

Texas Natural Resources Information System
Attn: Erik O'Brian
1700 N. Congress, B-40
Austin, Texas, 78701

Submit Your Info
Please enter your information below if you plan on submitting a poster to the gallery. This information will be displayed along with your poster.

Name * 
Name
Email * 
Enter email address
Poster Title * 
Enter the poster title
Description * 
Enter a short description of the poster's contents
Phone 
Enter your phone number
Organization * 
Who are you affiliated with?

**Comment by christoball** [comment]
@KCMack Preview ready here: 
https://preview.tnris.org/ellwood/12cbc98cb8592b0a7fdf7d9b5055116b2fa91ea2/texas-gis-forum/2019/poster-gallery/

**Comment by KCMack** [comment]
Looks great!

**Comment by adambreznicky** [comment]
code merged via PR. closing.
