### ISSUE TITLE
GIS Forum  Registration is OPEN!

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1788]
Front Page item:
Texas GIS Forum Registration is Open!

Register for the[ Early Bird](https://tnris.org/texas-gis-forum/2019/) rates!

Add the Forum graphic to catch attention.

**Comment by christoball** [comment]
@KCMack preview ready here: https://preview.tnris.org/ellwood/69556b5278c2a2a63d14b4ee5eb4f776551f6f9a/

**Comment by KCMack** [comment]
It looks good.  Thanks.

**Comment by christoball** [comment]
closed in pr #1789
