### ISSUE TITLE
new TCEQ logo

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#179]
I received a new TCEQ logo from Jennifer Kirby.  We will need to update the logo on DataHub and maybe all over the tnris site.

![2CR-TCEQ](https://user-images.githubusercontent.com/8459928/77554180-bbdfd100-6e83-11ea-945b-f92da2c7cf64.png)

**Comment by christoball** [comment]
@mitchellryant I'll start going through and fixing this.

**Comment by jwhaney** [comment]
fyi, i've added this logo to the tceq external collection on datahub and made it the thumbnail.

realized now i need to resize the image so it looks like the other external entities. i'll take care of it.

**Comment by jwhaney** [comment]
refreshed materialized view and realize now i need to resize the image. oops, hah. i'll take care of it.

**Comment by adambreznicky** [comment]
i noticed it when i was doing datahub stuff a couple days ago. i didnt realize this issue existed so in that moment i resized it, put it on a grey background like the other agencies, and reuploaded.
sorry if i accidentally stepped on y'alls toes with it

**Comment by adambreznicky** [comment]
reopened since there are references to a tceq logo within tnris.org.
datahub has been updated but references to the logo across tnris.org need to be addressed.

**Comment by christoball** [comment]
I reuploaded the image as the same filename into the API and it works correctly across the site.
