### ISSUE TITLE
GIS Community Meeting Agenda

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1792]
The GIS Community agenda is ready for posting. Please also update the map link in the agenda. 
[GISComm_Agenda_20190416.pdf](https://github.com/TNRIS/tnris.org/files/3383982/GISComm_Agenda_20190416.pdf)
[HHSC_campus.pdf](https://github.com/TNRIS/tnris.org/files/3383983/HHSC_campus.pdf)

**Comment by christoball** [comment]
@geochik preview available here:
https://preview.tnris.org/ellwood/9291e8fbe04d7dd1699176233eb6fc7ff81cf7d5/geographic-information-office/

I don't really feel like there is a place to share the campus map. I think it's overkill to have it in addition to the address and linking to google on the agenda.

**Comment by geochik** [comment]
I hear ya about the campus map. It was more about being able to view the parking garage directly behind the building.

Preview approved!
