### ISSUE TITLE
GIO Calendar Update

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1795]
Please update the GIO events with the following:

August 5-9, 2019
The 2019 Council of Geographic Names Conference
Baton Rouge, LA
URL: http://cogna50usa.org/2019_Baton_Rouge.html

September 28-October 2, 2019
URISA GIS-Pro 2019
New Orleans, LA
URL: https://www.urisa.org/gis-pro

**Comment by christoball** [comment]
@geochik preview of updated calendar:
https://preview.tnris.org/ellwood/2c0c97f2b22e9b48938d70521374779901be25d1/geographic-information-office/

**Comment by geochik** [comment]
Reviews and approved!
