### ISSUE TITLE
Advanced ArcGIS Programming _Status Change

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1799]
Change the status for August 19 Advanced ArcGIS Programming with Python from OPEN to CLOSED

The spreadsheet has been updated

**Comment by christoball** [comment]
@KCMack preview ready here:
https://preview.tnris.org/ellwood/cc659898e93dc28f249ef0a28512d5f7ce301bc2/education/

**Comment by KCMack** [comment]
Thanks, it looks good.

kcm

Kathleen C. Mack, PMP
TNRIS Operations Manager
1700 N. Congress Avenue
Austin, Texas  78701
Kathleen.Mack@twdb.texas.gov
512 463-4536
