### ISSUE TITLE
Education Resources Page Marketing (for next school year)

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#180]
Ideas for marketing the Education Resources page, long term (beginning of next school year)
1) Banner on the TNRIS home page
2) Tweet from all accounts and have TWDB retweet
3) Story in the TWDB newsletter
4) Communication with Surrounding ISD's
5) anything else we can think of

**Comment by KCMack** [comment]
Thanks, Chris.

**Comment by jwhaney** [comment]
@KCMack do you think we can close this issue? if not, please provide some details as to how we can move it forward to completion. thank you.

**Comment by KCMack** [comment]
Yes, I think it's time to close this item.  It was a good idea then and may be a good idea in the future but since we've not moved on this since it was created, please close this issue.
