### ISSUE TITLE
Poster Contest

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1804]
please change the attention in the address for the poster contest to

Texas Natural Resources Information System
**Attn: Forum Poster Contest**
1700 N. Congress, B-40
Austin, Texas, 78701

on page https://tnris.org/texas-gis-forum/2019/poster-gallery/

**Comment by christoball** [comment]
@e00o @mitchellryant edited that, does it look good to go?
https://preview.tnris.org/ellwood/bdd65db4fa3bffa2e0bfc50f831e9ba0dcdc4454/texas-gis-forum/2019/poster-gallery/

**Comment by e00o** [comment]
Good to go.
