### ISSUE TITLE
Add sponsor to Forum website

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1811]
GeoComm has registered to sponsor at the Silver level.

Please add them to the site.

**Comment by christoball** [comment]
@KCMack preview ready.

Geocomm added:
https://preview.tnris.org/ellwood/a825dfb1b90b9aedb3fc68bd1d51c92465895936/texas-gis-forum/2019/

A La Carte updated:
https://preview.tnris.org/ellwood/a825dfb1b90b9aedb3fc68bd1d51c92465895936/texas-gis-forum/2019/sponsors-and-exhibitors/#additional-sponsors

**Comment by KCMack** [comment]
Both changes look great!
