### ISSUE TITLE
Additional sponsor

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1814]
CARTO has registered to be a sponsor in the a` la carte category.  They have committed to support the purchase of lanyards.  Their logo was approved by Chris yesterday.

Please note that the lanyard option has been taken.

**Comment by christoball** [comment]
@KCMack lanyard has been marked as claimed, preview here:
https://preview.tnris.org/ellwood/4e1d2ca5314407ca8fdc4f84a60d0338ecbb99d5/texas-gis-forum/2019/sponsors-and-exhibitors/

**Comment by KCMack** [comment]
looks great!

**Comment by christoball** [comment]
closed in #1819
