### ISSUE TITLE
Replace parcel report on website

### ISSUE THREAD

**Issue by ilyannakadich** [TNRIS/tnris.org#1816]
@christoball   Chris, AppGeo added the date to the title page of the original parcel study report and supplement.  I'm not sure of all of the locations of the hyperlink to these on the website.  Can you please replace them all with these versions with underscore date please?

M:\Admin\Projects\Statewide_Parcel_Initiative\Final Report\Texas Statewide Parcel Data Report - Supplement_date.pdf

M:\Admin\Projects\Statewide_Parcel_Initiative\Final Report\Texas_Statewide.Parcel.Data.Report_FINAL_date.pdf

**Comment by christoball** [comment]
@ilyannakadich they are in a few places but I replaced the files so they will be correct whereever.

You can see the updated versions in the GIO documents section:
https://preview.tnris.org/haish/0054dffdee3e0f62ac9aa6b69737b06c352fb455/geographic-information-office/#gio-reports

**Comment by ilyannakadich** [comment]
Looks good @christoball
