### ISSUE TITLE
Forum - Sanborn Silver Sponsor

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1821]
Please add Sanborn Map Company as a Silver Sponsor
And, Sanborn will sponsor the Wednesday breakfast

**Comment by christoball** [comment]
Sanborn added, and one wednesday breakfast marked as claimed. 

@KCMack preview available here:
https://preview.tnris.org/ellwood/105246d67fe2e0a90e4db4a6b5d83d06664e83d7/texas-gis-forum/2019/sponsors-and-exhibitors/

**Comment by KCMack** [comment]
Thank you, looks great!
