### ISSUE TITLE
Training page changes

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1824]
Please change the status from OPEN to CLOSED for the following courses:
Collector and Survey 123 for ArcGIS - Field Data Collection
ArcGIS Pro Quick Start for the GIS Professional
Geoprocessing with ModelBuilder for ArcGIS Pro

The spreadsheet has been updated.

**Comment by christoball** [comment]
@KCMack training updated on page and front page, preview here:
https://preview.tnris.org/ellwood/49b73aebdc744c908c868e0e35c693618fb456e9/education/

**Comment by KCMack** [comment]
Looks perfect!
