### ISSUE TITLE
StratMap Contracts page broken link fixes

### ISSUE THREAD

**Issue by gmullins** [TNRIS/tnris.org#1825]
Merrick Vendor Contract page
https://www.merrick.com/services/geospatial-services/

RazorTek Vendor Contract page
https://www.razor-tek.com/tx-dir-info

Thanks!!

**Comment by christoball** [comment]
@gmullins Links updated, preview here:
https://preview.tnris.org/ellwood/49b73aebdc744c908c868e0e35c693618fb456e9/stratmap/stratmap-contracts/

**Comment by gmullins** [comment]
Look good to me!

**Comment by christoball** [comment]
closed in #1827
