### ISSUE TITLE
Geocortex - Silver Sponsor

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1830]
Please add as Silver Sponsor

https://www.geocortex.com/wp-content/themes/latitude/images/logo.svg

**Comment by christoball** [comment]
@KCMack GeoCortex added to bottom silver sponsors. Preview here:
https://preview.tnris.org/ellwood/187d15e586a87d0493fa97b01cb2b1a6618d57cf/texas-gis-forum/2019/

**Comment by KCMack** [comment]
Thanks.  It looks great!
