### ISSUE TITLE
Upload 3rd Qtr GIS Community PPT

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1831]
**Please update GIO news with 3rd Qtr meeting slides.** The additional slide deck was a presentation by TxDOT and should also be included. The accompanying text is as follows:

Slides: Texas GIS Community Meeting 2019 3rd Quarter - The 3rd Quarter GIS Community meeting was held on July 23, 2019 at the Department on State Health Services. Michael Chamberlain of Texas Department of Transportation presented on a project his team is working on to correct geometric anomalies in the county boundary files they have used for years. Keith Owens of Fugro demonstrated the city of Austin in a 3D environment to assist emergency planners, managers, and decision-makers. Roll call notes are listed in Slide 16 notes section.
[GIS_QtrlyMtg3_2019_Final.pptx](https://github.com/TNRIS/tnris.org/files/3487521/GIS_QtrlyMtg3_2019_Final.pptx)
[TxDOTCountyUpdate.pptx](https://github.com/TNRIS/tnris.org/files/3487535/TxDOTCountyUpdate.pptx)

**Comment by christoball** [comment]
Combined into #1832
