### ISSUE TITLE
Update Past 4 GIS Community Notes Postings

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1832]
**Slides: Texas GIS Community Meeting 2018 3rd Quarter** - The 3rd Quarter GIS Community Meeting was held on July 24, 2018 at Texas Parks and Wildlife Department headquarters in Austin, TX. Roll Call notes are listed in Slide 13 notes section. Attendees were invited to give lightning talks. Notes on the talks can be found on Slide 14.

**Slides: Texas GIS Community Meeting 2019 1st Quarter** - The 1st Quarter GIS Community Meeting was held on January 15, 2019 at the Texas Commission on Environmental Quality in Austin, TX. Guest presenters were Traci Tracey of Esri - San Antonio and Ed Kelly of the Department of Information Resources. Slides are included where permission granted. Roll call notes are located in Slide 28 notes section.

**Slides: Texas GIS Community Meeting 2019 2nd Quarter** - The 2nd Quarter GIS Community Meeting was held on April 16, 2019 at the State Health and Human Services Headquarters in Austin, TX. Dr. Stacey Lyle, Assistant Professor of Practice at Texas A&M was presented on his current efforts to help create the new State Plane Coordinate System of 2022 (SPCS2022). Roll call notes can be found in Slide 77 notes section.

**Comment by christoball** [comment]
@geochik where are the slides for this?

**Comment by geochik** [comment]
[2018 3rd Quarter.docx](https://github.com/TNRIS/tnris.org/files/3493657/2018.3rd.Quarter.docx)
[2019 1st Quarter.docx](https://github.com/TNRIS/tnris.org/files/3493666/2019.1st.Quarter.docx)
[2019 2nd Quarter.docx](https://github.com/TNRIS/tnris.org/files/3493667/2019.2nd.Quarter.docx)

**Comment by christoball** [comment]
@geochik Do you have the roll call notes from the most recent?

**Comment by geochik** [comment]
Yes! Sorry for the oversight.
[2019 3rd Quarter.docx](https://github.com/TNRIS/tnris.org/files/3494466/2019.3rd.Quarter.docx)

**Comment by christoball** [comment]
resolved with recent updates to API
