### ISSUE TITLE
Update GIO Calendar 

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1833]
Remove:
- 3rd Quarter Meeting
- Geographic Names Conference

Add:
- Alamo Area GIS 3rd Annual Professional GIS Conference
  September 18-19, 2019
  Hilton San Antonio Hill Country
  9800 Westover Hills Boulevard
  San Antonio, TX 78251
  Website: http://www.aagis.org/conference/

- Texas GIS Forum
  October 21-25, 2019
  UT Commons Learning Center
  10100 Burnet Road
  Austin, TX 78753
  Website: https://tnris.org/texas-gis-forum/2019/

**Comment by christoball** [comment]
@geochik Is the forum the 4th quarter meeting? I think it should be highlighted as such in some way. See preview:
https://preview.tnris.org/ellwood/154bf1d55f403b99a1dafc0f3907ae6fabaee037/geographic-information-office/

**Comment by geochik** [comment]
Yes, yes! We should also add the same sentence to the 2019 3rd quarter summary text.

**Comment by christoball** [comment]
@geochik add which sentence?

**Comment by geochik** [comment]
"**_The Annual Texas GIS Forum Serves as the 4th Quarter Community Meeting._**"

**Comment by christoball** [comment]
Resolved in #1837
