### ISSUE TITLE
Status Change to Close

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1834]
Please update the status for the 8/20 class  Editing with ArcGIS 10
From: OPEN
To: CLOSED

the spreadsheet has been updated

**Comment by christoball** [comment]
@KCMack the spreadsheet still says open. I just want to make sure that its supposed to be closed or if anything changed.

**Comment by KCMack** [comment]
Sorry.  I closed it now in the spreadsheet.

**Comment by christoball** [comment]
@KCMack front training and CSV updated, preview here:
https://preview.tnris.org/ellwood/1c7568e979a6af3d7d6b3a032341e4c6cc03ecbd/education/

**Comment by KCMack** [comment]
Looks good.  Thank you.
