### ISSUE TITLE
StratMap lidar page typos

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1835]
In the first paragraph, temporal and terrestrial are spelled wrong(see below for reference of their location). 

Lidar - Light Detection and Ranging, is a remote sensing technique that utilizes light in the form of a rapidly pulsed laser to measure return distances from the Earth captured by a sensor at the source of the pulse. These combined pulse return measurements with additional spatial and **temporal** data recorded by the acquisition system(airborne or **terrestrial**) produce a three-dimensional(3-D), detailed representation of the shape of the Earth illuminating its surface characteristics.

**Comment by christoball** [comment]
@ThorTheDestroyer made that edit, preview here:
https://preview.tnris.org/haish/e8f15c60cc13d3e618f4d24690c2ecebf041ebdc/stratmap/elevation-lidar/

**Comment by ThorTheDestroyer** [comment]
Looks good, thank you.
