### ISSUE TITLE
Add Draft GIS Forum Agenda

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#1836]
Draft agenda for posting to GIS Forum page. Please mark clearly as "DRAFT" or "Pending Final Approval" or "Agenda subject to change"

[2019 Draft Web Agenda.docx](https://github.com/TNRIS/tnris.org/files/3494024/2019.Draft.Web.Agenda.docx)

Setting a due date of 8/15.

**Comment by christoball** [comment]
@KCMack Will there be HOLL courses this year? We usually highlight them like this:
![image](https://user-images.githubusercontent.com/1877550/63287360-c39d1e80-c27f-11e9-9f68-af66d5fdd820.png)

**Comment by KCMack** [comment]
Yes, there will be HOLL courses in the Balcones Room on Wednesday and Thursday.  I don't have the list of courses yet.  The way you have it listed looks terrific until the specific list arrives..

**Comment by christoball** [comment]
@KCMack @geochik @gmullins Forum web Agenda available for preview:
https://preview.tnris.org/ellwood/f3d288d36ded00894a5103b74a2d40fbd4a78606/texas-gis-forum/2019/agenda/

**Comment by geochik** [comment]
Looks good. I found one thing. There is a presenter name on Thursday in Li'l Tex, last session, 11:30-12:00.
![PresenterName](https://user-images.githubusercontent.com/7750220/63395998-3810b400-c38b-11e9-9950-a73684f095c3.JPG)

**Comment by KCMack** [comment]
Good catch!

I’ve not had a chance to review the preview, so I’ll be the back up plan after requesting the name be removed from this session.

Did you have any comments about the brevity or length of the presentation descriptions?

Hope you receive the information you want today.  Sending healing vibes.

KCM

Kathleen C. Mack
Operations Manager
Texas Natural Resources Information System
A division of the Texas Water Development Board
Phone 512.463.4536

[cid:image001.jpg@01D557FD.86DF2110]<https://tnris.org/texas-gis-forum/2019/>

**Comment by gmullins** [comment]
Strategic Mapping - Celebrating Successful Public and Private Partnerships

@christoball Please add the s to Partnerships

**Comment by christoball** [comment]
@KCMack @geochik @gmullins latest draft, look ready to go yet?
https://preview.tnris.org/ellwood/2f0a0d054a298d083b5257eece2e2289ca7b0bd5/texas-gis-forum/2019/agenda/

**Comment by gmullins** [comment]
There's a < here: <Moderated by...

Does the GIS Leadership abstract text need to be there or popped out like the rest?

Are we going to provide presenter names? 

I don't understand 'City Smarts GIS' Should it be 'Smart Cities GIS'?

Can we change this _Parcels, Address Points, Future Lidar Roadmap, Texas Orthoimagery Program, Texas Imagery Service, and the National Agriculture Imagery Program_ to
this _Land Parcels, Address Points, Lidar Roadmap, Statewide Imagery_

**Comment by christoball** [comment]
@gmullins 
- I'll fix that
- The short descriptions are ket for the bigger sessions and keynotes
- We aren't providing presenters yet.
- I think it should be GIS City Smarts, if it's trying to play off the phrase 'city smarts'. 
- changed it

**Comment by gmullins** [comment]
@christoball Thanks for all! I need to educate myself on the 'city smarts' phrase :) No other comments/suggestions from me. I think it's ready to go.

**Comment by KCMack** [comment]
Comment about the use of caps versus lower case.  Think we need to be consistent on the program even though the content provided was not consistent.
