### ISSUE TITLE
Add workshop to Forum training

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1838]
Please add JD Godchaux's workshop content to the website.  Date/time Tuesday 1:00 - 5:00  The spreadsheet has been updated.

![JDG_headshot](https://user-images.githubusercontent.com/4912083/62895869-6fd98500-bd15-11e9-9468-77648215d180.jpg)

**Comment by christoball** [comment]
@KCMack workshop added, preview here:
https://preview.tnris.org/ellwood/0a4309bf2cd4d8e98f5735ef9946ebc52423aaaf/forumtraining2019/exploring-spatial-data-science-analysis-and-workflows-in-python/

**Comment by KCMack** [comment]
Looks good, but in the last sentence after laptop, the word environment is misspelled.  Please correct it.

**Comment by christoball** [comment]
@KCMack I'll fix it, the typo is on the spreadsheet.

**Comment by KCMack** [comment]
Thank you.  The error is mine alone.

**Comment by christoball** [comment]
@KCMack fixed it should be ready to go:
https://preview.tnris.org/ellwood/b400c5c8236d5da53591c0a584bd116f8f8d9854/forumtraining2019/exploring-spatial-data-science-analysis-and-workflows-in-python/

**Comment by KCMack** [comment]
Terrific.  Thank you.
