### ISSUE TITLE
Sponsor update 8.13.19

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1839]
Please move Tyler Technologies from Exhibitor to Silver Sponsor.

**Comment by christoball** [comment]
@KCMack Tyler added, preview here:
https://preview.tnris.org/ellwood/3e530c6227e5e71943cbc4524ec443f808b72d5a/texas-gis-forum/2019/

**Comment by KCMack** [comment]
Thank you.  Look great
