### ISSUE TITLE
Map updates

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1840]
please change the url for these maps on the following pages, 

https://tnris.org/news/2018-04-30/lidar-release-jefferson-liberty-counties/
https://tnris-twdb.carto.com/u/tnris/builder/1f82d0b8-4936-4ea7-af1e-4086b9181422/embed

https://tnris.org/news/2018-04-02/lidar-release-central-texas/
https://tnris-twdb.carto.com/u/tnris/builder/525a47fe-4e54-4a4a-a074-449aa3022c48/embed

https://tnris.org/contact/
https://tnris-twdb.carto.com/u/tnris/builder/ee67fbf1-5028-4d82-a082-b4bcfd626ee0/embed

**Comment by christoball** [comment]
@mitchellryant previews ready:

### Jefferson Liberty
https://preview.tnris.org/ellwood/3e530c6227e5e71943cbc4524ec443f808b72d5a/news/2018-04-30/lidar-release-jefferson-liberty-counties/

### Central Texas
https://preview.tnris.org/ellwood/3e530c6227e5e71943cbc4524ec443f808b72d5a/news/2018-04-02/lidar-release-central-texas/

### Contact Page
https://preview.tnris.org/ellwood/3e530c6227e5e71943cbc4524ec443f808b72d5a/contact/

**Comment by mitchellryant** [comment]
@christoball looks great and thanks for correcting my mistake.
