### ISSUE TITLE
Beta QC - Land Parcel page

### ISSUE THREAD

**Issue by ilyannakadich** [TNRIS/tnris.org#1848]
- Hyperlinks in FAQ section not working.

- Hyperlink for parcel study report does a download rather than a preview (like the GIO report)

**Comment by adambreznicky** [comment]
resolved via commit c6f9a6e584477c416f563920a824082f97de137b
hyperlinks added to faq as is prod
'Content-Type' for the parcel study pdf was incorrect from the admin console upload. it has manually been adjusted to 'application/pdf' and an issue created in the api.tnris.org repo to enhance the upload function to handle this in the future
