### ISSUE TITLE
Education and Training Contact form

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#185]
education contact added to the API and the API has been redeployed. 
all it needs now is the front end form added.

copy the general contact form and change the "form_id" to "education" from "contact"

this contact from for should be on the following pages.
https://tnris.org/education/
https://tnris.org/education/teachers/
https://tnris.org/education/purchasers/
https://tnris.org/education/course-cancellations/

**Comment by geochik** [comment]
@christoball Please remove text above contact button -"We encourage teachers and students to reach out to us with any suggestions or questions." 
We aren't ready for "suggestions" and really we aren't ready for questions. We will see how it goes with a simple "contact us" button. Thank you!

**Comment by christoball** [comment]
@geochik why are we putting it on the page then? What's the reason for having a contact button if people can't ask questions? Just to have comments? How is a comment different from a suggestion? Not trying to be difficult but I don't really see why we should have a contact button on here if we don't want their questions or comments.

@mitchellryant I don't follow what is being suggested here. I haven't discussed with anyone putting the contact form on each of those pages, only a button. My proposal was that 'education' should be one of the radio options on the general contact form. Having the forms on each page would involve redesigning, but also, I don't think they should have fillable forms on each of these pages.

**Comment by ghost** [comment]
@christoball i think it is easier for the user to get to the contact form directly from the page they are on. There is still a lot of confusion on what radial button we use. We do this on [Texas Imagery Service page](https://tnris.org/texas-imagery-service/) and the [Order Maps Page](https://tnris.org/research-distribution-center/custom-maps/).

the button that loads a new page with the form, like the way the links above work.

![contact](https://user-images.githubusercontent.com/8459928/78580573-33085400-77f8-11ea-8101-c18a96a6c189.PNG)

Even adding a new radial button on the General Contact page requires a new form. There may be some angular JS logic tied to radial buttons.

This new form allows for better assignment in the ticketing system. The ticketing system filters are based on Email Subject or Collection ID, it is the best most unique way to accomplish the filtering (auto-assignment).

**Comment by christoball** [comment]
@mitchellryant thanks for making it clearer - that makes more sense to me. Ill move forward with that stuff.

**Comment by geochik** [comment]
@christoball 
How much longer before this ticket can be addressed and closed?

**Comment by christoball** [comment]
@geochik focusing on finishing it today

**Comment by christoball** [comment]
@mitchellryant I've added a contact form for education that can be seen here:
http://ellwood.tnris.org/education/contact/

Is this where you meant 'education' should be put as the ID?

{{form.before("education")}}
  {{form.input("Name", "Name", "text", true)}}

**Comment by christoball** [comment]
@mitchellryant i didn't see where form_id is in relation to the code

**Comment by adambreznicky** [comment]
@christoball that's correct, the form_id goes in the form.before() macro
`{{form.before("< form_id >")}}`

**Comment by christoball** [comment]
@adambreznicky thanks.

I sent a test form, and @geochik just sent back a reply telling me she got it. I'm going to go ahead and merge.

**Comment by ghost** [comment]
@christoball i would like the button to be on the main education page, and the k-12 page. to streamline the contact process

**Comment by christoball** [comment]
@mitchellryant i've added it to all education pages now:
http://ellwood.tnris.org/education/

**Comment by ghost** [comment]
@christoball thank you.
