### ISSUE TITLE
Beta QC - Address Point contact

### ISSUE THREAD

**Issue by ilyannakadich** [TNRIS/tnris.org#1850]
Can we add some verbiage to guide users to visit the program page before submitting a question?  Often the questions asked are answered on the program page and the user may not be aware of it if they came through the DataHub page.

https://data.tnris.org/collection/c56ff69b-efe7-46e7-89c7-43e655188382

Current:
"For questions about the Address Points dataset, please complete the form below. Orders for this data cannot be submitted via this form. To order this dataset, please visit the Order tab."

Recommendation:
"Please visit the Address Points program page at https://tnris.org/stratmap/address-points/ for program details and FAQs.  For questions about the Address Points dataset, please complete the form below. Orders for this data cannot be submitted via this form. To order this dataset, please visit the Order tab."

**Comment by adambreznicky** [comment]
unfortunately, no we cannot. the verbiage used on said contact form in datahub is templated and is applied to every dataset equally. one-off customization for the dataset is currently out of scope. we apologize for the inconvenience. 

we suggest putting your recommended language into the dataset description. you can update the description for your dataset by logging into the api.tnris.org admin console and editing it under the "Dataset Collections" section
