### ISSUE TITLE
Beta QC - Land Parcels contact

### ISSUE THREAD

**Issue by ilyannakadich** [TNRIS/tnris.org#1851]
Can we add some verbiage to guide users to visit the program page before submitting a question?  Often the questions asked are answered on the program page and the user may not be aware of it if they came through the DataHub page.

https://data.tnris.org/collection/2679b514-bb7b-409f-97f3-ee3879f34448

Current:
"For questions about the Land Parcels dataset, please complete the form below. Orders for this data cannot be submitted via this form. To order this dataset, please visit the Order tab."

Recommendation:
"Please visit the Land Parcels program page at https://tnris.org/stratmap/land-parcels/ for program details and FAQs.  For questions about the Land Parcels dataset, please complete the form below. Orders for this data cannot be submitted via this form. To order this dataset, please visit the Order tab."

**Comment by adambreznicky** [comment]
unfortunately, no we cannot. the verbiage used on said contact form in datahub is templated and is applied to every dataset equally. one-off customization for the dataset is currently out of scope. we apologize for the inconvenience. 

we suggest putting your recommended language into the dataset description. you can update the description for your dataset by logging into the api.tnris.org admin console and editing it under the "Dataset Collections" section
