### ISSUE TITLE
Beta QC-StratMap Lidar page

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1853]
I'm thinking we should either remove or change the below language.

### StratMap Lidar Datasets
All lidar datasets are available at reproduction cost through our Research and Distribution center. They can be obtained by visiting the DataHub.

Maybe we can change it to something along the lines of the below edit.
 
### Bulk Copies of StratMap Lidar Datasets 
Bulk copies of all lidar datasets are available at reproduction cost through our Research and Distribution center. Copies to hard drives can be requested through the DataHub.

**Comment by ThorTheDestroyer** [comment]
All links, graphics and text look  good on the page.

**Comment by adambreznicky** [comment]
resolved via commit e84a248d69a15dba98556b95581c39600433ff4b
