### ISSUE TITLE
GIS Community Meeting - Qtr 2

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#186]
@christoball 
Please create a new title slide for the 2nd Quarter GIS Community Meeting. Also, please remove the scan code in the upper right corner. The meeting date is April 30, 2019. 
The body template will also require updating to reflect 2nd quarter. 
Thank you!

**Comment by geochik** [comment]
@christoball 
I updated the GIO page and used the "Location:" field to enter the Webinar registration link and this happened.....
<img width="485" alt="Screen Shot 2020-04-09 at 6 11 32 PM" src="https://user-images.githubusercontent.com/7750220/78948431-ea69c880-7a8d-11ea-8ad7-74cfb76d88ec.png">

Can you fix? And maybe make it a "true" hyperlink on the page? THANKS!!

**Comment by christoball** [comment]
storing the link here, will have to do a few things to figure this out
https://attendee.gotowebinar.com/register/3231973054519613710

**Comment by geochik** [comment]
@christoball 
I could no longer wait for you to fix the link so I took care of it with Ryan's help.
Please complete the initial request by EOB Wednesday.

**Comment by christoball** [comment]
@geochik What do you think of using this for the title slide?
![virtualgismeetingslide](https://user-images.githubusercontent.com/1877550/79269909-cd087600-7e62-11ea-8da2-56d10691d6e5.jpg)

**Comment by christoball** [comment]
Graphics completed and issue resolved
