### ISSUE TITLE
Abstract for Tribal GIS

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1860]

**Comment by KCMack** [comment]
Session B, Thursday  morning Tribal GIS for Transportation Planning
The Texas Tribal Histories Project is an effort to better inform statewide transportation planning between TxDOT and the 27 Native American tribes that participate in consultation with TxDOT. This effort includes development of GIS datasets for natural resources and traditional cultural places that each participating tribe considers important or sensitive. Trails, settlement sites, and locations of culturally significant activities may also be included. 
The goal is to produce a geographic historical narrative of tribal presence in Texas for each participating tribal nation. Distribution of this data will be limited to the tribes, TxDOT, and consultants who have signed restricted-data access agreements.

**Comment by christoball** [comment]
combined into #1836
