### ISSUE TITLE
Sponsorship updates Exhibitors and A la Carte

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1862]
Add: 
Exhibitor -USGS Water Science Center 
Exhibitor - Tessellations

Both Wednesday and Thursday b'fast have been claimed

**Comment by KCMack** [comment]
Mark all Platinum Sponsorship claimed

**Comment by christoball** [comment]
@KCMack Sponsorship page updates - platinum marked as taken, added exhibitors in bottom sponsors:
https://preview.tnris.org/ellwood/2f0a0d054a298d083b5257eece2e2289ca7b0bd5/texas-gis-forum/2019/sponsors-and-exhibitors/

**Comment by KCMack** [comment]
Looks good.
Thanks
