### ISSUE TITLE
Beta - Texas Geographic Names Committee

### ISSUE THREAD

**Issue by pwblanton** [TNRIS/tnris.org#1864]
1. Uncapitalize the word "State" in the second line of the introductory sentence.
2. Spell out United States instead of abbreviating it in the third line of the introductory sentence. United States is spelled out throughout the rest of the document.
3.. Suggest starting the third paragraph with the acronym, "COGNA", instead of spelling it out, since you did that in the introductory sentence.

Thanks!
Patricia

**Comment by adambreznicky** [comment]
resolved via commit 3a1d64974d195fcb55cc1ae59d042fd6315c2ad6
