### ISSUE TITLE
Beta - Texas GIO page

### ISSUE THREAD

**Issue by pwblanton** [TNRIS/tnris.org#1866]
1. Insert "(TNRIS)" at the end of the first sentence, following "to be the Director of the Texas Natural Resources Information System.".
2. Spell out GIS in the second paragraph the first time it's used and add parentheses around (GIS). Both of these occur in the second paragraph, second sentence.
3. Suggest using the word 'accomplishes' in the second paragraph, third sentence instead of the word 'achieves'.
4. Under Richard Wade: don't spell out GIS and remove parentheses around (GIS).
5. Under the October 21-25, 2019 4th Quarter Community Meeting heading -- uncapitalize the word "Serves" in the header sentence.

Thanks!
Patricia

**Comment by adambreznicky** [comment]
resolved commit #1063bf20eb1bc042f35c93f3b92a7d65b529652c
