### ISSUE TITLE
Two additional Exhibitors

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1870]
Please add as Exhibitor level sponsor:

U.S. Geological Survey Texas Water Science Center
![image](https://user-images.githubusercontent.com/4912083/63616781-eeec7a00-c5ad-11e9-923d-64689b3ef374.png)

Miller Imaging & Digital Solutions
https://www.google.com/maps/uv?hl=en&pb=!1s0x8644cbf731c0b61f%3A0xafbee58c1b7bf091!2m22!2m2!1i80!2i80!3m1!2i20!16m16!1b1!2m2!1m1!1e1!2m2!1m1!1e3!2m2!1m1!1e5!2m2!1m1!1e4!2m2!1m1!1e6!3m1!7e115!4shttps%3A%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipMJaxSYny4FaNCOrPAWUEWdMa4q7Xo2ij6nbVsf%3Dw173-h175-n-k-no!5smiller%20imaging%20%26%20digital%20solutions%20-%20Google%20Search!15sCAQ&imagekey=!1e10!2sAF1QipMJaxSYny4FaNCOrPAWUEWdMa4q7Xo2ij6nbVsf#

**Comment by christoball** [comment]
@KCMack Exhibitors added to bottom sponsor section on forum site, preview here:
https://preview.tnris.org/ellwood/5aa8a6b3c0c8478b04151f35f8d24d1bf152dba8/texas-gis-forum/2019/
