### ISSUE TITLE
Formatting for Acquiring Agencies

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/tnris.org#1871]
The Historical Imagery Archive page has a number of acquiring agencies that need to have the formatting adjusted. Would like the name of agency to be above sample image (i.e. similar to USGS and GLO entries) 
![image](https://user-images.githubusercontent.com/23489372/63622210-ac319e80-c5bb-11e9-99af-2b35162d72e3.png)

**Comment by adambreznicky** [comment]
resolved via commit e1ddc154ec2d92a17c47ddbda6720b7de7ed17a8
