### ISSUE TITLE
2019 StratMap Lidar Projects

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1877]
https://github.com/TNRIS/tnris.org/blob/haish/content/markdown/news/2019-08-28_2019-Brown-County-and-Missouri-City-lidar-release.md

**Comment by mitchellryant** [comment]
https://github.com/TNRIS/tnris.org/issues/1844

**Comment by christoball** [comment]
@ThorTheDestroyer Got a first draft up and going. think I should make the main image show both datasets?

preview here:
http://haish.tnris.org/news/2019-09-06/2018-stratmap-lidar-releases-brown-county-missouri-city/

**Comment by mitchellryant** [comment]
@ThorTheDestroyer @christoball please remove carto link. it is the wrong area and we are not using carto for coverage maps anymore.

**Comment by christoball** [comment]
@mitchellryant i've removed the carto

@ThorTheDestroyer discussed doing a different version of the map that zooms into each respective area. Other than that here is the latest draft:
http://haish.tnris.org/news/2019-09-06/2018-stratmap-lidar-releases-brown-county-missouri-city/

**Comment by christoball** [comment]
@ThorTheDestroyer I updated the coverage map. If it looks good, i can move forward with publishing:
http://haish.tnris.org/news/2019-09-06/2018-stratmap-lidar-releases-brown-county-missouri-city/

**Comment by ThorTheDestroyer** [comment]
Looks good.
