### ISSUE TITLE
Update Land Parcels website

### ISSUE THREAD

**Issue by ilyannakadich** [TNRIS/tnris.org#1878]
@christoball , Please replace the intro on the Land Parcels website with the below verbiage.  I had FDR and GM review already.  I'm open to further input.  This is our short term (this week) solution for the new standardized version of data.  I will be working with you on the long term (before Forum) version in September.  Thank you!

In collaboration with stakeholders from across Texas, TNRIS created a statewide standardized GIS land parcel schema.  This format of land parcel information consists of the most commonly requested data.  Land parcel data contributed from county appraisal districts or their service providers were translated into this common schema and are now available on the TNRIS DataHub. 
Land parcels are boundaries that have associated information such as property owner, land use, value, and location attributes. This property information is recorded and maintained at the county level in Texas at local appraisal districts. Land parcels are used by public entities to make informed decisions on community planning, development, or emergency preparation and response. 
In August 2019, an extension of the statewide parcel study was published to evaluate the existence of GIS parcel data and barriers to conversion.  The report found that nearly all Texas appraisal districts now maintain a GIS parcel layer or are in the process of converting.  It includes recommendations of 1) how TNRIS can facilitate local GIS conversion and 2) how to continue success of the land parcel program.

**Comment by ilyannakadich** [comment]
Trying to not say attributes.  How about 

This format of land parcel data consists of the most commonly utilized information as determined by the land parcel committee.

**Comment by christoball** [comment]
@ilyannakadich latest preview below. 

https://preview.tnris.org/ellwood/8abc0538e0d9f835a8795083538f4ad77697a771/stratmap/land-parcels/

**Comment by ilyannakadich** [comment]
@christoball Looks great!  

Can you please hyperlink the report to this August 2019 report from AppGeo?  M:\SM\Parcels\AppGeo\Update on Digital Parcel Data in Texas_Final Version.pdf

**Comment by christoball** [comment]
@ilyannakadich I'm on my way out and won't be able to do that. @jwhaney or another member of the IS team may be able to help you while I'm gone.

In the future please include any documents that need to be uploaded or linked to when the issue is created and specify what text needs to link to it.

**Comment by ilyannakadich** [comment]
@christoball @jwhaney If it cannot be uploaded then please remove the hyperlink as it is pointed to the wrong document.  We can add it later - no problem.

**Comment by gmullins** [comment]
[Update on Digital Parcel Data in Texas FINAL 20190903.pdf](https://github.com/TNRIS/tnris.org/files/3575430/Update.on.Digital.Parcel.Data.in.Texas.FINAL.20190903.pdf)

**Comment by christoball** [comment]
This has been resolved with recent move to API. I've also updated the document link in the most recent commit 54abe1485ff69914624e918a2eadb6a547aaaaf2
