### ISSUE TITLE
2 Additional Exhibitors

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#1879]
Please add:
Austin Community College, GIS and Geospatial Engineering Departments

TeachMeGIS

**Comment by christoball** [comment]
@KCMack exhibitors added, preview here:
https://preview.tnris.org/ellwood/361a36ff00a8eaf6d977e6034ec2967525b87ef5/texas-gis-forum/2019/

**Comment by KCMack** [comment]
Any chance the ACC information can be on one line?  Or, maybe it's too long.

**Comment by christoball** [comment]
@KCMack yes, i've fixed that. Preview here:
https://preview.tnris.org/ellwood/b7c630b8f91e0e36fef29810c733f108ce38c693/texas-gis-forum/2019/

**Comment by KCMack** [comment]
Thank you very much!

**Comment by christoball** [comment]
resolved in 562c4ebbccf41c9b39d56c5f3004026c230f226e
