### ISSUE TITLE
TNRIS web  - online training update - TMG

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#188]
TeachMeGIS

Online courses are offered

April 23-25. GISP Exam Preparation Course

May 4-5 
Fundamentals of ArcGIS (ArcMap)

May 11-13
Python for Pro - Writing Scripts to Manipulate GIS Data

Contact TNRIS for more information
@christoball

**Comment by christoball** [comment]
@KCMack have you updated these in the api?

**Comment by christoball** [comment]
@KCMack I'm not sure what is being requested here.

**Comment by KCMack** [comment]
This update is for the article referenced on the News section, front page.

**Comment by KCMack** [comment]
May 4-5
Fundamentals of ArcGIS (ArcMap)
$960

May 11-13
Python for Pro - Writing Scripts to Manipulate GIS Data
$1440

**Comment by KCMack** [comment]
GISP $400
