### ISSUE TITLE
USACE 2018 Buffalo Bayou lidar

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#1882]
**Data**
- [ ] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer 
- [x] Data Processing [renaming file, data organization]  @ThorTheDestroyer
- [x] Creation of derivative products [hypso and metadata] @ThorTheDestroyer
- [ ] Quality Assurance @ThorTheDestroyer

**DataHub**
- [x] Create collection @mitchellryant
- [ ] Complete console collection form including metadata and description @ThorTheDestroyer 
- [ ] Create Images, place on Website Dir @ThorTheDestroyer 
- [x] Upload supplemental info (breaklines, reports, index) @ThorTheDestroyer 
- [ ] Crop\Upload Images @christoball 
- [ ] Review Description @pwblanton
- [x] Add resources  @mitchellryant 

**Download\Prod**
- [x] Move data to production shares @mitchellryant 
- [ ] Make collection public  @mitchellryant

**Comment by mitchellryant** [comment]
@ThorTheDestroyer collection has been created
