### ISSUE TITLE
Update count on land parcel website

### ISSUE THREAD

**Issue by ilyannakadich** [TNRIS/tnris.org#1884]
@christoball or @jwhaney Please update the count and status bar on the Land Parcel website to 232.  Also, please change the color on the Project Timeline of the Fall 2019 box to green.

**Comment by christoball** [comment]
@ilyannakadich preview ready we'll go ahead and get asap. I've updated the timeline color and the parcel study update document link.

http://ellwood.tnris.org/stratmap/land-parcels/

**Comment by ilyannakadich** [comment]
@christoball @jwhaney Approved!  Thank you :)
