### ISSUE TITLE
NAIP 2018-19

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1887]
Data
- [ ] Enter dataset on StratMap Incoming data xlsx sheet @gmullins 
- [ ] Route Data Shipment (copy data to TNRIS Projects share) @LaurenKirk 
- [x] Data Processing (renaming file, data organization) @mitchellryant
- [x] Creation of derivative products [compressed images] @mitchellryant
- [ ] Quality Assurance @LaurenKirk

DataHub
- [x] Create collection @mitchellryant
- [ ] Complete console collection form including metadata and description @gmullins 
- [ ] Create Images, place on Website Dir @gmullins  
- [ ] Upload supplemental info (breaklines, reports, index) @gmullins 
- [ ] Crop\Upload Images @christoball 
- [ ] WMS Link @mitchellryant 
- [ ] Review Description @pwblanton
- [ ] Add resources @mitchellryant

Download\Prod
- [ ]  Move data to production shares @mitchellryant
- [ ] Make collection public @mitchellryant

Publication
- [ ]  Data Story @gmullins  @christoball
- [ ] Final Publication @christoball @gmullins 
- [ ]  Inform TNRIS staff of data availability @gmullins

**Comment by mitchellryant** [comment]
@gmullins @LaurenKirk @csidenblad i have created a jp2s in both erdas and global mapper to 8:1 please check the quality, and hen we can compress the rest.

**Comment by gmullins** [comment]
@mitchellryant Thanks! I want to edit the incoming procedure above. It doesn't look like I can do that anymore.
