### ISSUE TITLE
Update expired StratMap Contracts

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#190]
@christoball  Per the email I CC'd you on, we need to somehow show the expired contracts in red in the chart as no longer available/active. I would like to at least keep all the company logo boxes but maybe gray them out or in the least remove their inactive DIR Vendor Contract page links. DIR has already taken their pages down. Eventually all of these will expire and be replaced by a brand new pool later this summer. Maybe that line about new pool coming soon could be bigger/enhanced.

Thx!

<img width="337" alt="Expired status" src="https://user-images.githubusercontent.com/4921113/79394550-6441fc00-7f3d-11ea-8725-7deab9cc2baa.PNG">

**Comment by christoball** [comment]
@gmullins how's this look?
http://haish.tnris.org/stratmap/stratmap-contracts/

**Comment by ghost** [comment]
@christoball Perfect. Thank you!
