### ISSUE TITLE
New Pagination for News Articles (bootstrap 4)

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#194]
Hi y'all, I need to request your help in updating a feature for the transition to Bootstrap 4.

Currently, on the News page, there is a 'newer' and 'older' button to go through the articles. In bootstrap 4, this UI is no longer supported. While we could still style it ourselves, I do like the new pagination in BS4, and would like to implement it if possible.

Currently, this is the code for this feature on the **news.njk** template:
```
{% if pagination %}
          <nav>
            <ul class="pager">
              {% if pagination.prev.preserved %}
                <li>
                  <a href="{{pagination.prev.preserved}}">
                    <span aria-hidden="true">&larr;</span> Newer
                  </a>
                </li>
              {% else %}
                <li class="disabled"><a href="#"><span aria-hidden="true">&larr;</span> Newer</a></li>
              {% endif %}
              {% if pagination.next.preserved %}
                <li>
                  <a href="{{pagination.next.preserved}}">
                    Older <span aria-hidden="true">&rarr;</span>
                  </a>
                </li>
              {% else %}
                <li class="disabled"><a href="#">Older <span aria-hidden="true">&rarr;</span></a></li>
              {% endif %}
            </ul>
          </nav>
        {% endif %}
 {% if pagination %}
```
I'd like to use the following CSS/HTML for this, but we would need to change up the numbers in the pagination (see BS's example page here: https://getbootstrap.com/docs/4.0/components/pagination/#alignment).

```
  <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1">Previous</a>
        </li>
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item">
          <a class="page-link" href="#">Next</a>
        </li>
      </ul>
    </nav>
```

I appreciate any guidance or help y'all can provide on this. The **feature/bootstrap4** branch is up to date with the work I've done so far.

**Comment by christoball** [comment]
the branch is actually **feature/bootstrap-4** (with the dash)

**Comment by JasonKleinert** [comment]
@christoball you'll need to perform a calculation to determine the number of pages needed for all the articles we have. Here is an example: `number of pages = Math.ceil(total number of articles / number of articles per page)`

**Comment by adambreznicky** [comment]
the current pagination is implemented via a metalsmith plugin ("metalsmith-paginate" in the package.json file). the assembly of the paginated news pages and and associated buttons occurs during the build/gulp process which is how it generates all the paginated content as separate static pages that _know_ about each other.

on a surface level, i think the upgrade to utilize bootstrap would probably require looping all the generated pagination pages ("/news" and "/news-#") within the template where you identified. in that loop, for each generated pagination page, add your bootstrap `<li>` items with the proper links populated for each of those pages. i haven't looked at the gulp process in awhile but there is an object passed to the template which has all the generated page info you'd use in the loop. can't know without some console logs during the build to show what objects/info is available and passed to the template

**Comment by adambreznicky** [comment]
no longer needed - removed all news older than 2019 (1 year before the current one). an alternative will most likely replace current pagination method during site rebuild in the future
