### ISSUE TITLE
TNRIS map store page

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#197]
Start brainstorming and mocking up a possible TNRIS map store that sells prints of interesting maps from collection.

**Comment by adambreznicky** [comment]
finance has approved online purchase handling. awaiting feedback from IT as per acceptable plugins/libraries which can be used. further coordination with finance & IT in conjunction as per the proper security and workflow protocols necessary for implementation. once knowing what tools are acceptable, we will have substance to work with to begin designing... closing until then.
