### ISSUE TITLE
Fixing Broken External Links

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#198]
Got a report of external links that aren't working from the siteimprove that Matt is running our site through. 

Will start going through them.

http://page.report/QualityAssurance/report.aspx?site_id=971430&report_logon_md5=2EC53DCDAC5556AEF063DBB3126830FC&group_id=11150047124&source=email

**Comment by christoball** [comment]
@mitchellryant what do you recommend doing for old carto maps in articles?

https://tnris.org/news/2015-11-09/lidar-data-release-middle-brazos-palo-pinto-fema-project/

**Comment by ghost** [comment]
- [x] 2014 Texas GIS Forum | TNRIS - Texas Natural Resources Information System
Broken link: http://www.merrick.com/ 

- [x] 2014-2016 FEMA Lidar datasets for Texas | TNRIS - Texas Natural Resources Information System
Broken link: https://tnris-twdb.carto.com/viz/a47e9bc6-2454-11e7-bcd5-0e3ebc282e83/public_map 

- [x] 2015 Lidar Data Release for Brazos County | TNRIS - Texas Natural Resources Information System
Broken link: https://tnris.cartodb.com/viz/9214a5fa-63b4-11e5-9475-0e73ffd62169/embed_map 

- [x] 2015 Lidar Data Release for Middle Brazos-Palo Pinto FEMA Project | TNRIS - Texas Natural Resources Information System
Broken link: https://tnris.cartodb.com/viz/d698a32c-87b6-11e5-9eed-0ecfd53eb7d3/embed_map 

- [x] 2015 Texas GIS Forum | TNRIS - Texas Natural Resources Information System
Misspelling: reknowned	

~- [ ] 2015 Texas GIS Forum Agenda | TNRIS - Texas Natural Resources Information System
Misspelling: organisations~	

- [x] 2016 GeoRodeo Recap and Highlights | TNRIS - Texas Natural Resources Information System
Broken link: https://karenmcgrane.com/2014/01/13/the-mobile-content-mandate/
Misspelling: responsbility	

- [x] 2016 Smith County Aerial Imagery Now Available | TNRIS - Texas Natural Resources Information System
Broken link: https://tnris.cartodb.com/viz/f0086f04-dafe-11e5-b1d2-0e674067d321/embed_map 

- [x] 2016 Texas GIS Forum - Job Board | TNRIS - Texas Natural Resources Information System
Broken link: http://www.scaug.org/2016-SCAUG-CONFERENCE 

- [x] 2016 Texas GIS Forum | TNRIS - Texas Natural Resources Information System
Broken link: http://www.scaug.org/2016-SCAUG-CONFERENCE 

- [x] 2016 Texas GIS Forum Agenda | TNRIS - Texas Natural Resources Information System
Broken link: https://speakerdeck.com/texasnaturalresourcesinformationsytem/spatial-master-data-management
Broken link: http://www.merrick.com/
Broken link: http://www.scaug.org/2016-SCAUG-CONFERENCE
Misspelling: decisionmaking	
Misspelling: Univesity	

- [x] 2016 Texas GIS Forum Photo Recap, Part 1 | TNRIS - Texas Natural Resources Information System
Broken link: http://idav.ucdavis.edu/~okreylos/ResDev/SARndbox/
Misspelling: instuctor	

~- [x] 2016-2018 USGS Lidar Data Release | TNRIS - Texas Natural Resources Information System
Broken link: https://data.tnris.org/catalog/%7B%22filters%22:%7B%22category%22:%5B%22Lidar%22%5D%7D,%22search%22:%22USGS FEMA%22,%22sort%22:%22AZ%22%7D~ 

- [x] 2017 Lidar Data Release for East Texas | TNRIS - Texas Natural Resources Information System
Broken link: https://tnris-twdb.carto.com/u/tnris/builder/bbedf274-2141-4b1c-a443-8d339e7a9e7c/embed
Broken link: https://tnris-twdb.carto.com/u/tnris-sm/viz/a47e9bc6-2454-11e7-bcd5-0e3ebc282e83/public_map 

- [x] 2017 Texas GIS Forum Agenda | TNRIS - Texas Natural Resources Information System
Broken link: http://www.merrick.com/ 

- [x] 2018 GeoRodeo | Austin, Texas | TNRIS - Texas Natural Resources Information System
Broken link: https://adelbertsbeer.com/taproom/ 

~- [ ] 2018 Lidar Data Release for the H-GAC Operating Area & Coastal Region | TNRIS - Texas Natural Resources Information System
Broken link: https://data.tnris.org/collection/b5bd2b96-8ba5-4dc6-ba88-d88133eb6643~

- [x] 2018 Texas GIS Forum Agenda | TNRIS - Texas Natural Resources Information System
Broken link: https://speakerdeck.com/texasnaturalresourcesinformationsytem/south-by-south-where-tracking-local-government-response-to-austins-largest-annual-festival-using-web-based-gis
Misspelling: occurences	
Misspelling: Compatability	
Misspelling: conjuction	
Misspelling: acitivities	
Misspelling: gmail	

- [x] 2019 GeoRodeo | Austin, Texas | TNRIS - Texas Natural Resources Information System
Broken link: https://jsgeo.party/ 

~- [ ] 2019 StratMap Lidar Releases for Brown County and Missouri City | TNRIS - Texas Natural Resources Information System
Broken link: https://data.tnris.org/catalog/%7B%22search%22:%22StratMap Lidar 2019%22%7D~

- [x] 2019 Texas GIS Forum | TNRIS - Texas Natural Resources Information System
Broken link: https://www.merrick.com/ 

- [x] 2019 Texas GIS Forum Agenda | TNRIS - Texas Natural Resources Information System
Broken link: https://www.merrick.com/
Misspelling: recyling	

~- [ ] Address Points | TNRIS - Texas Natural Resources Information System
Broken link: https://data.tnris.org/collection/117cf9e1-3b1e-48f2-97a3-47020d871035~

- [x] Amarillo-DFW-El Paso-Lubbock 2015 Aerial Imagery Now Available | TNRIS - Texas Natural Resources Information System
Broken link: https://tnris.cartodb.com/viz/3eeb0c6e-df08-11e5-be12-0e787de82d45/embed_map
Broken link: https://tnris.org/2015-statewide-orthoimagery-project/ 

- [x] City of Georgetown 2015 Aerial Imagery Now Available | TNRIS - Texas Natural Resources Information System
Broken link: https://tnris.cartodb.com/viz/7db10e2c-6b8f-11e5-bd52-0ecfd53eb7d3/embed_map 

- [x] Digging Into the Augmented Reality Sandbox | TNRIS - Texas Natural Resources Information System
Broken link: http://idav.ucdavis.edu/~okreylos/ResDev/SARndbox/ 

- [x] Forum Keynote: UCGIS Fellow Dr. David Cowen | TNRIS - Texas Natural Resources Information System
Broken link: http://ucgis.org/ucgis-fellow/david-j-cowen 

- [x] Forum Keynote: UT Professor Todd Humphreys | TNRIS - Texas Natural Resources Information System
Misspelling: distinguised	

- [x] Forum Platinum Sponsor Spotlight: Harris Geospatial | TNRIS - Texas Natural Resources Information System
Misspelling: iniatives	

- [x] Forum Poster Gallery & Contest | TNRIS - Texas Natural Resources Information System
Broken link: http://www.scaug.org/2016-SCAUG-CONFERENCE 

- [x] Forum Poster Gallery & Contest | TNRIS - Texas Natural Resources Information System
Broken link: https://www.merrick.com/ 

- [x] Forum Pre-Conference Training | TNRIS - Texas Natural Resources Information System
Broken link: http://www.scaug.org/2016-SCAUG-CONFERENCE 

- [x] Forum Pre-Conference Workshops | TNRIS - Texas Natural Resources Information System
Broken link: https://www.merrick.com/ 

- [x] Forum Thank You and Photo Recap | TNRIS - Texas Natural Resources Information System
Broken link: http://idav.ucdavis.edu/~okreylos/ResDev/SARndbox/
Misspelling: Specialis	

- [x] H-GAC 2008 Lidar Data Released for Harris County and Surrounding Areas | TNRIS - Texas Natural Resources Information System
Misspelling: ther	

~- [ ] Historical Imagery Archive | TNRIS - Texas Natural Resources Information System
Broken link: https://data.tnris.org/catalog/%7B%22filters%22:%7B%22category%22:%5B%22Historic_Imagery%22%5D%7D%7D~

~- [ ] Hydrography | TNRIS - Texas Natural Resources Information System
Misspelling: gmail~

~- [ ] Land Parcels | TNRIS - Texas Natural Resources Information System
Broken link: https://data.tnris.org/collection/2679b514-bb7b-409f-97f3-ee3879f34448~

- [x] Lidar Data Release For Austin, CAPCOG 2012 | TNRIS - Texas Natural Resources Information System
Broken link: https://tnris.cartodb.com/viz/01a1b8ba-3abe-11e5-bfd3-0e018d66dc29/embed_map 

- [x] Lidar Data Release For Georgetown, Texas | TNRIS - Texas Natural Resources Information System
Broken link: https://tnris.cartodb.com/viz/a3cf9e14-3a1d-11e5-9323-0e0c41326911/embed_map 

- [x] Location & Lodging | TNRIS - Texas Natural Resources Information System
Broken link: http://www.scaug.org/2016-SCAUG-CONFERENCE 

- [x] New 2017 Brazos County Aerial Imagery Now Available | TNRIS - Texas Natural Resources Information System
Broken link: https://tnris.cartodb.com/viz/843bf1e2-1e14-11e7-8f3b-0ee66e2c9693/embed_map
 
~- [ ] New 2018-2019 NAIP Aerial Imagery Now Available | TNRIS - Texas Natural Resources Information System
Broken link: https://data.tnris.org/collection/f1d66250-4021-47df-9fe9-9fca286b0f50~

~- [ ] New 2019 Capital Area Aerial Imagery Now Available | TNRIS - Texas Natural Resources Information System
Broken link: https://data.tnris.org/collection/f84442b8-ac2a-4708-b5c0-9d15515f4483~

- [x] New Brazos County/City of Palestine Aerial Imagery Now Available | TNRIS - Texas Natural Resources Information System
Broken link: https://tnris.cartodb.com/viz/f420e7ee-6612-11e5-bfdc-0e76aec36da9/embed_map 

~- [ ] New USGS Lower Colorado San Bernard 2018 Lidar Data Release | TNRIS - Texas Natural Resources Information System
Broken link: https://data.tnris.org/collection/b246f8f7-9c79-4c89-91f7-9c7f44955fca~

- [x] News Archive | TNRIS - Texas Natural Resources Information System
Misspelling: imporant	

- [x] Notes: Texas GIS Community Meeting 1st Quarter 2017 | TNRIS - Texas Natural Resources Information System
Misspelling: agenies	
Misspelling: Availble	
Misspelling: recieved	

- [x] Notes: Texas GIS Community Meeting 1st Quarter 2018 | TNRIS - Texas Natural Resources Information System
Misspelling: acquistion	

- [x] Notes: Texas GIS Community Meeting 2nd Quarter 2016 | TNRIS - Texas Natural Resources Information System
Broken link: https://tnris.org/2015-statewide-orthoimagery-project/
Misspelling: exisiting	

- [x] Notes: Texas GIS Community Meeting 2nd Quarter 2017 | TNRIS - Texas Natural Resources Information System
Misspelling: Availble	
Misspelling: availabilty	
Misspelling: addtional	

- [x] Notes: Texas GIS Community Meeting 2nd Quarter 2018 | TNRIS - Texas Natural Resources Information System
Broken link: https://tnris.org/geographic-information-office/2016-12-01/texas-geographic-information-landscape-inaugural-gio-report/
Misspelling: Deparment (word appears 2 times)	

- [x] Notes: Texas GIS Community Meeting 3rd Quarter 2016 | TNRIS - Texas Natural Resources Information System
Broken link: http://www.glo.texas.gov/history/archives/map-store/index.cfm
Misspelling: recieved	

- [x] Notes: Texas GIS Community Meeting 3rd Quarter 2017 | TNRIS - Texas Natural Resources Information System
Misspelling: availabilty	

- [x] Poster Gallery Winners - 2016 Texas GIS Forum | TNRIS - Texas Natural Resources Information System
Broken link: http://www.glo.tx.gov/ 

- [x] Poster Gallery Winners - 2017 Texas GIS Forum | TNRIS - Texas Natural Resources Information System
Broken link: http://www.glo.texas.gov/history/archives/map-store/index.cfm 

- [x] San Antonio River Authority 2015/2016 Aerial Imagery Now Available | TNRIS - Texas Natural Resources Information System
Broken link: https://tnris.org/2015-statewide-orthoimagery-project/
Broken link: http://tnris.cartodb.com/viz/74be531c-897e-11e5-9e0b-0e5db1731f59/embed_map 

- [x] Slides: Texas GIS Community Meeting 2018 3rd Quarter | TNRIS - Texas Natural Resources Information System
Broken link: https://tnris-org-static.s3.amazonaws.com/images/txdshs_logo.jpgg 

- [x] Sponsors & Exhibitors | TNRIS - Texas Natural Resources Information System
Broken link: http://www.scaug.org/2016-SCAUG-CONFERENCE 

- [x] Sponsors & Exhibitors | TNRIS - Texas Natural Resources Information System
Broken link: http://www.merrick.com/ 

- [x] Sponsors & Exhibitors | TNRIS - Texas Natural Resources Information System
Broken link: https://www.merrick.com/ 

- [x] Sterling Harris Retires, Leaving GIS Legacy at GLO | TNRIS - Texas Natural Resources Information System
Misspelling: responsibilty	
Misspelling: acheivement (word appears 2 times)	

- [x] StratMap Contracts | TNRIS - Texas Natural Resources Information System
Broken link: https://www.merrick.com/services/geospatial-services/
Broken link: http://www.merrick.com/ 

~- [ ] Texas Address Points Datasets Transformed Into Common Schema | TNRIS - Texas Natural Resources Information System
Broken link: https://data.tnris.org/collection/117cf9e1-3b1e-48f2-97a3-47020d871035~

- [x] Texas GIS Community Meeting 2019 3rd Quarter - Slides and Notes | TNRIS - Texas Natural Resources Information System
Broken link: https://www.tnris.org/texas-gis-forum/2019/index 

- [x] Texas GIS Forum Platinum Sponsor Spotlight - Harris Geospatial | TNRIS - Texas Natural Resources Information System
Broken link: https://www.harrisgeospatial.comproductsandsolutions/GeospatialProducts/GeigerModeLiDAR.aspx 

- [x] Texas Imagery Service | TNRIS - Texas Natural Resources Information System
Broken link: https://txgi.tnris.org/login/path/xxxx-xxxxxx-xxx-xxxx/wmts?service=wmts&VERSION=1.0.0&request=GetCapabilities
Misspelling: sofware	

~- [ ] Texas Land Parcel Datasets Transformed Into Common Schema | TNRIS - Texas Natural Resources Information System
Broken link: https://data.tnris.org/collection/2679b514-bb7b-409f-97f3-ee3879f34448~

- [x] Texas Parks and Wildlife 2015 Aerial Imagery Now Available | TNRIS - Texas Natural Resources Information System
Broken link: https://tnris.cartodb.com/viz/dd5ba2c6-df05-11e5-90a3-0ea31932ec1d/embed_map
Broken link: https://tnris.org/2015-statewide-orthoimagery-project/

- [x] TNRIS Lidar Data Now Available for Download | TNRIS - Texas Natural Resources Information System
Broken link: https://tnris-twdb.carto.com/u/tnris-sm/viz/a47e9bc6-2454-11e7-bcd5-0e3ebc282e83/embed_map
Broken link: https://tnris-twdb.carto.com/u/tnris-sm/viz/a47e9bc6-2454-11e7-bcd5-0e3ebc282e83/public_map

- [x] USGS Releases Geologic Atlas of Texas (GAT) Viewer | TNRIS - Texas Natural Resources Information System
Broken link: http://www.usgs.gov/blogs/features/usgs_top_story/the-history-of-texas-is-under-your-feet-and-at-your-fingertips
Broken link: http://www.usgs.gov/blogs/features/usgs_top_story/the-history-of-texas-is-under-your-feet-and-at-your-fingertips/ 

- [x] Year in Review: 2015 Statewide Orthoimagery Project | TNRIS - Texas Natural Resources Information System
Misspelling: Availabilty (word appears 2 times)
