### ISSUE TITLE
Add Breakline and Project Reports 

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/tnris.org#2]
There are a few collections that need to have Breakline and Project Reports links uploaded. 

Neches River Basin needs breaklines and project report
Jack Archer needs project report 
Upper Coast needs project report 

@ThorTheDestroyer @gmullins

**Comment by ThorTheDestroyer** [comment]
Upper coast was updated several weeks ago with a report.
Jack & Archer report was dropped to due file size restrictions(working on pulling out fluff). 
neches basin-report was dropped to to file size restrictions. @mitchellryant breaklines for neches basin exceed file size limit of the api.  Please increase breakline filesize limit to 110MB.

**Comment by ThorTheDestroyer** [comment]
supplemental reports have been posted.

**Comment by adambreznicky** [comment]
increasing the breakline upload filesize limit is bad practice and unconventional. the excessive filesize is a special case so we manually uploaded to the bucket and then manually queried to update the database directly. the collection has been updated successfully and the api was refreshed to qc/push the manual update to the frontend. datahub and api admin console both reflect the change.

you're good-to-go insofar as the neches river basin collection's breaklines download is concerned. let me know if you have any questions or issues

**Comment by ThorTheDestroyer** [comment]
@adambreznicky just to give you a heads up, It isn't really a special case.  Since the USGS is acquiring these huge collection, you'll likely have to do it for about 4 more collections in the near future as they are around the same size as this collection.  I'll just start adding  a line into the incoming data that requests you upload them.
