### ISSUE TITLE
Descriptions for Forum StratMap Session

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#20]
@christoball On the agenda, please add these descriptions to this session. Thx!

Strategic Mapping - Celebrating Successful Public and Private Partnerships

Program Overview – How everyone benefits 
Celebrate this 10 year milestone with us as TNRIS program specialists provide an overview of program benefits and major accomplishments gained for the Texas GIS community and the public in general. Learn how the program has enhanced the purchasing power of GIS data and services in Texas and how that translates into problems solved for the greater good of humans and our environment. 
 
Success Stories 
Hear first-hand from StratMap data, services and software providers as well as Texas government users on the direct impact the program has had on their work. Industry experts from both sectors will tell the human side of the successes they achieve over and over through this model.  
 
What's New? 
Learn about new program goals and details on the next phase of public/private partnerships in Texas. Engage with a Texas Department of Information Resources (DIR) representative who will describe the new contract solicitation process and answer any questions. How can the contracting model help you as a user or as a provider? What do you want to see on the contract that's different? What improvements could be made? Following the session, program experts (actual humans) from TNRIS and DIR will be on hand to answer additional questions.

**Comment by christoball** [comment]
combined into #10
