### ISSUE TITLE
Website front page section GIS Education & Training 5.6.20

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#206]
Please update the front page, right column Education GIS Training 
[GIS Training Front Page Update 5.6.20.docx](https://github.com/TNRIS/tnris.org/files/4587306/GIS.Training.Front.Page.Update.5.6.20.docx)

@christoball

**Comment by christoball** [comment]
@KCMack the language here is too much for the front page. Take a look at the preview below.

We should just use the language in the 'Important Notice' on the education page right now:
https://tnris.org/education/

![image](https://user-images.githubusercontent.com/1877550/81198344-fc546380-8f86-11ea-8831-3ba10fc9706e.png)

**Comment by KCMack** [comment]
I must be missing something.  On the front page, the right hand column under GIS Education & Training generally offers the next two courses.  I was hoping to provide more information in that space.  There is a lot of blank space here now.

And, the language at the top of that section needs to be replaced.  – “The  2020 Training Season is now over.  Let us know if you have suggestions for courses that can be added to our program…… and check back for next year’s schedule.”  I was hoping to provide a bit more information here.

KCM

Kathleen C. Mack
Texas Natural Resources Information System
A Division of the Texas Water Development Board
Kathleen.Mack@twdb.texas.gov
Phone 512 463.4536

**Comment by christoball** [comment]
@KCMack can you take a look and tell me if this is alright?

http://glidden.tnris.org/

**Comment by KCMack** [comment]
[GIS Training Front Page Update 5.7.20.docx](https://github.com/TNRIS/tnris.org/files/4593672/GIS.Training.Front.Page.Update.5.7.20.docx)
@jwhaney
