### ISSUE TITLE
5.15 Education Notice & Re-Organization/Removal of unnecessary content

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#210]
Please replace the important notice at the top of the education page with the attached file.

Retain the yellow box around the new notice

[5.15.20 Edu Web update.docx](https://github.com/TNRIS/tnris.org/files/4634280/5.15.20.Edu.Web.update.docx)

Eliminate paragraph -- Our experienced instructors possess technical and teaching skills which are combined with industry knowledge and practical applications of GIS. Courses are offered at a lower price compared to commercial training organizations.
@jwhaney

**Comment by jwhaney** [comment]
additional items tacked on to this issues work:
- remove course cancellation, both tab content and side content
- remove w9 info from side
- remove purchaser info tab and content
- remove training address from side
- remove purchaser resources from footer and add teacher resources in place

only info on side will be contact button, and discount code copy content if/when education resources from the api are available.
