### ISSUE TITLE
5.19.20 Website Front Page Training News Article and GIS Education updates

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#212]
Please replace the current News article with the attached.
Also on the right column remove and replace with the attached update.

Time sensitive

[Website training update 5.19.20 .docx](https://github.com/TNRIS/tnris.org/files/4651264/Website.training.update.5.19.20.docx)

**Comment by adambreznicky** [comment]
i'm reviewing your document now to implement it.

the first half of the content for the "website front page, right hand column" makes sense.

the second half, News Article Update is slightly puzzling to me. by "replace the current News article with the attached" do you mean that you want me to swap out the content of the latest new article (link [here](http://localhost:8000/news/2020-05-01/transitioning-from-live-courses-to-online-or-remote-instructor-led))? the latest article is dated 5/1 and the content is dramatically different so your asking me to completely remove all content in this article and swap it for the documents'? (including the date?)
or do you want me to create a new News article page for the content you provided? so it will be the _latest _post__ after the 5/1 dated one i linked to?

**Comment by KCMack** [comment]
Hi Adam,

Great question.  I phrased it incorrectly.

Please add the News Article which was recently added to GitHub.

It gets tricky because usually we merely keep adding News and in this case, we’re updating the content to reflect the recent changes.  I guess for a historical progression point of view, as you suggest, we should simply add the new one and drop the article Make Texas Count in the 2020 Census.

Thanks very much for asking the question – and please continue to do that.  And, continue to make corrections such as the addition of Google Chrome, when the language submitted was incorrectly stated as Chrome.  Your intelligent questions and modifications keep our website looking it’s best.  I appreciate the care you contribute.

I hope this all makes sense.  Working on only my first cuppa and a bit tired today.

Many thanks.
Kathleen


Kathleen C. Mack
Texas Natural Resources Information System
A Division of the Texas Water Development Board
Kathleen.Mack@twdb.texas.gov
Mobile 512 415.3847

**Comment by adambreznicky** [comment]
new article via commit 1c7133d5f207ac43d2673d565f6691953a26036b
front sidebar updated via commit 990aa6ee6417378b0eede6860e6ce8710ccd8572
