### ISSUE TITLE
GIS Community Meeting Notes - 2nd Qtr 2020

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#213]
The slide deck and "notes"....really a blurb....is ready for posting to the GIO page. Speaker Deck requires a PDF rather than PPT so I took the liberty of adding the commercial presentation to ours, exporting and compressing the PDF file. Please let me know if you need additional information. Thank you!
[2nd qtr GIS community meeting blurb.docx](https://github.com/TNRIS/tnris.org/files/4652843/2nd.qtr.GIS.community.meeting.blurb.docx)
[GIS_QtrlyMtg2_2020.pdf](https://github.com/TNRIS/tnris.org/files/4652850/GIS_QtrlyMtg2_2020.pdf)

**Comment by adambreznicky** [comment]
resolved via commit 294252f5ce0216bc02456ebea22ad8cc8337a187
