### ISSUE TITLE
Browser Issue - Education Page update

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#214]
Because we've heard issues related to browsers not working with the TNRIS website, please add the following statement on the Education page, right hand column, under the contact us box

The courses may incorrectly show as closed in some browsers. We recommend that Chrome be used to accurately view the list of Courses with the Registration Open status.

@adambreznicky

**Comment by adambreznicky** [comment]
resolved via commit ae97b4727427e89cf2a3dbaac6ee7b02f9e5cfd5
