### ISSUE TITLE
REvised Agenda

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#22]
[Copy of 9.9.2019 Forum Agenda_Draft_9.13.19.xlsx](https://github.com/TNRIS/tnris.org/files/3616988/Copy.of.9.9.2019.Forum.Agenda_Draft_9.13.19.xlsx)
Please refresh the agenda including the speaker names and bios.  Note: specifically the Emergency Management session includes a CARTO presentation which is on this schedule.

**Comment by christoball** [comment]
combined into #10
