### ISSUE TITLE
news migration to twitter

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/tnris.org#221]
initial kickoff meeting ideas:
 1. [x] remove legacy news/gio-news articles and code
 2. [x] move 'follow us on twitter' button
 3. [ ] change site font to match twitter (bootstrap default?)
 ~~4. embed feed anywhere else aside from front page?~~

* establish committee of ambassadors
* establish internal workflow (review process?)
* establish standards/requirements for tweet formatting
* individual, professional accounts which TNRIS retweets?
* document all workflows and standards as repo wiki

**Comment by jwhaney** [comment]
fyi, it appears that Twitter uses a proprietary or custom font that is not free. i think they are using this one:
https://www.fonts.com/font/linotype/neue-helvetica?QueryFontType=Web&src=GoogleWebFonts

i'm gonna hold off on any font changes across the site until we can discuss or decide its worth spending some time on.

**Comment by jwhaney** [comment]
issues related to the feature branch for this issue - #233

**Comment by jwhaney** [comment]
closed via #234
