### ISSUE TITLE
Janky

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#225]
Could this be fixed, easily? Looks weird to me, I tend to prefer symmetrically lines and equal columns. I do understand the bird sounds portion is from beta, and not fully finished yet.

![front_end_LI](https://user-images.githubusercontent.com/8459928/84162207-bc751600-aa35-11ea-8167-3bcecd7265fb.jpg)
![front_end2_LI (2)](https://user-images.githubusercontent.com/8459928/84162211-bd0dac80-aa35-11ea-9d5c-ba9a6f0df086.jpg)

**Comment by adambreznicky** [comment]
i like your proposition @mitchellryant . good idea. maybe this mock up could help fill out the design?
we can most definitely shorten the length of the new tweet list, but re-arranging could also help in other ways in addition to adjusting the news length. could give us an actual jumbotron style banner. i dunno, just trying to throw some ideas out there to help build on yours.

![Selection_104](https://user-images.githubusercontent.com/5650145/84435082-c42fe880-abf6-11ea-991b-aa94c18c1eb7.png)

**Comment by adambreznicky** [comment]
also, since most every section of tnris is represented on the landing page, we could swap out the extra large banner so we don't duplicate information (example being that the banner is currently for training while we also already have a section for training below it). maybe replace it with a slightly slimmer, full width static tnris image?

**Comment by jwhaney** [comment]
the issue i see here is that the right panel GIS Education & Training content is possibly a temporary notice and may go away. i'm not sure how the right side can be properly aligned and symmetrical. i do like the idea for the left side though bringing the datahub element down below the top. another possible option is to shorten the height of the twitter embed. we can control that if we need to adjust.

the easiest quickest fix might be to just adjust the height of the twitter embedded timeline. idk.

**Comment by jwhaney** [comment]
related to #221 and some design/layout changes are being worked on the feature/news-migration branch

**Comment by jwhaney** [comment]
resolved with #228
