### ISSUE TITLE
Texas Statewide Land Parcel Data Report Cover Page

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#23]
Please use the StratMap graphic for this cover page
[Final Report Cover Page_9.16.19.docx](https://github.com/TNRIS/tnris.org/files/3617680/Final.Report.Cover.Page_9.16.19.docx)

**Comment by KCMack** [comment]
[Texas Statewide Land Parcel Data second page_9.13.19.docx](https://github.com/TNRIS/tnris.org/files/3617727/Texas.Statewide.Land.Parcel.Data.second.page_9.13.19.docx)
Changed TNRIS reference to TWDB

**Comment by christoball** [comment]
resolved
