### ISSUE TITLE
maps page skewing collection dates

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/tnris.org#231]
![Selection_117](https://user-images.githubusercontent.com/5650145/86278635-5a27b500-bb9e-11ea-967d-7768a3910380.png)

as shown in the picture, the dates set in the api admin console for map collections is getting altered in the frontend. the proper dates set are correctly coming out of the api, this means it's a frontend issue. (may be related to the date object issue that messed up the training dates in firefox in the past)
looks like all dates are being set in the frontend JS to 30 days prior to what the api says.

**Comment by jwhaney** [comment]
i can look into this

**Comment by adambreznicky** [comment]
resolved via commit e52cf5ba4155e2d8b853a2cd7fde038e94d3cdea
