### ISSUE TITLE
3rd Qtr GIS Community Agenda

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#232]
@jwhaney 
The attached agenda was typically loaded somewhere so I could have a link to post in the announcement. Is it something that can continue? If not, I can put the agenda straight into the announcement. I'm not a fan of the design, anyway.
Please advise and thank you!!
[GISComm_Agenda_20200721.pdf](https://github.com/TNRIS/tnris.org/files/4898495/GISComm_Agenda_20200721.pdf)

**Comment by jwhaney** [comment]
in what format is this announcement going to be, an email blast, twitter post, news article?

**Comment by jwhaney** [comment]
https://tnris-org-static.s3.amazonaws.com/documents/GISComm_Agenda_20200721.pdf
