### ISSUE TITLE
gio page - new gis community meeting slide deck list on right side

### ISSUE THREAD

**Issue by jwhaney** [TNRIS/tnris.org#240]
new slide deck document url list on right side of GIO page underneath GIO headshots
- just like the solution group meeting notes list - re-use code
- also a backend change with api.tnris.org, handled by @adambreznicky

requested by @geochik on 7/28/20

**Comment by adambreznicky** [comment]
[https://api.tnris.org/api/v1/tnris_org/comm_note](https://api.tnris.org/api/v1/tnris_org/comm_note)
i made the model and admin console changes. added the new api endpoint. and redeployed. so backend is good to go if we want to continue with the original idea. we can change direction if it's decided that is what's best, np
