### ISSUE TITLE
More sustainable HTTPS redirect for contact forms

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#241]
Perhaps we should have all contact forms located at something like `tnris.org/forms/form-name` and just create a single `location` directive for `/forms` to redirect to https. That way we don't have to modify nginx.conf for every additional form.

**Comment by jseppi** [comment]
I guess that wouldn't work if we want contact forms on lots of various pages :\

**Comment by wilsaj** [comment]
We are redirecting all HTTP traffic to HTTPS, so no need to have a special case for forms now.
