### ISSUE TITLE
Update Lidar Status Map

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#245]
Data needs massaging and map need work.

Lidar Status Map. https://tnris.org/stratmap/elevation-lidar/ 

`<style>.embed-container {position: relative; padding-bottom: 80%; height: 0; max-width: 100%;} .embed-container iframe, .embed-container object, .embed-container iframe{position: absolute; top: 0; left: 0; width: 100%; height: 100%;} small{position: absolute; z-index: 40; bottom: 0; margin-bottom: -15px;}</style><div class="embed-container"><iframe width="500" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" title="Lidar" src="//tnris.maps.arcgis.com/apps/Embed/index.html?webmap=66a83e8e93f54068a16477eb4e9f0e75&extent=-116.1567,23.277,-83.703,38.7672&zoom=true&previewImage=false&scale=true&legend=true&disable_scroll=true&theme=light"></iframe></div>`

**Comment by jwhaney** [comment]
@mitchellryant , @ThorTheDestroyer 
preview will be here in a few when i push to develop:

http://develop.tnris.org/stratmap/elevation-lidar/
