### ISSUE TITLE
Update Texas Imagery Services Map

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#248]
Data needs massaging and map need work.

Map Location - https://tnris.org/texas-imagery-service/

`<style>.embed-container {position: relative; padding-bottom: 80%; height: 0; max-width: 100%;} .embed-container iframe, .embed-container object, .embed-container iframe{position: absolute; top: 0; left: 0; width: 100%; height: 100%;} small{position: absolute; z-index: 40; bottom: 0; margin-bottom: -15px;}</style><div class="embed-container"><iframe width="500" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" title="Google Imagery Service" src="//tnris.maps.arcgis.com/apps/Embed/index.html?webmap=410b7caad2ec4e2687b960f488f55ea8&extent=-115.8717,23.3266,-83.4181,38.8093&zoom=true&previewImage=false&scale=true&disable_scroll=true&theme=light"></iframe></div>`

**Comment by ghost** [comment]
i did not realize teh pain and suffering this would cause to my life and other. Try to be proactive and help and it leads to a life of pain and suffering.

**Comment by JasonKleinert** [comment]
![image](https://user-images.githubusercontent.com/5649664/91847969-33c6da00-ec20-11ea-9c30-2e17e2123374.png)
### @mitchellryant No tears, please. It's a waste of good suffering.
