### ISSUE TITLE
Remove Education page Important Notice Banner

### ISSUE THREAD

**Issue by jwhaney** [TNRIS/tnris.org#249]
Is this banner still needed? The banner was first posted on the site in May 2020 so we have now had the notice to users up over 3 months. In my opinion it could be removed. Please provide your opinions on this in the comments below at your earliest convenience. Thanks.

![Screen Shot 2020-08-31 at 10 03 52 AM](https://user-images.githubusercontent.com/13525011/91735090-66fe6000-eb71-11ea-8522-660dc2579d2b.png)

**Comment by geochik** [comment]
I concur. 3 months is a sufficient amount of time.

**Comment by KCMack** [comment]
I agree.

**Comment by ctrepka** [comment]
I agree
