### ISSUE TITLE
Google Imagery Request Form

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#251]
the google request are coming into os tickets as unknown user.

**Comment by jseppi** [comment]
The contact-app automatically uses the `Name` and `Email` fields from the submitted form to set the from name and email address. @christoball needs to modify the google request forms to have fields with those names to get that behavior.

**Comment by wilsaj** [comment]
@christoball specifically the First Name and Last Name fields should be combined into one "Name" field.

**Comment by wilsaj** [comment]
closed as of 18618777293301414111a03a2f7b8c53f39b858b
