### ISSUE TITLE
Update Training Page to fy 2021

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#254]
Remove header 2020 Course Schedule
Replace with 2021 Course Schedule

Remove courses between May 27-28 through August 25-26
Thank you.

@jwhaney

**Comment by jwhaney** [comment]
@KCMack please visit the url below (login if you need to) and turn off the courses you no longer want displayed on the education page by unchecking the `public` checkbox in each training record.

https://api.tnris.org/admin/tnris_org/tnristraining/?o=-3.1

regarding the fiscal year header, i'd like to discuss further in our planned meeting next week to make sure everyone is on the same page.

**Comment by KCMack** [comment]
Of course.

kcm

Kathleen C. Mack
Texas Natural Resources Information System
A Division of the Texas Water Development Board
Kathleen.Mack@twdb.texas.gov
Mobile 512 415.3847

**Comment by jwhaney** [comment]
closing this per our meeting discussion today. please let me know if there are any questions or concerns. thanks.
