### ISSUE TITLE
Education page > crop banners to create consistent page layouts

### ISSUE THREAD

**Issue by Ldsmiths** [TNRIS/tnris.org#256]
Currently, the banner on the "Teacher Resources" page is larger than the banner on the "Main/Courses" page which pushes the content down and creates an inconsistent feel when navigating from one page to the other. 

**Side-by-side example:**

![image](https://user-images.githubusercontent.com/70979203/93898596-fc949780-fcb8-11ea-8314-a5c639b8e568.png)

**Corrected:**

![image](https://user-images.githubusercontent.com/70979203/93898709-1a61fc80-fcb9-11ea-80c7-310fd3e6176e.png)

Some additional changes that help create consistency:
-added title text on translucent background to match Teacher Resources
-moved "Education & Training" header and copy below navigation bar

**Comment by Ldsmiths** [comment]
Teacher Resources banner image cropped to 2000 x 505 to match 

![rovers1](https://user-images.githubusercontent.com/70979203/93900238-c48e5400-fcba-11ea-8293-1c679e32c0c6.jpg)

**Comment by Ldsmiths** [comment]
Cropped image URL: https://cdn.tnris.org/images/rovers3.jpg

**Comment by ctrepka** [comment]
Resolved via commit 659c2b8
