### ISSUE TITLE
StratMap Elevation- Lidar Page >  Change lidar status map hyperlink address to new AGO map

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#257]
@Ldsmiths @jwhaney Suggest replacing  status map hyperlink address under the embedded map with new Arc GIS Online lidar status map link on [StratMap Elevation-Lidar Page](https://github.com/TNRIS/tnris.org/edit/master/content/markdown/stratmap/elevation-lidar.md)

Suggested edit to Line 14:
 
 <p>Lidar coverage varies across the state. Lidar coverage and project details (date, nominal point spacing, vendor, etc.) can be found on the <a href="https://tnris.maps.arcgis.com/home/webmap/viewer.html?webmap=66a83e8e93f54068a16477eb4e9f0e75">Lidar Status Map</a>. All details about each dataset in our collection can be found in the supplemental reports for each project.</p>

Not sure which link is more appropriate, but a shorter link " https://arcg.is/1nmCnm0 " works as well.

**Comment by ghost** [comment]
@jwhaney the link to the download the availability index be change to use the CDN link? Since you are in there. 

http://data.tnris.org.s3.amazonaws.com/5751f066-28be-46af-b795-08387a27da6e/resources/tnris-lidar_48_vector.zip

**Comment by jwhaney** [comment]
resolved via commit b21353e41670cb51c6ec5dab1972c78a5b982d27
