### ISSUE TITLE
Texas Imagery Service (TIS) changes

### ISSUE THREAD

**Issue by jwhaney** [TNRIS/tnris.org#258]
The TIS page (https://tnris.org/texas-imagery-service/) needs to be changed pretty significantly to reflect the change over from Google to Hexagon/AppGeo. A lot of it will be just content changes. Gayla has provided a document that describes the changes requested to the page. A meeting will be scheduled to go over this in more detail to try and refine the requirements a little more if needed. At that point, additional information may be added to this issue.

https://twdb-my.sharepoint.com/:w:/g/personal/gayla_mullins_twdb_texas_gov/ETAeGsEXBRJOuoJaJQEtsBwBAfIC5snQa7lOAbLZn5w8EA?e=ksZ2fI

bootstrap reference for enhancement to TIS FAQ - https://getbootstrap.com/docs/4.0/components/collapse/

**Comment by ghost** [comment]
@jwhaney can you please assign @geochik to this issue too? I don't believe I have the permissions.

**Comment by ghost** [comment]
@geochik The link request content is ready for your review on the Word doc starting on page 11.

**Comment by geochik** [comment]
@gmullins Looks good! 

@jwhaney - would you like for us to save the document out and email it to you?

**Comment by jwhaney** [comment]
[test.txt](https://github.com/TNRIS/tnris.org/files/5301907/test.txt)

**Comment by jwhaney** [comment]
> @jwhaney - would you like for us to save the document out and email it to you?

if you'd like, i believe you can drag and drop the final document in a comment here for this issue and it will be available. let me know if that doesn't work. it should though.

**Comment by geochik** [comment]
[TIS - Webpage update.docx](https://github.com/TNRIS/tnris.org/files/5301968/TIS.-.Webpage.update.docx)

@jwhaney Done!

**Comment by jwhaney** [comment]
Just a note here for documentation purposes, on completing the content updates and faq functionality changes, we will need to merge to either `beta` or `develop` first, go to https://api.tnris.org/admin/contact/emailtemplate/ and change the Texas Imagery Service Contact and Texas Imagery Service Request form id's to match what has been changed in the frontend code. Once this change is confirmed to work, we can merge to `master` to deploy to production.

The new ids are as follows:

__Email Template Type__: Texas Imagery Service Contact ----> change to `tis-contact`
__Email Template Type__: Texas Imagery Service Request ----> change to `tis-request`

**Comment by ghost** [comment]
What are the terms of use?
The Texas Imagery Service is a subscription service providing licensed imagery data. The exact terms of use are coming soon.

Change Regional and Local costs to:
Annual flat fee 

Good to go.
Thank you!!
