### ISSUE TITLE
Information Architecture / Navigation Bar Revisions

### ISSUE THREAD

**Issue by Ldsmiths** [TNRIS/tnris.org#259]
There are some inconsistencies with the information architecture that could be hindering navigation. 

1.)	Some tabs on the primary navigation bar are dropdowns to secondary navigation options while others (Events, Geographic Information Offices) are direct links to pages. We should add chevrons to give users a visual symbol to know whether they will see a dropdown or be taken to a new page.

**It looks like Chris has already started working on implementing this in the latest update. We discussed potentially enhancing this in the future to highlight the active tab and flip the chevron.

ex) 
![image](https://user-images.githubusercontent.com/70979203/94185679-34dbd780-fe6b-11ea-9563-1f705d01deb1.png)

2.)    Some pages (Education and Training, Geographic Information Office) have navigation levels that are not accessible via the primary navigation header. Unless these are intentionally more hidden, they should be added as dropdown options so users can navigate to these pages from anywhere on the site. 

![image](https://user-images.githubusercontent.com/70979203/94181527-3d311400-fe65-11ea-8bd9-db74d7f0c791.png)

3.)	Data from Google Analytics suggests some users could be having difficulty navigating to Stratmaps (and Stratmaps sub-pages)

While /stratmap/land-parcels is the most visited page (behind the home page), only 16%* of users navigate there directly from the home page 
*excluding direct visits (typing URL, bookmark, clicking link on other site, etc.)

For comparison: (% of visits preceded directly by home page visit):
/maps/ - 51%
/geographic-information-office/ - 41%
/Texas-imagery-service/ - 38%
/research-distribution-center/ - 36%
/events/ - 36%
/applications-and-utilities/ - 31%
**/stratmap/stratmap-contracts/ - 22%
/stratmap/elevation-lidar – 22%
/stratmap/hydrography/ 13%
/stratmap/orthoimagery/ - 10%
/stratmap/address-points/  - 8%**

*Stats from Jan 1, 2020 - Sep 15, 2020

Hypothesis: Some users that want Stratmaps don’t immediately know to look under Programs.
	7-10% navigate from Maps to Stratmaps
	only 1-2% navigate from Stratmaps to Maps

If we give Stratmaps its own tab, then more users will get to their desired destination in fewer steps

How it could be structured:

![image](https://user-images.githubusercontent.com/70979203/94184575-bdf20f00-fe69-11ea-9e1a-d500fb1a40a2.png)

**Comment by Ldsmiths** [comment]
*Research & Distribution Center also has secondary navigation options. This is still a relevant issue as we want to provide navigation paths that are easy and obvious, but this may require further thought so we don't clutter the nav bar.

**Comment by jwhaney** [comment]
nice work @Ldsmiths 👍🏻 🚀 💯
