### ISSUE TITLE
Data Catalog Location Maps

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#263]
How do you want to create the  maps in cartodb?

1) do you want individual shape files per entry? 
or
2) do you want to use sql queries to select from County, DOQ, or DOQQ.

**Comment by wilsaj** [comment]
The current prototype version that you've seen is a web map (leaflet) with pan/zoom disabled. I think it works pretty well for the visualization things and I'd prefer it over using images with source maps - it's easier to change out base layers and change styles and such. It uses UTF grids generated along side the image tiles for interaction, and SQL to determine bounding boxes when visiting a quad/county by name. 

The current implementation issues are:

1. CartoDB occasionally clips quad labels that are tilted. We could either reduce the angle and/or ask CartoDB support ticket about it.
2. CartoDB's UTFgrid cache is at times doing funny things, which result in going to the wrong quad on click. Again, this is probably a CartoDB support issue but there are workarounds.


The current data issues are:

1. Some quad names in data download are not standard (OK 1, OK 2, etc). These should be re-written to use the standard USGS quad names.
2. We have more quads on the boundaries than we had before - meaning there are some quads that just don't have data.

**Comment by wilsaj** [comment]
Ok, it's in there now. The process is:

1. make a visualization on CartoDB
2. add the vis id to the catalog csv in the `status_map_cartodb_id` field
3. delete the old status map .jpg
4. :sunglasses:

**Comment by jseppi** [comment]
:+1:

**Comment by wilsaj** [comment]
As far as shapefiles - it doesn't matter since visualizations are separate from data tables, but it's probably easiest organizationally to keep one shapefile/table per visualization. We can re-use visualizations if they are the same for multiple catalog entries (just use same viz id).

**Comment by mitchellryant** [comment]
The interns are currently making the maps in cartobd. both have edit rights to the data-catalog-master google sheet. after completion their rights will be removed.
