### ISSUE TITLE
Lidar page special note

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#264]
@jwhaney We'd like to add the following text to this page: https://tnris.org/stratmap/elevation-lidar/
I'm thinking to the right of the map would be appropriate.

------------

**Special Note**

TNRIS is pleased to announce we are in possession of these three lidar collections that will complete 100% coverage of the state: _USGS 2019 West Texas_, _USGS 2019 Desert Mountains_, and _USGS 2019 Texas Pecos Dallas_

TNRIS is working aggressively to make these three datasets _available soon_ for download by the public through our [DataHub](https://data.tnris.org/). To expedite a data request for __STATE GOVERNMENT USE ONLY__, please [contact TNRIS](https://www.tnris.org/contact/).

**Comment by ghost** [comment]
@gmullins @geochik  

Before preceding with this note, should we make sure following issues are properly updated and assigned? To ensure "aggressive" working.  I have not done any work on the desert mountains collection. 

https://github.com/TNRIS/incoming-data/issues/50
https://github.com/TNRIS/incoming-data/issues/51
https://github.com/TNRIS/incoming-data/issues/52

**Comment by jwhaney** [comment]
@geochik and @gmullins are you ok with the bullets for the three datasets like this? i can change it back to be in paragraph form if not. let me know what you think.

![image](https://user-images.githubusercontent.com/13525011/95589525-7db69300-0a0a-11eb-9006-ebb85482d445.png)

**Comment by ghost** [comment]
@jwhaney I like the bullets and see how that fits better on the side of the map.
@ThorTheDestroyer Will you please review the issues for these three datasets to see if anything is missing at this point? @mitchellryant I believe @ThorTheDestroyer is working through the other two with you before beginning Desert Mountains. Thank you for your concern. We reviewed a timeline of January to have all these available online to the public with FR, RW, JT, JH and myself yesterday.

**Comment by geochik** [comment]
@jwhaney Yes, the bullets are great! However, now that I read it again, I think we need to take out the word "aggressively". It reads well without it.

@mitchellryant There is a bit of an urgency to make these datasets available. As @ThorTheDestroyer works through the list of action items to get these data online, he will continue to monitor data requests through the contact form and fill them as they come through.

**Comment by jwhaney** [comment]
@gmullins and @geochik please review the url below which reflects these changes (new text to the right of the lidar availability map). if you're good with them, give me a 👍  on this comment and i'll merge to production.

http://develop.tnris.org/stratmap/elevation-lidar/

__note__: you might have to clear your browser cache to see the changes

**Comment by ghost** [comment]
@jwhaney thumbs up!

**Comment by jwhaney** [comment]
ok complete. should be live now. closing this issue.
