### ISSUE TITLE
GIS Community Meeting PPT Template Slides

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#270]
@Ldsmiths -- the templates for this years community meeting slides are attached. The title slide and the blank slide each have the incorrect meeting (2nd qtr as opposed to 4th) times that need to be corrected. I tried to draw a white box over each of the needed corrections but could not find the proper matching font. Any assistance you can provide on getting these up to date is most appreciated.

![2020_virtual_gio_slide_blank](https://user-images.githubusercontent.com/7750220/96889206-ff1b1600-144b-11eb-9378-473afb9fe7e6.jpg)
![virtual2020_titleslide](https://user-images.githubusercontent.com/7750220/96889221-02160680-144c-11eb-812e-7e37db653817.jpg)

**Comment by Ldsmiths** [comment]
![Q4ppt1](https://user-images.githubusercontent.com/70979203/96899298-5cb46000-1456-11eb-8e3d-18946d1f3ec8.png)
![Q4ppt2](https://user-images.githubusercontent.com/70979203/96899300-5d4cf680-1456-11eb-97c0-9e0dc94a3d4b.png)

Font used: Roboto Condensed
