### ISSUE TITLE
front page quicknav looks bad on mobile

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/tnris.org#277]
Maybe don't show icons at xs screen size?

![mobile-tnris](https://cloud.githubusercontent.com/assets/303866/6929849/bf8c6612-d7c3-11e4-8100-603ae6ed189b.png)

**Comment by wilsaj** [comment]
@christoball  ping

**Comment by christoball** [comment]
I've removed 'follow us' on mobile which improves the situation.

Planning some other adjustments.

**Comment by wilsaj** [comment]
Ok, cool. Check the twitter group item height as well. It's a little bit shorter, which works when they are vertically oriented not but not horizontal.

**Comment by jseppi** [comment]
Looks good now, closing.
