### ISSUE TITLE
Add conditionals for TWDB map page

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#279]
Created a twdb-order-form.html in this branch:
https://github.com/TNRIS/tnris.org/tree/twdb-maps-form/templates

I commented in the html what portions will be conditional.

Also hoping to get a date selector in there.

**Comment by christoball** [comment]
the URL for the page is  /twdb-map-ordering

**Comment by wilsaj** [comment]
Note: we need to inform the TWDB web folks to update their link on the TWDB maps page

**Comment by wilsaj** [comment]
Updated the branch to have conditionals if you want to check those out.

How important is the date selector? It's a non-trivial amount of work for a form that will rarely be used. Is it okay to just use a text field for now and maybe update it in the future?

**Comment by jseppi** [comment]
FYI: angular 1.3 and up has built-in support for HTML5 `input[type=date]` Not a date/calendar selector, but at least easy validation and model binding.

**Comment by christoball** [comment]
It doesnt need a calendar popout, but it would be nice to have the dropdowns for year month and date like the image below

![dateselector](https://cloud.githubusercontent.com/assets/1877550/6967830/a5da4080-d927-11e4-8996-4931df4a1039.jpg)

And it would be cool to have the calendar option for future stuff, but agree its not worth holding it up for it.

**Comment by wilsaj** [comment]
Yeah, was thinking about that. It will render as a text with validation on anything but Chrome or IOS

**Comment by wilsaj** [comment]
Also, in the context of this form at least, an exact date or strict validation may not be necessary. If someone puts in "no rush" or "by the end of April", we'll know what they mean enough to get the map done on time.

**Comment by christoball** [comment]
that makes sense. ill just make it a text field
