### ISSUE TITLE
USGS Lower Colorado\San Bernard

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#28]
Data Story please copy all content for news article into this issue.

**Comment by ThorTheDestroyer** [comment]
---
title: New USGS Lower Colorado San Bernard 2018 Lidar Data Release
author: Joey Thomas, StratMap
layout: news-article.njk
mainimage: https://s3.amazonaws.com/data.tnris.org/46b000dd-83b2-4701-b5c6-3f6e18cedccf/assets/34a0cde1-d679-411c-8ced-973143b93d26.jpg
thumbnail: https://tnris-org-static.s3.amazonaws.com/images/brown_missouri_th.jpg
thumbalt: A thumbnail for USGS 2018 Lidar Projects
abstract: A collaborative initiative to capture high-quality Lidar data for portions of west south central Texas.
---

The Texas Natural Resources Information System (TNRIS) is pleased to announce the release of about 17,942 square miles of recently acquired, high resolution lidar data over 26 counties in south central Texas. Aerial collection took place during the 2018 leaf-off season in Texas.

The project was funded by a federal consortium of partners to support the 3DEP mission, the Federal Emergency Management Agency (FEMA) Risk Mapping, Assessment, and Planning(MAP) program and the Natural Resources Conservation Service (NRCS) high resolution elevation enterprise program

Further details regarding this acquisition can be found by downloading the Project Report(s) found in the data catalog entry.

## Data Access

<p>To download the 2018 USGS Lower Colorado San Bernard lidar data products, please use the <a href="https://data.tnris.org/collection/b246f8f7-9c79-4c89-91f7-9c7f44955fca">DataHub</a>.</p>

<a class="btn btn-lg btn-tnris" href="https://data.tnris.org/collection/b246f8f7-9c79-4c89-91f7-9c7f44955fca"><img style="width: 20px; margin-bottom: 0 !important;" src="https://tnris-org-static.s3.amazonaws.com/images/baseline_view_comfy_white_36dp.png"> Launch DataHub</a>

## Data coverage
<img src="https://tnris-org-static.s3.amazonaws.com/images/brown_missouri_city.jpg" class="img-responsive" alt="Map showing coverage of the USGS 2018 Lower Colorado San Bernard lidar project">

Please see our [Lidar status map](https://tnris-twdb.carto.com/u/tnris-sm/builder/a5dfc759-9a90-4acd-a8d1-57d521c7e1fe/public_map) for statewide lidar coverage.

## Products
- Classified all-return lidar  in LAS 1.4 format
- Bare-earth digital elevation model (DEM) in .img format (1-meter)
- Lidar intensity images in GeoTIFF format (1-meter)
- Hydro-flattening breaklines in SHP or Geodatabase
- Project-level FGDC metadata in XML

#### 3-D Image of Lower Colorado San Bernard Lidar

<img class="img-responsive" src="https://s3.amazonaws.com/data.tnris.org/46b000dd-83b2-4701-b5c6-3f6e18cedccf/assets/d213837e-d966-4291-bcf0-078da17d9e13.jpg" alt="detail image of the Lower Colorado San Bernard Lidar">

#### 3-D Image of Lower Colorado San Bernard Lidar

<img class="img-responsive" src="https://s3.amazonaws.com/data.tnris.org/66d886a6-13b9-46a9-936a-bf2ce4f71aaf/assets/2abdf2da-60d1-43d8-bca3-1627da2c337d.jpg" alt="detail image of the Lower Colorado San Bernard Lidar">

## Product Specification
- Vertical NVA RMSEz tested 4.9 cm . The tested accuracy in all areas meets the project specification for 10 cm.
- Average first-return point density meets the 2 ppsm project specification.
- Point data is classified according to the following American Society for Photogrammetry and Remote Sensing (ASPRS) class schema:
  * Class 1:  Unclassified
  * Class 2:  Ground
  * Class 7:  Low Point (noise)
  * Class 9:  Water
  * Class 10: Ignored Ground
  * Class 14: Culverts
  * Class 17: Bridges

- **Projection Specifications**
  + Horizontal projection is UTM NAD83 (2011) Zone 14
  + Vertical projection is NAVD88 Geoid 12B
  + Units are in meters denoting orthometric heights

**Comment by ThorTheDestroyer** [comment]
@christoball , tried to upload a .md and it said that format wasn't supported.

**Comment by christoball** [comment]
@ThorTheDestroyer the comment will work fine

**Comment by ThorTheDestroyer** [comment]
![LCSB_coverage_map](https://user-images.githubusercontent.com/8398036/65274795-c9d62300-dae9-11e9-8c4a-fecb57ee054d.jpg)
@christoball  here is the coverage map.

**Comment by christoball** [comment]
@ThorTheDestroyer Preview ready here:
http://haish.tnris.org/news/new-usgs-lower-colorado-san-bernard-2018-lidar-data-release/

**Comment by ThorTheDestroyer** [comment]
![image](https://user-images.githubusercontent.com/8398036/65325904-be303e00-db75-11e9-84bb-7d525575d278.png)
@christoball the caption circle in the image need to change from "3D Lidar Point cloud" to  "Bare Earth Digital Elevation Model"

Other than that, looks great.

**Comment by christoball** [comment]
@ThorTheDestroyer I've gone ahead and made that change, will initiate the move to publish
