### ISSUE TITLE
GLO Oil Response Toolkit - Broken Link

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#281]
Per S. Friedman email:

From: Scot Friedman 
Sent: Thursday, October 29, 2020 1:35 PM
To: Lauren Kirk <Lauren.Kirk@twdb.texas.gov>
Cc: Jeff Perkins <Jeff.Perkins@GLO.TEXAS.GOV>; Jimmy Martinez <Jimmy.Martinez@GLO.TEXAS.GOV>
Subject: Broken TNRIS Link
 
Hey Lauren, not sure if you're the right person at TNRIS for this, but you all are hosting the downloadable Zipped version of our Oil Spill Toolkit. We just found out that the link is broken. Could you check on this or point me to the person I should contact about that?
 
https://www.glo.texas.gov/ost/download/index.html (click "Download Oil Spill Toolkit")
https://s3.amazonaws.com/tnris-misc/glo-toolkit/ost.zip (broken link)
 
Thanks!
-Scot

**Comment by jwhaney** [comment]
@geochik where is the link to this OST download, on tnris.org or the datahub?

**Comment by jwhaney** [comment]
nevermind, i see that we were hosting a zip file for the OST for THEIR website?

**Comment by ghost** [comment]
https://spaces.hightail.com/receive/Z62LWdVspb#dload

**Comment by jwhaney** [comment]
> https://spaces.hightail.com/receive/Z62LWdVspb#dload

@geochik looks like GLO fixed it themselves. Can we close this issue now?
