### ISSUE TITLE
TNRIS.org Land Parcel/Address Point announcement v2

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/tnris.org#291]
@jwhaney @Ldsmiths @gmullins 

Morning y'all.  Due to an influx of questions regarding the whereabouts of the 2020 LP and AP data refresh, I wanted to discuss with you all the possibility of putting the message below on the respective LP and AP project pages on TNRIS.org and their 2019 project cards on DataHub.  If this works for y'all, I'll follow IS' lead on what looks best, where to put it, etc..

-------------------
Thank you for your interest in TNRIS Land Parcel~~s~~ and Address Point~~s~~ datasets. Due to unexpected circumstances, our annual 2020 statewide refresh _for_ ~~of~~ both _of these_ ~~Land Parcels and Address Points~~ datasets have been delayed. If you are interested in obtaining 2020 data, please use the __"Contact"__ tab located on the respective 2019 [Land Parcels](https://data.tnris.org/collection/2679b514-bb7b-409f-97f3-ee3879f34448) and [Address Points](https://data.tnris.org/collection/117cf9e1-3b1e-48f2-97a3-47020d871035) DataHub _collection_ pages ~~on our website~~.

**Please note data may not be available for all counties.**

The production timeline for the 2021 Land Parcel~~s~~ and Address Point~~s~~ datasets has not been affected. Currently, TNRIS anticipates a mid to late Summer 2021 release for the annual refresh. We invite you to use the Contact tab located on the respective DataHub ~~project~~ _collection_ pages for any questions you may have.

**Comment by LaurenKirk** [comment]
P.S. meant to hyperlink to the datahub project cards where I write "2019 Land Parcels and Address Points.."

**Comment by jwhaney** [comment]
> P.S. meant to hyperlink to the datahub project cards where I write "2019 Land Parcels and Address Points.."

@LaurenKirk you can click the three dots in the top right of your comment to make edits. if possible, get the text and formatting as close to what you want published on the site. let me know if you have any issues and I'll be glad to help.

**Comment by LaurenKirk** [comment]
@jwhaney got it. updated!

**Comment by jwhaney** [comment]
> @jwhaney got it. updated!

@LaurenKirk is that the spacing and formatting you'd like as well?

**Comment by LaurenKirk** [comment]
@jwhaney I'm good with it, unless y'all suggest something different.

**Comment by jwhaney** [comment]
@LaurenKirk i made a few changes but tried to keep what you had there with a strikethrough so you can see what i changed. take a look and let me know if that's ok. Probably be good to get @gmullins feedback as well.

_edit 1:_ to address the part of your issue here to put a notice on each 2019 datahub collection card, i'm not sure that's the right way to go about the notification. we can definitely add the text to each tnris.org page though, which would actually require some slight edits to the text above. we can discuss this more if needed.

_edit 2:_ one last thing to mention here, this type of notification is likely to reach more people initially if drafted in mailchimp and email blasted as a special notification and the mailchimp page linked to in a short tweet as well. just my opinion. we can add it to the ap and lp tnris.org pages as well, but i'm suggesting we don't add it to the datahub collections.

**Comment by LaurenKirk** [comment]
@jwhaney These edits look great, thanks for the heads up!

I hear ya, my concern with not putting some notice on the 2019 datahub collection cards are for people who don't visit tnris.org, but rather, go straight to datahub and otherwise wouldn't see the notice.  I'm down to discuss any edits that need to be made for tnris.org.

Oh, I had not thought about mailchimp/tweeting, that's a good point.  Yeah, would like to chat about these options with you and @gmullins

**Comment by ghost** [comment]
@jwhaney @LaurenKirk hey y'all. LOL. I pluralized Land Parcels and Address Points on Lauren's first draft (not seen here) bc that is how they are across the site. I think the ideas in this thread call for a live discussion. I'm not a fan of this type of announcement, maybe that's the wrong word, notice? to have an email blast/tweet due to the nature of the news we are providing. And if so, I think something like that can be reworded to put the most positive spin on it. My impression is that the 2020 data are more of a soft launch without a lot of fanfare, but we still want to have notice(s) on our website to direct people on how to get the 2020 data and why it is less complete compared to 2019. How about a meeting amongst the four of us to outline the best approach for these different areas of the site? I can set it up.

**Comment by Ldsmiths** [comment]
Yeah, I'm good to meet. My calendar is up to date.

**Comment by Ldsmiths** [comment]
![image](https://user-images.githubusercontent.com/70979203/101380919-c0b2ac80-387b-11eb-8306-ad9d20203867.png)

@gmullins @LaurenKirk 

Wanted to get your thoughts on how this looks. Also a couple questions:

1) Would you like this same message on both pages or would you like to have a slightly modified version for each?
2) Are you okay with the length? We might be able to shorten it a bit to take up slightly less space, but I also think it could be fine as is if that's how you want it. I'll let you make the call.

Thanks

**Comment by JasonKleinert** [comment]
@Ldsmiths the second sentence in the message text should be: Due to unexpected circumstances, our annual 2020 statewide refresh for both of these datasets **has** been delayed. Need to replace the "have" with a "has".

**Comment by LaurenKirk** [comment]
@Ldsmiths @jwhaney  that preview looks great, thank you!

Yeah, I think the same message on both project pages is fine.  I don't think the message needs to be shortened.

**Tweet/Email:** @gmullins @geochik below is a shortened version of the main message that could be tweeted.  I'm not sure if Twitter still has character limits and if this does/does not adhere.  We also discussed sending the announcement in an email via MailChimp.  I don't think the email will need to be much more than the announcement we are putting on tnris.org, however, I'm available to meet/collab on spinning the message differently.

"Thank you for your interest in TNRIS' Land Parcels and Address Points datasets.  Our annual 2020 statewide refresh for both of these datasets has been delayed.  Please contact us about current availability."

**Comment by jwhaney** [comment]
> **Tweet/Email:** @gmullins @geochik below is a shortened version of the main message that could be tweeted. I'm not sure if Twitter still has character limits and if this does/does not adhere...
> 
> "Thank you for your interest in TNRIS' Land Parcels and Address Points datasets. Our annual 2020 statewide refresh for both of these datasets has been delayed. Please contact us about current availability."

this shortened version will work with the twitter character limit which does still exist 👍  💯

**Comment by jwhaney** [comment]
@LaurenKirk @gmullins Please do one last check on the text at the below preview urls. @Ldsmiths has already knocked this out so I just want to double check one last time that yall are good for this to go to production today in this form. 

Just give a thumbs up on this comment if you are good with it. Thanks.

http://develop.tnris.org/stratmap/land-parcels/
http://develop.tnris.org/stratmap/address-points/

**Comment by LaurenKirk** [comment]
@jwhaney Can confirm, everything looks good on both urls.

**Comment by ghost** [comment]
@LaurenKirk @geochik For the **Tweet**, how about something like this to make it a little more conversational:
We don't have to tell you that 2020 did not go as planned, and our statewide [land parcels](https://www.tnris.org/stratmap/land-parcels/) and [address points](https://www.tnris.org/stratmap/address-points/) annual data collection were no exception. Nonetheless, we were productive and did acquire and standardize a substantial amount of these datasets this year! If you are interested in the 2020 data, please use the "Contact" tab on the respective 2019 [Land Parcels](https://data.tnris.org/collection/2679b514-bb7b-409f-97f3-ee3879f34448) and [Address Points](https://data.tnris.org/collection/117cf9e1-3b1e-48f2-97a3-47020d871035) DataHub collection pages.

@LaurenKirk do you have a graphic for this you'd like to use?

**Comment by jwhaney** [comment]
> @LaurenKirk @geochik For the **Tweet**, how about something like this to make it a little more conversational:
> We don't have to tell you that 2020 did not go as planned, and our statewide [land parcels](https://www.tnris.org/stratmap/land-parcels/) and [address points](https://www.tnris.org/stratmap/address-points/) annual data collection were no exception. Nonetheless, we were productive and did acquire and standardize a substantial amount of these datasets this year! If you are interested in the 2020 data, please use the "Contact" tab on the respective 2019 [Land Parcels](https://data.tnris.org/collection/2679b514-bb7b-409f-97f3-ee3879f34448) and [Address Points](https://data.tnris.org/collection/117cf9e1-3b1e-48f2-97a3-47020d871035) DataHub collection pages.

@gmullins just an fyi, twitter has a character limit. i pasted in your text as a draft tweet and it says how many characters it's over the limit:

![Screen Shot 2020-12-08 at 3 24 43 PM](https://user-images.githubusercontent.com/13525011/101543338-b7077280-3969-11eb-9923-2a3ae47f4c6a.png)

the limit is [280 characters](https://developer.twitter.com/en/docs/counting-characters#:~:text=In%20most%20cases%2C%20the%20text,as%20more%20than%20one%20character.).

**Comment by geochik** [comment]
I'm on it! I shortened substantially to fit. How does this sound?

"Looking for 2020 land parcel and address point data? We have received and processed several counties for 2020. Request these datasets by using the "Contact" tab on the respective 2019 Land Parcels and Address Points DataHub collection pages."

An image to accompany the Tweet would be fantastic!

**Comment by ghost** [comment]
Tweet: "Looking for 2020 land parcel and address point data? We have received and processed many counties for 2020. Request these datasets by using the "Contact" tab on the respective 2019 [Land Parcels](https://data.tnris.org/collection/2679b514-bb7b-409f-97f3-ee3879f34448) and [Address Points](https://data.tnris.org/collection/117cf9e1-3b1e-48f2-97a3-47020d871035) DataHub collection pages."

**Comment by geochik** [comment]
@jwhaney @Ldsmiths - do either of you know if Twitter allows for hyperlinking of text? I haven't come across that capability but maybe there is a trick I don't know about.....

**Comment by jwhaney** [comment]
> @jwhaney @Ldsmiths - do either of you know if Twitter allows for hyperlinking of text? I haven't come across that capability but maybe there is a trick I don't know about.....

i don't believe so. i googled around a bit and it doesn't seem like it's possible. here is some reference - https://help.twitter.com/en/using-twitter/how-to-tweet-a-link. the only way to maybe do a hack to make it work is to setup a hash link/tag maybe? but not sure that's the proper way to use hash tags.

**Comment by Ldsmiths** [comment]
> @jwhaney @Ldsmiths - do either of you know if Twitter allows for hyperlinking of text? I haven't come across that capability but maybe there is a trick I don't know about.....

I don't believe you can hyperlink, however Twitter does automatically shorten URLs. 

I tested @gmullins latest message and if you put the links in parentheses after the words, it's only 8 characters over the limit, so something like this could be an option

"Looking for 2020 land parcel & address point data? We have received and processed many counties for 2020. Request these datasets by using the "Contact" tab on the respective 2019 Land Parcels (https://data.tnris.org/collection/2679b514-bb7b-409f-97f3-ee3879f34448) & Address Points (https://data.tnris.org/collection/117cf9e1-3b1e-48f2-97a3-47020d871035) DataHub collections"

ex) 
![image](https://user-images.githubusercontent.com/70979203/101666181-824ff580-3a13-11eb-98e5-2f7b1bfb4059.png)

**Comment by LaurenKirk** [comment]
@jwhaney @geochik @gmullins @Ldsmiths 

Here is a graphic for the tweet
![2020_LP_AP](https://user-images.githubusercontent.com/31768897/101676154-699a0c80-3a20-11eb-98ae-f9080c201fe5.PNG)

**Comment by geochik** [comment]
Executed! Thank you, Team!

**Comment by jwhaney** [comment]
@geochik , @gmullins , @LaurenKirk ----> do yall think this issue should be closed now since we've knocked out both the tweet and the tnris.org notification?

**Comment by LaurenKirk** [comment]
@jwhaney yes, issue can be closed.
