### ISSUE TITLE
Education page discount language update

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#298]
Please revise the language describing the discount

From:To receive a discounted price on all TNRIS trainings provided through our service partners, copy the coupon code below to use during the registration process.

To: To receive the TNRIS discounted price for courses provided by our training partners TeachMeGIS and GeoSpatial Training Services, enter the coupon code below when registering.

Add: TNRIS discount code can be used for all scheduled courses listed on training partner's websites.

@Ldsmiths @jwhaney

**Comment by jwhaney** [comment]
closed via #299
