### ISSUE TITLE
2019 CapArea Brazos Orthoimagery

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/tnris.org#3]
Data
- [x] Enter dataset on StratMap Incoming data xlsx sheet @gmullins 
- [x]   Route Data Shipment [copy data to TNRIS Projects share] @LaurenKirk 
- [x]  Data Processing [renaming file, data organization @LaurenKirk 
- [x]   Quality Assurance @LaurenKirk

DataHub
- [x]  Create collection @mitchellryant
- [x]   Complete console collection form including metadata and description @gmullins 
- [x] Create Images, place on Website Dir @gmullins  
- [x] Upload supplemental info (breaklines, reports, index) @gmullins 
- [ ] Crop\Upload Images @christoball 
- [ ]  WMS Link @mitchellryant 
- [x] Review Description @pwblanton
- [x]  Add resources @mitchellryant

Download\Prod
- [x]  Move data to production shares @mitchellryant
- [x] Make collection public @mitchellryant

Publication
- [x]  Data Story @gmullins  @christoball
- [ ] Final Publication @christoball @gmullins 
- [ ]  Inform TNRIS staff of data availability @gmullins

**Comment by gmullins** [comment]
Oops! Both new nc and cir for 1to2500 zilker park are there now. And can you please caption or label them with Zilker Park?
M:\SM\SM Contract\2019 Projects\CapArea_Brazos_Ortho\Web_Announce\Graphics

**Comment by christoball** [comment]
@gmullins I've made the updates:
http://washburn.tnris.org/news/2019-09-11/new-2019-capital-area-aerial-imagery-now-available/

**Comment by gmullins** [comment]
@christoball 
The very top Zilker image should be SCALE 1:2500
Apple Inc. should be SCALE 1:2300
Zoomed Zilker Park should be SCALE 1:600
Downtown Austin should be SCALE 1:900
@mitchellryant I can barely read the legend on the map or the smaller city labels. Can you please increase their point sizes? I know you "don't make maps". THANK YOU.

**Comment by christoball** [comment]
@gmullins @mitchellryant I fixed the scales and also updated the map myself with a larger legend.

http://washburn.tnris.org/news/2019-09-11/new-2019-capital-area-aerial-imagery-now-available/

**Comment by gmullins** [comment]
@christoball @mitchellryant That's a go!
