### ISSUE TITLE
NAIP 2018-2019

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#30]
Data Story please copy all content for news article into this issue.

**Comment by ghost** [comment]
@christoball Latest News write up and image graphics are here:  M:\Website\Updates\NAIP 2018 Statewide Imagery release
Thanks!

**Comment by christoball** [comment]
@gmullins Do you not want NAIP included in the headline? It's currently:

## New 2018-19 Statewide Aerial Imagery Now Available

**Comment by ghost** [comment]
@christoball Yes, let's put NAIP in there since so many people know it.

**Comment by christoball** [comment]
@gmullins preview of article now ready: http://razor-wire.tnris.org/news/2019-10-03/new-2018-2019-naip-statewide-aerial-imagery-now-available/

**Comment by ghost** [comment]
@christoball Looks great! The only thing I see is the oil pads slider is missing the CIR image. Good to go after that.

**Comment by christoball** [comment]
@gmullins k i've fixed that and moving forward with publishing
