### ISSUE TITLE
Update to TIS terms of use FAQ

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#301]
@Ldsmiths @jwhaney I got the pdf. Can you please add an option on this FAQ to view it? I put a suggestion but open to best UX on this :)

What are the terms of use?
The Texas Imagery Service is a subscription service providing licensed imagery data. View the license agreement:
[HxGN Content Program_StateGov_EULA_2019_State of Texas_NOV2020.pdf](https://github.com/TNRIS/tnris.org/files/5748327/HxGN.Content.Program_StateGov_EULA_2019_State.of.Texas_NOV2020.pdf)

**Comment by Ldsmiths** [comment]
@gmullins 

I kept your wording and made the link a button to match the other FAQ dropdowns with clickable links

![image](https://user-images.githubusercontent.com/70979203/103241219-30b2d080-4918-11eb-8691-b0a780b66c31.png)

**Comment by ghost** [comment]
@Ldsmiths I like it! Thx.
