### ISSUE TITLE
Video on Lidar page

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#303]
@Ldsmiths @jwhaney I spoke with @ThorTheDestroyer on this way back. We'd like to put the lidar video here: https://texaswaternewsroom.org/videos/lidar_and_floodplain_maps.html embedded as the banner image on the [lidar page](https://www.tnris.org/stratmap/elevation-lidar/) This would be similar to the video banners on the land parcels and address points pages. What do you think? Thx!

**Comment by Ldsmiths** [comment]
@gmullins 

That makes sense to me. Is this what you had in mind?

![image](https://user-images.githubusercontent.com/70979203/103419456-ce94de00-4b58-11eb-82ec-a4a4d2d2117e.png)

**Comment by ghost** [comment]
@Ldsmiths Yes 👍
