### ISSUE TITLE
Project Page Idea

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#305]
**Idea:**
Create and Maintain single page for users to track Data Collection that are in the "pipeline". StratMap personal would maintain project fact and dates related to projects. Information update could be tweeted.

**Project Fact\Status:**
Keep it simple.
Awarded
In Acquisition
Processing
Post Processing
When a dataset collection makes it to the data site, it is removed from the page.

**Coverage Maps:**
Simple Jpg\Png static maps

No percentage complete.
No ETA delivery (just sets up failure.)

**Comment by ghost** [comment]
This idea is based on user feedback. This idea or something has been suggested before, but never gone anywhere.

Examples from the ticketing system. Maybe additional feedback comments from the survey.

![Feedback](https://user-images.githubusercontent.com/8459928/103689327-ca9dfd00-4f58-11eb-96fb-d191ff2b0e0b.PNG)

![Feedback2](https://user-images.githubusercontent.com/8459928/103689337-cd98ed80-4f58-11eb-99a0-766f754c4488.PNG)

**Comment by ghost** [comment]
Could place the new page here in the menu.

![Untitled](https://user-images.githubusercontent.com/8459928/103690558-8a3f7e80-4f5a-11eb-8b9e-87cde13ac465.png)

**Comment by ghost** [comment]
@mitchellryant Yes! FR just mentioned this Issue to me. I've often thought, the only way people get this type of info is if they are in the 'secret club' and come to the GIS Community Meetings. Similarly, JT and I have been discussing splitting out the lidar projects vs. lidar coverage from the map on the lidar page. We were thinking the StratMap main page would be the area for current data acquisition project status of lidar, imagery, land parcels, address points, scanning project, etc.... Updated by SM staff. I'm open to a new page though if that enhances the UX. Shall we meet on this to kick something off?

**Comment by ghost** [comment]
- Im not sure what splitting the lidar map gets the user besides 2 maps. 
- Im not sure bury this information on the StratMap is the best way to go, but that would be a call for UI|UX. It is data, that is why i suggested putting it under the data heading.
- in lieu of an meeting, maybe the StratMap team members put together some facts the projects, some simple static maps, and we let @jwhaney & @Ldsmiths put something together. meeting are bad for the soul, if you believe in that sort of thing. 
- i just think we should provide our customers a way to get information about ongoing projects, without emailing. 
- the project details and keeping them updated will always be the hard part.

**Comment by Ldsmiths** [comment]
If this is for all TNRIS data and not just data relating to StratMap projects I think it makes sense to make it a separate page under the “Data & Maps” tab as Ryan suggested. Maybe call the page “Data Collection Pipeline” or something similar. 

If It's strictly StratMaps data then I think another tab under StratMaps makes sense. Depending how many projects will be shown at a given time and how much info will be displayed, it _might_ make sense to have them on the main SM page, possibly similar to the 3 column layout currently used for the "Projects" section. 

Overall this idea makes sense to me as a way to help keep users informed.

**Comment by Ldsmiths** [comment]
https://ldsmiths.github.io/data-collection-pipeline/

Here's something I put together to as an example. I'm open to any ideas on what this could look like, just wanted to share something a potential idea.

**Comment by ghost** [comment]
@Ldsmiths ! I like this prototype. Thank you. It really helps to visualize the possibilities. You just reminded me that we used to put progress information in quarterly reports that never went on our site, I don't think. We would make a page in the document per project like the one here. Where my brain starts to break a little is when we have projects that don't fit this exact pipeline, but that's ok as I'm sure we can make them work. I can help vet the fields. For example, we would want to show funding partners, but not exact $dollars or %.

![image](https://user-images.githubusercontent.com/4921113/105534143-ac533380-5cb2-11eb-9fc5-1d86864dbf1f.png)

@jwhaney If StratMap folk assemble this information, what might be the best way to provide to IS for inclusion on a page? 

My only thought on Data Collection Pipeline is not to tie us down to data acquisition only as we may want to include data development or enhancement projects such as 3D buildings development Miguel produces, low water crossings data development Chelsea is looking into, and maybe even projects sponsored by other agencies that StratMap funds contribute to such as TCEQ's storage tank ID pilot project, GLO public lands potential project, etc. Just thoughts.

**Comment by jwhaney** [comment]
> @jwhaney If StratMap folk assemble this information, what might be the best way to provide to IS for inclusion on a page?

i think it might be best to schedule a meeting to discuss this with @Ldsmiths, myself, you, and anyone else you want from stratmap. its important to make sure we have the requirements we need on our end, as well as to make sure we are on the same page.

from my perspective and just to document it here to refer to in the meeting if needed, I would think this page content would need to be closely monitored and updated by stratmap personnel due to any changes to anticipated completion of datasets and publishing to the datahub, as well as funding percentages, checkboxes for project status, etc. that being said, it would make sense to expand the api so stratmap personnel could easily manage and update the content on the page themselves. this would require both front and back-end development work. we aren't talking about tons of work here and it's total doable, but i just wanted to bring it up for discussion.

let us know what you think, or feel free to schedule a meeting and we can work out the details then. thanks.

**Comment by ghost** [comment]
@jwhaney Sounds good! I'll schedule us a meeting on this. I need to get past tomorrow's Comm. Meeting and make progress on a couple other things first.

**Comment by ghost** [comment]
Guidance document is [here](https://twdb-my.sharepoint.com/:o:/r/personal/gayla_mullins_twdb_texas_gov/Documents/Notebooks/Current%20Projects%20page?d=wf4a0caa11ada4d3ea3a747a63ced244c&csf=1&web=1&e=hT9KE9).
