### ISSUE TITLE
GIO Page - Events

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#308]
First, not a huge priority but I thought I would point out the inconsistency in the "Events" views on the GIO page based on Safari and Chrome only. See images below. Is it possible to address the tile sizes and consistent look across the tiles? 
<img width="946" alt="Safari" src="https://user-images.githubusercontent.com/7750220/105061769-7fe3b100-5a3f-11eb-9a69-b987461ed216.png">
<img width="931" alt="Chrome" src="https://user-images.githubusercontent.com/7750220/105061781-840fce80-5a3f-11eb-88a2-37ad64234a18.png">

**Comment by jwhaney** [comment]
hmm, @geochik i'm not seeing this bug in firefox, chrome or safari. @Ldsmiths and I will look into it. just in case, what device are you using? ipad or macbook? thanks.
