### ISSUE TITLE
delete datacatalog/entry folder 

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#31]
@adambreznicky while working on maps feature branch, i noticed the **datacatalog/entry** folder with all the catalog markdowns is in all the branches of the repo. 

Had we deleted that already? If not, we should be able to delete it no problem right?

**Comment by adambreznicky** [comment]
we did not delete them. if you open one, you should see that the "layout" (template) is directed to the redirect njk. we held onto them to satisfy concern raised about users who may have a bookmark to one of those old data catalog pages. the concern was that if they did have a bookmark and used it, they would get a 404 and that this would be a bad situation. this same scenario is why we held onto the data download md, wms md, and a few others. 
i, personally, don't see a problem in them going away. we only held onto them to put others in tnris at ease. if you want to continue to leave them in there, that is completely fine. this is wholly your discretion.

**Comment by christoball** [comment]
@adambreznicky going to think about it but I'll be sure to make a decision soon.

**Comment by christoball** [comment]
@adambreznicky looking at the analytics, there are still a notable amount of people entering through various data-catalog urls.

There 70 hits directly to data catalog entries in the table below. I we should leave it for now.

![image](https://user-images.githubusercontent.com/1877550/65189242-15c79000-da36-11e9-866e-0e34769e2018.png)
