### ISSUE TITLE
Education updates 1.25.21 Code & Payments

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#310]
Please update the Education page as follows:
Change the TNRIS discount code from TNRIS2020 to TNRIS2021

Add the following new notice between the TNRIS code and Contact us box:
NOTE. Payments must be received before students will be allowed to take courses.

Thank you.

**Comment by Ldsmiths** [comment]
@KCMack The updates are ready to go. Before we make them live I just wanted to confirm--have all the training service providers been notified that the discount code is changing?

**Comment by KCMack** [comment]
Thanks for asking - yes they have and they will honor both codes for several months.

**Comment by jwhaney** [comment]
thanks @Ldsmiths for checking on that.

@KCMack we can go ahead and push these changes today. however, i wanted to point out that the education training records have a section in the description with the old discount code that was added at some point. you'll just need to go into the api for each one of the records and update the code in the description if you'd like to keep it there. please let me know if you have any questions related to this. thanks.

**Comment by KCMack** [comment]
Thank you John.  I'll make the changes later today.
