### ISSUE TITLE
Website Education - Registration Cut-off update

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#312]
Please add new update to the Education page listing courses:

![image](https://user-images.githubusercontent.com/4912083/106047404-32072280-60a9-11eb-912a-962dce0d9cba.png)

Please make it prominent for all to see.  

@Ldsmiths

**Comment by KCMack** [comment]
When adding the registration information #312, it would be helpful to make the recent Payment notice more prominent so it stands out for people to take notice.  
Thank you.

**Comment by jwhaney** [comment]
resolved via #313
