### ISSUE TITLE
Recognize Links in Map Collections

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#32]
@e00o has put links in the map collection descriptions to link back to the TWDB pages for the maps. These either need to be recognized as links in the description field or added as another field in the API that we can pull from. See below.

![image](https://user-images.githubusercontent.com/1877550/65161318-f8c29b00-d9fc-11e9-8e15-503c1a1487ba.png)

**Comment by adambreznicky** [comment]
i added a new field to the api and migrated the links out of the descriptions to utilize it. redeploying api now.
updated frontend to utilize a conditional ternary and create a link for this field if populated

resolved 7fc36edcf81b76379991e87ee6f915e9f51fee92
