### ISSUE TITLE
Pricing change on Texas Imagery Service FAQ

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#320]
@Ldsmiths We need to update the State Universities cost under the "How much does the Service cost for my agency?" FAQ. It should be:

State Universities
Department Annual flat fee $15,625**
University Wide Annual flat fee $125,000**

I don't think it's necessary to have them in the table with Unlimited Service Requests.
Thx!

**Comment by Ldsmiths** [comment]
@gmullins 

Were you thinking just removing the table completely for the State Universities section like this?

![image](https://user-images.githubusercontent.com/70979203/109996865-3ee4ea80-7cd5-11eb-8563-deee18200ee4.png)

Or we could leave the table and just eliminate that column for Universities:

![image](https://user-images.githubusercontent.com/70979203/109997752-23c6aa80-7cd6-11eb-93ee-f49635218dd1.png)

**Comment by ghost** [comment]
@Ldsmiths I like the first option, eliminating the table for State Universities.

**Comment by Ldsmiths** [comment]
> @Ldsmiths I like the first option, eliminating the table for State Universities.

Ok I'll go ahead and make the change. One other thing, did you want to keep "(single use)" next to "Department"?

**Comment by ghost** [comment]
No. Just "Department"
Thx!!
