### ISSUE TITLE
Loading TIle layers in GEMSS2

### ISSUE THREAD

**Issue by mpavon** [TNRIS/tnris.org#322]
When adding a tile layer in GEMMS2

Example: http://example.com/{z}/{x}/{y}.png 

![add_tile_layer_in_gemss2](https://cloud.githubusercontent.com/assets/12090693/7323804/ee073362-ea76-11e4-89a9-68a67421bf81.jpg)

Does not work as desired, I have found that putting the letters in reverse order works better:  {z}/{y}/{x}

Thanks for the tutorial @jseppi

**Comment by jseppi** [comment]
Right, that's just an example, not a prescription. The ordering is dependent upon the service. There's not a formal specification.
Nearly every other tile service I've come across orders them as `{z}/{x}/{y}`. For whatever reason ESRI does it in a different order.

Also, GEMSS2 related issues should be lodged in the GEMSS2 repository: https://github.com/TNRIS/GEMSS2/issues

**Comment by jseppi** [comment]
Sorry @mpavon - I don't think you even had access to https://github.com/TNRIS/GEMSS2/issues. I believe you have access now. Let me know if it didn't work.

**Comment by mpavon** [comment]
Thanks again.
