### ISSUE TITLE
TNRIS.org carousel recommendation

### ISSUE THREAD

**Issue by rwade2126** [TNRIS/tnris.org#327]
I would like to recommend that we change the current carousel affect from a swipe to a gentle fade to minimize the distracting movement from one image to another.   In addition, I think the image should not change for at least 15 seconds.  

I am open to any other suggestions and happy to discuss if needed.  

Thanks,

Richard

**Comment by jwhaney** [comment]
@rwade2126 take a look at the beta site for changes to the carousel that @Ldsmiths knocked out quickly for you. a friendly reminder when testing, if your mouse is hovering over the carousel area, the transition functionality (swipe, or fade in this case) is paused.

https://beta.tnris.org/

changes made:
- swipe changed to fade
- data-interval changed from 8000 ms (8 secs) to 10000 ms (10 secs)
