### ISSUE TITLE
Firefox giving error about SHA-1 certificate

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#332]
Do we have a certificate with a stronger signature method?

**Comment by wilsaj** [comment]
Our cert is SHA-256, so we should be good. This looks to be an issue with one certs that is part of the set of things ajax'd in from Google as part of the recaptcha system.

**Comment by wilsaj** [comment]
Closing - not much we can do about, and I think it is just a CSS file anyway
