### ISSUE TITLE
Removal of Old Address Point Page

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/tnris.org#332]
@Ldsmiths @jwhaney

Hey guys,

This webpage on TNRIS.org was brought to my attention: https://tnris.org/news/2019-11-20/texas-address-points-datasets-transformed-into-common-schema/

It's out of date all around and no longer relevant.  Can this page be removed?

**Comment by jwhaney** [comment]
yes we can remove it. but just for your reference, that is a part of the news archive which was usually not deleted but left as historical reference for what was going on at the time. we now use twitter and other methods for news and a user can't click to get to the news archive anymore. that user must have had it bookmarked or accidentally stumbled upon the /news url path. that is not an address points page for the public to get current information.

**Comment by JasonKleinert** [comment]
Are we considering deleting the archival news articles?

**Comment by LaurenKirk** [comment]
Understood.  It was brought to my attention by RW.  Because its archived information that changes my opinion.  I don't see the need to delete.
