### ISSUE TITLE
Flash-fallback upload for zip files doesn't work

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#333]
Appears the issue is that the flash-fallback FileAPI doesn't use `"application/zip"` for the `file.type`. It just specifies `"zip"`

**Comment by jseppi** [comment]
Still doesn't work -- possibly an S3 policy problem

**Comment by jseppi** [comment]
Punting on getting this working in old IE versions. Just going to hide the upload for IE version less than 10, so those users will have to continue submitting site files by email. It should be an ever-diminishing set of users. cc @ThorTheDestroyer

**Comment by ThorTheDestroyer** [comment]
As much as I want to agree with you regarding that, I believe that a large amount of our users still run on those browsers, unfortunately. Point in case, the first person to try and use this feature was running and old IE.

**Comment by jseppi** [comment]
As discussed, if the site file checkbox is checked, an information message will be shown to users on old versions of IE.

**Comment by jseppi** [comment]
ref c90728e4daac447149094592c36e1b0b10ecc2ee
