### ISSUE TITLE
Forum - Save the Date

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#338]
@Ldsmiths, I would like to commission you to come up with a design for a "Save the Date" announcement about the Forum. The design does not have to follow the Forum theme, as we have yet to come up with one. It just needs to be simple and fit into the carousel space on our front page. The text will be: 

Texas GIS Forum 2021 will be IN-PERSON!
SAVE THE DATE - October 18-22, 2021
Location: Austin, TX.

This text can be adjusted, edited or questioned. It should just be kept simple. We might even include a link to the question/comment area with a specific button for the Forum as suggested by @mitchellryant. We can discuss.

Thank you and feel free to reach out for clarification.

**Comment by geochik** [comment]
@Ldsmiths Please use this graphic for the Forum Save the Date. This image will replace the "Adam" image in the front page carousel.
Thank you!
![Artboard Copy 29](https://user-images.githubusercontent.com/7750220/114080334-e6bf7c00-9870-11eb-8271-5a96c845420a.png)

**Comment by Ldsmiths** [comment]
> @Ldsmiths Please use this graphic for the Forum Save the Date. This image will replace the "Adam" image in the front page carousel.

Would you like this remain in that 4th position in the carousel (where the "Adam" image currently is)? Or would you like it to be higher in the order?

**Comment by geochik** [comment]
Great question. Higher order, please!
