### ISSUE TITLE
Carousel Image Refresh

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#344]
@gmullins @LaurenKirk @csidenblad @ThorTheDestroyer @KCMack @mpavon 

Need your ideas for replacing the current images in the front page carousel. There are tons of images here - https://api.tnris.org/admin/tnris_org/tnrisimage/ for your review. Or you could come up with your own....we would just need to make sure it fits the size requirements. We would like to replace the current images but not with just images. There needs to be some context. It could be for data highlighting or current projects or anything you think would be good to highlight.

Ready. Set. GO!! 

Thanks in advance for your help!

**Comment by geochik** [comment]
@Ldsmiths Please remove the "Save the Date" image from the carousel/website. We are contemplating a new date and will update everyone as soon as we know.
Thank you!

**Comment by Ldsmiths** [comment]
> @Ldsmiths Please remove the "Save the Date" image from the carousel/website. We are contemplating a new date and will update everyone as soon as we know.
> Thank you!

Done, thanks!

**Comment by ghost** [comment]
@TNRIS/tnris has this issue been resolved? can it be closed?

**Comment by geochik** [comment]
No followup, no resolution. Closing until web admin position filled.

**Comment by KCMack** [comment]
Close, pls

Kathleen C. Mack
Texas Natural Resources Information System
A division of the Texas Water Development Board
***@***.***
Office Phone 512.463.4536
Cell phone 512.415.3847
