### ISSUE TITLE
GIS Community Meeting - Q2 Graphics Request

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#345]
@Ldsmiths I am in need of new dates on the graphics you created for the 1st quarter meeting. If you no longer have the files, let me know and I'll add them to this issue. 
The graphics should be updated to reflect the 2nd quarter and the date of the meeting, April 27, 2021, including the PPT title slide and header for the content slides.
Feel free to email the files to me when complete. 

Thank you!!!

**Comment by geochik** [comment]
@Ldsmiths Can you please take a look at the Q2 campaign in MailChimp? I updated but have the following I need help with:
1. Need a graphic replacement for the campaign.
2. Need help with the font sizes in the agenda. The presenter names are not consistent size/style.
3. Review of content/message. Could it be improved? I'm out of ideas.

Thank you!

**Comment by Ldsmiths** [comment]
> @Ldsmiths Can you please take a look at the Q2 campaign in MailChimp? I updated but have the following I need help with:
> 
> 1. Need a graphic replacement for the campaign.
> 2. Need help with the font sizes in the agenda. The presenter names are not consistent size/style.
> 3. Review of content/message. Could it be improved? I'm out of ideas.
> 
> Thank you!

I updated the graphic and corrected font sizes and styles to be consistent. 

I reviewed the rest of the messaging and it looks good to me. I like that there's an emphasis on inviting the community to share project updates in the roll call, giving this a more interactive feel.

**Comment by geochik** [comment]
Excellent! Closing this issue....
