### ISSUE TITLE
Events Page - GIS Forum Alert Banner

### ISSUE THREAD

**Issue by Ldsmiths** [TNRIS/tnris.org#347]
<img width="1564" alt="Screen Shot 2021-04-14 at 12 49 44 PM" src="https://user-images.githubusercontent.com/70979203/114759750-2d571f80-9d24-11eb-837c-94f7aba1cdde.png">

![image](https://user-images.githubusercontent.com/70979203/114759914-5e375480-9d24-11eb-8481-b987702d0f4d.png)

There is currently an alert banner at the top of the Events page with the message that the GIS Community meeting has been cancelled. Since we have announced the date for the 2021 meeting, it probably makes sense to update or remove this message. @KCMack pointed out that this message also pops up as one of the top results when googling "tnris". 

A suggested replacement message is:

"The 2021 Texas GIS Forum will be held in-person October 18-22. Location and further details to be announced."

Wanted to get input from @geochik as well on the wording of the message. Any other details we should include? We can change the color of the "alert" box as well.

**Comment by geochik** [comment]
Good catch @KCMack! 

@Ldsmiths I think your wording is spot on. Let's go with it. Regarding the "alert" box, I don't know that it is necessary to put there. We only had that to ensure people knew the Forum was cancelled. Since it is over, I say we just remove it.
