### ISSUE TITLE
Update Sitemap & Spring Cleaning

### ISSUE THREAD

**Issue by Ldsmiths** [TNRIS/tnris.org#349]
Updating the sitemap.xml file to prioritize pages to optimizing Google search results. 

The top sublink under the "tnris" google result is a link to a 2 year old article announcing data.tnris.org. Re-organizing the sitemap file should correct this to show more relevant links. 

![image](https://user-images.githubusercontent.com/70979203/115262124-dd000900-a0f9-11eb-9a59-48a3c5eba13e.png)

**Comment by Ldsmiths** [comment]
Visual sitemap: https://www.gloomaps.com/lZgh3mzAxG

I used this as a reference for which pages we might want to include in our sitemap.xml. White blocks represent all the clickable pages in the navbar and footer

**Comment by jwhaney** [comment]
Lumping in some serious spring cleaning into this issue as well. See PR #351
