### ISSUE TITLE
GIS Community Meeting Video Upload

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#359]
@jwhaney - the 2nd qtr GIS community meeting video and the accompanying CC file are ready for upload to Youtube.  Please let me know when complete and I will add to the GIO page. Thank you!

Video - https://twdb-my.sharepoint.com/:v:/g/personal/felicia_retiz_twdb_texas_gov/Eelm3V2DPsNNpwK2HpkIJlwBlYID6Q-tPVcGjBprhQv3wQ?e=GU9aMs

CC File - https://twdb-my.sharepoint.com/:u:/g/personal/felicia_retiz_twdb_texas_gov/EaRWtFEl0vJBmusqnh64jqoBbXj115lB_kkzIzoBUb5Ghw?e=OWD7fp

**Comment by Ldsmiths** [comment]
@geochik - The video is up: https://www.youtube.com/watch?v=l0d4q6kvqwM

I skimmed the video to test the closed captions and they seem to be pretty good. I also added the agenda with timestamps in the description.  

I went ahead and added the video to the API as well: https://api.tnris.org/admin/tnris_org/tnrisdocument/f6284e82-3ef2-4049-82fa-c2b099dfe3db/change/

**Comment by geochik** [comment]
Excellent! Thank you for the lightspeed!
