### ISSUE TITLE
Texas Imagery Service FAQs update

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#360]
@Ldsmiths I have an overhaul of the first FAQ listed below. Plus, I am adding two brand new FAQs that may go directly after the Service layers FAQ in the list. Thanks!

**The Service contains several layers. What are these layers? Which one(s) should I use?**

![TIS FAQ](https://user-images.githubusercontent.com/4921113/118681702-6839f080-b7c5-11eb-97cb-7b1205fa7ed4.PNG)
There are several layers in the WMTS and WMS Texas Imagery Service. The ‘Texas’ main layer contains 6-inch imagery from Hexagon flown in 2020. Recommended layer for most applications.

Layer Descriptions:

Texas
**Recommended Layer:** Statewide mosaic of latest available imagery in the Texas Imagery Service. This layer includes consistent, **statewide 6-inch imagery flown in 2020 by Hexagon.** 

texas-basemap
This layer includes roads, county boundaries, major water features, and city names available as base information that were cartographically designed for use on top of imagery while using the service.

Texas_Hexagon_2018_15cm
This layer includes Texas’ major urban areas only flown by Hexagon in 2018 at 6-inch/15cm resolution.

Texas_Hexagon_2018_30cm
This layer includes consistent, statewide imagery flown by Hexagon in 2018 at 1-foot/30cm resolution.

Texas_Hexagon_2020_Status
A repeat of the statewide 6-inch 2020 imagery from Hexagon. **Do not use.** Use the ‘Texas’ main layer for this imagery.

Texas_Hexagon_Content_Stream
A repeat of the statewide 6-inch 2020 imagery from Hexagon. **Do not use.** Use the ‘Texas’ main layer for this imagery.

Hexagon_2020_Delivery_NA_WAC
A repeat of the statewide 1-foot 2018 imagery from Hexagon. **Do not use.**

Google Composite
A statewide 6-inch composite of the latest imagery obtained from Google as a patchwork across the state, years 2014 – 2020. 

texas-2011 through texas-2020
These layers contain imagery captured by Google from 2011 – 2020 as a patchwork across the state that were archived after newer imagery became available. These layers each contain any imagery collected within each year.

Hurricane Harvey image layers
•	corpuschristi_20170830
•	houston_20170831
•	la_lakecharles_tx_beaumont_20170902 and 03
These layers include imagery flown over some of the affected areas during the Hurricane Harvey event. They include Corpus Christi flown on 8/30/2017, Houston flown on 8/31/2017, and Lake Charles/Beaumont flown on 9/2/2017 & 9/3/2017.

**What is the horizontal accuracy of the imagery?**
The official accuracy of the 6-inch imagery from Hexagon is +/- 50 cm. This is very conservative as Hexagon customers have found accuracy to be much higher in most areas.

**What equipment was used to capture the data?**
The aerial imagery from Hexagon was acquired with the market leading Leica ADS100 large format digital airborne sensors. Visit Hexagon’s capture technology page for more information.

**Comment by Ldsmiths** [comment]
@gmullins 

Here is a link for you to review and make sure everything looks how you want it: http://develop.tnris.org/texas-imagery-service/

If it looks good we can go ahead and merge this to production to make it live.

**Comment by ghost** [comment]
@Ldsmiths I have just a few word changes now that I read these with fresh eyes.

_Third sentence, change to:_ This is the recommended layer for most applications.

_On accuracy first sentence, change to:_ The official accuracy of the 6 in (15 cm) imagery from Hexagon is +/- 20 in (50 cm).

_On equipment both sentence, change to:_ The aerial imagery from Hexagon were acquired with the market leading Leica ADS100 large format digital airborne sensors. Visit Hexagon’s [capture technology](https://hxgncontent.com/about/capture-technology) page for more information.

**Comment by Ldsmiths** [comment]
@gmullins 

Develop URL has been updated with these most recent changes: http://develop.tnris.org/texas-imagery-service/

**Comment by ghost** [comment]
@Ldsmiths Good to go. Thanks!

**Comment by Ldsmiths** [comment]
Update is now live
