### ISSUE TITLE
TNRIS.org Land Parcel Page Refresh

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/tnris.org#371]
Howdy @Ldsmiths ,

I'm hoping to steal a little of your time when you're available to make some small tweaks to the land parcel project page on tnris.org.

1. I'm ready to remove the yellow warning banner on the land parcel page.
2.  I'd like to remove the status bar and status map under the "Available Datasets" section.  May add a current version of this back in the future, but tbd at this point.
3. I'd like to move the giant youtube video off of the banner making it much smaller and moving it to the space previously occupied by the status bar/status map section.
4. Will work on creating a stylized image to be added to the banner.  Are there any sizing requirements or other info I should know when creating that image?

I think this should cover it for that page in particular.  Please let me know if I can help with anything!! @gmullins

**Comment by Ldsmiths** [comment]
@LaurenKirk If you can make the new banner dimensions 1362 x 394 they will match the other Stratmap page banners. 

I'm in meetings the rest of the day but I can get started on this (and Address Points) tomorrow

**Comment by LaurenKirk** [comment]
@Ldsmiths Will do!  Thanks for the help.

**Comment by LaurenKirk** [comment]
Hey @Ldsmiths ,

Attached are two versions of the same image.  Let's go ahead and use the same image for both banners on the land parcels and address points pages for the time being.  The first has been resized to 1362 x 394 and the other is 1701 x 1034

If the first image works for the banner and doesn't look too stretched lets go with that one.  The second image has not been resized from the original, but I can tinker with it if you need it resized larger to fit the banner.


![2020_LP_AP](https://user-images.githubusercontent.com/31768897/127195433-8446b50e-4672-4f19-8e53-2f6d94096b36.PNG)


![2021_AP_LP](https://user-images.githubusercontent.com/31768897/127195320-108586a5-f302-4b72-b65e-4c7bc7058b86.png)

Let me know what you think and/or if you need me to make any changes.

Thank you!!

**Comment by Ldsmiths** [comment]
@LaurenKirk 

These changes are now live on our develop branch if you want to give a final review. If it looks the way you want we can go ahead and merge to master

http://develop.tnris.org/stratmap/land-parcels/
http://develop.tnris.org/stratmap/address-points/

**Comment by LaurenKirk** [comment]
@Ldsmiths 

Reviewed both pages and they check out with me.  Please merge to master.

Thanks!

**Comment by Ldsmiths** [comment]
Merged to master 👍
