### ISSUE TITLE
TNRIS.org Address Point Page Refresh

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/tnris.org#372]
Howdy again @Ldsmiths ,

Very similarly to the land parcel page issue I submitted earlier; I'd like to make the same tweaks to this page as well.

1. I'm ready to remove the yellow warning banner on the address points page.
2. I'd like to remove the status map under the "Available Datasets" section. May add a current version of this back in the future, but tbd at this point.
3. I'd like to move the giant youtube video off of the banner making it much smaller and moving it to the space previously occupied by the status map section.
4. Will work on creating a stylized image to be added to the banner. Are there any sizing requirements or other info I should know when creating that image?

I think this should cover it for that page in particular. Please let me know if I can help with anything!! @gmullins

**Comment by Ldsmiths** [comment]
updates completed

full details on issue #371
