### ISSUE TITLE
Texas Imagery Service video

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#375]
@Ldsmiths I'd like to embed the video [here](https://www.appgeo.com/take-flight-with-tnris-what-you-need-to-know-about-the-texas-imagery-service/?utm_medium=email&_hsmi=144750375&_hsenc=p2ANqtz--ZZP0h1JBr-6xXngZrRDloR6WeY2-l63Ut6KJ98UNy9rh3Gm2p1Ol6o8vD0vo6Klf_6Y3o7-ZNcztVErpB4OroMzVQkm_rA5DvdsH4M76Q_JUhJcY&utm_content=144749088&utm_source=hs_email) on the Texas Imagery Service [page](https://tnris.org/texas-imagery-service/).

Let me know if you need anything other than the link.

I'm thinking maybe in this empty area under the Request a Free Trial Today.

![image](https://user-images.githubusercontent.com/4921113/127556584-93f83725-f7a1-4331-85f1-5d0000cc3537.png)

@geochik For any thoughts.

I do like the caption AppGeo wrote underneath the video too. Wondering how that could be incorporated on the page.

**Comment by Ldsmiths** [comment]
@gmullins 

The video by itself without caption fits in perfectly. We definitely could add a caption, we'll just have to get a little creative and either shorten the caption or re-arrange the page layout slightly. Below are some screenshots from me playing around with potential solutions. Let me know what you think.

![image](https://user-images.githubusercontent.com/70979203/127660189-04157797-637d-457b-8958-7bcc026594fa.png)

![image](https://user-images.githubusercontent.com/70979203/127659975-2f6e816b-ae39-441c-8e92-3e0a51556e26.png)

![image](https://user-images.githubusercontent.com/70979203/127661949-c570b3b2-ef88-4b82-a8c6-b2c568426f1f.png)

![image](https://user-images.githubusercontent.com/70979203/127662193-d5bbd228-c1d4-4b62-bbfb-37af60a3dc9e.png)

**Comment by geochik** [comment]
I like the very last one, with the request a link button moved to the left and elongated.....imo.

**Comment by ghost** [comment]
Me too! The last one is my favorite. Let's remove this line to reduce text: _We highly recommend reading through the FAQ below before requesting a unique link for your organization._

Thx!

**Comment by Ldsmiths** [comment]
> Me too! The last one is my favorite. Let's remove this line to reduce text: _We highly recommend reading through the FAQ below before requesting a unique link for your organization._
> 
> Thx!

Got it. These latest changes are now live on the develop branch if you'd like to take a final look before we send it to master: http://develop.tnris.org/texas-imagery-service/

(Issue #374 Contract page updates are included in this as well)

**Comment by ghost** [comment]
All looks good except the Beacon logo is incorrect. The one you have is for a different company. It should be something like this: 
![image](https://user-images.githubusercontent.com/4921113/127697837-7904ec44-83ce-431e-afb1-866428eee9e2.png)

Don't wait on me to merge. I'm on vacation all next week.
Thanks!

**Comment by Ldsmiths** [comment]
Logo updated and merged
