### ISSUE TITLE
TNRIS Events Page

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#378]
@Ldsmiths Can you please change the circled paragraph on the [TNRIS Events ](https://tnris.org/events/) page to read:
The 2021 Texas GIS Forum is cancelled due to factors beyond our control. The new date is set for March 7-11, 2023. Location and further details to be announced. Please stay tuned for TNRIS event information and updates by following us on Twitter.
![TNRISevent](https://user-images.githubusercontent.com/7750220/128406859-7af83ac3-8463-4caf-a925-440ae27fa546.png)

**Comment by Ldsmiths** [comment]
@geochik I'll get this updated right away for you, but I want to double check that date first. _March 7-11, 2023_. Is that correct? I was thinking it would be 2022

**Comment by geochik** [comment]
I keep doing that!! Yes, the date is 2022.
