### ISSUE TITLE
Link to nowhere on GIS Community Recap

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#383]
This page: http://tnris.org/geographic-information-office/2015-05-14/gis-community-meeting-recap-2nd-quarter-2015/

See the "--> Read More about the 2014 NAIP Imagery" link as shown in this screenshot:
![image](https://cloud.githubusercontent.com/assets/697848/7662145/c2f1cf76-fb1e-11e4-910b-52b4b7515e88.png)

**Comment by christoball** [comment]
The code here is this: 
`[--> Read More about the 2014 NAIP Imagery](news/2015-01-09/naip-2014-statewide-aerial-available)`

Im not sure what's wrong here. Is there an issue with an internal link on markdown that has multiple directories? Other internal links that are only one i.e. [contact us](contact-us) work fine.

@wilsaj could you advise?

**Comment by wilsaj** [comment]
internal links should point to content file paths, not generated urls `news/2015-01-09/naip-2014-statewide-aerial-available` - usually these are the same, but they are slightly different for dated news articles because the articles use directory separator for dates

**Comment by christoball** [comment]
:+1: thanks :+1:
