### ISSUE TITLE
GIS Solutions Group Notes

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#384]
I am having trouble with the upload of GIS Solutions Group notes. Each time I try to upload a document into the API console, once I hit the save button, I get a 404 error. HELP!

**Comment by ghost** [comment]
Use Firefox.

**Comment by ghost** [comment]
@geochik can you upload the file now or do you still need assistance?

**Comment by ghost** [comment]
@geochik can you upload the file now or do you still need assistance?

**Comment by geochik** [comment]
All good. Closing.
