### ISSUE TITLE
GIS Community Video Upload

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#386]
Hello All - I am trying to upload the GIO Community meeting video to our youtube account under tnris.twdb@gmail.com. I got in, however, I don't believe I am in the correct account. I am using **tnris.twdb@gmail.com**. This account has no subscribers and no community videos. I can point someone to the S: drive on the TWDB network to retrieve and upload the video or, I can upload it myself with access to the correct account. 

Please advise

**Comment by geochik** [comment]
<img width="615" alt="Screen Shot 2021-09-03 at 1 01 48 PM" src="https://user-images.githubusercontent.com/7750220/132048809-f8aefc66-bae3-43d5-85f3-617f43bb3f02.png">
This is the account that should be used. I just don't have the credentials to get in.

**Comment by Ldsmiths** [comment]
Messaged @geochik with Youtube email and password

**Comment by ghost** [comment]
@geochik can you upload the video now or do you still need assistance?

**Comment by geochik** [comment]
Video is uploading now....will close this ticket!
