### ISSUE TITLE
StratMap Contracts page links update

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#387]
Greetings @ctrepka and @mitchellryant 
DIR changed their entire website which broke all our DIR Contract Page links [here](https://tnris.org/stratmap/stratmap-contracts/). Fun times. Are either of you able to update the links with the correct ones @ThorTheDestroyer just updated in this [spreadsheet](https://twdb-my.sharepoint.com/:x:/r/personal/felicia_retiz_twdb_texas_gov/_layouts/15/Doc.aspx?sourcedoc=%7B99F4992F-19D2-4926-B209-37677DCC1B2A%7D&file=StratMap%20Contractors%202020.xlsx&action=default&mobileredirect=true) DIR Contract Page field?

**Comment by ctrepka** [comment]
completed by @mitchellryant
