### ISSUE TITLE
TWDB URL

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#392]
I got the following email from TWDB Web Admin.

Hello Ryan,

I have just noticed that the TWDB URL on TNRIS is all pointing to http://www.twdb.texas.gov/.  Is it possible to update the links to https://www.twdb.texas.gov/?  There is supposedly some kind of redirect setup, but it has never worked for me. 

It’s not urgent, and I noticed just now.

Thank you. 

Jeff Lin
Web Administrator

**Comment by ghost** [comment]
Footer & https://tnris.org/about/

This might (will) extend to all sites we have.

**Comment by ctrepka** [comment]
fixed in commits 
https://github.com/TNRIS/tnris.org/commit/5cb0c2791cdace1d606c61065f8ad424e1d92e2d
https://github.com/TNRIS/tnris.org/commit/9ef9993d596838979418eb929f595a628ccc8820
