### ISSUE TITLE
Date Change for 2022 Texas GIS Forum

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#394]
@ctrepka - please change the date on https://tnris.org/events/ from March 7-11, 2022 to the accurate date range of **March 8-11, 2022**.
![DateChange](https://user-images.githubusercontent.com/7750220/144930033-277bf987-6a4f-4da3-8fda-14f20fa716f2.JPG)

**Comment by ctrepka** [comment]
fixed with 
https://github.com/TNRIS/tnris.org/commit/9e3bfab57317369aef5a2d1de0d9bbff8df41ce6
