### ISSUE TITLE
Add GIO Report to GIO Page

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#395]
@rachel-longoria 
Please add the GIO report (M:\GIO Report\Public_WebLink GIO Report 11-30-2021.pdf) to the GIO Page. I can will email the report to you as it would not upload here.

The Texas Water Development Board presents the 2021 Texas Geographic Information Landscape Report. This report is presented to the Governor, Lt. Governor, and Speaker of the House every 5 years. 

The primary focus of the report is to outline our accomplishments over the past five years and to call attention to the needs of the state for improved services using geographic information technology. Significant contributions were provided by state agencies with a vested interest in geographic information technologies to perform agency operations and serve the general public. The report will serve as a discussion document for state leadership and as a guide to fulfill the recommendations for each of the needs listed in the report.

Your thoughts and comments are appreciated. Send your feedback to GIO@twdb.texas.gov.
<Link to download report>

(It would be good to use a PDF doc viewer for visitors to view if download is not optimal. See https://tnris.org/geographic-information-office/2016-12-01/texas-geographic-information-landscape-inaugural-gio-report/)
Read using the document viewer below or download the PDF. For best results, use the Full Screen option on the document viewer.

**Comment by geochik** [comment]
Is it possible to get the GIO Report accessible via a weblink? I tried to drop it here but being it is a PDF (or maybe it's the file size), It will not take. I believe that is one way to make it accessible via a weblink. I am announcing its release and would like to point people to it.

**Comment by space-longoria** [comment]
@geochik I logged into the RDP Farm but I don't think I have access to the folder (M:\). Could you add the pdf file to the shared folder in onedrive? I can grab it from there and create a weblink (and then we can also add that weblink to the tnris site).

**Comment by space-longoria** [comment]
@geochik How does this look:

![image](https://user-images.githubusercontent.com/94866591/151215180-9e06b145-4a91-4f82-8277-818ac53f996c.png)

**Comment by geochik** [comment]
@rachel-longoria  BRAVO!!!
