### ISSUE TITLE
Lidar Index Wording

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#396]
Can we look into changing the line about the index on [lidar](https://tnris.org/stratmap/elevation-lidar/)? Currently the line is somewhat misleading.

![index](https://user-images.githubusercontent.com/8459928/148961925-528d0f02-1c45-4453-a39d-24f610068e61.png)

**Maybe to this:**
`You can [download](https://cdn.tnris.org/data/lidar/tnris-lidar_48_vector.zip) an index of best available lidar data at TNRIS. This index represents the best available data and not complete collections, especially where an old collection overlaps with a newer collection.`

**Context:**
The index does not contain every tile for every collection. The index was originally designed to help staff and customers locate data and collections. It is based on the Lidar Selector, which the RDC and internal TWDB (Texas Water Development Board) uses to located LPC (Lidar Point Clouds), DEM (Digital Elevation Models), or Hypsography files. 

discuss among yourselves.

**Comment by ThorTheDestroyer** [comment]
I agree and support. Here are my suggestions for language. 

_You can [download](https://cdn.tnris.org/data/lidar/tnris-lidar_48_vector.zip) an index of best available lidar data at TNRIS. This index represents the best available data and not complete coverage of all collections, especially where new collections overlap older collections._

**Comment by geochik** [comment]
Is it best? Or latest? If it is both, we can say:
_You can download an index of best available lidar data at TNRIS. This index does not contain complete coverage of all collections, especially where new collections overlap older collections._

**Comment by ghost** [comment]
it is best to cover the state and leave no holes. that index still had data from 2007-2010.

**Comment by space-longoria** [comment]
Fixed! :)
