### ISSUE TITLE
Geology Direct Download Disappears at Smaller Window Size

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#401]
The USGS is launching an app today that reference the GDbT, http://tnris.org/data-catalog/geology/geologic-database-of-texas/. 

If you narrow the window, the data download stuff just disappears all together.  That shouldn't happen right?  I would expect the download section to be added in line with the other content.  So when you click 'Get Data' from our app (txpub.usgs.gov/dss/texasgeology/), it pops up a new window pointing you to the TNRIS webpage for download.  783px x 600px is the size if you wanna try it.  No data download. It assumes that windows over a certain size are mobile devices and therefore should not be able to download data.

**Comment by christoball** [comment]
USGS fixed this by going to a new window instead of a small pop-up
