### ISSUE TITLE
Mobile Agenda Sponsor

### ISSUE THREAD

**Issue by space-longoria** [TNRIS/tnris.org#403]
Changed from Mobile App to Mobile Agenda

- [x] Add mobile sponsor logo to mobile version of site
 - [x] Wait until certain date? - date needs tbd

**Comment by rachel-longoria** [comment]
Changed from Mobile App to Mobile Agenda

- [ ] Add mobile sponsor logo to mobile version of site
- [ ] Wait until certain date? - date needs tbd
