### ISSUE TITLE
Filter Data Catalog by Source

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#410]
Would like to have a checkbox filter, probably underneath category list, that let's you filter by source so folks can easily access TWDB data, and future additions, etc.

![filter-example](https://cloud.githubusercontent.com/assets/1877550/8010112/182a487e-0b73-11e5-9e57-c607c20a6800.jpg)

**Comment by jseppi** [comment]
Modifying issue title to incorporate possibility of other types of filtering. What else do we want? We only have 157 current data sets, so we don't need to go too overboard with filtering options, but I agree that some would be a good idea. Can we brainstorm some filters?

cc @mitchellryant @wilsaj @christoball

**Comment by christoball** [comment]
A live keyword search at the top would be cool.

**Comment by mitchellryant** [comment]
functionality exist
