### ISSUE TITLE
TIS Form - Unable to select option for contractor access

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/tnris.org#411]
The Texas Imagery Service request link form has a required question that does not currently have a field/textbox for requested info. 
https://tnris.org/tis-request/

Required input (located below Organization): 
Are you requesting access on behalf of a contractor currently under contract with your agency? *

Missing fields are those list in the TNRIS API - Change Texas Imagery Service Request
![image](https://user-images.githubusercontent.com/23489372/151886068-e26809e2-c988-485c-bcc3-f6d0ce67d3de.png)

Please let me know if further explanation is needed.

**Comment by ctrepka** [comment]
Hi @csidenblad, can we confirm that the changes I've made have resolved this issue?

Verify on the dev site: 
https://staging.tnris.org/tis-request/

**Comment by csidenblad** [comment]
@ctrepka Yep looks correct on the dev site. 
Thanks for the quick fix
