### ISSUE TITLE
Data Disclaimer

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#413]
I would like to add a disclaimer to the download and data catalog pages.  something like this.

These products, data, and/or tools are for informational purposes only and may not have been prepared for or be suitable for legal, engineering, or surveying purposes. They do not represent an on-the-ground survey and represent only the approximate relative location of property boundaries. Mapping may not reflect on the ground conditions. The TNRIS makes no further claims as to the accuracy or reliability of the data, and neither assumes, nor will accept liability for their use. Use or reproduction of this data without acknowledging the TNRIS as the source is strictly prohibited.

@rwade2126 
@geochik

**Comment by wilsaj** [comment]
What about using a formal data license that includes language disclaiming liability? Such as: http://opendatacommons.org/licenses/pddl/

From what I understand, the data is already in the public domain and this would also clarify rights with regard to reuse and redistribution of data and derived products.

**Comment by mitchellryant** [comment]
Whatever is best. I just think we should have something on the site so we are covered. 

This is the one the RDC uses for LiDAR orders.

"TNRIS makes no guarantees, representations or warranties of any kind, express or implied, arising by law or otherwise, including but not limited to, content, quality, accuracy, completeness, effectiveness, reliability, and fitness for a particular purpose, usefulness, use or results to be obtained from this information. In no event will TNRIS be liable for any damages, including loss of data, lost profits, business interruption, loss of business information or other pecuniary loss that might arise from the use of these digital data."

**Comment by mitchellryant** [comment]
Just discussed with @rwade2126. He said you the open commons PDDL language, http://opendatacommons.org/licenses/pddl/.

Maybe just a statement saying the data is covered by the PDDL, and linking to the full description.

**Comment by wilsaj** [comment]
Yeah, I think the suggested text on the PDDL site covers it pretty well:

> This data is made available under the Public Domain Dedication and License v1.0 whose full text can be found at: http://www.opendatacommons.org/licenses/pddl/1.0/

**Comment by wilsaj** [comment]
As @jseppi points out, we should self-host a copy of the license either instead of or in addition to in case that site moves or goes down or something.

Also, in general we should try to include a copy of the license with downloaded products. I don't think we need to necessarily do this retro-actively, but just something to keep in mind when packaging data in the future.

**Comment by christoball** [comment]
I also like the portion with the graphics. It's very engaging and to me a way to be explicit about our approach to data.

http://opendatacommons.org/licenses/pddl/summary/

**Comment by jseppi** [comment]
Also note that if we copy the content of the license and host ourselves, we need to attribute the OKF, as their content is released under a Creative Commons Attribution license.

> Site content licensed under a Creative Commons Unported v3.0 Attribution license. - See more at: http://opendatacommons.org/licenses/pddl/1.0/#sthash.w4rYqm6E.dpuf

**Comment by jseppi** [comment]
Any movement on this @mitchellryant @wilsaj ?

**Comment by wilsaj** [comment]
Started a [public-domain-license](https://github.com/TNRIS/tnris.org/tree/public-domain-license) branch with a self-hosted version of the PDDL: 

https://deploy.tnris.org/api/v1/preview/653b02dd28053f9395d23df97604f33ee5984aaa/public-domain-license/

**Comment by jseppi** [comment]
@wilsaj Looks nice!

I think we need to have @rwade2126 verify that this license is 100% applicable to ALL of our downloadable data.

**Comment by mitchellryant** [comment]
I sent the the dev link to Management via email, to hard to get them to use GitHub.

**Comment by mitchellryant** [comment]
after some discussion @geochik thinks.

Mr Mitchell, I was not attempting to make your request more complicated, nor am I management. However, if you are asking my opinion, I think the language is a little confusing and should be summarized. 

What about this shorter version: http://opendatacommons.org/licenses/pddl/summary/

**Comment by KCMack** [comment]
The decision is up to Mr. Wade.  I support the abbreviated version Ms. Retiz offered because it answers the question.  And, I urge that the description be presented to the legal department to insure that they agree.

Kathleen C. Mack, PMP
Operations Manager
Texas Natural Resources Information System / 1700 N. Congress Ave., Austin, Texas 78701
Phone 512 463-4536 / Cell 512 415-3847
Kathleen.Mack@twdb.texas.gov<mailto:Kathleen.Mack@twdb.texas.gov> / www.tnris.texas.gov<http://www.tnris.texas.gov/>

**Comment by mitchellryant** [comment]
@KCMack Are you going to discuss this with someone in TWDB Legal, as you have a prior relationship and dealing with them?

**Comment by mitchellryant** [comment]
after much trials and tribulations, and so hard feelings, @rwade2126 says we are good.

Management would like to show this, http://opendatacommons.org/licenses/pddl/summary/, then expanding to the full description, https://deploy.tnris.org/api/v1/preview/653b02dd28053f9395d23df97604f33ee5984aaa/public-domain-license/

**Comment by wilsaj** [comment]
I am confuse. That **is** the summary followed by the full text of the license.

**Comment by wilsaj** [comment]
Not to throw a wrench into things, a perhaps simpler alternative is CC0, which is often used by the US federal government: https://creativecommons.org/publicdomain/zero/1.0/

**Comment by mitchellryant** [comment]
![wrench](https://cloud.githubusercontent.com/assets/8459928/8778376/2772a362-2ec3-11e5-8d80-4064410615f7.gif)

**Comment by mitchellryant** [comment]
i like the pddl better, can we just publish the full text on the deploy page as is. discussed with @jseppi what management would like, not his favorite idea.

**Comment by wilsaj** [comment]
@mitchellryant ping ping, what did we decide on this?

**Comment by mitchellryant** [comment]
I think we decided to go with the CC0 license over PDDL.

**Comment by wilsaj** [comment]
CC0 version for review: https://deploy.tnris.org/api/v1/preview/6b9c067dafc278df0b73aad471ad5da918587597/public-domain-dedication-summary/

Thoughts?

**Comment by jseppi** [comment]
:+1:

**Comment by mitchellryant** [comment]
looks good

**Comment by wilsaj** [comment]
Added link to bottom of data download page: https://deploy.tnris.org/api/v1/preview/793b35214258581e8f86e384ba944b2158251ea4/data-download/#!/statewide

And some CYA text to the dedication:
`This dedication does not
apply to any datasets for which TNRIS does not have ownership rights (including
some datasets linked from other parts of this website)`

Clear for takeoff?

**Comment by jseppi** [comment]
:rocket:

**Comment by jseppi** [comment]
should we maybe put a little public domain/no copyright image there to call it out a little bit?

![noun_669](https://cloud.githubusercontent.com/assets/697848/10248890/ffd1cbc6-68e7-11e5-8817-876556070960.png)

**Comment by wilsaj** [comment]
added the CC public domain badge, per our discussion
