### ISSUE TITLE
Updated DataHub Land Parcel & Address Point URLs on TNRIS.org

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/tnris.org#414]
Hey @rachel-longoria 

I was hoping you could help me update the links on the "Launch DataHub" buttons on the respective Land Parcel and Address Point project pages on the TNRIS.org site?

Currently, when opened, the links take the user to the 2019 project cards on DataHub.  The links for the most current 2021 projects are here:

Land Parcels:
https://data.tnris.org/collection?c=a3c04828-1036-481b-b1e0-bb456c3cbcf4#5.53/31.32/-100.121

Address Points:
https://data.tnris.org/collection?c=94502179-9389-4bfa-b753-5e43f6d477bf#5.53/31.32/-100.077

Please let me know if I can provide any other info. Thanks!

**Comment by space-longoria** [comment]
Is it okay if the links are updated and the old links are deleted? Moreso, is there any reason someone would need both the 2019 and the 2021 links? Just want to make sure I'm not deleting any content that people would still need to use. @LaurenKirk

**Comment by LaurenKirk** [comment]
@rachel-longoria 

Yes, you can delete the old links!  No need to have the 2019, we just want to keep that launch button up to date with the most current version.  I'll direct anyone to the 2019 project page if need be.  Thank you!!

**Comment by space-longoria** [comment]
@LaurenKirk Can you check [staging.tnris.org](http://staging.tnris.org/) to see if the links are correct/in the right place please?

**Comment by LaurenKirk** [comment]
@rachel-longoria Just checked staging.tnris.org, the "Launch Data" buttons on both the land parcel and address point project pages still take me to the 2019 project cards on DataHub.

**Comment by space-longoria** [comment]
Fixed and live
