### ISSUE TITLE
Texas GIS Forum Page and Education/Training Info.

### ISSUE THREAD

**Issue by pwblanton** [TNRIS/tnris.org#415]
Hi @rachel-longoria, on the Education section of the front page, we mention training classes are "through the fall". Please remove those words "through the fall".

Texas GIS Forum front page, we refer to the Commons Event Center, but on the Venue & Information sheet, we say the Commons Learning Center (which is correct). Felicia isn't sure you can change the front page.

Last item I noticed: would it be possible to hyperlink the Keynote Speakers to their web pages? I think we've done that in the past and it allows our readers to read more about them.

Those are just my thoughts. Thanks! Patricia

**Comment by space-longoria** [comment]
@pwblanton Unfortunately I was sent a graphic with the wrong text already on it from CMP. We're working on getting a blank version of the graphic so this can be fixed. I'll log these as separate issues so we can keep an eye on it. :)

**Comment by space-longoria** [comment]
On the Education section of the front page, we mention training classes are "through the fall". Please remove those words "through the fall". #417

Texas GIS Forum front page, we refer to the Commons Event Center, but on the Venue & Information sheet, we say the Commons Learning Center (which is correct). Felicia isn't sure you can change the front page. #418

Would it be possible to hyperlink the Keynote Speakers to their web pages? I think we've done that in the past and it allows our readers to read more about them. #419
