### ISSUE TITLE
Bad Link for Sponsorship Rules/Regulation

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#416]
@rachel-longoria 
When I click on the Rules/Regulation link, I get the following:
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>documents/Rules and Regulations 2022.pdf</Key>
<RequestId>VZDP931KKREV0MCT</RequestId>
<HostId>Fmyw1i4VyW5RjR5PVjsx9ReNGiPkm//LaGbmzFVhquHrX7D2vgjBZW6RykeRxjSZhSSgc6R7O7o=</HostId>
</Error>

**Comment by space-longoria** [comment]
Fixed!
