### ISSUE TITLE
Do TWDB datasets need data download button?

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#419]
Currently, the new twdb sets have the data search and download showing up on their pages.

We don't need to have this, since they're hosted elsewhere, right? We'd need to remove the "T" from the 'download' column.

**Comment by mitchellryant** [comment]
I removed the T from the column, I thought it was needed to have the direct download appear.

**Comment by christoball** [comment]
cool, I'll update to the new CSV.
