### ISSUE TITLE
Historical Pricing Updates

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/tnris.org#42]
Add pricing blurb on the RDC Historical Imagery Archive page. Please use the similar formatting to pricing in cart and add just under contacts on page. See image below. 

![historicalpricingupdates](https://user-images.githubusercontent.com/23489372/65532972-720d3280-dec2-11e9-8d6a-99da6ade0bb9.PNG)

**Historical Imagery Costs**
Historical search (1 image per decade): $40.00 per site
Single year search: $18.00 per site
Scanned historical frame: $10.00 per image
Scanned + georeferenced historical frame: $20.00 per image
Digital download (0 - 10GB): $7.00

**Data Reproduction Costs**
This pricing is only available for collections that have been fully digitized. 
Staff time: $46.00 per TB
Server/computer time: $0.15 per GB
TNRIS provided USB flash drive (64 GB): $40.00
TNRIS provided external hard drive (1 TB): $100.00

**Comment by christoball** [comment]
@csidenblad everything look good? preview here: http://washburn.tnris.org/research-distribution-center/historical-imagery-archive/

**Comment by csidenblad** [comment]
@christoball Looks great. Thanks for updating Chris
