### ISSUE TITLE
Acquire Keyword Supremacy for tnris.org!

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#423]
GLO must be struck down!

How might we unleash our SEO powers upon them? @jseppi @wilsaj @mitchellryant 

![image](https://cloud.githubusercontent.com/assets/1877550/8138854/40100026-1114-11e5-9928-206587a2f77b.png)

**Comment by jseppi** [comment]
Ha, we show up first for "texas gis **data**"

I think we basically just have to use the term "texas gis" more often on our site, especially in page titles and headers.

**Comment by mitchellryant** [comment]
We are second though, that is pretty good. Why so competitive?

![mad-max-tom-hardy-thumbs-up](https://cloud.githubusercontent.com/assets/8459928/8138920/ee31c1da-1114-11e5-9fbb-c4ce47f1b099.gif)

**Comment by christoball** [comment]
Furiosa didn't stop 'til she was on top.

**Comment by jseppi** [comment]
:100:
