### ISSUE TITLE
GIS Community Meeting Video

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#423]
@rachel-longoria The 1st quarter GIS Community video is now uploaded to our Youtube account. Can you please add to the GIO Page and Tweet out that it is available? Thank you!

https://youtu.be/AnQ5Wm2PBpA

**Comment by space-longoria** [comment]
- [x] Replace current GIO report link to **open old report**
- [x] Move parcel report to parcel data page
- [x] Add new GIO report link to page to **open new report**
- [x] Add GIS community video to page
- [ ] Tweet w/ graphic

**Comment by space-longoria** [comment]
@geochik will you take a look at the site [here](http://staging.tnris.org/geographic-information-office/) to make sure it looks okay?

**Comment by geochik** [comment]
Looks good on my iPhone! I would say we need to remove the “inaugural” word since it is the 2nd report. No need to say 2nd report. I would also remove the parentheses around the dates. So it would be:
GIO Report 2021
GIO Report 2016

**Comment by space-longoria** [comment]
Done!
