### ISSUE TITLE
Applications & Utilities

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#427]
The GEMSS application has been turned off, could you please remove or comment out reference on this page https://tnris.org/applications-and-utilities/
![image](https://user-images.githubusercontent.com/8459928/156625854-a50ce1fc-4a81-4ebd-9da5-fde68a937816.png)

**Comment by space-longoria** [comment]
@mitchellryant Hey Ryan, can you check [staging.tnris.org](http://staging.tnris.org/applications-and-utilities/) to make sure all of the information is correct? Thanks!
