### ISSUE TITLE
Dead DataHub Link

### ISSUE THREAD

**Issue by A-M-Pearce** [TNRIS/tnris.org#429]
The "Launch DataHub" Button within the [Historical Imagery Archive page](https://tnris.org/research-distribution-center/historical-imagery-archive/) on tnris.org is dead and does not function properly. When possible, @space-longoria would you please replace the link with this one:

https://data.tnris.org/?category=Historic+Imagery&pg=1&inc=24#5.5/31.33/-99.341

Thank you!

**Comment by space-longoria** [comment]
@A-M-Pearce Hi Aaron, can you check [staging.tnris.org](http://staging.tnris.org/research-distribution-center/historical-imagery-archive/) and make sure the link is working now? Thanks!
