### ISSUE TITLE
Add enter email box to GIO page

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#433]
On the old site there was an option to enter an email address if you wanted to keep up with the latest GIO announcements. Please add to current GIO page.

"Enter your email address to receive meeting announcements and periodic news regarding the Geographic Information Office."

**Comment by jseppi** [comment]
Where did those email addresses get collected?

**Comment by geochik** [comment]
GIO@twdb.texas.gov

**Comment by jseppi** [comment]
What I mean is where did the entered email addresses get stored? Some mailing list software, or did you manually enter each one into Outlook?

**Comment by jseppi** [comment]
I don't know of any mailing list software currently in-use here. Maybe we should evaluate some because I imagine there are other instances where we might want to have subscribers to various email channels.

**Comment by geochik** [comment]
Okay sounds good. I'll table this for now. Thanks!

**Comment by jseppi** [comment]
Let's keep it open so we don't forget :)

**Comment by christoball** [comment]
I've advocated for us to have our own email list for a while (rather than just using CMP). I thought that we send stuff out sometimes on our own?

If something does happen, we should start by making sure we have all the forum email lists.

**Comment by jseppi** [comment]
@geochik - Has there been any movement on mailing list software or services? MailChimp seems pretty good and is free for up to 2000 subscribers: http://mailchimp.com/pricing/entrepreneur/

**Comment by geochik** [comment]
@jseppi -- yep, I'm using MailChimp. Is there a way to integrate MailChimp to enlist subscribers from our site?
![thechimp](https://cloud.githubusercontent.com/assets/7750220/10248979/759fae2c-68e8-11e5-88ab-bfdda9ece9e0.JPG)

**Comment by jseppi** [comment]
I believe so. I'll need to get the account credentials from you (don't post here).
