### ISSUE TITLE
Update registration link for Learning ArcGIS Pro: 1: Maps & Projects on Education page 

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/tnris.org#437]
@space-longoria 

Looks like the registration link for the Learning ArcGIS Pro: 1: Maps & Projects course is linked to Getting Started with Arcade.

![image](https://user-images.githubusercontent.com/23489372/163250830-3a9cfc48-5a06-48a1-ad9d-e458fcd957f5.png)

Can we please update link to point to correct registration?

**Comment by ghost** [comment]
fixed!
