### ISSUE TITLE
Add carousel graphic highlighting the 2022 video and that presentations are available - 4/18

### ISSUE THREAD

**Issue by lebell** [TNRIS/tnris.org#439]
Ideally, this can go up next Tuesday, 4/18 to coincide with our planned tweets.

Let's plan to keep it up for a month.

**Comment by space-longoria** [comment]
- [x] Create graphic for main carousel
- [x] Add forum video to events page
- [x] Add forum video to 2022 forum page
- [ ] Add graphic to main carousel
