### ISSUE TITLE
Use new CartoDB logo in GIS Forum banners

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#446]
Here is the one they've asked us to use:

![](https://cartodb-libs.global.ssl.fastly.net/cartodb.com/static/logos_full_cartodb_light.png)

@christoball please modify the 2015 Forum banners and any other graphics to use this version.

**Comment by jseppi** [comment]
I changed it in the Platinum Sponsors section in e9e1a0077c0c604dd1eaab8ca5bf645655c06fe3

**Comment by wilsaj** [comment]
looks like this has been taken care of - we good to close this @christoball ?

**Comment by christoball** [comment]
Yes :thumbsup:
