### ISSUE TITLE
Speaker Deck

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#447]
I received a request (see below) to remove some slides from an old slide deck visible on our Speaker Deck account. I attempted to log onto Speaker Deck using the credentials I had stored, but to no avail. Can I get some assistance getting into the Speaker Deck account so I can remove the slides as requested?
![Screen Shot 2022-06-13 at 9 39 38 AM](https://user-images.githubusercontent.com/7750220/173611679-6475ff91-43f5-4e99-bc03-feb88e5a750f.png)
Here is the email request:
Hi, Felicia:
 
I hope you are doing well.
 
I recently came across the slides I presented at the 2019 TNRIS Forum. Because of a development in our open records policy, there are certain screenshots we are no longer able to release. Would it be possible to remove my slides from the following website?
 
https://speakerdeck.com/texasnaturalresourcesinformationsytem/leveraging-python-to-automate-gis-updates-and-reporting-in-an-appraisal-district
 
Any help is greatly appreciated,
-Keith
 
 
cid:image001.png@01D50BF4.7D368B30
Keith R. Dailey; MS, GISP
GIS Director
Bexar Appraisal District
411 N. Frio St., San Antonio TX 78207
210.242.2530
[KDailey@BCAD.org](mailto:KDailey@BCAD.org)

**Comment by space-longoria** [comment]
@geochik The slides should be removed now.
