### ISSUE TITLE
Mis-spelling - 6/15

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#448]
https://tnris.org/geographic-information-office/gis-solutions-group/

![image](https://user-images.githubusercontent.com/8459928/173827317-6bea0736-72f8-41d1-a88f-c45f502fc6f0.png)

**From:**
![image](https://user-images.githubusercontent.com/8459928/173827422-a10b94c6-6c05-4ded-b2dc-48b76d15fcfb.png)

**Comment by space-longoria** [comment]
Fixed
