### ISSUE TITLE
StratMap Contracts special announcement

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#45]
@christoball Could you please post the following, perhaps in a red box, on the StratMap Contracts page? Including @ThorTheDestroyer for review. Thanks!

Special Announcement: After four years of success, the re-bid of these contracts is coming up this **November 2019**! For the solicitation release date and other official posting information, please see the [DIR Current Contracting Initiatives](https://dir.texas.gov/View-Information-For-Vendors/Current-Contracting-Initiatives/Landing.aspx) site. The new Request for Offer is listed as:

_Geographic Information Systems (GIS) Hardware, Software, and Services and Information Technology (IT) Based Land Surveying Hardware, Software and Related Services

DIR-CPO-TMP-444 Geographic Information Systems (GIS) Hardware, Software, and Services and Information Technology (IT) Based Land Surveying Hardware, Software and Related Services_

**All current contract holders are required to re-submit.**

**Comment by christoball** [comment]
@gmullins what do you think of this?
http://haish.tnris.org/stratmap/stratmap-contracts/

**Comment by ghost** [comment]
@christoball Perfect. Can you bold November 2019? Good to go after that.
