### ISSUE TITLE
Fallback when typekit doesn't load

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#451]
I think we need a fallback to show the page when typekit is blocked or otherwise won't load.
We've had a report from a user who cannot see the page at all, likely due to some issue with typekit being blocked on his network.

**Comment by wilsaj** [comment]
I thought the same thing, but webfontloader is used to load typekit and it has a timeout that s/b firing if typekit fails to load

**Comment by jseppi** [comment]
Hmmm, ok...we've asked the customer to send us output from the developer console. Maybe that will give us a lead.

**Comment by jseppi** [comment]
Closing this. Turned out to be the customer's router apparently truncating content. Should still do #453 however.
