### ISSUE TITLE
3rd Qtr 2022 GIO Community Meeting Video

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#452]
The video along with the CC files are ready for posting to the GIO page. This files can be found here - https://twdb-my.sharepoint.com/:f:/g/personal/felicia_retiz_twdb_texas_gov/Ep0CqZ5awUdKrWsal3WdyIQBwNRQL4tbAZNpjFDTavvIxg?e=3C4g9R

Edit:
- [x] Add video and .srt file to Youtube
- [x] Embed Youtube video to GIO page
- [x] Add past video to tnris api to show up in side nav
- [x] Post tweet

**Comment by space-longoria** [comment]
Updated.

**Comment by space-longoria** [comment]
Complete
