### ISSUE TITLE
Update Public Lidar Availability Index Link

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#453]
Page: https://tnris.org/stratmap/elevation-lidar/

Location:
![image](https://user-images.githubusercontent.com/8459928/185657326-f78c5cce-628d-4e42-a425-46bcba5149cd.png)

Old: https://cdn.tnris.org/data/lidar/tnris-lidar_48_vector.zip
New: https://cdn.tnris.org/lidar-availability/tnris-lidar_48_vector.zip

FYI: @ThorTheDestroyer

**Comment by space-longoria** [comment]
Updated.
