### ISSUE TITLE
Need to remove typekit fonts

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#453]
cc @wilsaj 

We strongly need to consider not using fonts from typekit. The way they have to be loaded results in poor UX in a number of circumstances.
1. At its best we have to add a hide/show to the whole page while the fonts load. This is why the site fades into view every time a page is visited.
2. If we remove the fading, then the site loads with an unstyled font then the font jumps into place once it is loaded from typekit.
3. If typekit goes down or has an interruption, our site has to wait some amount of time and then show the unstyled font after a significant delay.
4. If other javascript breaks on the page it could prevent the typekit font from loading, which can result in the page never showing any content.

We should choose a font(s) that we can either self-host or that can be loaded in a normal fashion (from Google for instance). We could either purchase the one we are currently using or use one with an amenable license to self-hosting.

**Comment by wilsaj** [comment]
:+1:
