### ISSUE TITLE
Education Page Update

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#456]
@space-longoria 
The Education page is in dire need of updating. Attached are screenshots of what needs to be addressed on the TNRIS homepage and the education page. Additionally, the Education page language requires a message change - see attached Word doc. I am available to discuss and will defer to your design experience. Thank you!
![FrontPg_EduRemove](https://user-images.githubusercontent.com/7750220/189797133-10791768-ddb4-4d60-9229-01ab349fd29a.png)
![EduPage_Adjust](https://user-images.githubusercontent.com/7750220/189797149-79230c9e-a4af-4f07-8d4e-a8bbff93b201.png)
[Edu_PageLanguage220912.docx](https://github.com/TNRIS/tnris.org/files/9553151/Edu_PageLanguage220912.docx)

**Comment by space-longoria** [comment]
![education-page-revised](https://user-images.githubusercontent.com/94866591/192040715-75b5898c-b14b-4e42-8a58-4042b1ec816b.png)
