### ISSUE TITLE
StratMap Contracts Page: Logo and Link Conflict

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#457]
@space-longoria just an FYI, noticed a conflict of one of our vendors logos and links on the contract page not resizing appropriately at a few window sizes(see example below). 

![image](https://user-images.githubusercontent.com/8398036/191540117-a702ea43-3807-4209-bf72-1ea4316891b9.png)

**Comment by space-longoria** [comment]
oof, thanks for the catch. I'm on it

**Comment by space-longoria** [comment]
Fixed!
