### ISSUE TITLE
Addition to the FAQs on the Texas Imagery Service Project Page

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/tnris.org#458]
Hey @space-longoria,

I'd like to add a new FAQ under the "General FAQs" section at: https://tnris.org/texas-imagery-service/

The question could read: "How frequently is the Texas Imagery Service Updated?"

The answer is: "The **goal** of the Texas Imagery Service is to serve orthoimagery at full statewide coverage every other year.  Currently, the TIS has two statewide flights scheduled for 2022-2025.  Please reach out to us via our Contact Form for further details as needed."

Thanks Space! Let me know if you need anything else

**Comment by space-longoria** [comment]
@LaurenKirk This is done. I also fixed the excessive space in between questions
