### ISSUE TITLE
Shifting up Front page, adding events feature

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#46]
@KCMack I wanted to feature the keynotes on the front page in a cleaner way, so I put them on the side where the training was, but with the training it became a lot. Is it ok if we take off the training for now and bring it back after the forum, especially since the season is closed and we dont have new courses yet?

Preview this here:
http://glidden.tnris.org/

**Comment by KCMack** [comment]
Really good idea.  Thanks!
