### ISSUE TITLE
Use pointer hand for mouse on data download

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#460]
When navigating on the data download between counties, quads, etc, would be helpful to have the pointer icon instead of just the arrow in order to indicate interactivity/clickability.

![image](https://cloud.githubusercontent.com/assets/1877550/8558114/b3947d62-24c7-11e5-9f6e-af1fdc594c9a.png)

**Comment by wilsaj** [comment]
:+1:

**Comment by wilsaj** [comment]
:point_up_2:

**Comment by christoball** [comment]
@wilsaj or this one when we're feeling sassy.

![image](https://cloud.githubusercontent.com/assets/1877550/8558290/d1b058e2-24c8-11e5-874c-14bceb4563d8.png)

**Comment by christoball** [comment]
:open_mouth:
