### ISSUE TITLE
Adjust bulk downloader section at https://tnris.org/applications-and-utilities/

### ISSUE THREAD

**Issue by ctrepka** [TNRIS/tnris.org#464]
Hey @space-longoria,

I'd like to make some adjustments to tnris.org, specifically related to the bulk downloader section. Here's an outline of suggested tasks:
- [x] Move bulk downloader from column on right-hand side to main applications column
- [x] Provide updated thumbnail of bulk downloader
- [x] Provide direct links to the Windows and Linux compressed archives from tnris.org as opposed to linking to the s3 bucket html list here http://bulk-download-output-110722.s3-website-us-east-1.amazonaws.com/

**Comment by space-longoria** [comment]
@ctrepka As of now, the applications are listed in this order:

1 -DataHub
2 - Flood Viewer
3 - Interactive State Water Plan

Where should the bulk downloader fall on this list? I'm thinking maybe after the Datahub.

1 - DataHub
2 - Bulk Downloader
3 - Flood Viewer
4 - Interactive State Water Plan

**Comment by space-longoria** [comment]
http://staging.tnris.org/applications-and-utilities/
