### ISSUE TITLE
File upload error

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#468]
![fileupload](https://cloud.githubusercontent.com/assets/8459928/8599214/caf13208-2624-11e5-8168-1525101b9050.PNG)

Any ideas on the error? This was from a test I tried. Zip file was only 7MB

**Comment by jseppi** [comment]
@mitchellryant could you send me the zip?

**Comment by jseppi** [comment]
Looks like it fails on anything. Working on it.

**Comment by jseppi** [comment]
This was @wilsaj's fault. Reassigning.

**Comment by wilsaj** [comment]
![](http://i.imgur.com/wfT8VL7.gif)

**Comment by mitchellryant** [comment]
![trampoline_dunk1](https://cloud.githubusercontent.com/assets/8459928/8602221/bedf834a-2636-11e5-9700-f7b76ff669e8.gif)

**Comment by wilsaj** [comment]
fixed now

![](http://i.imgur.com/mrwUQqC.jpg)

**Comment by mitchellryant** [comment]
![fireworks1](https://cloud.githubusercontent.com/assets/8459928/8602347/7eb77dda-2637-11e5-8682-6a7dbb61408c.gif)
