### ISSUE TITLE
Add StratMap Vendor to StratMap Contract Page

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#468]
@space-longoria Please add VertiGIS to the stratmap contract webpage. 

Vendor website for logo : https://www.vertigis.com/
DIR website: https://dir.texas.gov/contracts/dir-cpo-5192
Vendor DIR Website: not published yet

**Comment by space-longoria** [comment]
@ThorTheDestroyer, which of these do they offer:
- [ ] products
- [x] services
- [x] software

**Comment by ThorTheDestroyer** [comment]
@ Space They do software and services.  I would also change products to hardware if you are going to start adding descriptors.  Under this contract are GIS hardware, services, and software.

**Comment by space-longoria** [comment]
@ThorTheDestroyer Does it make sense to change products to hardware for all of the contracts? I'm not adding anything new, it's just the icons we currently use. I'll add a picture as reference:

![image](https://user-images.githubusercontent.com/94866591/225974012-bc015454-7c37-4d03-8b79-973a7da6223c.png)

**Comment by ThorTheDestroyer** [comment]
@space-longoria hmm well I see that a lot of vendors that don't sell hardware that have products listed, so maybe keep it as it is at the moment. I'm not sure who previously made these category selections so I'm unclear on what the criteria was.  I'd say leave them as.

**Comment by space-longoria** [comment]
Okay, I'll leave them as is for now. We can definitely discuss the definition of these categories and whether or not they're useful separately. Maybe we can rope Gayla into that conversation as well, she may have a better understanding than both of us!

**Comment by space-longoria** [comment]
Content for review [here](http://staging.tnris.org/stratmap/stratmap-contracts/). Pushing to live site by EOB.

**Comment by ThorTheDestroyer** [comment]
@space-longoria  Looks great! Thank you very much.
