### ISSUE TITLE
Upload GIS Community Agenda

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#478]
Need to upload new agenda PDF file to http://tnris.org/geographic-information-office/

PDF file location: \\twdb4aefssvr\vault\Admin\GIO\2015QrtlyMtgs\2015\Qtr3

Did my best to make it accessible. Can someone help upload to site? Thanks!

**Comment by jseppi** [comment]
Any reason these agendas can't just be pages on our site? That would be a lot more accessible than PDFs, and will be easily indexable by search engines.
cc @christoball

**Comment by geochik** [comment]
Not from my view.

**Comment by jseppi** [comment]
What's going on with this @christoball and @geochik ?

**Comment by geochik** [comment]
@jseppi -- First time I've seen this. I'll get with Chris to make that change.

**Comment by christoball** [comment]
closing this, planning on making future agendas a post within site.
