### ISSUE TITLE
form uploads

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/tnris.org#48]
in migrating the contact app to api.tnris.org, testing on the Job Board form yielded buggy behavior for file uploads. although almost all uploading was removed from the site, test the uploading capabilities on any forms to verify it is still working. Forum Job Board form definitely should be supporting uploads. Georodeo speaker submissions should too although there are no instances of this currently on the site. Any other locations that support uploads on tnris.org we could test??

**Comment by christoball** [comment]
@adambreznicky I verified with @mitchellryant that the forum job board the only place on tnris.org that has uploads currently. 

AOI uploads are now on Datahub

**Comment by adambreznicky** [comment]
looks like one on https://tnris.org/texas-imagery-service/ contact form also when the reason is an issue.

image upload failed on this one too insofar as i can tell

**Comment by adambreznicky** [comment]
resolved 2bfea7d7fdc12a7af82970842ba20876398dbf43

**Comment by adambreznicky** [comment]
@christoball i fixed contact app form uploads syntax. the fix is currently in both develop and master branches. be sure to merge these changes into the other branches as you work on them so they don't get overwritten accidentally. thanks!
