### ISSUE TITLE
Broken links on "latest data" on home

### ISSUE THREAD

**Issue by aziza-twdb** [TNRIS/tnris.org#481]
- [x] /static/js/datahub.js/ (done)
- [x] /static/js/latest_stratmap.js/ (done)
- [x] /static/js/maps.js/ (done)

fix javascript, constructed links are broken Make sure they have a "?c=" before the section that ... fill dom list element with collection detail (builds the URL basically)

**Comment by space-longoria** [comment]
Approved and pushed to live site
