### ISSUE TITLE
Carousel height fix

### ISSUE THREAD

**Issue by space-longoria** [TNRIS/tnris.org#489]
The carousel is built for specific sizes images (21x9). Comms gave us a graphic that is shorter, which is causing the page to break when the carousel switches to the graphic. Can we make the carousel uniform no matter the image size without compromising the image quality?

**Comment by aziza-twdb** [comment]
I put some style in there to ensure no matter what picture you put in it's not going to have a jarring jump anymore. The other pictures were just fine it was just the TxGIO banner. I believe whoever made it made it too skinny in height. I suggest telling creators using a Photoshop or AI canvas/template size
16x9
1520x 650 canvas size is most accurate to laptop view of website.
I can optimize always myself when I get tasked to update the site when I receive PS in my machine, I put in ticket.

**Comment by space-longoria** [comment]
Waiting on new graphic from Comms

**Comment by space-longoria** [comment]
changes pushed to tnris.org

**Comment by space-longoria** [comment]
Taking care of this one so it can get closed out. @aziza-twdb you will need to sync your local instance with dev

**Comment by space-longoria** [comment]
Changes pushed to live site
