### ISSUE TITLE
Add meta data in the head on forum 2023 pg

### ISSUE THREAD

**Issue by aziza-twdb** [TNRIS/tnris.org#494]
data is pulled from the site metadata, and that's how it populates the information on the card. So we just have to make sure that the metadata we have on the backend of our site is actually pulling from the page or linked..... then see if you can figure out hownto do it for full site

**Comment by space-longoria** [comment]
Adding myself to this issue for support. Let's try to get this knocked out before EOD so Gwen can send a tweet!

**Comment by aziza-twdb** [comment]
Universal fix to to the injection of meta tags on the events page, I saw the entire site struggled with this so I went to the files that edited the Head on all pages and try to input it there.

**Comment by space-longoria** [comment]
changes pushed to tnris.org
