### ISSUE TITLE
Time-enabled auto-scroll for Forum Agenda page

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#498]
At TXJS that @wilsaj and I went to a few weeks ago, we were impressed that during the conference, when we visited their agenda page, it automatically scrolled to the block of talks for the current actual time. I think we could pretty easily implement this for our forum agenda page. What do you think @christoball?

**Comment by christoball** [comment]
Sounds awesome let me know how i can help implement.

**Comment by christoball** [comment]
I had to hard code the agenda for customization purposes, but I"m guessing we'll need to have IDs for each time section?

**Comment by jseppi** [comment]
Yeah basically we'll just have an anchor or an id for each time block, and some simple javascript that checks if it is currently a day of the forum, and then checks the time and moves the page to the correct anchor.

**Comment by jseppi** [comment]
@christoball You can probably tell from the markup I added in `2015-gis-forum.md`, but in case you need to change the schedule around, all you have to do is make sure the divs that hold times look like this:

```html
<div class="col-sm-3 col-md-2 time-block" id="DayOne_0700">
  7:00 - 8:30 a.m.
</div>
```

Note the `time-block` class and an id of the form `DayOne_HHMM` (or `DayTwo_HHMM`), where HHMM is 24-hour style times.
