### ISSUE TITLE
m.link not working for news article

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#499]
I can't figure out why this internal link isn't working for this news article. It just generates a blank link

`<a href="{{ m.link('news/2015-07-16/ucgis-fellow-david-cowen-keynote-forum')}}">Full Bio</a>`

**Comment by wilsaj** [comment]
because you need to link to the markdown file: `news/2015-07-16-ucgis-fellow-david-cowen-keynote-forum`

**Comment by christoball** [comment]
Thanks :+1:

**Comment by wilsaj** [comment]
![](http://www.reactiongifs.com/r/lvar.gif)
