### ISSUE TITLE
Beta QC- Hydrography

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#5]
Can we change the _Overview of the Watershed Boundary Dataset_ picture so that when it is clicked on it will pop out larger or change the size of the image? At the moment you can't read any of the numbers for the huc boundaries.

**Comment by christoball** [comment]
@ThorTheDestroyer take a look and see if this is what you were looking for. I've made the image enlargeable.

http://haish.tnris.org/stratmap/hydrography/

**Comment by ThorTheDestroyer** [comment]
Looks Great! Thank you.
