### ISSUE TITLE
Update Booth sizes on website

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#51]
The correct sizes follow:
Platinum sponsors = 8x20 booth. 
Gold and Silver Sponsors = 8x10 booth. 
Exhibit only exhibitors = 8x8 booth.

**Comment by christoball** [comment]
@KCMack booth sizes updated, see changes here:
http://ellwood.tnris.org/texas-gis-forum/2019/sponsors-and-exhibitors/

**Comment by KCMack** [comment]
Looks great.  Thanks
