### ISSUE TITLE
Use consistent capitalization for LiDAR / lidar/ LIDAR

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/tnris.org#510]
LiDAR / lidar/ LIDAR is capitalized differently around the site. For example, this page uses all three: http://tnris.org/data-catalog/elevation-lidar/capcog-2012-140cm/

I know there is not a universally correct capitalization, but we should probably pick one and be consistent with it.

**Comment by mitchellryant** [comment]
replace all to Lidar. will be corrected on site with next push.

**Comment by wilsaj** [comment]
:+1:

**Comment by jseppi** [comment]
Reopening. There are articles and other pages that need to stick with our decided capitalization: "Lidar."
cc @ThorTheDestroyer @christoball @gmullins 
Existing articles need to be adjusted to be consistent.

**Comment by mitchellryant** [comment]
ongoing thing item, writer of news article needs to remember
