### ISSUE TITLE
Adding Texas Historic Overlay download to Data Catalog

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#513]
I would like user to be able to download the Texas Historic Overlay. Due to the footprint of the files it can not be added to the existing data download. I would like to make a static site out of the existing s3 bucket tnris-tho bucket. I have tried using the console and the existing files but I have been very unsuccessful.  

Could you look at it see what I'm doing wrong?

**Comment by wilsaj** [comment]
On it

**Comment by wilsaj** [comment]
Sorry for delay, was side-tracked by website errors. Is good now: [http://tnris-tho.s3-website-us-east-1.amazonaws.com/](http://tnris-tho.s3-website-us-east-1.amazonaws.com/)

For future reference, the whole process is documented at [https://github.com/TNRIS/data-download/tree/master/s3-bucket-listing](https://github.com/TNRIS/data-download/tree/master/s3-bucket-listing). The thing that was missing was the CORS policy.
