### ISSUE TITLE
Fort Bend 2006 cm Lidar status map broken

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/tnris.org#514]
Looks like it was assigned a bad a `status_map_cartodb_id` in the csv.

cc @mitchellryant

**Comment by mitchellryant** [comment]
Dataset was replaced by the TNRIS 2014 Fort Bend data. Not sure how we are handling retired or obsolete datasets in the catalog.

**Comment by wilsaj** [comment]
We have to keep the `status_map_cartodb_id` field clean, since putting notes and info in there will gives us a broken status map. For short term solution, I'd say add something in the description text that says that it has been deprecated and either leave at field blank or link to a working status map.

For a longer term fix, we can try to have a special note somewhere prominent that says something to the effect "Newer versions of this data are available... <link>"?

**Comment by mitchellryant** [comment]
i will recreate the coverage map.

**Comment by wilsaj** [comment]
cool

**Comment by mitchellryant** [comment]
new cartodb coverage map has been created and id place on google sheet

**Comment by jseppi** [comment]
This has been resolved
