### ISSUE TITLE
Data Catalog link to related datasets

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/tnris.org#517]
Continuing discussion with @mitchellryant from #514 -

There are some datasets that have been updated multiple times. For example, we have two lidar datasets for Fort Bend, from 2006 and 2014.

Would be nice to link to more recent versions of datasets when they are available, so users who end up on a catalog page for will know that they can get the more recent data if they want it. I think we should also make this more general and link to older datasets, too, for people who might be interested in comparing for change detection and that sort of thing.

How this would work:

I'd propose adding a csv field called `related-group` that takes a string as a group id. It should be descriptive, but can be anything as long as it is shared between entries. Using Fort Bend as an example, we could use `fort-bend` as the group id. So to set up the relationship, you would set `related-group` to `fort-bend` for both rows in the CSV.

Then the catalog entries could automatically link to each other. This could should also be general enough to work for multiple (more than 2) related datasets like NAIP, potentially.

cc @christoball

**Comment by jseppi** [comment]
Per discussion yesterday, implement this for the GAT datasets as an experiment.

For datasets that are superceded by more recent versions, we will probably need a different field from just a relationship class since the relationship has directionality.
