### ISSUE TITLE
Additional sponsors

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#52]
Razor-Tek - Exhibitor
Intrado -  Silver
![Intrado-color-tagline](https://user-images.githubusercontent.com/4912083/65909269-daaa5280-e38d-11e9-90eb-b7e7408659a7.jpg)

**Comment by KCMack** [comment]
@christoball

**Comment by christoball** [comment]
@KCMack Intrado doesn't have it's own website it all just goes to West still. Advice?

**Comment by christoball** [comment]
they have this on their main page so i'll just link to West
<img width="1003" alt="Screen Shot 2019-09-30 at 3 23 36 PM" src="https://user-images.githubusercontent.com/1877550/65913957-54463e80-e396-11e9-9602-6a8b2485a1b0.png">

**Comment by christoball** [comment]
@KCMack sponsors updated, preview here:
http://ellwood.tnris.org/texas-gis-forum/2019/

**Comment by KCMack** [comment]
Thanks!
