### ISSUE TITLE
Incorrect keynote speaker name - "Humphreys"

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#524]
Looks like the new keynote speaker's last name is "Humphreys" not "Humpreys" https://www.ae.utexas.edu/faculty/faculty-directory/humphreys
I think the keynote speaker image and several instances of text in eb3a1fb7fc94fcf1d33f2a420393181619a5b2cf needto be fixed.

**Comment by christoball** [comment]
im fixing it right now, i realized when i pushed it

**Comment by jseppi** [comment]
:+1:

**Comment by jseppi** [comment]
fixed in 7fe6808731e3a4afddcb126a36e2fd74416114d2
