### ISSUE TITLE
Laura Chapa's bio

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#53]
Please update her session with her bio:
Laura Chapa is a GIS Analyst for the Landscape Ecology Program at Texas Parks and Wildlife Department. Since joining TPWD in 2014, Chapa has worked on mapping Texas vegetation statewide, as well as Conservation Opportunity Areas for Texas species of greatest conservation need. Over the past year, she has devoted her time to mapping potential breeding habitat for an endangered species, Houston Toad. Chapa earned a BS in Biology and MS in Sustainability from Texas State University, wherein her thesis involved using an UAV to map vegetation along a riparian corridor.

@christoball

**Comment by christoball** [comment]
@KCMack her bio has been updated, preview here:
http://ellwood.tnris.org/texas-gis-forum/2019/agenda/#two-B-1030-c

**Comment by KCMack** [comment]
Looks great.
