### ISSUE TITLE
Forum Agenda Update 8.26

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#538]
@christoball 
Please add the following to the forum agenda:

Thursday, October 29, Session B - 2:00-3:30 p.m.
1st presentation - Connecting the Dots Between Data and Problem Solving, Leah Casey, Texas Department of Health and Human Services and Jeff Jordan, Institute for Demographic Studies and Socioeconomic Research
3rd presentation - 3 Words to Address the World, Tim Williams, What3Words

**Comment by christoball** [comment]
resolved in #539
