### ISSUE TITLE
Data Catalog - Don't hide Data Access / Download Data Set on smaller screens

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#549]
Some of our users are on smaller screens, and on those screens the Data Access column gets hidden. We need to make sure that section is still shown on all screens so that users don't get confused/surprised when they can't see it (eg, the email from Lucia).

![no download](https://cloud.githubusercontent.com/assets/697848/9606486/42a22080-5089-11e5-8c6f-f54890e03ed8.jpg)

**Comment by christoball** [comment]
Working on it, need to make sure it looks good when included.

I still think that for the XS, which is handheld mobile  (or ridiculously narrow window) doesn't need it. 

@jseppi @wilsaj  do you agree?

**Comment by jseppi** [comment]
I kinda think we should show it still on XS just in case someone resizes their browser or whatever. Maybe just pushed to near the bottom of page.

**Comment by wilsaj** [comment]
I'm with @jseppi - screen size doesn't guarantee what type of device it is.

**Comment by christoball** [comment]
Here's my proposed solution. It's shown on everything but XS, at which point it collapses and is expandable by clicking:
https://deploy.tnris.org/api/v1/preview/d02ff0d56d02a07d5b90fac4a154a5d33f4bb505/data-catalog/aerial-orthoimagery-regional/bexar-county-2003-nc/

**Comment by christoball** [comment]
I think I solved the issue:
https://deploy.tnris.org/api/v1/preview/0246a0aecaf0eb0ae90eabe9b1aeef01f704151a/data-catalog/aerial-orthoimagery-regional/bexar-county-2003-nc/

**Comment by christoball** [comment]
resolved in #550
