### ISSUE TITLE
Data Category Selector for small screens

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#554]
First run at Data Catalog selector @wilsaj @jseppi 

https://deploy.tnris.org/api/v1/preview/1a44fc3d499d9ccedff88f6477aacb2eaf5c0ed6/data-catalog/

**Comment by christoball** [comment]
Trying to see if it's possible to push down where the anchor tag jumps to so the title isn't blocked by the selector.

How do you feel about the fixed selector? I think it makes navigating easier to always have instead of only being able to use it once when you're at the top.

**Comment by wilsaj** [comment]
I like the dropdown selector behavior, but I'm not sure about it being fixed to top of the screen.
- It's tricky to get right, and a behavior that doesn't exist elsewhere on our site, so is kind of jarring.
- It eats into screen space which is scarce on smaller screens.
- Is only useful for jumping between categories. I'm not sure how big a need this actually is. Selecting with the dropdown follows an anchor link so just going back (swipe left->right) would get you to the top of the page with the original select/dropdown anyway, so this only shaves off 1 simple gesture.

**Comment by christoball** [comment]
I've updated it to remove the affixing to the top. Do y'all think this will do the trick? @wilsaj @jseppi 

https://deploy.tnris.org/api/v1/preview/fce6747484b9c4e2d24279d8ff7ee03ce8835e98/data-catalog/

**Comment by jseppi** [comment]
Looks like the `site.js` is still causing the affix to happen: https://github.com/TNRIS/tnris.org/blob/fce6747484b9c4e2d24279d8ff7ee03ce8835e98/static/js/site.js#L54

That code is targeting `.nav-cat` which is also a class on the small screen version, so either site.js needs to change, or the small screen container for the dropdown needs that class removed.

**Comment by christoball** [comment]
Thanks, I thought I had fixed it, but got it now. If it looks alright, I'll go ahead and push.

https://deploy.tnris.org/api/v1/preview/75fd0262644430497fc67de0cb2a79a8c1c808bb/data-catalog/

**Comment by jseppi** [comment]
:+1:
