### ISSUE TITLE
Forum Agenda - Ability to 'Star' talks

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#563]
Suggested by @christoball - He'll do the markup and I'll implement with JS using localStorage to save user's starred talks.

**Comment by christoball** [comment]
Got a version to play with in the branch star-forum-talks.

Let me know if I can adjust anything.

**Comment by jseppi** [comment]
Sweet! I'll get going on it. :star:

**Comment by christoball** [comment]
I've added the individual times to each presentation and readded the checkbox @jseppi

**Comment by jseppi** [comment]
Cool, I add back in the hide/show toggling.
