### ISSUE TITLE
Land Parcels Data Release and News Article

### ISSUE THREAD

**Issue by ilyannakadich** [TNRIS/tnris.org#57]
@christoball  
[News10012019.docx](https://github.com/TNRIS/tnris.org/files/3678473/News10012019.docx)

Chris, I have the attached for release on the website.  Is it possible to add an inset of the Carto map into the end of the article?  If not, I can grab an image.  Let me know if you have any questions.  Thanks, Ilyanna

**Comment by christoball** [comment]
@ilyannakadich @geochik @gmullins preview article ready here:
http://frye.tnris.org/news/2019-10-03/land-parcels-transformed-into-common-schema/

**Comment by ilyannakadich** [comment]
Looks great!  Let's see if @gmullins has any comments.

**Comment by geochik** [comment]
Two thumbs up from me!

**Comment by ghost** [comment]
Looks good to go to me!
