### ISSUE TITLE
Broken markup on Custom Maps page

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/tnris.org#578]
https://tnris.org/maps-and-data/custom-maps/ is all sorts of janky:
![screen shot 2015-09-17 at 4 50 29 pm](https://cloud.githubusercontent.com/assets/303866/9946990/764f3a8c-5d5c-11e5-8b30-1384877437e0.png)

**Comment by mitchellryant** [comment]
it would be helpfully to give a basic cost breakdown.
Staff time
Printing fee
Paper charge.

**Comment by wilsaj** [comment]
I'm referring to just formatting stuff, not content. There's a lot going on:
- "...fill out a custom map order form at (link) and include ..."
- ###Custom Fishing Map
- Empty "Printed Dimensions"
- inconsistent capitalization of words

**Comment by wilsaj** [comment]
@mitchellryant do you have an example of the cost breakdown language you want added?

**Comment by mitchellryant** [comment]
Custom work: $36.40
Map fee: $0.10 per linear inch
Printing fee: $4.50

**Comment by wilsaj** [comment]
Per our conversation, there is a new comprehensive pricing page in development so we'll leave pricing info off of this page for now

**Comment by wilsaj** [comment]
has been fixed with  #684
