### ISSUE TITLE
Possible Error on Order Form.

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#583]
User:
Question or Comments: Hello I'm trying to submit an inquiry/order on your order line and the recaptcha system won't validate. Is it because I'm using a Mac?

TNRIS Data Support:
We did receive your your order. You should be hearing from TNRIS RDC staff today. To help us troubleshoot the form error I will need some additional information?

What version of os X?, What internet browser?, What version of that browser?

User:
OSX 10.10.5
Browser: Safari
Version: 8 (Yosemite)

I hope this helps - Here is what I recall about placing this order.
It was the second time I had started filling out the form and I was deflated by having to input all the info again, so before embarking on inputting all that, I pushed the “Not a Robot” button. 
Your order form does not like auto-input information, which my computer likes to do. It entered an email address that the order form did not like. I erased and entered a different one.
I hit the submit button without answering one of the questions (about the external drive, I think)
I tried to fix it and submit it, but could not get the Robot button to acknowledge me as a person.

Hope this information helps.
And thanks so much for a response from a real person!

**Comment by mitchellryant** [comment]
Not sure if the is actually a problem, but I told her I would have one of our Developers look into it. Based on my experience with her last week, I thinking user error.

**Comment by jseppi** [comment]
Possibly related to #584

**Comment by wilsaj** [comment]
The recaptcha should present an image-based recaptcha challenge if it thinks someone might be a robot; auto-filling does trigger this sometimes. Is the recaptcha challenge that not happening for her?

I can't reproduce on my system (same OS & browser).
