### ISSUE TITLE
Data Catalog Update 

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#589]
The following entries have been added to the data catalog. 
HPIDS 2015 NC-CIR 6in Brazos and Palestine (images M:\Admin\Website\DataCatalogImages\tnris)

images unknown @ThorTheDestroyer 
City of Lubbock
TPWD 2015 Galveston Island State Park
TNRIS 2015 Brazos Lidar

**Comment by ThorTheDestroyer** [comment]
M:\IS\Staff\Ledesma\LiDAR_announcements

**Comment by christoball** [comment]
Where are the images for hpids_brazos_and_palestine_2015_6in_nc_cir?

**Comment by ThorTheDestroyer** [comment]
Ask Gayla

**Comment by mitchellryant** [comment]
Will the images be moved the standard location for the data catalog images? and will they be renamed to match the naming convention?

M:\Admin\Website\DataCatalogImages

**Comment by mitchellryant** [comment]
can @ThorTheDestroyer or Intern Stokes copy\move and rename the images to the main location?

**Comment by ThorTheDestroyer** [comment]
yes, i'm sure we are both able.

**Comment by jseppi** [comment]
https://en.wikipedia.org/wiki/Modal_verb

**Comment by ThorTheDestroyer** [comment]
done
