### ISSUE TITLE
Around the State Update

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#592]
Please update the "Around the State" page to feature Sterling Harris, an early contributor to GIS rules and reports. Interview and pictures attached. Retirement date is 9/30/2015.

![sterling harrs 2014](https://cloud.githubusercontent.com/assets/7750220/10179325/de62ecdc-66ca-11e5-9e78-87a79ff2a0b4.JPG)
![capitol of texas](https://cloud.githubusercontent.com/assets/7750220/10179330/e497f03e-66ca-11e5-91f9-45bf02df5cb5.JPG)
![img_5328](https://cloud.githubusercontent.com/assets/7750220/10179335/e90dea7e-66ca-11e5-8873-09a236801dac.jpg)
[SterlingHarris_InterviewResponses.xlsx](https://github.com/TNRIS/tnris.org/files/4749/SterlingHarris_InterviewResponses.xlsx)

**Comment by christoball** [comment]
@geochik Would it be possible for him to get us a higher res version of the photo of him in front of the capitol?

**Comment by geochik** [comment]
I tried to get a higher resolution. They sent this to see if it might work better.....
![b-25 yellow rose](https://cloud.githubusercontent.com/assets/7750220/10201584/6be0c1d6-6772-11e5-9212-bd9401d9b6b1.JPG)

**Comment by wilsaj** [comment]
:-1:
