### ISSUE TITLE
High Water Mark Data Dictionary

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#595]
Received this Data Dictionary file from Ben. He thinks we should include it in the data catalog or perhaps with the HWM download (it could be put in the zip).

[Data Dictionary for Texas Highwater marks inventory_update.docx](https://github.com/TNRIS/tnris.org/files/5386/Data.Dictionary.for.Texas.Highwater.marks.inventory_update.docx)

**Comment by mitchellryant** [comment]
sure, i'll convert to pdf an add to zip file, maybe tomorrow.

**Comment by mitchellryant** [comment]
word doc was converted to pdf, added to tnris-hwm_tx.zip on tnris-datadownload s3 bucket.

@ThorTheDestroyer @mpavon
