### ISSUE TITLE
Main Contact page - Simplify Reasons choices

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#597]
Just like in #585

**Comment by jseppi** [comment]
Or maybe since that form doesn't change too much, just default the Reason radio to General Inquiry.

**Comment by wilsaj** [comment]
I like that

**Comment by mitchellryant** [comment]
i do not

**Comment by wilsaj** [comment]
![we are at an impasse](http://33.media.tumblr.com/tumblr_mcis3zHZO61rdrgrio1_400.gif)

**Comment by wilsaj** [comment]
Per our discussion, we are going to:

1. Simplify available reasons to only two options:
  - General Question or Comment
  - Help with Data

2. Only show rest of the form fields after one of those has been selected

**Comment by wilsaj** [comment]
Also include a third reason option:
 - Order Data or Get Pricing Information

That, when selected, just shows a text pointing people to the order form page
