### ISSUE TITLE
Order Form Description

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#605]
Welcome to the Research and Distribution Center's order form.

Please use this form to get a quote or order the amount of data that you need, Digital Data, Historical Imagery, LiDAR, and Maps. Price is based on the amount, in GB, of data ordered plus staff and reproduction cost.

Please fill out all the information below and TNRIS staff will begin processing your order. You will be sent quote before any work begins. After receiving the quote you can proceded or cancel the order. Order for data request are completed in 3-10 business days.

For other inquiries please use the general contact form.

**Comment by wilsaj** [comment]
How's this...


This form is used to request pricing information or order data. The cost will be based on the amount staff time and reproduction cost.

Please fill out all the information below and TNRIS staff will begin processing your order. You will be sent a quote before any work begins.  After receiving the quote, you can proceed or cancel the order. Orders are completed in 3-10 business days.

For other inquiries please use the general contact form.

**Comment by jseppi** [comment]
:+1:

**Comment by mitchellryant** [comment]
Very good!!
