### ISSUE TITLE
poster-submission template inconsistency

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/tnris.org#63]
within every 'year' folder for the texas-gis-forum templates (templates/events/texas-gis-forum/<<year>>/) is a "poster-submission.njk" template file that is never used. every event year page has a "poster-gallery" page/template and each one calls the same partial from 2015 for the poster submission form, `{% include "partials/2015-forum/poster-submission.njk" %}`, while the poster-submission.njk for that year goes unused.

this should be cleaned up to create consistency and remove unused files. i see 2 ways to clean it up, either:
1. delete all the unused poster-submission.njk files from all the forum year folders. then move the shared poster-submission form template out of the 2015-forum partial folder into a properly descriptive location in the file structure. then update all the poster-gallery includes to use this new location.
2. update all poster-gallery includes to point toward the proper poster-submission.njk for that particular year

i think solution 1 is more correct considering all poster-submission templates are exactly the same. multiple duplicate files justifies a properly, shared partial and removal of the unnecessary excess.

**Comment by christoball** [comment]
@adambreznicky I've applied solution 1 in the following commit.

7d9a301044542a959a426e58984c63e83d5e47dd
