### ISSUE TITLE
Data Catalog update FEMA 2015 lidar, TOP 2015 Imagery, and TxDOT Airports

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#638]
Can you update the data catalog to add the new FEMA 2015 lidar and the TOP 2015 imagery? 

Images for TOP 2015 - M:\Admin\Website\DataCatalogImages
Images for FEMA 2015 lidar - M:\IS\Staff\Ledesma\LiDAR_announcements\FEMA_2015

Dataset TxDOT Airport and been renamed to TxDOT Public Airports per TxDOT request.
Images - M:\Admin\Website\DataCatalogImages\txdot

Also some minor word changes has occurred within the google sheet.

**Comment by christoball** [comment]
resolved in #688
