### ISSUE TITLE
online map service tooltips partially hidden

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/tnris.org#644]
Tooltips on the OMS page are being partially hidden, so they look bad and are not very readable.

![online-map-tooltips](https://cloud.githubusercontent.com/assets/303866/10555314/cdd8198a-7432-11e5-8eb9-0166dbe5c88c.gif)

Do we even need these? Can we get rid of them? The messages themselves seem kind of obvious.

cc @christoball  @jseppi

**Comment by jseppi** [comment]
I think they can be removed
