### ISSUE TITLE
switch template engine to nunjucks?

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/tnris.org#647]
swig templates library is no longer maintained (see: https://github.com/paularmstrong/swig/issues/628)

nunjucks looks pretty solid, is actively maintained (backed by mozilla) and should be mostly compatible in terms of syntax and concepts, but I expect a few small differences exist that will make it less than a complete drop-in replacement

**Comment by jseppi** [comment]
dang

**Comment by wilsaj** [comment]
Shelving this for the moment. This is actually going to be a healthy bit of work and it looks like some maintainers are stepping up.
