### ISSUE TITLE
web map services: Lidar availability index link is missing

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/tnris.org#649]
should update catalog csv with a valid link, or drop wms_category so it does not get listed

cc @christoball  @mitchellryant 

![screen shot 2015-10-19 at 12 05 45 pm](https://cloud.githubusercontent.com/assets/303866/10584845/e2e16902-7659-11e5-8fbf-d54dd56ce706.png)

**Comment by mitchellryant** [comment]
no wms service exist for this entry, we have a web map hosted in AGO. i think it should be removed from the wms page.

**Comment by wilsaj** [comment]
Sounds good

**Comment by jseppi** [comment]
@mitchellryant status?

**Comment by mitchellryant** [comment]
The wms_link was removed, I guess I did not understand I needed to remove the wms_category also. that has been done. on next update it should be removed from the wms page.
