### ISSUE TITLE
front page highlights section images should be links

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/tnris.org#685]
All of the images on the front page are within anchor elements (clickable links) that take you to their respective section of the site (banner article, statewide ortho program, around the state) except for the ones in the highlights bar:

![screen shot 2015-11-06 at 2 58 56 pm](https://cloud.githubusercontent.com/assets/303866/11008608/3a30219e-8497-11e5-9bc6-0dc44470307d.png)

These should be also be links, I think. In that case, we can also drop the "Learn More" buttons which will give a horizontal.

@christoball what do you think?

**Comment by christoball** [comment]
Word. will do.
