### ISSUE TITLE
fill out download_lvl for catalog entries

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/tnris.org#687]
This will allow us to provide direct search UI elements for the catalog entries. Valid options are:
- `state`
- `county`
- `quad`
- `qquad`

If they are provided at multiple levels, they should be comma separated (no spaces). For example: `county,qquad`

**Comment by mitchellryant** [comment]
values added to entries. left blank where data is not downloadable

**Comment by wilsaj** [comment]
We'll also need to identify which datasets have are available at roughly in all counties and/or quads (see the discussion at #698). 

Sorry to throw another thing at you @mitchellryant - but can you add a `statewide_coverage` field and set it to `true` for those that have statewide coverage in data download?

**Comment by jseppi** [comment]
Is this finished?

**Comment by mitchellryant** [comment]
yes
