### ISSUE TITLE
Forum Social Description

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#69]
We still don't have the details up for the social, which we would also need on the program.

**Comment by KCMack** [comment]
Forum Social at the Commons Center
Relax, catch up, and enjoy food, and fun in the Atrium at the Commons Center.  Enjoy delicious appetizers, beverages, music and games.
![2019 Forum Games](https://user-images.githubusercontent.com/4912083/66527519-25307b00-eac2-11e9-8959-cba0093972de.png)
![And more games](https://user-images.githubusercontent.com/4912083/66527525-282b6b80-eac2-11e9-997c-4bba4ddab2a0.png)
![Games](https://user-images.githubusercontent.com/4912083/66527529-2b265c00-eac2-11e9-8530-2d00d74ddecc.png)
![More games](https://user-images.githubusercontent.com/4912083/66527533-2e214c80-eac2-11e9-8608-20bb3590d05c.png)
