### ISSUE TITLE
Data Catalog - Show Data Download County and Quad search boxes

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#698]
On catalog entry pages, use the `download_lvl` field to show County and/or Quad search boxes that launch directly to the appropriate Data Download page.

Related: #687

**Comment by wilsaj** [comment]
We'll need to filter to available counties and quads for datasets that don't have statewide coverage, else it will be confusing. For example, the HPIDS datasets that have small coverage areas are generally only available at quad/qquad level. We can't expect people to know quad names, so they'll most likely end up somewhere random in Texas that won't have the data. Not great.

Instead, if we can populate the dropdowns and search with only relevant quads then users will at least land somewhere that has the data and can navigate to their area of interest.

Filtered county and quad lists are required for datasets that don't have statewide coverage. We can't currently do this filtering - so we should probably shelve this until we get our updated data download backend off the ground. Catalog entries will also need to be associated with data download dataset codes so the entry page knows how to ask which county/quads have data for the dataset.


In the meantime, we can still get this going for datasets with statewide coverage.
