### ISSUE TITLE
Data Catalog Search and Filtering

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#699]
Starting an issue to propose ideas and show mockups for the next big re-working of the Data Catalog.

Below is a mockup inspired by istockphotos: http://www.istockphoto.com/photos/maps

**Desired features**
- Search Bar
- Category drop down filter
- Sort By filter:
  - best match
  - year

**Other possible filters**
- Type/Format
- Time Range
- Source
- Access
- Coverage
  - Statewide
  - Regional

![data-catalog-nov-10](https://cloud.githubusercontent.com/assets/1877550/11073762/cac10404-87b1-11e5-9277-c9154324ec26.jpg)

**Comment by christoball** [comment]
For reference, looking at Google's 'material' style guide for inspiration and ideas:
http://www.google.com/design/spec/components/cards.html#cards-usage

**Comment by christoball** [comment]
Notes:

- Add filter for **Access**

**Comment by adambreznicky** [comment]
reference commit a6039cd7cd0e7d3ea5bd8023a82f4dc903076416
-fixed href broken link bug
-created live card counter
-added access type filter
-rearranged sort options into horizontal button group
-consolidated filter options into a collapsible pane
-updated recovery function to retrieve last sorting/filtering/search results. sorting/pane display reliant on sessionstorage
-removed 'jump to' category functionality
-resolved digital raster cards' category bug
-added additional search attributes for each dataset. searches now include source, coverage extent, agency, & date added
-created 0 results dialogue
-added sort by category

**Comment by christoball** [comment]
When adding the first category, the way the **pill-nav-container** div expands is a little jumpy, because it just adds in the 'clear filters' button after.

It should continue the smooth downward expansion as the clear filters button comes in.

**Comment by adambreznicky** [comment]
reference commit 942730fd5d73f03f709476a73a06c3421b57818d
-fixed the jumpy pill container slide.
