### ISSUE TITLE
Catalog entry TWDB Submitted Driller's Reports: change "Driller's" -> "Drillers"

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/tnris.org#718]
Grammatical error. These are reports from submitted drillers, not reports that belong to a single Submitted Driller.

FWIW, it has been written both ways on the TWDB site: 
- as Drillers here: http://www.twdb.texas.gov/groundwater/data/drillersdb.asp
- as Driller's here: http://www.twdb.texas.gov/mapping/

The first one of those is the page focused on the database itself, so a more legit source.

**Comment by mitchellryant** [comment]
google sheet changed to Drillers. will change on next data catalog update.

**Comment by christoball** [comment]
resolved with #722
