### ISSUE TITLE
Use Separate 'Staging' Sheet for Upcoming Datasets

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#720]
I'd like to request that we place any new dataset in the '**Staging**' Sheet instead of directly onto the main sheet on the Google Doc

We need a copy of the sheet that is most current to the existing datasets, that we can manage and make edits to in lieu of adding new datasets, especially before I've added the images.

There are times when I still haven't uploaded images when we may need to make a quick edit to the data catalog. I can incorporate the new datasets into the master once an issue is created saying that all the images are ready.

I've currently placed the TCEQ datasets and a couple others onto the staging sheet while I add the TPWD and GLO data.

For edits to existing datasets, making it directly to the master is no problem. 

If this seems okay with everyone, can we follow this workflow from now on?

Ping @mitchellryant @ThorTheDestroyer @wilsaj @jseppi

**Comment by jseppi** [comment]
Sounds good

**Comment by wilsaj** [comment]
Sounds good to me. Has the staging sheet been shared w/everyone?

**Comment by wilsaj** [comment]
oh wait I see what you did - it's just a different tab

**Comment by ThorTheDestroyer** [comment]
No problem
