### ISSUE TITLE
No Images for TWPD Trails/GLO Oil Gas Nominations

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#721]
I may be overlooking them, but I can't identify the images for **TPWD State Park Trails** data set and the **GLO Oil & Gas Lease Sale Nominations**

**Comment by mitchellryant** [comment]
M:\Admin\Website\DataCatalogImages\glo\glo_oil_gas_lease_sale_nominations_detail.jpg
M:\Admin\Website\DataCatalogImages\tpwd\tpwd_state_park_trails_detail.jpg
