### ISSUE TITLE
Remake Some GLO Overview Images for Coastal Data

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#723]
For the GLO datasets focused on the coast, there's no need for the full statewide overview. Could we regenerate to have the coast fill the extent, as in the image below? Note that we need a **little bit of padding on the bottom** to account for the Blue info bar.

![image](https://cloud.githubusercontent.com/assets/1877550/11307522/612445cc-8f7e-11e5-9dd5-8b1619d7cb29.png)

**GLO Three Marine League Line**
https://tnris.org/data-catalog/entry/glo-three-marine-league-line/

**GLO Three Nautical Mile Line**
https://tnris.org/data-catalog/entry/glo-three-nautical-mile-line/

**GLO Priority Protection Habitat Areas**
https://tnris.org/data-catalog/entry/glo-priority-protection-habitat-areas/

**GLO Environmental Sensitivity Index Shoreline**
https://tnris.org/data-catalog/entry/glo-environmental-sensitivity-index-shoreline/

**GLO Pipelines and Miscellaneous Easements**
https://tnris.org/data-catalog/entry/glo-pipelines-and-miscellaneous-easements/

**GLO State Submerged Lands**
https://tnris.org/data-catalog/entry/glo-state-submerged-lands/

**GLO State Tracts with Resource Management Codes**
https://tnris.org/data-catalog/entry/glo-state-tracts-with-resource-management-codes/

**GLO Species/Habitats**
https://tnris.org/data-catalog/entry/glo-species-habitats/

ping @mitchellryant @ThorTheDestroyer

**Comment by mitchellryant** [comment]
all images have been regenerated.
