### ISSUE TITLE
Add Resources Page to Education & Training

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#726]
Includes links to third-party training resources

**ESRI**

**TeachmeGIS**

**Geospatial Training Services**
Geospatial Training Services provides GIS training in various formats including classroom, live-online, instructor-guided, online, and self-paced.  We provide training for ArcGIS Server, ArcGIS Desktop, ArcGIS Online, ArcGIS Pro, Google Earth, Google Maps, and Open Source software.

Eric Pimpler GISP, 215 W Bandera #114-104, Boerne, TX.  eric@geospatialtraining.com, 210-260-4992, http://geospatialtraining.com

ping @KCMack

**Comment by wilsaj** [comment]
How is that going to be curated? Just vendors that have partnered with us on trainings?
