### ISSUE TITLE
add data license to catalog entries?

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/tnris.org#738]
Catalog entries should describe the data license where possible. For example, TNRIS-hosted datasets would all be under CC0.

**Comment by christoball** [comment]
Like this?

![image](https://cloud.githubusercontent.com/assets/1877550/11352541/9774b220-9202-11e5-958e-cee7498254a2.png)

**Comment by wilsaj** [comment]
was thinking as a row in "More Details" since the license can vary for other datasets

**Comment by christoball** [comment]
I'm assuming anything we hostd directly is under the CC0. What are the other licenses?

Do we need to add a license field to the CSV?

**Comment by wilsaj** [comment]
Anything we host is CC0 but that maybe not true for the data from other agencies we are going to add to the catalog (TCEQ, GLO, TPWD). There is no defined set of licenses since they can be any custom legal, but there are a few established ones to keep in mind like CC0 and it might be nice to show logos for those where possible. We can just play it by ear to see what licenses other agencies are using.

Yes, I think adding a column to the CSV would be the way to do it.

**Comment by wilsaj** [comment]
The data-catalog CSV now contains licenses and frontend changes are good to go. We need to review the license listings for external datasets before publishing. Specifically, we should make sure USGS and TxDOT data are actually licensed under CC0 (and not just *generally* in Public Domain or some other license).

Might be a good idea to link to the license from the data source, so users can directly verify license terms with the data sources.

**Comment by mitchellryant** [comment]
completed
