### ISSUE TITLE
PLSS on data-download?

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/tnris.org#740]
The pages for the PLSS datasets are listed as being available on our data download page, but they aren't actually:
- http://tnris.org/data-catalog/entry/plss-section
- http://tnris.org/data-catalog/entry/plss-township

So either they should be added to data download, or not listed as available. I'm thinking it's the second one, since that is kind of an esoteric dataset.

**Comment by mitchellryant** [comment]
Texas was not a Public Land Survey System, PLSS, state. PLSS for Texas only exist for counties along the border with OK, NM, AR, and LA.  For Texas the closest thing we have is Original Texas Land Survey, OTLS

https://en.wikipedia.org/wiki/Public_Land_Survey_System

All that being said you can remove it if you want.

**Comment by wilsaj** [comment]
To be clear: I'm not talking about removing the catalog entry, just talking about removing the link to data-download since they aren't available at data-download (in the cast `data_download` shouldn't be `T` in the CSV).

**Comment by wilsaj** [comment]
my bad - it is available at the county level
