### ISSUE TITLE
data catalog change feed

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/tnris.org#741]
would be a nice feature to have a view that shows what datasets have been added, removed or updated

**Comment by mitchellryant** [comment]
I talked to @christoball about using the bottom right hand corner of the front page, under the data spotlight, to show recently added entries. recently added data_added field to google sheet.

**Comment by wilsaj** [comment]
Nice! Can I request that dates be formatted as YYYY-MM-DD for easy parsing?

**Comment by mitchellryant** [comment]
that is the format @christoball requested. so done!

**Comment by mitchellryant** [comment]
catalog can sorted by date
