### ISSUE TITLE
Forum Video Uploads

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#742]
@christoball Please upload all past Forum Keynote videos, in addition to the Forum keynote videos recently received, and make available from tnris.org.

Thank you!

**Comment by christoball** [comment]
We've sent the Mockumentary, and keynotes for Patrick Meier and David Cowen to Matt Erickson for captioning.

We didn't get video of the Humphries keynote, or it didn't turn out correctly, based on what @rwade2126 told me.

**Comment by geochik** [comment]
@christoball  Oh boo. I heard too. What about 2013 and 2014 videos?

**Comment by jseppi** [comment]
@christoball @geochik any updates on this issue?

**Comment by geochik** [comment]
@jseppi 2014 and 2015 videos are up. 

@christoball Do we have video for 2013 keynotes?
