### ISSUE TITLE
Data Catalog - update

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#745]
please update the data catalog. the following datasets have been added to the data download. download field in google sheet has been populated.

ibwc11-nc-6in
lrgv11-cir-6in-mcallen
lrgv11-nc-6in-cameron
lrgv11-nc-6in-hidalgo
usgs08-nc-30cm-border
usgs09-nc-30cm-amarillo
usgs09-nc-30cm-lubbock
usgs09-nc-30cm-mcallen
usgs12-nc-30cm-amarillo
usgs12-nc-30cm-elpaso
usgs13-nc-30cm-dfw
usgs14-nc-30cm-corpuschristi

**Comment by christoball** [comment]
Sorry, I accidentally closed this and cant figure how to reopen. @mitchellryant do you have to be the owner to repoen?

**Comment by christoball** [comment]
Actually, I'll just update the sheet right now.
