### ISSUE TITLE
Data Catalog: Include NC and CIR preview images

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#747]
For datasets that are released in NC and CIR versions, include both.

We've been creating data catalog entries with just Natural Color.

@mitchellryant can you coordinate with @gmullins on those datasets when they come up in the future?

I can go back and add CIR previews to existing datasets in the catalog.

**Comment by mitchellryant** [comment]
im just biased against cir. so i do not make images for it.

**Comment by christoball** [comment]
**needed for**
- HPIDS Brazos 2011 6in\1ft NC\CIR
- HPIDS Brazos 2013 6in\1ft NC\CIR
- HPIDS Brazos and Palestine 2015 6in NC\CIR
- HPIDS Galveston 2009 6in NC\CIR
- HPIDS Houston 2013 1ft NC\CIR
- HPIDS Smith 2010 1ft NC\CIR
- HPIDS Smith 2014 6in NC\CIR
- HPIDS University Lands 2015 6in NC\CIR
- National Agriculture Imagery Program (NAIP) 2010 1m NC\CIR
- National Agriculture Imagery Program (NAIP) 2012 1m NC\CIR
- National Agriculture Imagery Program (NAIP) 2014 1m NC\CIR

**Comment by mitchellryant** [comment]
WPD has been modified to have PM create data catalog images. With this change I'm sure more CIR images will appear.
