### ISSUE TITLE
Updates: 2015 Statewide Ortho Project Year in Review

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#748]
After talking to @rwade2126, we're proposing this as a main banner story for the TNRIS home page.

Article will highlight that the 2015 TOP is available through download, but still incomplete. Will illustrate current data, what's anticipated and discuss acquisition status and any other information we want to get out there.

Will also highlight the currently available buyups that have been released.

Would like to shoot for releasing this early next week if possible. Will remain in the banner through December and Late January pending the next main banner story.

@gmullins I can help in any way you need me to facilitate writing and putting this together. I think it will be a really cool update.

**Comment by gmullins** [comment]
Sounds great! I'll start some content and get with you @christoball

**Comment by gmullins** [comment]
@christoball I've started putting graphics here: M:\SM\HPIDS\2015 Projects\580150618 Ortho\Web page\2015 Year in Review

**Comment by gmullins** [comment]
@christoball 

Graphics captions:

Alan Henry Reservoir in Garza County acquired on Jan. 1, 2015 at 0.5-meter resolution, SCALE 1:30,000

Crop irrigation near Dell City, TX and Guadalupe Mtns. acquired on April 18, 2015 at 0.5-meter resolution, SCALE 1:30,000

Lake Meredith in Hutchinson County acquired on Oct. 29, 2014 at 0.5-meter resolution, SCALE 1:40,000

Oil pad in Winkler County acquired on Mar. 12, 2015 at 6-inch resolution, SCALE 1:700

Oil pads in Andrews County acquired on Mar. 22, 2015 at 6-inch resolution, SCALE 1:4,000

Palo Duro Canyon State Park in Randall County acquired on Nov. 25, 2014 at 0.5-meter resolution, SCALE 1:15,000

Residential housing in El Paso, TX acquired on Mar. 15, 2015 at 0.5-meter resolution, SCALE 1:1,890

San Antonio River in Goliad County acquired on Mar. 28, 2015 at 6-inch resolution, SCALE 1:700.

Shafter Lake in Andrews County acquired on Mar. 15, 2015 at 0.5-meter resolution, SCALE 1:12,000

Swamp and crop features in Goliad County acquired on Mar. 28, 2015 at 6-inch resolution, SCALE 1:2500.

University of Texas at El Paso campus acquired on Mar. 15, 2015 at 0.5-meter resolution, SCALE 1:2500.

Oil pads in Wheeler County acquired on Nov. 7, 2014 at 0.5-meter resolution, SCALE 1:12,000.

**Comment by christoball** [comment]
@gmullins What are the captions for the redline images?

**Comment by christoball** [comment]
@gmullins I'm sorry, but I have an new image request. Would you be able to re-generate the NC/CIR for the following two images, but to match the dimensions I'm showing with that black? Basically, they need to be a lot longer for what I have in mind.

![georgetown_lampasas_crop](https://cloud.githubusercontent.com/assets/1877550/11692202/005c904c-9e64-11e5-9c14-3358cd9d453e.jpg)

![lakemeredithcrop](https://cloud.githubusercontent.com/assets/1877550/11692207/08cbf272-9e64-11e5-8498-8a92631d3e2f.jpg)

**Comment by gmullins** [comment]
@christoball How are these:  M:\SM\HPIDS\2015 Projects\580150618 Ortho\Web page\2015 Year in Review

lake meredith Statewide 50cm 3501203_20141029 nc 1to40000 ex.jpg
lampasasriver Georgetown 6in 3097_03_2_b_1_20150306 nc 1to3100.jpg

**Comment by christoball** [comment]
Perfect, thank you.

**Comment by christoball** [comment]
![elpaso](https://cloud.githubusercontent.com/assets/1877550/11698529/a59a072c-9e84-11e5-9a86-302fcdf55e09.jpg)

**Comment by gmullins** [comment]
This is ready: M:\SM\HPIDS\2015 Projects\580150618 Ortho\Web page\2015 Year in Review

residential el paso Statewide 50cm 3106133_20150315 nc 1to1890 ex.jpg

I also did this one. If not used now maybe for something later.

border el paso Statewide 50cm 20150315 cir 1to15000.jpg
