### ISSUE TITLE
Data Catalog - Supplemental Reports

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#749]
I would like to add Supplemental Reports for download via the data catalog. This can be any additional information the customer could use for a dataset. ex: QAQC reports, Project Level Meta, etc. Please zip any applicable information and place it here, M:\Admin\Website\SupplementalReports.

Zip files naming convention. 
lidar -  organization_year_resolution_area_supplementalreports.zip
imagery - organization_year_bands_resolution_area_supplementalreports.zip

@gmullins 
- [x] HPIDS Bexar 2010 6in NC
- [x] HPIDS Brazos 2011 6in\1ft NC\CIR
- [x] HPIDS Brazos 2013 6in\1ft NC\CIR
- [x] HPIDS Brazos and Palestine 2015 6in NC\CIR
- [x] HPIDS Galveston 2009 6in CIR
- [x] HPIDS Galveston 2009 6in NC\CIR
- [x] HPIDS Georgetown 2015 6in NC\CIR
- [x] HPIDS Houston 2013  1ft NC\CIR
- [x] HPIDS SARA 2015 6in NC\CIR
- [x] HPIDS Smith 2010 1ft NC\CIR
- [x] HPIDS Smith 2014 6in NC\CIR
- [x] HPIDS South Texas 2013 6in\9in\12in NC
- [x] HPIDS University Lands 2015 6in NC\CIR
- [x] Texas Orthoimagery Program (TOP) 2008 50cm NC\CIR
- [x] Texas Orthoimagery Program (TOP) 2009 50cm NC\CIR
- [ ] Texas Orthoimagery Program (TOP) 2015 50cm NC\CIR

@ThorTheDestroyer 
- [x] TNRIS 2009 1m Dallas
- [x] TNRIS 2009 1m Goliad, McMullen, Zapata
- [x] TNRIS 2009 50cm Tarrant
- [x] TNRIS 2010 1m Lee, Leon, Madison & Milam
- [x] TNRIS 2010 50cm Bexar
- [x] TNRIS 2010 50cm Cooke, Grayson, Montague & Wise
- [x] TNRIS 2011 1M Shelby, Sabine and Newton 
- [x] TNRIS 2011 50cm  Austin, Grimes, Walker
- [x] TNRIS 2011 50cm Bell, Burnet, McLennan
- [x] TNRIS 2011 50cm Blanco, Caldwell, Gonzales, Kendall, Kerr
- [x] TNRIS 2011 50cm Collin, Denton, Kaufman
- [x] TNRIS 2012 50cm DeWitt
- [x] TNRIS 2012 50cm TCEQ Dam Safety Sites
- [x] TNRIS 2013 50cm Ellis, Navarro,Wilson & Karnes
- [x] TNRIS 2014 50cm Bandera & Lampasas
- [x] TNRIS 2014 50cm Fort Bend
- [x] TNRIS 2014 50cm Henderson, Smith, Van Zandt, Trinity River
- [x] TNRIS 2015 50cm Brazos County
- [x] TNRIS 5ft Contours
- [x] TPWD 2014 50cm Palo Pinto Mountains State Park
- [x] TPWD 2015 Galveston State Park

Non TNRIS Projects @ThorTheDestroyer 
- [x] CAPCOG 2007 140cm
- [x] CAPCOG 2008 140cm
- [x] CAPCOG 2012 140cm
- [x] City of Georgetown 2015 50 cm
- [x] City of Grand Prairie 2009 70cm
- [x] City of Lubbock 2011 70cm Lidar
- [x] FEMA 2006 140cm
- [x] FEMA 2011 1m Liberty
- [x] FEMA 2011 1m Parker
- [x] FEMA 2011 61cm Comal, Guadalupe
- [x] FEMA 2013 60cm Middle Brazos-Palo Pinto
- [x] FEMA 2015 70 cm 
- [ ] Harris County Flood Control 2001 150cm
- [x] IBWC 2011 70cm
- [x] LCRA 2007 140cm
- [x] USGS 2008 120cm
- [x] USGS 2011 150cm

**Comment by gmullins** [comment]
How about original solicitation PDFs too? I can see people getting use out of the specification/SOW contained in those. @ThorTheDestroyer @mitchellryant

**Comment by mitchellryant** [comment]
after talking to @christoball please name the zips file the same as the data catalog name

**Comment by mitchellryant** [comment]
@gmullins @ThorTheDestroyer please add whatever information you think would be helpful to the customers.

**Comment by christoball** [comment]
Naming examples:
HPIDS Bexar 2010 6in NC 
---> hpids_bexar_2010_6in_nc

TNRIS 2010 50cm Cooke, Grayson, Montague & Wise 
---> tnris_2010_50cm_cooke_grayson-montague_wise

**Comment by ThorTheDestroyer** [comment]
Done,  nothing on the books for palopinto tpwd, 5ft contours, use 2014 bandera lampasses fortbend zip for both collections

**Comment by mitchellryant** [comment]
@ThorTheDestroyer do any of the other Lidar projects have information that could be zipped into a supplemental report.

**Comment by ThorTheDestroyer** [comment]
Can't wait to pull the drives and find out!

**Comment by mitchellryant** [comment]
if we have something should it not be on I:\?

**Comment by ThorTheDestroyer** [comment]
I have been putting it there as we receive the new stuff;however, i'm unclear as to whether my predecessor did the same.

**Comment by mitchellryant** [comment]
![carreywild 0 0](https://cloud.githubusercontent.com/assets/8459928/11638499/f40e067c-9cec-11e5-9d5e-a486c6d0dd9e.gif)

**Comment by gmullins** [comment]
Waiting until project completion for full supplemental documentation release for Texas Orthoimagery Program (TOP) 2015 50cm NC\CIR

**Comment by mitchellryant** [comment]
@wilsaj I located most of the non-TNRIS information, added flags to data catalog, and double checked the names of the zip files. I would like to work on getting the information into the data catalog. 

For the tile indices:
csv column - tile_index
s3 location - s3://tnris-datadownload/datacatalog/tile_index
flags - T for report, null for no report, Lidar to use the lidar index (https://tnris-datadownload.s3.amazonaws.com/d/tnris-lidar/state/tx/tnris-lidar_tx.zip)

For the supplemental reports:
csv column - supplemental_report
s3 location - s3://tnris-datadownload/datacatalog/supplemental_reports
flags - T for report, null for no report

**Comment by wilsaj** [comment]
Supplemental reports are pretty much ready on my end. Some of the S3 keys are bad though, so the links will be broken. Can you go through and check / correct as needed:

- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/city_of_georgetown_2015_50_cm_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/city_of_grand_prairie_2009_70cm_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/city_of_lubbock_2011_70cm_lidar_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/fema_2006_140cm_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/fema_2011_1m_liberty_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/fema_2011_1m_parker_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/fema_2011_61cm_comal_guadalupe_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/fema_2013_60cm_middle_brazos_palo_pinto_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/fema_2015_70_cm_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/fort_bend_2006_60cm_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/hpids_bexar_2010_6in_nc_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/hpids_brazos_2011_6in_1ft_nc_cir_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/hpids_brazos_2013_6in_1ft_nc_cir_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/hpids_brazos_and_palestine_2015_6in_nc_cir_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/hpids_galveston_2009_6in_cir_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/hpids_galveston_2009_6in_nc_cir_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/hpids_georgetown_2015_6in_nc_cir_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/hpids_houston_2013_1ft_nc_cir_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/hpids_sara_2015_6in_nc_cir_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/hpids_smith_2010_1ft_nc_cir_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/hpids_smith_2014_6in_nc_cir_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/hpids_south_texas_2013_6in_9in_12in_nc_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/hpids_university_lands_2015_6in_nc_cir_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/texas_orthoimagery_program_top_2008_50cm_nc_cir_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/texas_orthoimagery_program_top_2009_50cm_nc_cir_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/tnris_2009_1m_dallas_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/tnris_2009_1m_goliad_mcmullen_zapata_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/tnris_2009_50cm_tarrant_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/tnris_2010_1m_lee_leon_madison_milam_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/tnris_2010_50cm_bexar_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/tnris_2010_50cm_cooke_grayson_montague_wise_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/tnris_2011_1m_shelby_sabine_and_newton_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/tnris_2011_50cm_austin_grimes_walker_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/tnris_2011_50cm_bell_burnet_mclennan_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/tnris_2011_50cm_blanco_caldwell_gonzales_kendall_kerr_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/tnris_2011_50cm_collin_denton_kaufman_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/tnris_2012_50cm_dewitt_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/tnris_2012_50cm_tceq_dam_safety_sites_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/tnris_2013_50cm_ellis_navarro_wilson_karnes_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/tnris_2014_50cm_bandera_lampasas_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/tnris_2014_50cm_fort_bend_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/tnris_2014_50cm_henderson_smith_van_zandt_trinity_river_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/tnris_2015_50cm_brazos_county_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/tpwd_2014_50cm_palo_pinto_mountains_state_park_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/tpwd_2015_galveston_state_park_supplementalreports.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/supplemental_reports/usgs_2011_150cm_supplementalreports.zip

**Comment by wilsaj** [comment]
Same for tile indices:

- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/bexar_county_2001_1m_cir_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/bexar_county_2003_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/bexar_metro_911_2006_6in_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/bexar_metro_911_2009_6in_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/bexar_metro_911_2010_6in_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/bexar_metro_911_2013_6in_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/capcog_1997_2m_bw_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/capcog_2002_2m_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/capcog_2006_1ft_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/capcog_2009_6in_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/city_of_austin_2003_6in_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/el_paso_2003_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/el_paso_2005_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/geologic_atlas_of_texas_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/hgac_2000_50cm_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/hgac_2002_1ft_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/hgac_2004_6in_1ft_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/hgac_2006_6in_1ft_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/hgac_2008_3in_6in_1ft_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/hgac_2010_3in_6in_1ft_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/hpids_bexar_2010_6in_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/hpids_brazos_2011_6in_1ft_nc_cir_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/hpids_brazos_2013_6in_1ft_nc_cir_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/hpids_brazos_and_palestine_2015_6in_nc_cir_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/hpids_galveston_2009_6in_cir_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/hpids_galveston_2009_6in_nc_cir_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/hpids_georgetown_2015_6in_nc_cir_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/hpids_houston_2013_1ft_nc_cir_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/hpids_sara_2015_6in_nc_cir_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/hpids_smith_2010_1ft_nc_cir_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/hpids_smith_2014_6in_nc_cir_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/hpids_south_texas_2013_6in_9in_12in_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/hpids_university_lands_2015_6in_nc_cir_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/ibwc_2011_6in_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/lrgv_2011_6in_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/lynn_2005_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/national_agriculture_imagery_program_naip_2004_1m_cir_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/national_agriculture_imagery_program_naip_2005_2m_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/national_agriculture_imagery_program_naip_2006_2m_cir_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/national_agriculture_imagery_program_naip_2008_ccm_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/national_agriculture_imagery_program_naip_2009_ccm_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/national_agriculture_imagery_program_naip_2010_1m_nc_cir_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/national_agriculture_imagery_program_naip_2012_1m_nc_cir_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/national_agriculture_imagery_program_naip_2014_1m_nc_cir_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/national_elevation_dataset_ned_2004_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/national_elevation_dataset_ned_2011_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/national_elevation_dataset_ned_2013_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/national_elevation_dataset_ned_hillshade_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/nctcog_2001_1ft_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/nctcog_2003_1ft_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/nctcog_2007_1ft_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/noaa_2007_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/shuttle_radar_topography_mission_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/spot_select_for_texas_pan_bw_1999_2001_10m_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/taylor_county_2002_bw_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/texas_forest_service_east_texas_1m_cir_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/texas_orthoimagery_program_top_1996_cir_bw_1m_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/texas_orthoimagery_program_top_2008_50cm_nc_cir_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/texas_orthoimagery_program_top_2009_50cm_nc_cir_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/texas_orthoimagery_program_top_2015_50cm_nc_cir_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/tpwd_2015_galveston_state_park_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/usgs_2002_corpus_christi_bay_1m_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/usgs_2008_border_30cm_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/usgs_2009_amarillo_30cm_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/usgs_2009_lubbock_30cm_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/usgs_2009_mcallen_30cm_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/usgs_2012_amarillo_30cm_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/usgs_2012_el_paso_30cm_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/usgs_2013_dallas_fort_worth_30cm_nc_tileindex.zip
- [ ] https://tnris-datadownload.s3.amazonaws.com/datacatalog/tile_index/usgs_2014_corpus_christi_30cm_nc_tileindex.zip

**Comment by mitchellryant** [comment]
I was able to download all list files.

**Comment by wilsaj** [comment]
Awesome, thanks!

**Comment by wilsaj** [comment]
Reopening as there are still a few unresolved datasets to track down. Those will take a while, so we are publishing the reports we do have as is for now.

**Comment by mitchellryant** [comment]
supplemental reports and tile indices have been added to the wpd for incoming data. routine for adding new file has been created.
