### ISSUE TITLE
Forum website changes

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#75]
Wednesday 2-3:30 in Lil' Tex
Third speaker listing 
From: Ceran Hibbard
To: Jennifer Estes

Speaker Change From::
Session A (Big Tex)
Emergency Management
10:30 – 11:00AM
Hurricane Emergency Response - Operational and Technical Infrastructure Challenges
Jaime de Mora, Vice President of Sales, CARTO

To:
JD Godchaux, Customer Success Manager with CARTO
Bio: JD Godchaux is based in Houston. JD has over 20 years of experience solving geospatial problems for governments, non-profit organizations and businesses, with a focus on environmental and social sustainability. JD holds a Master of Public Administration from Arizona State University and a Bachelor of Science in Geosciences from Trinity University in San Antonio.

Description change
From:
This presentation will describe the experience in emergency management during hurricane season. Specifically he will discuss the operational and technical infrastructure challenges faced by his team when the hurricane hit Harris County, Texas.

TO:
This presentation will describe the experience in emergency management during hurricane season. They will focus on the use of CARTO in emergency management with a case study of how the team supported Harris County, Texas during Hurricane Harvey recovery operations through their ATLAS application.

**Comment by KCMack** [comment]
Add to the speaker change
From: JD Godchaux, Customer Success Manager with CARTO

To: 
JD Godchaux, Customer Success Manager with CARTO
Jeff Goalen, Director of BUdget Support Services at Harris County, Texas

**Comment by KCMack** [comment]
correct the above: Jeff Goalen, Director of Budget Support Services at Harris County, Texas

**Comment by christoball** [comment]
@KCMack can you take a quick look to make sure everything is up to date and correct?
http://ellwood.tnris.org/texas-gis-forum/2019/agenda/

**Comment by KCMack** [comment]
This is the last item to be repaired

Topic description change
Session A (Big Tex)
Emergency Management
10:30 – 11:00AM
Hurricane Emergency Response - Operational and Technical Infrastructure Challenges

Description change to:
This presentation will describe the experience in emergency management during hurricane season. They will focus on the use of CARTO in emergency management with a case study of how the team supported Harris County, Texas during Hurricane Harvey recovery operations through their ATLAS application.

All else looks good

**Comment by KCMack** [comment]
Add one last thing for Friday

Registration and Breakfast 

Thanks
@christoball
