### ISSUE TITLE
Data Catalog Update NLCD and TCEQ Links

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#754]
Please update the data catalog, several ,minor updates have been made to the google sheet.

1. Catalog name for National Land Cover Database 2002 changed to correct year now National Land Cover Database 2001.  
2. wms links added for NLCD 1992, 2001, 2011
3. updated download links for 4 tceq datasets.
4. National Land Cover Database 2006 is in staging and ready to be added.

**Comment by christoball** [comment]
I don't see the name change to 2001 in the master sheet.

**Comment by mitchellryant** [comment]
the old name was National Land Cover Database 2002 in changed it to National Land Cover Database 2001. after re-downloading the data from usgs

**Comment by mitchellryant** [comment]
or i thought i did. just made the change.

**Comment by christoball** [comment]
It looks like the preview images for the 2011 and 2006 images are the same. Is this intentional? is there not enough change to see a difference? @mitchellryant

**Comment by mitchellryant** [comment]
Yes, not at this scale and with all 4 using the the same Anderson classification method.
