### ISSUE TITLE
2015 Orthoimagery Update HTML Tags Visible

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#772]
html paragraph tags are visible

https://tnris.org/2015-statewide-orthoimagery-project/

**Comment by jseppi** [comment]
![image](https://cloud.githubusercontent.com/assets/697848/11932510/8fae4564-a7bb-11e5-8302-f780dbc5a911.png)

**Comment by jseppi** [comment]
Likely related to the new parsing of front-matter with markdown. Reassigning to @wilsaj.
