### ISSUE TITLE
Update GIS Community Meeting Agenda - Jan 12, 2015

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#776]
[gio-meeting-agenda-jan-12.pdf](https://github.com/TNRIS/tnris.org/files/71182/gio-meeting-agenda-jan-12.pdf)

Need to replace the old agenda with new Jan. 12 agenda on the GIO webpage.

**Comment by mitchellryant** [comment]
are we posting a pdf or creating a page that would be a lot more accessible than PDFs, and will be easily index-able by search engines.

https://github.com/TNRIS/tnris.org/issues/478

**Comment by geochik** [comment]
Forgot about the page. I like the idea of a page.

**Comment by jseppi** [comment]
Page creation is more in @christoball's realm. Reassigning.
