### ISSUE TITLE
Cross post articles from different directories on front page

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#777]
i.e. be able to post a GIO article under front page 'updates' without putting file in 'news' directory.

**Comment by jseppi** [comment]
Idea: Create a new macro or swig filter that accepts an array of lists and concatenates them. Then use the `sort` filter to sort by the desired field (such as date).

**Comment by wilsaj** [comment]
Went with just creating the stream in metalsmith to save some time. A macro would be more generally useful, but the details were getting messy and didn't want to throw in additional complexity that would need to be ported from swig -> nunjucks (if and when that happens)
