### ISSUE TITLE
catalog: SRTMv2 entry should mention v3?

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/tnris.org#781]
The SRTM v2 entry probably should mention that SRTM v3 exists and is available from NASA? v3 is newer and higher resolution (30 meter instead of 90 meter):  http://www2.jpl.nasa.gov/srtm/

Also, this is neat:  http://dwtkns.com/srtm30m/

**Comment by mitchellryant** [comment]
SRTM v2 data for US is 30M, with the v3 30m data was made available rest of coverage. V3 data was reprocessed to fill voids with existing elevation data, NED. It is possible SRTM for US/TX was improved via this process. Using Mr Watkins site I was able to download all tiles for Texas. The will be converted from hgt format to dem format. 

I will update the entry to reflect updated data.

**Comment by mitchellryant** [comment]
Entry has been updated to reflect new data.

Dataset name was changed to Shuttle Radar Topography Mission removing the version number. This way we only have to update short and long desc fields if new data comes available.

@christoball Can you update the data catalog to reflect this change and direct download the NWI vector data from US-FWS site.
