### ISSUE TITLE
TNRIS About Page

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#790]
Following text on the about page should be updated to reflect TNRIS being made a division.

Texas Water Development Board
TNRIS is a part of the Texas Water Development Board (TWDB) under the Operations and Administration division.

https://tnris.org/about/

**Comment by wilsaj** [comment]
fixed with a20a709

**Comment by wilsaj** [comment]
thanks @mitchellryant :+1: :rocket: :tophat:
