### ISSUE TITLE
2016-17 Lidar Acquisition Project Page

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#791]
A Informative and dynamic page to post updates on Lidar Acquisition, proposed AOIs, etc.

Working with @ThorTheDestroyer to develop content.

- Intro
- Main Statewide Section
- AOI Sections:
  - TWDB
  - SARA
  - Williamson County

**Comment by christoball** [comment]
Created branch - lidar-project-2016.

View 1st outline draft here:
https://deploy.tnris.org/api/v1/preview/ef6a838410dda27032ebf41b7cef789fbc7e6546/2016-lidar-acquisition-project/

**Comment by ThorTheDestroyer** [comment]
Generated two sets of images to be used as slider images. Deposited them is Lidar projectpage folder in ledesma staff folder.

**Comment by ThorTheDestroyer** [comment]
created draft text for the page and placed in same location

**Comment by ThorTheDestroyer** [comment]
Created all cartodb maps for the project page, SARA AOI, TWDB AOI, Williamson County AOI, and overall AOI map of all projects.

**Comment by ThorTheDestroyer** [comment]
TWDB AOI-  https://tnris.cartodb.com/viz/fc611896-becf-11e5-b71a-0ecfd53eb7d3/map

SARA AOI-  https://tnris.cartodb.com/viz/f3fc4f30-bee4-11e5-9369-0e787de82d45/map

Williamson County AOI- https://tnris.cartodb.com/viz/53e075be-bedd-11e5-8a29-0ecfd53eb7d3/map

Total Project AOI-  https://tnris.cartodb.com/viz/0447c616-bee6-11e5-bf8f-0ea31932ec1d/map

**Comment by mitchellryant** [comment]
@ThorTheDestroyer please add the proper tags to the cartobd datasets and visualizations. Also please remove any table or datasets not being used.

**Comment by ThorTheDestroyer** [comment]
these are purely for use as graphics on a content page, not the data catalog.  Do they really need Tags?

**Comment by ThorTheDestroyer** [comment]
also, each map only has the tables being used? which one has extras?

**Comment by mitchellryant** [comment]
all datasets and visualizations in cartodb have tags and descriptions, i do not see why these should be different.

**Comment by ThorTheDestroyer** [comment]
The only tag i see is datacatalog

**Comment by mitchellryant** [comment]
untitled_table_3
untitled_table_4
untitled_table_5

if they do not fit that tag, make up a new one

**Comment by ThorTheDestroyer** [comment]
on which map?

**Comment by mitchellryant** [comment]
![image](https://cloud.githubusercontent.com/assets/8459928/12431239/fa413b06-beb9-11e5-90f3-7f4f070f3082.png)

**Comment by ThorTheDestroyer** [comment]
? hmmmm not sure where those came from

**Comment by ThorTheDestroyer** [comment]
I found an untitled map and deleted it, but none of my maps i created have those tables

**Comment by mitchellryant** [comment]
The tables were created at the same time as all the other datasets you added. So most likely they were created inadvertently. In order to move this along I deleted them. 

I also added the tags and descriptions to the datasets, well at least the ones I determine. The following datasets do not have descriptions **table_2016_lidar_aoi**, **lidar_status**, and **aoi_15**.

Also the Williamson AOI Map has a misspelling **Wiliiamson_Lidar_AOI_16**.

It is important completely to fill out the metadata for both the datasets and maps.  We currently have 147 Datasets and 129 Maps, and this will only increase with the flood project. The metadata, tags and descriptions will help in the organization of the both maps and datasets.

**Comment by ThorTheDestroyer** [comment]
New Slider images created deposited in ledesma staff folder

**Comment by ThorTheDestroyer** [comment]
The "Untitled Table" tagged to Lidar Project is being used by another map and is not related to Lidar Project page.  Please remove tag and add appropriate tag. this was for some map created 2 months ago.

**Comment by ThorTheDestroyer** [comment]
Updated Lidar project page content.  All maps, graphic and article components are complete and ready to be updated.

**Comment by christoball** [comment]
Could y'all kindly assist with contact form stuff?
- [ ] Create spreadsheet for form submissions @mitchellryant 
- [ ] Add form to contact app. form id is **lidar-project** @wilsaj 

@wilsaj Everything is in the lidar-project-2016 branch

**Comment by wilsaj** [comment]
I'll get the spreadsheet setup, too

**Comment by christoball** [comment]
@ThorTheDestroyer @geochik @gmullins 
Here's a link to a preview of the lidar project page. Can y'all please review for final edits to get ready for publishing?

https://beta.tnris.org/2016-lidar-acquisition-project/

*note that the contact form is buggy (at least at the moment im writing this)*

**Comment by gmullins** [comment]
Some general comments:
- Seems like the Statewide Overview heading should come before the state map.
- The TWDB AOI South is blue in the statewide map and green in the TWDB map which is a little confusing. Maybe label them A & B?
- TWDB Funding Status: Committed for one AOI, in need of partners for full coverage
- Love the Lidar sample!

I have further text edits.

**Comment by wilsaj** [comment]
Contact form and spreadsheet are good to go

**Comment by ThorTheDestroyer** [comment]
Update needed ASAP for Williamson County Lidar to reflect addition of US fish and wildlife. Maps have been updated.  
[Williamson_FWS_Update.docx](https://github.com/TNRIS/tnris.org/files/140819/Williamson_FWS_Update.docx)

**Comment by jseppi** [comment]
This issue should probably be closed and new modifications/updates should go into their own issues.
