### ISSUE TITLE
GIO Updates: Publish meeting notes for 1st quarter

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#795]
@geochik has content, will post in M drive.

**Comment by geochik** [comment]
Documents loaded here - M:\IS\Staff\Ledesma\GIO_Page
Notes with 3 supporting PPTs

**Comment by geochik** [comment]
do you have an estimated time for when the notes will go up? I have received an inquiry for the notes

**Comment by KCMack** [comment]
Nice way to urge the notes.


kcm


Kathleen C. Mack, PMP
Operations Manager
Texas Natural Resources Information System
1700 N. Congress Avenue
Austin, Texas 78701
Phone 512 463-4536/Cell 512 415-3847
Kathleen.Mack@twdb.texas.gov

Direct: (512) 463-4536
Main: (512) 463-8337


________________________________

**Comment by christoball** [comment]
Yes, I'll have them up by lunchtime
