### ISSUE TITLE
order from: Change FTP

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#799]
On the order form can we change FTP to Digital Download? TNRIS does not offer FTP services. It will also match the Prefer Digital Download check box at the top of the form.

![image](https://cloud.githubusercontent.com/assets/8459928/12455968/6e044d2c-bf63-11e5-90df-a3a861241375.png)

**Comment by wilsaj** [comment]
:+1:

**Comment by wilsaj** [comment]
Should this be bumped to the top, too?
