### ISSUE TITLE
Forum Agenda - Add leadership panelists names

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#80]
@christoball 
Please add leadership panelists names, titles and organizations to the Wednesday, 10/23, 4;00-5:30 p.m. time slot. 

Selena Walsh, Director – Executive Management in Public Leadership, LBJ School of Public Affairs 
Molly Schar, Director – National States Geographic Information Council 
Ed Kelly, Chief Data Officer – Department of Information Resources 
Richard Wade – GIO of Texas and Deputy Executive Administrator at the Texas Water Development Board

**Comment by christoball** [comment]
@geochik yes they will be added in the next update that will push asap
