### ISSUE TITLE
data catalog: Texas NHD Rivers and Streams

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#800]
Download was updated to include waterbodies. within the data catalog sheet dataset name was updated to be Texas NHD River, Streams, and Waterbodies. Long Description was updated to include extraction criteria from NHD.

**Comment by christoball** [comment]
@mitchellryant  I recently made a general user account for tnris so it's not under my personal gmail, could you share the data catalog master sheet with tnrisuser@gmail.com?

**Comment by mitchellryant** [comment]
sheet was shared with user
