### ISSUE TITLE
data catalog: Removed Double Spaces after Punctuation

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#801]
Double spaces were removed after punctuation in all columns. 

Per The Chicago Manual of Style Online.

Published work these days rarely features two spaces after a period. In the era when type was set by hand, it was common to use extra space (sometimes quite a bit of it) after periods, a practice that continued into the first half of the twentieth century. And many people were taught to use that extra space in typing class. But introducing two spaces after a sentence-ending period—and only after those periods—causes problems. Absolute consistency is easy to monitor when double spaces are never allowed, but less easy when some spaces after periods are double and others single (such as those at the ends of abbreviations and initialisms in running text). Since there is no proof that an extra space actually improves readability—as your comment suggests, it’s probably just a matter of familiarity—CMOS follows the industry standard of one space after a period.

**Comment by jseppi** [comment]
HTML will only render a single space anyway, bee-tee-dubs

**Comment by christoball** [comment]
I'm all about that one-space life, but I everything I get from the olds has double spaces.

**Comment by mitchellryant** [comment]
closing issue since it does not really matter.
