### ISSUE TITLE
data catalog: standardized footprint field 

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#811]
The footprint fields need to be standardized. Currently there are 43 unique values. I would like to standardize with more human friendly language. @geochik @ThorTheDestroyer @gmullins 

Here is the list of Unique Values
1 degree x 2 degree block
250k
3.75" Quarter Quad
3.75" Quarter Quad, County
4 quadrangle x 8 quadrangle
7.5' Quadrangle
7.5" Quad
Brazos County, City of Palestiine
City of Abilene Grid
City of Austin Grid
City of Grand Prairie Grid
City of Lubbuck Grid
Coastal
County
County, City, Park, Cultural boundaries
Custom (1.3 sq. mi. tiles)
Degree Block
Degree block, 250k, 100k, Quadrangle, Quadrangle 4th/DOQQ, Quadrangle 16th/DOQQQ, Quadrangle 64th/DOQQQQ
DOQ
DOQ, Statewide coverage, various polygons
DOQ, Statewide coverage, various polygons, scanned sheets
DOQQ
DOQQQ
DOQQQQ
HGAC Lambert grid
Individual Frames
N/A
NCTCOG Flight Grid
Quad
State
State, 7.5" Quad
Statewide
Statewide coverage
Statewide coverage, County
Statewide, County
Taylor County Flight Grid
Texas Coastal
Texas Louisiana Coastal
Texas, surrounding state, Mexico
TPWD Grid
US National Grid
USGS 1 Degree Block
USGS 1k Grid

**Comment by mitchellryant** [comment]
Example of changes:

7.5' Quadrangle --> USGS Quadrangle
7.5" Quad --> USGS Quadrangle
DOQ --> USGS Quadrangle
3.75" Quarter Quad --> USGS Quarter Quadrangle
DOQQ --> USGS Quarter Quadrangle
DOQQQ --> 1/16 USGS Quarter Quadrangle
DOQQQQ --> 1/64 USGS Quarter Quadrangle

**Comment by jseppi** [comment]
:+1:

**Comment by mitchellryant** [comment]
Here is the complete list of my proposed changes. Changes are based on downloadable unit or delivery unit.

1 degree x 2 degree block-->**USGS 250k**
250k-->**USGS 250k**
3.75" Quarter Quad-->**USGS Quarter Quadrangle**
3.75" Quarter Quad, County-->**USGS Quarter Quadrangle**
4 quadrangle x 8 quadrangle -->
7.5' Quadrangle-->**USGS Quadrangle**
7.5" Quad-->**USGS Quadrangle**
Brazos County, City of Palestiine-->**1/64 USGS Quarter Quadrangle**
City of Abilene Grid-->**No change**
City of Austin Grid-->**No change**
City of Grand Prairie Grid-->**No change**
City of Lubbuck Grid-->**No change**
Coastal-->**Texas Coastal**
County-->**County**
Custom (1.3 sq. mi. tiles) -->**1/64 USGS Quadrangle**
Degree Block-->**USGS 1 Degree Block** 
Degree block, 250k, 100k, Quadrangle, Quadrangle 4th/DOQQ, Quadrangle 16th/DOQQQ, Quadrangle 64th/DOQQQQ-->**No change**
DOQ-->**USGS Quadrangle**
DOQ, Statewide coverage, various polygons-->**USGS Quadrangle**
DOQ, Statewide coverage, various polygons, scanned sheets-->**USGS Quadrangle**
DOQQ-->**USGS Quarter Quadrangle**
DOQQQ-->**1/16 USGS Quadrangle**
DOQQQQ-->**1/64 USGS Quadrangle**
HGAC Lambert grid-->**No change**
Individual Frames-->**No change**
N/A -->
NCTCOG Flight Grid-->**No change**
Quad-->**USGS Quadrangle**
State-->**State**
State, 7.5" Quad-->**State, USGS Quadrangle**
Statewide-->**State**
Statewide coverage-->**State**
Statewide coverage, County-->**State, County**
Statewide, County-->**State, County**
Taylor County Flight Grid-->**No change**
Texas Coastal-->**Texas Coastal**
Texas Louisiana Coastal-->**Texas Coastal**
Texas, surrounding state, Mexico-->**State**
TPWD Grid-->**No change**
US National Grid-->**No Change**
USGS 1 Degree Block-->**USGS 1 Degree Block**
USGS 1k Grid -->**No Change**

**Comment by gmullins** [comment]
I love it!

**Comment by mitchellryant** [comment]
All changes have been made. Catalog will be updated soon.
