### ISSUE TITLE
data catalog: move entry details above description

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#812]
@christoball What do you think about moving the details section of each data catalog entry above the description. When I use the catalog I tend to start at the details and move to the description. Generally the information I'm looking for is there.

**Comment by christoball** [comment]
Going to look at reworking of data catalog entry pages:

Ideas:
- Don't show download size
- Put coverage extent in top blue bar, move tags out

**Comment by christoball** [comment]
Here's an attempt at the new version of the entry incorporating suggestions.

Things get weird when the description is really short. Maybe the data access column should move to the right to be a little more balanced.

@mitchellryant @wilsaj @jseppi what do you think?
https://deploy.tnris.org/api/v1/preview/69ba5723bab40d5edf9ee5fd8d7ce30a515e1c5b/data-catalog/entry/bexar-metro-911-2006-6in-nc/

**Comment by jseppi** [comment]
I think it'll look good once the More Details section is built out.

**Comment by wilsaj** [comment]
Also, there will be a license field to fit somewhere on the page: https://github.com/TNRIS/tnris.org/pull/808
