### ISSUE TITLE
GeoRodeo 2016 Page

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#815]
@christoball - Do you have availability to start working on the 2016 GeoRodeo page? For now, just a placeholder would be great. The event will again be at the Commons Center, and this year's date is May 20.

I'd like to keep the current one up and accessible -- perhaps it could be put at `/georodeo/2015` and the new one could be at `/georodeo/2016` Thoughts, @wilsaj?

**Comment by wilsaj** [comment]
I like `/georodeo/<year>`

**Comment by christoball** [comment]
I'll get mockin-uppin.

**Comment by christoball** [comment]
1st version of page now up here, in branch:  *georodeo-2016-draft* 
https://deploy.tnris.org/api/v1/preview/0bbc90460c771e657a75a69ce8fcea4bb6f4b4f4/georodeo/2016/

@jseppi @wilsaj Would this preliminary agenda be ok to put out there?

**Comment by jseppi** [comment]
Looking pretty good!

In the graphic, maybe change "Pickle Center" to "Commons Center"

Let's wait on publishing until I get Waldo's official headshot.

**Comment by wilsaj** [comment]
Looks nice!

Also, Waldo works for [US Open Data](https://usopendata.org), not data.gov

**Comment by geochik** [comment]
And is the graphic a placeholder? It still has 2015. That's all I got. The rest is GREAT!!

Sent from my iPhone

On Feb 3, 2016, at 6:38 PM, Andy Wilson <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks nice!

Also, Waldo works for US Open Data<https://usopendata.org>, not data.gov<http://data.gov>

-

**Comment by jseppi** [comment]
Look at it on a larger screen. This quick mockup still has last year's
banner for small screen sizes.

**Comment by jseppi** [comment]
Closing since the page is now up. Any subsequent modifications will have their own issues.
