### ISSUE TITLE
new dataset: TOP 2015 North Texas

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#816]
- [x] Add data to measures spreadsheet @gmullins
- [x] Route Data Shipment @gmullins
- [x] Data Processing [renaming file, data organization, coverage map]@mitchellryant
- [x] Quality Assurance @gmullins
- [x] Download Prep [zip, copy to s3 bucket] @mitchellryant
- [x] Data Publication [Update data catalog sheet, create data catalog images, data story] @gmullins
- [x] Add to Data Download @wilsaj https://github.com/TNRIS/data-download/issues/58 https://github.com/TNRIS/data-download/issues/60
- [x] Move data to production shares @mitchellryant
- [x] Final Publication @christoball @gmullins

**Comment by gmullins** [comment]
Ready for you Ryan. I don't want to hold up this process for the two remaining rejected CCMs (Hill and Delta). They are set off in a diff dir.
Thanks!

**Comment by gmullins** [comment]
@mitchellryant Can we close this issue?

**Comment by mitchellryant** [comment]
yes.
