### ISSUE TITLE
GeoRodeo - Code of Conduct

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#819]
Let's make sure we have a Code of Conduct for the GeoRodeo this year.

This is a good one: http://confcodeofconduct.com/

**Comment by KCMack** [comment]
At the risk of being a goof, how do we enforce a code of conduct?

Kathleen C. Mack, PMP
Operations Manager
Texas Natural Resources Information System / 1700 N. Congress Ave., Austin, Texas 78701
Phone 512 463-4536 / Cell 512 415-3847
Kathleen.Mack@twdb.texas.gov<mailto:Kathleen.Mack@twdb.texas.gov> / www.tnris.texas.gov<http://www.tnris.texas.gov/>

**Comment by jseppi** [comment]
> If a participant engages in harassing behavior, the conference organisers may take any action they deem appropriate, including warning the offender or expulsion from the conference with no refund.

**Comment by KCMack** [comment]
Who is going to be the police?

Kathleen C. Mack, PMP
Operations Manager
Texas Natural Resources Information System / 1700 N. Congress Ave., Austin, Texas 78701
Phone 512 463-4536 / Cell 512 415-3847
Kathleen.Mack@twdb.texas.gov<mailto:Kathleen.Mack@twdb.texas.gov> / www.tnris.texas.gov<http://www.tnris.texas.gov/>

**Comment by jseppi** [comment]
TNRIS staff at the event will be the points of contact for attendees.

**Comment by christoball** [comment]
It also sets a tone and expectations. I don't think our crowd has had any issues, unless something has happened I haven't seen, but it's still good to state so people are aware of some standards.

**Comment by jseppi** [comment]
As the organizers we would already have to deal with any situations. Having a stated CoC just lets people know.

**Comment by KCMack** [comment]
Agreed.

Just want to be sure we set our own expectations about who responds to issues and how they do it.

I do believe having a stated policy is valuable.  Thank you for bringing up the topic and making sure we do the right thing.

Kathleen C. Mack, PMP
Operations Manager
Texas Natural Resources Information System / 1700 N. Congress Ave., Austin, Texas 78701
Phone 512 463-4536 / Cell 512 415-3847
Kathleen.Mack@twdb.texas.gov<mailto:Kathleen.Mack@twdb.texas.gov> / www.tnris.texas.gov<http://www.tnris.texas.gov/>

**Comment by jseppi** [comment]
:+1:

**Comment by jseppi** [comment]
@christoball - when you get the "save the date" page up at `/georodeo/2016/`, could you also get up the Code of Conduct at `/georodeo/2016/code-of-conduct` ?

Let's go ahead and use a modified version of http://confcodeofconduct.com/, with our contact information in the "Need Help?" section.

**Comment by KCMack** [comment]
James,

Who do you want to answer any questions that may be posed?

kcm

Kathleen C. Mack, PMP
Operations Manager
Texas Natural Resources Information System / 1700 N. Congress Ave., Austin, Texas 78701
Phone 512 463-4536 / Cell 512 415-3847
Kathleen.Mack@twdb.texas.gov<mailto:Kathleen.Mack@twdb.texas.gov> / www.tnris.texas.gov<http://www.tnris.texas.gov/>

**Comment by jseppi** [comment]
Richard, you, me, Andy, and Chris

**Comment by jseppi** [comment]
Done
