### ISSUE TITLE
Redirect /georodeo/ to most recent (/2016/)

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#828]
We need a redirect from the base `/georodeo/` to `/georodeo/2016/`. Right now, `/georodeo/`, which was previously functioning and has been sent out to speakers, is giving a 403 error.

cc @wilsaj

**Comment by wilsaj** [comment]
can only do a client-side fix for this right now

can't deploy a server-side fix for this from outside the office at the moment :/

**Comment by jseppi** [comment]
Yeah, I know

**Comment by wilsaj** [comment]
Also, kind of interesting that trying to hit any directory without an index returns a 403 instead of 404. s/b 404

**Comment by jseppi** [comment]
Actually my attempt to redirect was wrong and didn't do anything.

**Comment by jseppi** [comment]
Now it works.
