### ISSUE TITLE
GeoRodeo - Waldo head shot and bio

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#840]
![image](https://cloud.githubusercontent.com/assets/697848/13184259/63be72ca-d700-11e5-80dc-69633115ab9f.png)

Bio incoming shortly...

**Comment by jseppi** [comment]
Bio:

Waldo Jaquith is the director of U.S. Open Data, an organization building the capacity of open data and supporting government in that mission. He also serves as the senior technology advisor to the Sunlight Foundation. Previously, he worked for the White House Office of Science and Technology Policy on open data initiatives. He lives in Charlottesville, Virginia with his wife and son.

**Comment by christoball** [comment]
We usually release a news update for keynotes. Where could I get a fuller bio and info to put together something?

**Comment by jseppi** [comment]
I can ask him for that.

**Comment by jseppi** [comment]
He said he'll have a longer form bio for us by Monday.

**Comment by jseppi** [comment]
@christoball here is a longer bio for Waldo:

> Waldo Jaquith is an open government technologist and the director of U.S. Open Data. He serves as the senior technology advisor to the Sunlight Foundation. He's been a website developer for over two decades.
> 
> Previously, Jaquith was a a John S. and James L. Knight Foundation News Challenge Fellow, funding the development of The State Decoded, a free, open-source web-based application to parse and display legal codes in a friendly, accessible manner, as well as machine-readable data.
> 
> In 2011–2012, Jaquith worked for the White House Office of Science and Technology Policy, creating a unified data source of federal ethics data, fulfilling a campaign promise made by President Obama during the 2008 election. In 2012–2013, he was a member of the White House Open Data Working Group, advising the White House on the standardization of storage and transmission of public data to ensure its broad availability and accessibility, which resulted in the White House Open Data Policy (M-13-13: “Managing Information as an Asset”).
> 
> In acknowledgement of his open data work, Jaquith was named a "Champion of Change" by the White House in 2011. In 2012, the Sunlight Foundation named him an "OpenGov Champion.”
> 
> Jaquith, his wife, and their young son live in the woods on top of a mountain near Charlottesville, Virginia, with a dog, a horse, and an ever-changing menagerie of poultry and foster animals. He’s @waldojaquith on Twitter.
