### ISSUE TITLE
GeoRodeo - Speaker - John Gravois

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#842]
Employer: ESRI

Bio: John is a Developer Advocate who specializes in programming against both ArcGIS Server and Esri's SAS offerings.  He has a tattoo of a California Raisin and when he's not in front of a computer you can often find him tangled up in poison oak somewhere near his mountain bike.

Talk title: Hey esri, what have you open-sourced for me lately?

**Comment by christoball** [comment]
Will we be getting headshots for everyone?

Dang, that title goes hard.

**Comment by jseppi** [comment]
Yeah, we'll be trying to get headshots from all the speakers.

:)

**Comment by wilsaj** [comment]
John's headshot: https://dl.dropboxusercontent.com/u/59331579/headshot-pacifier.jpg

**Comment by christoball** [comment]
- [ ] Photo Posted in 'other speakers
- [ ] Time assigned and placed in agenda
