### ISSUE TITLE
new dataset: HPIDS 2015 NGA

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#853]
WPD process to add new dataset TOP 2015 NGA areas
- [x] Add data to measures spreadsheet @gmullins
- [x] Route Data Shipment @gmullins
- [x] Data Processing [renaming file, data organization, coverage map] @mitchellryant
- [x] Quality Assurance @gmullins
- [x] Download Prep [zip, copy to s3 bucket] @mitchellryant
- [x] Move data to production shares @mitchellryant
- [x] Add to Data Download @wilsaj https://github.com/TNRIS/data-download/issues/65 
- [x] Data Publication [Update data catalog sheet, create data catalog images, supplemental reports staging] @gmullins
- [x] Data Story @gmullins
- [x] Final Publication @christoball @gmullins
- [x] Inform TNRIS Staff of data availability @gmullins

**Comment by gmullins** [comment]
@mitchellryant JP2s and J2Ws are done.

**Comment by gmullins** [comment]
@mitchellryant 
Please change El Paso to _20151025
Thx.

**Comment by gmullins** [comment]
@christoball I started the data release article:
https://github.com/TNRIS/tnris.org/blob/nga-ortho-release/content/markdown/news/2016-04-28-nga-2015-aerial-imagery-now-available.md

Images are available here: M:\SM\HPIDS\2015 Projects\580150618 Ortho\Web page\NGA_Graphics
And here: M:\Admin\Website\DataCatalogImages\tnris
