### ISSUE TITLE
new dataset: HPIDS 2016 Smith

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#854]
wpd process for HPIDS 2016 Smith County

- [x] Add data to measures spreadsheet @gmullins
- [x] Route Data Shipment @gmullins
- [x] Data Processing [renaming file, data organization, coverage map] @mitchellryant
- [x] Quality Assurance @gmullins
- [x] Download Prep [zip, copy to s3 bucket] @mitchellryant
- [x] Move data to production shares @mitchellryant
- [x] Add to Data Download @wilsaj https://github.com/TNRIS/data-download/issues/62
- [x] Data Publication [Update data catalog sheet, create data catalog images, supplemental reports staging] @gmullins
- [x] Data Story @gmullins started on #866
- [x] Final Publication @christoball @gmullins

**Comment by gmullins** [comment]
Ready for next step @mitchellryant

**Comment by gmullins** [comment]
Note to self:
Location for creating data catalog images: M:\Admin\Website\DataCatalogImages
datacatalogimage.mxd

**Comment by gmullins** [comment]
@mitchellryant DO4Q tiles are ready to be replaced with corrected tiles in 
GeoTIFF_Correction....
JPEG2000_Correction...
JPG_Correction...
folders

Mosaics were rejected and will be redelivered from Surdex.

**Comment by christoball** [comment]
I'm not seeing data access options on the dataset:
https://deploy.tnris.org/api/v1/preview/f6679ba3ee8c67c8e44839180aa1f68dce5aaaef/data-catalog/entry/hpids-smith-county-2016-6in-nc-cir/

**Comment by gmullins** [comment]
@christoball and @mitchellryant The article looks great! Before we put this 'Issue' to rest, I was wondering about the graphics on the Data Access page. https://tnris.org/data-catalog/entry/hpids-smith-2016-6in-nc-cir/  Per the incoming data WPD, I created natural, urban, and overview jpg's.

**Comment by mitchellryant** [comment]
![rgmdm5](https://cloud.githubusercontent.com/assets/8459928/13783656/3258b09e-ea9a-11e5-8d84-6737756f32cd.GIF)

**Comment by gmullins** [comment]
I'm laughing so much right now!!!!!

**Comment by gmullins** [comment]
Also, Supplemental Reports and Tile Index download not showing up on Data Access page.

**Comment by mitchellryant** [comment]
@christoball That was my fault. i used the Y instead of T. On next update of data catalog it should be fixed.
