### ISSUE TITLE
GeoRodeo Speaker - Mateo Clarke

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#859]
Organization: Open Austin (http://www.open-austin.org/)

Bio: Mateo Clarke is the Brigade Captain and Chair of Open Austin, a volunteer citizen brigade advocating for open government, open data, and civic application development. Open Austin is an official brigade affiliated with the national nonprofit Code for America which believes government can work for the people and by the people in the 21st century. As a part of a national movement we design and build open source technology and organize a network of people dedicated to making government services simple, effective, and easy to use. Mateo is also a Front End Engineer at AcademicWorks, an education software company that matches students with scholarship opportunities so they can afford a college education.

Talk Title: TBD

Picture has been requested. Will post here once received.

**Comment by jseppi** [comment]
Here's his picture: 

![mateo-clarke](https://cloud.githubusercontent.com/assets/697848/13322197/e7a14544-db98-11e5-9658-4a8e28a49b08.jpg)

**Comment by christoball** [comment]
- [ ] Photo Posted in 'other speakers
- [ ] Time assigned and placed in agenda
