### ISSUE TITLE
Turn off past forum forms

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/tnris.org#86]
Going back to the past years' texas gis forum pages, many of them have "Job Board" and "Poster Contest" forms directly available on the pages. They also have pages that, although not linked to, still exist with open forms. All of these forms need to either be deleted from the templates or commented out as to prevent users from utilizing them. If used, they may cause errors or confliction (at least confusion) for both them and TNRIS internally.

**Comment by christoball** [comment]
@adambreznicky k, done that in this commit 62e484dcb6cbf793de50ac911e26b90877c658f8

made a universal job board form, deleted extras, and got rid of past instances in forums

if it looks good i will make the pull request.

**Comment by adambreznicky** [comment]
@christoball AWESOME! thanks for such a quick response. go ahead and create the PR
