### ISSUE TITLE
Add twitter cards for TNRIS links

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#862]
Could we look into implementing this for links to our website from twitter?

https://dev.twitter.com/cards/overview

ping @wilsaj @jseppi

**Comment by jseppi** [comment]
good idea!

**Comment by wilsaj** [comment]
:+1:

**Comment by christoball** [comment]
Looks like we'll need some way to grab the permalink.

<meta property="og:url" content="LINK HERE" />

@wilsaj
