### ISSUE TITLE
tnris.org: Lidar Project Contact form

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#867]
The Lidar Project Contact form is not using the reply to address configuration. Items being pushed into osTickets have the tnris data support email not users.

**Comment by mitchellryant** [comment]
![image](https://cloud.githubusercontent.com/assets/8459928/13605514/7f656d74-e50d-11e5-8e29-d3ee89a1f61c.png)

**Comment by jseppi** [comment]
The problem was in osTicket's Ticket Filter. The checkbox for "Use Reply-To Email" was not checked for the auto-assignment filter for this email. @mitchellryant is checking to make sure all other filters have that checkbox checked.
