### ISSUE TITLE
GIS Solutions Group Page

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#869]
Branch: create-gis-solutions-group-page

You can view the current version here:
https://beta.tnris.org/geographic-information-office/gis-solutions-group/

I think that the body text needs to be pared down, or broken up more, possibly with headers and graphics.

**Comment by jseppi** [comment]
Typo in this block of the image: 

![image](https://cloud.githubusercontent.com/assets/697848/13677152/6fa4b780-e6ae-11e5-98b4-bc179eabcd20.png)

**Comment by wilsaj** [comment]
Is that image just a placeholder? It has watermarks all over it.

**Comment by christoball** [comment]
Those are latitude and longitude lines.

**Comment by jseppi** [comment]
:laughing:

**Comment by wilsaj** [comment]
:joy:

**Comment by christoball** [comment]
Any ideas for a a graphic? I actually kind of like this one.

@geochik thoughts?

**Comment by geochik** [comment]
I really like that one and the group likes it too. Can we buy it?

Sent from my iPhone

On Mar 10, 2016, at 12:12 PM, Chris <notifications@github.com<mailto:notifications@github.com>> wrote:


Any ideas for a a graphic? I actually kind of like this one.

@geochik<https://github.com/geochik> thoughts?

-

**Comment by christoball** [comment]
Latest version of page with new edits and graphics:
https://deploy.tnris.org/api/v1/preview/8be3f578552a369a4f843ed4483ed02ffb3c0652/geographic-information-office/gis-solutions-group/

**Comment by geochik** [comment]
- Adjust Header
- Take out gis community meeting on this page.
- Move latest meeting notes into top box.
- Change 'solutions group' to 'data governance model'.
- Adding context to discussion topics @geochik
- Add meeting archive in top box

**Comment by mitchellryant** [comment]
issue over 15 months old, appear corrected
