### ISSUE TITLE
new dataset: HGAC 2008 Lidar

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#873]
wpd process for incoming lidar data.

- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment @ThorTheDestroyer
- [x] Data Processing [renaming file, data organization, coverage map] @mitchellryant
- [x] Quality Assurance @ThorTheDestroyer
- [x] Move data to production shares @mitchellryant
- [x] Data Publication [Update data catalog sheet, create data catalog images, supplemental reports staging] @ThorTheDestroyer
- [x] Data Story @ThorTheDestroyer
- [x] Final Publication @christoball @ThorTheDestroyer

**Comment by christoball** [comment]
resolved in #905
