### ISSUE TITLE
GeoRodeo - Speaker - Paige Bailey

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#874]
Name: Paige Bailey

Organization: Chevron

Bio: Geophysicist with computer science habits. Passionate about public transportation, sustainable energy, scientific computation, STEM education reform, adventures -- and how Python integrates with all of the above.

Talk title: Dungeons & Development: Creating a Randomized D&D Map Generator with Python

**Comment by jseppi** [comment]
I've emailed to ask for a photo.

**Comment by christoball** [comment]
- [ ] Photo Posted in 'other speakers
- [ ] Time assigned and placed in agenda
