### ISSUE TITLE
Two speakers to add to the Emergency session - add to the website

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#88]
Two presenters from Harris County will join JD in his presentation.

We have Jeff Goalen's name listed, but not his bio.  And Dominic Lai is not listed, please add his name along with the other two.

Jeff Goalen
Jeff Goalen, M.S., PMP is the Director of Budget Support Services (a division of the Budget Management Department in Harris County, Texas).  The division’s core function is to collect accurate, timely, and relevant data and present that data in a way that is easy to understand.   The ATLAS mapping/business intelligence system, built by BSS, is an enterprise-wide system created to support budgetary decisions within BMD and is made available to all County knowledge workers and decision-makers.  Mr. Goalen’s background has centered in data collection and acquisition, data processing, data analysis, and presentation of results; it has spanned both private and public sector directorships and project management in IT, research, business analysis, geosciences, and scientific instrumentation.

Dominic Lai
Dominic Lai is a member of Mr. Goalen’s team.  He has more than 10 years of successful experience in designing and implementing innovative software solution for Harris County, including the ATLAS mapping/business intelligence system.
Mr. Lai holds a Master of Computer Science degree from the Graz University of Technology, Austria

@christoball

**Comment by christoball** [comment]
resolved
