### ISSUE TITLE
GeoRodeo - Speaker - Santiago Giraldo

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#885]
Name: Santiago Giraldo

Org: CartoDB

Title: Community Science Lead

Bio: Santiago Giraldo is an environmental and urban scientist, cartographer, and multi-disciplinary designer from Brooklyn, NY. His celebrated theory and urban design work has been exhibited, published, and featured internationally at notable institutions including the MoMA in NYC, MAK Museum in Vienna, the Vienna Biennale, IUAV University in Venice, Stalker Labs in Rome and Pompeii, Interartive Spain, and other notable design, theory, and environmental publications. Currently, Santiago works to push the boundaries of open source geospatial technology in community engagement at CartoDB.

Talk title: TBD

**Comment by jseppi** [comment]
I have sent Santiago an email requesting a photo for the site.

**Comment by jseppi** [comment]
Photo:

![image](https://cloud.githubusercontent.com/assets/697848/13823055/14e0cd80-eb76-11e5-9aab-b2945728f4dc.png)

**Comment by christoball** [comment]
- [] Photo Posted in 'other speakers
- [] Time assigned and placed in agenda
