### ISSUE TITLE
new dataset: TOP 2015 Centralish (pink area)

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#888]
- [x] Add data to measures spreadsheet @gmullins
- [x] Route Data Shipment [copy data to TNRIS Projects share] @gmullins
- [x] CCMs Quality Assurance @gmullins
- [x] Data Processing [renaming file, data organization, coverage map] @mitchellryant
- [x] JP2s Quality Assurance @gmullins
- [x] Download Prep [zip, copy to s3 bucket] @mitchellryant
- [x] Move data to production shares @mitchellryant
- [x] Add to Data Download @wilsaj https://github.com/TNRIS/data-download/issues/68
- [x] Data Publication [Update data catalog sheet, create data catalog images, supplemental reports staging] @gmullins
- [x] Data Story @gmullins
- [x] Final Publication @christoball @gmullins

**Comment by gmullins** [comment]
@mitchellryant There's nothing on this step I need to do for this one, correct?

Data Publication [Update data catalog sheet, create data catalog images, supplemental reports staging] @gmullins
