### ISSUE TITLE
GeoRodeo - Front page block?

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#889]
Might be good to put GeoRodeo block on the front page

![selection_087](https://cloud.githubusercontent.com/assets/697848/13884133/a3d1039a-ecfa-11e5-8808-b782f7396cd5.png)

**Comment by jseppi** [comment]
Ha super weird. Apparently it is there already, but it is getting blocked by ad blockers probably because the name is "cowsay_web_ad.jpg". Perhaps consider changing the filename?

**Comment by christoball** [comment]
sorry, just seeing this.

weird, i'll change the name.

**Comment by christoball** [comment]
Or I might just replace it with your awesome graphic @jseppi

**Comment by christoball** [comment]
Oh, so, the statewide imagery has ad in the name too. It looks like it must be because it says 'ad' in the alt text.
