### ISSUE TITLE
Address Point web page update

### ISSUE THREAD

**Issue by ilyannakadich** [TNRIS/tnris.org#90]
@christoball @gmullins 

Chris, please remove the information above the Program Timeline and replace with the attached.  Also, the Fall 2019 box should be green in the timeline.  

[AP site updates.docx](https://github.com/TNRIS/tnris.org/files/3757704/AP.site.updates.docx)
[TNRIS Address Point Schema.pdf](https://github.com/TNRIS/tnris.org/files/3757706/TNRIS.Address.Point.Schema.pdf)

**Comment by christoball** [comment]
@ilyannakadich I need to double check, are you saying to take off the 'download dataset' section as well?

You said to replace what's above the timeline. If not, i'm going to move it into the side above the contact us

![image](https://user-images.githubusercontent.com/1877550/67318873-b267cc80-f4d1-11e9-83a3-d966b8c75458.png)
