### ISSUE TITLE
New StratMap Contract Page

### ISSUE THREAD

**Issue by gmullins** [TNRIS/tnris.org#911]
Work with @christoball @ThorTheDestroyer to develop contract page

- [x] Draft content
- [x] Publish to production @christoball

**Comment by christoball** [comment]
Created branch '**new-sm-contract-page**'
https://github.com/TNRIS/tnris.org/tree/new-sm-contract-page

content/markdown/stratmap/contract.md
contains content from article and old HPIDs contract content

**Comment by gmullins** [comment]
@christoball Please add a contact form on the SM Contract Page. The tickets should go to me and Joey or I can be the first assigned and filter to Joey as needed.

**Comment by gmullins** [comment]
@christoball Please un-grey these Vendors. Thanks!:

AppGeo
Vendor Contract Page in progress
DIR Contract Page: http://dir.texas.gov/View-Search/Contracts-Detail.aspx?contractnumber=DIR-TSO-3417&keyword=applied%20geographics

Fugro Geospatial
Vendor Contract Page in progress
DIR Contract Page: http://dir.texas.gov/View-Search/Contracts-Detail.aspx?contractnumber=DIR-TSO-3391&keyword=fugro%20geospatial

Geo-Comm
Vendor Contract Page in progress
DIR Contract Page: http://dir.texas.gov/View-Search/Contracts-Detail.aspx?contractnumber=DIR-TSO-3441&keyword=geo-comm

SADA Systems
Vendor Contract Page in progress
DIR Contract Page: http://dir.texas.gov/View-Search/Contracts-Detail.aspx?contractnumber=DIR-TSO-3413&keyword=Sada

Sanborn
Vendor Contract Page in progress
DIR Contract Page: http://dir.texas.gov/View-Search/Contracts-Detail.aspx?contractnumber=DIR-TSO-3395&keyword=Sanborn

Tessellations
Vendor Contract Page in progress
DIR Contract Page: http://dir.texas.gov/View-Search/Contracts-Detail.aspx?contractnumber=DIR-TSO-3443&keyword=tessellations

**Comment by gmullins** [comment]
@christoball Please change StratMap Contract to StratMap Contracts on all headings. This is a requirement from DIR. Thx!

**Comment by gmullins** [comment]
@christoball These are now available. Please update. Also, please see previous comment.

Geo-Comm
Vendor Contract Page:  http://www.geo-comm.com/2016texas-dircontract/

Tessellations
Vendor Contract Page: http://tessellations.us/?page_id=675

**Comment by gmullins** [comment]
@christoball Please add a grayed out box for West. Thx!
Vendor home: https://www.west.com/ 
No other links available yet.

**Comment by gmullins** [comment]
@christoball Welcome back! These are now available. Please update. Thx!

AppGeo
Vendor Contract Page: http://www.appgeo.com/about/contracting-with-appgeo-is-easy/texas-dir-tso-3417/#more-4656

Fugro 
Vendor Contract Page: http://www.fugrogeospatial.com/txdir

SADA Systems
Vendor Contract Page: https://sadasystems.com/cloud-solutions/google-for-work/apps/government/certifications/contracts/DIR-TSO-3413

Sanborn
Vendor Contract Page: http://www.sanborn.com/texasdir-dir-tso-3395/

**Comment by christoball** [comment]
@gmullins I'm closing this issue since the page is up. From here on, can you create a new issue when it's time to update vendors? Thanks!
