### ISSUE TITLE
new dataset: top 2015 east texas (gray area)

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#918]
- [x] Add data to measures spreadsheet @gmullins
- [x] Route Data Shipment [copy data to TNRIS Projects share] @gmullins
- [x] Data Processing [renaming file, data organization, coverage map] @mitchellryant
- [x] Quality Assurance @gmullins
- [x] Download Prep [zip, copy to s3 bucket] @mitchellryant
- [x] Move data to production shares @mitchellryant
- [x] Add to Data Download @wilsaj https://github.com/TNRIS/data-download/issues/72
- [x] NOT NEEDED: Data Publication [Update data catalog sheet, create data catalog images, supplemental reports staging] @gmullins
- [x] NOT NEEDED: Data Story @gmullins
- [x] Final Publication @christoball @gmullins

![tx_remaining_deliveries](https://cloud.githubusercontent.com/assets/4921113/14506743/f72af91c-0184-11e6-8593-c159178a0794.jpg)

**Comment by gmullins** [comment]
32 3195 DOQQs are in z14 and need to be in z15
23 3096 DOQQs are in z15 and need to be in z14
Wait to see if any are like this in 'green area' and re-request from Surdex.

**Comment by gmullins** [comment]
Let's move on with the Download Prep before we get the areas that are missing. @mitchellryant
