### ISSUE TITLE
Front page and Forum page changes

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#92]
The usual - Thank you for making the Texas GIS Forum a huge success!

Videos will follow after adding closed captioned.....

Presentations will be uploaded to enjoy the sessions again by XXX date

@christoball

**Comment by christoball** [comment]
@KCMack Photo recap article ready for review

I essentially resued the same text from last year so any ways to make it more specific to this year are welcome. Still making other edits to front page and adding presentations

front page:
http://ellwood.tnris.org/

photo recap:
http://ellwood.tnris.org/news/2019-11-01/texas-gis-forum-2019-wrap-up-photo-recap/

**Comment by KCMack** [comment]
Looks great, Chris

**Comment by christoball** [comment]
@KCMack @gmullins can y'all take a look at the agenda and the slides i've posted. ones that don't have one means i didnt get the file, unless i made a mistake: http://ellwood.tnris.org/texas-gis-forum/2019/agenda/

@gmullins can you tell me where these presentations go under? I wasnt sure which sessions they should be put under, the wednesday or friday one

https://speakerdeck.com/texasnaturalresourcesinformationsytem/stratmap-celebrating-successful-public-and-private-partnerships

https://speakerdeck.com/texasnaturalresourcesinformationsytem/stratmap-land-parcel-data

Can someone direct me where this one goes?
https://speakerdeck.com/texasnaturalresourcesinformationsytem/dir-cooperative-contracts-overview

**Comment by KCMack** [comment]
Let's make the thank you more about the attendees and less about us as follows:

Thank you for attending the 2019 Texas GIS Forum..  Your participation and enthusiasm contributed to another great event.

We hope you enjoyed it as much as we did! Photos from the conference are shared along with the  slideshows available from this year's presenters on the agenda page.  Videos of the Keynotes and our video skit will also be on the website in the near future.

Take a look at the impressive cartography that won the top spots in this year's Poster Gallery & Contest.

Finally, be sure to save the dates for next year, October 19-23, 2020, when we'll return to the Commons Center for the 33rd Annual Texas GIS Forum. In the meantime, please send us any comments or ideas that will make next year's event even better. We are always looking for ways to improve and ensure that the Forum serves you, the Texas GIS community.

**Comment by KCMack** [comment]
Slides appear to be attached to the session topic correctly.
I will contact those speakers whose slides are not currently available.
