### ISSUE TITLE
Add GeoRodeo Speakers

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#923]
Add 

- Ben Guhin, City of Austin Office of Innovation

- Paige Bailey, Chevron

- John Clary, City of Austin

**Comment by christoball** [comment]
We've been breaking out each speaker into its own issue so we can keep bios and headshots more organized. Ben and Paige already had issues and I've gone ahead and created one for John.

Ben:
https://github.com/TNRIS/tnris.org/issues/892

Paige:
https://github.com/TNRIS/tnris.org/issues/874

John:
https://github.com/TNRIS/tnris.org/issues/925

Once times are assigned, I can add to the agenda.
