### ISSUE TITLE
new dataset: top 2015 south central (green area)

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#927]
- [x] Add data to measures spreadsheet @gmullins
- [x] Route Data Shipment [copy data to TNRIS Projects share] @gmullins
- [x] Data Processing [renaming file, data organization, coverage map] @mitchellryant
- [x] Quality Assurance @gmullins
- [x] Download Prep [zip, copy to s3 bucket] @mitchellryant
- [x] Move data to production shares @mitchellryant
- [x] Add to Data Download @wilsaj https://github.com/TNRIS/data-download/issues/74
- [x] NOT NEEDED: Data Publication [Update data catalog sheet, create data catalog images, supplemental reports staging] @gmullins
- [x] NOT NEEDED: Data Story @gmullins
- [x] Final Publication @christoball @gmullins
- [x] Inform TNRIS staff of data availability @gmullins

![tx_remaining_deliveries](https://cloud.githubusercontent.com/assets/4921113/14506774/17e07e70-0185-11e6-9159-7ff1f04e961d.jpg)

**Comment by gmullins** [comment]
A handful of missing tiles I'll request from Surdex.
