### ISSUE TITLE
Address Point Collection URL

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#93]
Please change the url for the Address Points Collection from `https://data.tnris.org/collection/c56ff69b-efe7-46e7-89c7-43e655188382` 
to
`https://data.tnris.org/collection/117cf9e1-3b1e-48f2-97a3-47020d871035`

<img width="404" alt="Screen Shot 2019-10-30 at 8 48 30 AM" src="https://user-images.githubusercontent.com/8459928/67863540-169e1800-faf2-11e9-8556-6b5614b5d641.png">

**Comment by christoball** [comment]
@mitchellryant I've gone ahead and staged this change in this commit 4c34fc9c0720793b37e1cc75d28bbc8ac129e80d

preview here:
http://washburn.tnris.org/stratmap/address-points/

**Comment by ghost** [comment]
i just made the collection public so it will take up to one hour to for the materialized view to refresh.

**Comment by ghost** [comment]
@christoball looks great!
