### ISSUE TITLE
Parking Pass - GeoRodeo

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#931]
Please post the parking pass for the GeoRodeo by April 20th. Kathy sent it yesterday.

**Comment by christoball** [comment]
It's already posted :+1:
https://tnris.org/georodeo/2016/

**Comment by KCMack** [comment]
Sorry, I didn’t scroll down to the bottom of the page.

Thanks,
kcm

Kathleen C. Mack, PMP
Operations Manager
Texas Natural Resources Information System / 1700 N. Congress Ave., Austin, Texas 78701
Phone 512 463-4536 / Cell 512 415-3847
Kathleen.Mack@twdb.texas.gov<mailto:Kathleen.Mack@twdb.texas.gov> / www.tnris.texas.gov<http://www.tnris.texas.gov/>
