### ISSUE TITLE
GeoRodeo - Speaker -  Calvin Metcalf

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#935]

**Comment by KCMack** [comment]
Please add Calvin's photo and name to the list of speakers.  Will the submitted photo work?

**Comment by christoball** [comment]
- [ ] Photo Posted in 'other speakers'
- [ ] Time assigned and placed in agenda

**Comment by christoball** [comment]
@KCMack what is his organization?

**Comment by KCMack** [comment]
AppGeo
