### ISSUE TITLE
New StratMap Content

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#936]
Reference #711 if needed.

New Branch:
https://github.com/TNRIS/tnris.org/tree/new-sm-contract-page/content/markdown/stratmap

Menu w/subPages
Home | Orthoimagery | Lidar | StratMap Contract | Projects | History

**Short intro** - One Paragraph 'What is StratMap' @gmullins 

Three sections
- **Home**
- **StratMap Current Projects/Initiatives** 
  - Current activity, projects, announcements Ex. DIR solicitation status, 3-DEP links/info, etc.
  - Data Releases - latest 3
  - Ongoing Projects Ex. 2016/17 Lidar project page, 2015 Ortho project page, etc.
- **StratMap Ortho & Lidar** 
  - Pop-out boxes referencing Catalog Entries @christoball 
  - Past project representation @gmullins @ThorTheDestroyer 
  - [ ] list of partners
  - [ ] statistics, graphics
  - [ ] funding over time
- **StratMap Contract**
  - [x] Intro/description @gmullins 
- **Projects**
- [ ] solicitation PDFs
- **StratMap Inception/History** - @gmullins 
- [ ] Add 2014 Survey stuff to timeline @gmullins
- [ ] Gather vintage SM graphics @gmullins

Content elements for subpages:
- [x] Lidar specification @thorthedestroyer
- [x] Ortho specification @gmullins 
- [x] Vendor List, links and logos @gmullins @thorthedestroyer @christoball

**Comment by christoball** [comment]
Preview of draft content up to now with menu and subpages. Going to start shaping it up more with graphics and stuff. @ThorTheDestroyer @gmullins 

https://deploy.tnris.org/api/v1/preview/d5841de5d7f3f947193c360f9870256faa27d1c3/stratmap/

**Comment by christoball** [comment]
Also, seeing some inconsistent styles of **Lidar** from **LIDAR** to **LiDAR** :eyes:

@ThorTheDestroyer

**Comment by ThorTheDestroyer** [comment]
I haven't gotten around to fixing them all.  The proper representation should be Lidar

**Comment by ThorTheDestroyer** [comment]
@christoball here is the lidar spec. 
[Lidar_Spec.pdf](https://github.com/TNRIS/tnris.org/files/229881/Lidar_Spec.pdf)

**Comment by christoball** [comment]
Latest content preview with updates to sub pages
https://deploy.tnris.org/api/v1/preview/1e104661f34b4b6aee20b8ceccdf51de2cc2628f/stratmap/

**Comment by gmullins** [comment]
@christoball And here is the ortho spec. 
[TX_Orthoimagery_SOW_v9.pdf](https://github.com/TNRIS/tnris.org/files/238924/TX_Orthoimagery_SOW_v9.pdf)

**Comment by ThorTheDestroyer** [comment]
Lidar page
![scene](https://cloud.githubusercontent.com/assets/8398036/14895622/2b304bf2-0d3f-11e6-8806-101ffbf23ab4.jpg)
![point](https://cloud.githubusercontent.com/assets/8398036/14895623/2b305840-0d3f-11e6-9d15-f38b18cf3953.jpg)

 swipe graphics

**Comment by ThorTheDestroyer** [comment]
updated Lidar graphics for fly over graphic. 

Also, here is the new Lidar Status map by source 
 https://tnris-twdb.cartodb.com/u/tnris/viz/41bcf87c-0248-11e6-b572-0e31c9be1b51/public_map

**Comment by christoball** [comment]
@ThorTheDestroyer @gmullins Added some Lidar data tiles, preview here:

https://deploy.tnris.org/api/v1/preview/d9570863bcdf18a425ba9c4e6a0d9528fe1e64f7/stratmap/elevation-lidar/

**Comment by mitchellryant** [comment]
what if, maybe, possibly, just a suggestion the lidar data tiles were order by year instead of name. 

![giphy](https://cloud.githubusercontent.com/assets/8459928/15405657/6c94af4a-1dc8-11e6-8aaf-e660ae8b001b.gif)

**Comment by christoball** [comment]
@ThorTheDestroyer @gmullins @mitchellryant can you take a look at the ortho tiles?
https://deploy.tnris.org/api/v1/preview/960e7263cb6e05c8d61463ad101fe5b204670b2a/stratmap/orthoimagery/

As you can see, the short description isn't short enough. I think that the quick description is good on the these new tiles, but it will have to be even briefer.

My proposed solution is another field (yay, more fields) on the data catalog to create even shorter descriptions that fit tiles. 

**tile_description** or something.

**Comment by gmullins** [comment]
@christoball Yes. A shorter description is needed. How can I help? 
Remove SPOT from the listing.

And to @mitchellryant suggestion for ordering the lidar tiles. I think the ortho tiles should also be ordered by year, most recent first.

**Comment by mitchellryant** [comment]
@christoball 
is there anyway to parse out the information you need?
what if the tiles just did not have a description? just a title. think about it!! 

@gmullins @ThorTheDestroyer 
Also I think the stratmap page should only highlight items with direct funding. Both Imagery and LiDAR.

![just-a-thought](https://cloud.githubusercontent.com/assets/8459928/15510905/04366008-219f-11e6-9935-11af88907030.gif)

**Comment by christoball** [comment]
I have thought about it. I'm not opposed but generally think our users who don't see the data every day appreciate more context, including myself.

Data aren't like shoes or clothes where the main information is just the visible one - more context is helpful. I think the the tiles look very naked like this. I think if we added the category and maybe some more small icons denoting important info, then I could be down for it. What informational, helpful icons could go maybe on this? Because I wouldn't agree that as minimal as possible is the way to go.

![image](https://cloud.githubusercontent.com/assets/1877550/15511315/9d59d35e-21a0-11e6-9c70-50f5933b4086.png)

**Comment by gmullins** [comment]
@christoball I just committed changes on the StratMap Contract page. If possible, can we concentrate to publish this page out?...due to increased activity surrounding the contract. Look what AECOM did: http://www.ursbtr.com/DirStratMap/storymap/index.html Let me know how I can help. Thanks!

**Comment by christoball** [comment]
@gmullins @ThorTheDestroyer I've polished up the main stratmap page to get it ready for release.
https://deploy.tnris.org/api/v1/preview/bb756c418f837899a152964535dbbc6445777d6b/stratmap/

I can get this into good enough shape and then the contract page probably by EOB tomorrow (may 25) and then we can push something out without the other sub-pages.

The main page and contract pages will still be works in progress, but i think they will still be an improvement to the current content.

**Comment by gmullins** [comment]
@christoball Yes. Thank you.

**Comment by gmullins** [comment]
@christoball Example SOW.
[SM_580160615.pdf](https://github.com/TNRIS/tnris.org/files/282821/SM_580160615.pdf)

**Comment by christoball** [comment]
@gmullins @ThorTheDestroyer Almost there.
https://deploy.tnris.org/api/v1/preview/6a6c5c0b2c22e3758c11ef938829af67cc90d036/stratmap/

Will try to come up with some better banner graphics tomorrow and then think it's ready to go.

**Comment by christoball** [comment]
@ThorTheDestroyer @gmullins  heres a preview of the Lidar page's current stage of development

https://deploy.tnris.org/api/v1/preview/60a28c96f9e92c5ca1fffe1ef3bfb846a1db30e8/stratmap/elevation-lidar/

**Comment by gmullins** [comment]
@christoball Here are the ortho time series graphics options for the Ortho page. Three different areas. I don't expect using every single graphic but wanted to provide all possible options.
M:\SM\Program Administration\Website Content\Ortho_TimeSeries_Graphics

**Comment by gmullins** [comment]
@christoball Ortho and Lidar 'By the Numbers' for each of their pages:

Orthoimagery
**37** past agency partners and counting...
**13** project Statement of Work (SOW) releases since 2009 and counting...
**$5.1 Million** total spent on orthoimagery data products for the State of Texas since 2009 through cost-share initiatives.

Lidar
**19** past agency partners and counting...
**21** project Statement of Work (SOW) releases since 2009 and counting...
**$9.9 Million** total spent on lidar data products for the State of Texas since 2009 through cost-share initiatives.

**Comment by gmullins** [comment]
@christoball StratMap Partners
[SM_Partners_2009-2016.pptx](https://github.com/TNRIS/tnris.org/files/362298/SM_Partners_2009-2016.pptx)

**Comment by mitchellryant** [comment]
looks to be complete and published
