### ISSUE TITLE
Poster Gallery Web Feature

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#94]
Please create the poster gallery "Winners" feature for the web site.

All info is here:  M:\Forum_GeoRodeo\2019_Forum\Poster Contest\Winners

Thanks!

**Comment by ghost** [comment]
@christoball

**Comment by christoball** [comment]
@e00o @KCMack preview ready here:
http://frye.tnris.org/news/2019-10-04/poster-gallery-winners-2019-texas-gis-forum/

**Comment by KCMack** [comment]
Looks terrific, Chris!

**Comment by ghost** [comment]
Nice! Looks excellent. Thanks!
