### ISSUE TITLE
tnris.org: new_rdc_page.md

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/tnris.org#942]
Development of the new RDC webpage

https://github.com/TNRIS/tnris.org/blob/RDC_Page_rework/content/markdown/RDC/RDC.md
- [ ] Content rewrite @thorthedestroyer
- [ ] New graphics(historical/current imagery swipe) @christoball @thorthedestroyer
- [ ]  Incorporating price sheet into page @christoball 
- [ ] incorporation of historical index if possible. 
- [ ] info-graphics relating to RDC @christoball @thorthedestroyer

**Comment by ThorTheDestroyer** [comment]
@christoball Generated Dallas 1927 and current TOP 12 inch Downtown Dallas images to be used as comparison graphics(slider, fader, whateverer). Put them in your staff folder in new directory RDC_Page

**Comment by christoball** [comment]
issue moved to #1423
