### ISSUE TITLE
Address Point web page map

### ISSUE THREAD

**Issue by ilyannakadich** [TNRIS/tnris.org#95]
Chris, once the button on the Address Page to download data is operational and live, can you please add the Carto map.  It will be the same setup as the Land Parcel map.  Here's the map https://tnris-twdb.carto.com/u/tnris/builder/9ea89bcc-63b5-4ed5-924d-e6c1910bb6f4

Thanks! Ilyanna

**Comment by ghost** [comment]
@christoball here is the embed link.

<iframe width="100%" height="520" frameborder="0" src="https://tnris-twdb.carto.com/u/tnris/builder/9ea89bcc-63b5-4ed5-924d-e6c1910bb6f4/embed" allowfullscreen webkitallowfullscreen mozallowfullscreen oallowfullscreen msallowfullscreen></iframe>
