### ISSUE TITLE
data catalog: Adding Orthoimagery and Lidar to Data Catalog Names

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#954]
After seeing this dataset:
**HPIDS NGA\USGS 2015 1ft NC\CIR**

I felt like it's not good practice to not include 'orthoimagery' in the title.

In this case especially, its a whole lot of acronyms, and there's no indication of what this might be unless someone is familiar with NC/CIR. I think someone should be able to know this is imagery straight from the title, even if they aren't experts.

This includes the Lidar datasets which are also strings of acronyms. These are critical traits of the dataset and should be included in the title, not just as their category.

What are y'all's thoughts? I'd like to add these to the titles if there's consensus.

@gmullins @ThorTheDestroyer @mitchellryant

**Comment by mitchellryant** [comment]
My concern would be the length of the names, titles, and URLs. What effect will this change have on all the things based on the existing dataset name (detail\overview images, supplemental reports, and tile indices?

**Comment by mitchellryant** [comment]
https://github.com/TNRIS/tnris.org/commit/13fa9b1b40e05c6a5ff28f94b70fcfd58f83f39d

**Comment by christoball** [comment]
resolved in 6a74aba60f453ff0a9e00db51cc87590e8443f4b
