### ISSUE TITLE
Caption wording changes

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#99]
Change reference to Peter Lake FROM:
Board Member 
TO:
Board Chairman

http://ellwood.tnris.org/news/2019-11-04/texas-gis-forum-2019-wrap-up-photo-recap/#

http://ellwood.tnris.org/news/2019-11-04/texas-gis-forum-2019-wrap-up-photo-recap/#

@adambreznicky

**Comment by ghost** [comment]
added to #101
